### ISSUE TITLE
Read and write a DXF file using GeoPandas

### ISSUE THREAD

**Issue by neha845** [Toblerity/Fiona#1000]
I want to read a DXF file. Do some processing and export it again in the DXF format. I am using GeoPandas for reading and processing. It is happening successfully. But while exporting, it's not coming in DXF format. It is exporting in shapefile.

I have given file name extension as .dxf and driver = 'DXF' I tried using ezdxf but it gives an error of paperspace.

What can be the possible solution of exporting it in DXF format or DWG format?

**Comment by rbuffat** [comment]
@neha845 
Could you provide a minimal working example that shows this behavior? Does it work with other formats and just not with DXF? On the surface, this looks like something related to geopandas, as Fiona should only write the format which was specified in fiona.open.

**Comment by pzq123456** [comment]
Hello, can I get further information about your dxf file reading&writing professor? I want to read an autoCAD dxf file and then simplify it to walls only.Could you give me some advices?
Thanks.

**Comment by neha845** [comment]
You can do it with Fiona.
