### ISSUE TITLE
can not install?

### ISSUE THREAD

**Issue by BEAST-Community** [Toblerity/Fiona#1003]
Package intel-openmp conflicts for:
scipy -> mkl[version='>=2019.4,<2020.0a0'] -> intel-openmp
mkl_random -> mkl[version='>=2019.4,<2020.0a0'] -> intel-openmp
mkl-service -> mkl[version='>=2018.0.3,<2019.0a0'] -> intel-openmp
numpy -> mkl[version='>=2019.4,<2020.0a0'] -> intel-openmp
mkl -> intel-openmp
numpy-base -> mkl[version='>=2019.4,<2020.0a0'] -> intel-openmp
mkl_fft -> mkl[version='>=2019.4,<2020.0a0'] -> intel-openmp

Package setuptools conflicts for:
matplotlib-base -> setuptools
fiona -> munch -> setuptools[version='>=17.1']
wheel -> setuptools
fiona -> setuptools
pip -> setuptools
python=3.8 -> pip -> setuptools

**Comment by BEAST-Community** [comment]
no fiona for python 3.8?

**Comment by BEAST-Community** [comment]
(py38) lixingguangtekiMacBook-puro:0-wnv-phylogeography lixingguang$ pip3 install fiona-1.8.18-py38hd34e6ff_0.tar.bz2
Processing ./fiona-1.8.18-py38hd34e6ff_0.tar.bz2
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-req-build-61y_f09x/setup.py'"'"'; __file__='"'"'/private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-req-build-61y_f09x/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-pip-egg-info-cwepct85
         cwd: /private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-req-build-61y_f09x/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/q4/gvrdsnj94vl527nfhj25rxh40000gn/T/pip-req-build-61y_f09x/setup.py'
    -----------------------

**Comment by sgillies** [comment]
I'm sorry, but I cannot understand this report. The project does not package specifically for intel-openmp and fiona-1.8.18-py38hd34e6ff_0.tar.bz2 doesn't look like it comes from this project either.
