### ISSUE TITLE
Collection __getindex__ indexing starts at 1 for SQLite files

### ISSUE THREAD

**Issue by maxfreu** [Toblerity/Fiona#1004]
To reproduce:

1) Open QGIS, create a vector layer containing some MultiPolygons (not tested with other stuff) and save it as sqlite or spatialite.
2) 
```python
import fiona
file = "..."
fiona.supported_drivers["SQLite"] = "rw"
with fiona.open(file) as f:
    print(len(f))  # e.g. 4
    print(f[-1]["id"])  # this is 3
    for p in f:
        print(p["id"])  # runs from 1 to 4
    print(f[0]["id"])  # errors

Output:
4
3
1
2
3
4
Traceback (most recent call last):
  File "/home/max/programs/anaconda3/envs/dr/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-44-03daf2b261e4>", line 10, in <module>
    print(f[0]["id"])
TypeError: 'NoneType' object is not subscriptable
```
Expected behaviour: `f[0]["id"]` is 1 and `f[-1]["id"]` is 4 - which would match the behaviour of an identical ESRI shapefile.

## Operating system
Debian 10 5.9.0-0.bpo.5-amd64

## Fiona and GDAL version and provenance
fiona 1.8.17 via pip in conda env
gdal 3.1.4

**Comment by sgillies** [comment]
This quirk is documented at https://fiona.readthedocs.io/en/stable/manual.html#collection-indexing. I'm sorry you got tripped up by it.

**Comment by maxfreu** [comment]
Thanks for the reply and sorry for not reading the docs carefully.
