### ISSUE TITLE
Import order for fiona and rasterio

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Fiona#1007]
With the current binary wheels on PyPI, the order that fiona and rasterio are imported into a script/module is important.

Good:
```python
import fiona
import rasterio
```
Bad:
```python
import rasterio
import fiona
```

#### Steps to reproduce
To reproduce the issue (on linux), use a virtual environment to install the current binary wheels from pip:
```bash
$ python3 -m venv /tmp/venv
$ . /tmp/venv/bin/activate
(venv) $ pip install fiona rasterio
```
(installs `Fiona-1.8.18-cp36-cp36m-manylinux1_x86_64.whl`, `rasterio-1.2.1-cp36-cp36m-manylinux1_x86_64.whl`, and dependancies)

#### Importing rasterio before fiona is no good
```
(venv) $ python -c "import rasterio; import fiona"
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
```
The transform module does not work well:
```
(venv) $ python -c "import rasterio; from fiona.transform import transform; print(transform('EPSG:3857', 'EPSG:4326', [19455906], [-5026598]))"
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
ERROR 10: Pointer 'hTransform' is NULL in 'OCTTransform'.

([19455906.0], [-5026598.0])
```
these are the same coordinates as the input, as it's a failed operation.

#### Importing fiona before rasterio is OK
```
(venv) $ python -c "import fiona; import rasterio"
```
shows no error message, and the transform module works as expected:
```
(venv) $ python -c "from fiona.transform import transform; import rasterio; print(transform('EPSG:3857', 'EPSG:4326', [19455906], [-5026598]))"
([174.77537726192696], [-41.09658239799418])
```
these are the expected long, lat coords.

#### Other discussion

This does not seem to be an issue with packages installed via conda (with conda-forge), testing with `rasterio-1.2.1` and `fiona-1.8.18`. This appears to be an issue while setting GDAL_DATA within the pip package directory. There are some similarities to #673.

**Comment by mwtoews** [comment]
I'll acknowledge that this could be a tricky bug, so a fine resolution is to document import orders somewhere. Another import order with fiona is with shapely; see https://github.com/Toblerity/Shapely/issues/1107

**Comment by rbuffat** [comment]
@mwtoews I guess the issue is that the rasterio wheels now include gdal 3.x https://github.com/rasterio/rasterio-wheels/pull/54 while fionas wheel still include gdal 2.4. Gdal 3.x contains major changes regarding axis ordering.

**Comment by jorisvandenbossche** [comment]
But that means that fiona is not correctly finding its own GDAL included in the wheel?

**Comment by mwtoews** [comment]
As for the GDAL_DATA environment variables, these appear to be set after `import`, so:
```
(venv) $ echo $GDAL_DATA

(venv) $ python -c "import fiona; import os; print(os.environ['GDAL_DATA'])"
/tmp/venv/lib/python3.6/site-packages/fiona/gdal_data
(venv) $ python -c "import rasterio; import os; print(os.environ['GDAL_DATA'])"
/tmp/venv/lib/python3.6/site-packages/rasterio/gdal_data
```
this does not change in a `with fiona.Env()` context (should it?).

And yes, these are different versions of GDAL in the binary wheels:
```
(venv) $ python -c "import fiona; print(fiona.gdal_version)"
GDALVersion(major=2, minor=4, revision=4)
(venv) $ python -c "import rasterio; print(rasterio.gdal_version())"
3.2.1
```
---
Here is a trial pair-up of GDAL 2.4.4 versions in the binary wheels:
```
(venv) $ pip install fiona==1.8.18 rasterio==1.1.8
(venv) $ python -c "import rasterio; from fiona.transform import transform; import rasterio; print(transform('EPSG:3857', 'EPSG:4326', [19455906], [-5026598]))"
([174.77537726192696], [-41.09658239799418])
```
works! Should a solution be to try and coordinate releasing binary wheels of rasterio and fiona with the same GDAL version?

---
As for potential issues with the [axis order change](https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order) with GDAL 3, this is indeed a major thing to consider, but is a separate issue.

**Comment by jorisvandenbossche** [comment]
> Should a solution be to try and coordinate releasing binary wheels of rasterio and fiona with the same GDAL version?

Although that might be a practical solution (and maybe the only possible), IMO that is in "principle" a wrong solution. Wheels should be self-contained and independent for such dependencies. A fiona wheel should use the GDAL data included in its own wheel, and not the one included in rasterio.

`rasterio` indeed sets `GDAL_DATA` if this environment variable did not yet exist (so that explains what you see above): https://github.com/mapbox/rasterio/blob/60d106b6bc3fb7b4652e6d33565c14f9a87c5ee4/rasterio/env.py#L617-L636 
But what I am wondering: is setting this environment variable needed? (eg is it needed for GDAL itself? Is there no API method to configure GDAL where to look for data?) 
Looking at the Env code in rasterio (https://github.com/mapbox/rasterio/blob/99511e4069feec4db91374243b7edc382b620b9d/rasterio/_env.pyx#L359-L364), it seems it should not be needed to set `GDAL_DATA`, as it will do another `GDALDataFinder().search()` when entering the Env when `GDAL_DATA` is not set.

**Comment by sgillies** [comment]
@jorisvandenbossche I have been overlooking the option to use [`set_gdal_config()`](https://github.com/mapbox/rasterio/blob/99511e4069feec4db91374243b7edc382b620b9d/rasterio/_env.pyx#L133) at https://github.com/mapbox/rasterio/blob/60d106b6bc3fb7b4652e6d33565c14f9a87c5ee4/rasterio/env.py#L624. I'm going to give that a try.

**Comment by jorisvandenbossche** [comment]
Also fiona edits the environment variables:

https://github.com/Toblerity/Fiona/blob/885dbd11c5dcb2c61862faefc28bfbbff99954de/fiona/env.py#L590-L601

That could maybe also be changed?

**Comment by sgillies** [comment]
Fixed.

**Comment by jorisvandenbossche** [comment]
Thanks!
