### ISSUE TITLE
Writing to GeoPackage doesn't check for SQL-protected words in column names or "forbidden" characters in layer names

### ISSUE THREAD

**Issue by phildias** [Toblerity/Fiona#1009]
## Expected behavior and actual behavior.

When creating a `GPKG` file, there are a few safe-checks that are missing. The two kinds of problems I've identified are:

1) Column names that use SQL protected words, like `select` and `count` are currently allowed 
2) Layer names that contain hyphens are allowed

Currently, `Fiona` allows you to generate GeoPackage files that violate these rules. However, when you try to open files that violate these rules in ArcGIS Pro, the file fails to load and you just get a non-descriptive error message. 

My expectation is that the columns should be automatically renamed to avoid clashes with SQL-protected words. Offending columns can have an underscore added to the end. 

Furthermore, layer names should automatically transform hyphens into underscores.

Note: Since I mainly use `Fiona` through `GeoPandas`, I've also created an [issue on their Github](https://github.com/geopandas/geopandas/issues/1914). 

Note 2: Apologies for the example below using `GeoPandas`

## Steps to reproduce the problem.

```python
import geopandas as gpd

test_gdf = gpd.GeoDataFrame({'my_id':[1,2,3],
                             'select':[1,2,3],
                             'count':[1,2,3]},
                            geometry=gpd.points_from_xy([0,1,2], [0,1,2]),
                            crs='epsg:4326')

test_gdf.to_file('test.gpkg', driver='GPKG',layer='with-hyphen')
```

Then, try to open the `with-hyphen` layer from the `test.gpkg'` file in ArcGIS Pro. An error message will pop up.

## Operating system

Windows 10

## Fiona and GDAL version and provenance

fiona: 1.8.13.post1 (installed through Anaconda, I think)
GDAL: 3.0.2 (installed through Anaconda

**Comment by rbuffat** [comment]
Personally, I would not consider an ESRI product as the reference implementation for GPKG. 

The question is if the GPKG / SQLite specification has any restrictions for column names. I never heard such a restriction for column names in SQL. A quick google search did not reveal any documentation for such limitations. At least with Postgis, a table with columns named count, select and with-hypen work without issue:

`select testtable.count, testtable.select, testtable."with-hypen" from testtable`

If the GPKG specification does not limit column names I would suggest creating a bug report at ESRI for Arcgis.

**Comment by phildias** [comment]
Yep, that sounds super fair. I'll see about filing an issue/request/something on ESRI's page. 

Thanks so much for the super quick response, though! =)

**Comment by phildias** [comment]
One important note, though: the issue with hyphens isn't in column names - it's with table names! I'm not sure if that makes any difference, but I just wanted to make that clarification.

**Comment by rbuffat** [comment]
`select * from "test-table"` seems also to work. Note that this is with PostGIS and not GPKG/SQLite. 

I don't want to rule out that there are restrictions, I'm just at the moment not aware of any.

**Comment by d-wasserman** [comment]
It does seem like a PR for compatibility warnings for different table types could address some of the issues here (without mentioning a specific product). Anything else feels outside of the scope of fiona. That said, this does feel like something ESRI should address on their end.

**Comment by sgillies** [comment]
Format-specific details and guards for attribute names are out of scope for fiona. The GDAL project is responsible for such things.

**Comment by d-wasserman** [comment]
Understood. That makes sense to me. It felt like a stretch as a suggestion.
