### ISSUE TITLE
Fiona import error : dlopen : Symbol not found: _CPLCheckForFile

### ISSUE THREAD

**Issue by GHCamille** [Toblerity/Fiona#1010]
Hello, 

I'm on a MacBook Air (M1), with MacOS BigSur 11.1.

I've installed Fiona in a pipenv, Python 3.9.1, and when I import Fiona, I get the following : 

```
ImportError: dlopen([path_to_my_pipenv_venv]/lib/python3.9/site-packages/fiona/ogrext.cpython-39-darwin.so, 2): Symbol not found: _CPLCheckForFile
  Referenced from: [path_to_my_pipenv_venv]/lib/python3.9/site-packages/fiona/ogrext.cpython-39-darwin.so
  Expected in: flat namespace
 in [path_to_my_pipenv_venv]/lib/python3.9/site-packages/fiona/ogrext.cpython-39-darwin.so
```

I really don't understand what I should do ... My pipenv looks fine, I've tried uninstalling/reinstalling Fiona with different versions, but I'm always getting the same mistake.

I have another project running just fine with the same version of Fiona (Fiona==1.8.18), but without the pipenv. 

Do you have any idea what the problem is ?

**Comment by sgillies** [comment]
@GHCamille please bring this question to the discussion group linked in https://github.com/Toblerity/Fiona#support.

**Comment by GHCamille** [comment]
Ok thanks

**Comment by rajasimon** [comment]
@GHCamille How did you solve it?

**Comment by GHCamille** [comment]
@rajasimon I didn't
