### ISSUE TITLE
Test failures on aarch64

### ISSUE THREAD

**Issue by dotlambda** [Toblerity/Fiona#1012]
## Expected behavior and actual behavior.
I expected `pytest` to work without a problem on aarch64-linux.
Actually, `test_write_or_driver_error[DGN]` and `test_append_or_driver_error[DGN]` failed:
https://gist.github.com/r-rmcgibbo/068b6ed50bbeb2515e8a2ecd11e26a00

## Steps to reproduce the problem.
`nix-build -A python3.pkgs.fiona` on aarch64 NixOS

## Operating system
NixOS

## Fiona and GDAL version and provenance
1.8.19 sdist from PyPI using pip version 21.0.1.

GDAL 3.2.2 installed via Nix

**Comment by risicle** [comment]
This continues to be an issue on fiona 1.8.20.

**Comment by sgillies** [comment]
I believe this was resolved by #1060 and fixed in 1.8.21.
