### ISSUE TITLE
Does `.filter(where=)` with GPKG driver work at all?

### ISSUE THREAD

**Issue by culebron** [Toblerity/Fiona#1016]
I tried Fiona's `.filter()` to filter GPKG file with `where` argument ([Iterator source](https://github.com/Toblerity/Fiona/blob/a6ed5b2e6972e4dad438b85e6f4b4ac8db1154c6/fiona/ogrext.pyx#L1482), [.filter source](https://github.com/Toblerity/Fiona/blob/a6ed5b2e6972e4dad438b85e6f4b4ac8db1154c6/fiona/collection.py#L371), [OGR docs](https://gdal.org/user/ogr_sql_dialect.html#where)), but it doesn't seem to work:

    import geopandas as gpd
    import fiona
    from shapely.geometry import Point

    ds = (
        (Point(0, 0), 'abcde'),
        (Point(1, 1), 'fghij'),
        (Point(2, 2), 'klmno')
    )

    gdf = gpd.GeoDataFrame(ds, columns=['geometry', 'fieldX'])
    gdf.to_file('test.gpkg', driver='GPKG')

    with fiona.open('test.gpkg', layername='test') as fp:
        itr1 = fp.filter(where="fieldX='klmno'")
        print(next(itr1))

        itr2 = fp.filter(where="fieldX like '%klmno%'")
        print(next(itr2))

outputs:

    {'type': 'Feature', 'id': '1', 'properties': OrderedDict([('fieldX', 'abcde')]), 'geometry': {'type': 'Point', 'coordinates': (0.0, 0.0)}}
    {'type': 'Feature', 'id': '1', 'properties': OrderedDict([('fieldX', 'abcde')]), 'geometry': {'type': 'Point', 'coordinates': (0.0, 0.0)}}

Fiona version: 1.8.13.post1.
In Sqlite3 this works as expected:

	sqlite> .open notebooks/test.gpkg
	sqlite> .tables
	gpkg_contents           gpkg_spatial_ref_sys    rtree_test_geom_node  
	gpkg_extensions         gpkg_tile_matrix        rtree_test_geom_parent
	gpkg_geometry_columns   gpkg_tile_matrix_set    rtree_test_geom_rowid 
	gpkg_ogr_contents       rtree_test_geom         test                  
	sqlite> select * from test where fieldX='klmno';
	3|GP|klmno

**Comment by loicdtx** [comment]
This feature is planned for a future release and not yet available in the version you're using. The 1.8.x releases are not built from the master branch but from `maint-1.8` instead, which explains why the code you're pointing to is not available even in most recent releases.

 I asked nearly the same [question](https://fiona.groups.io/g/main/topic/83289263#103) today on the fiona mailing list...
