### ISSUE TITLE
Fiona assumes CRS when empty while reading GPKG with GDAL 3.3.0

### ISSUE THREAD

**Issue by martinfleis** [Toblerity/Fiona#1024]
## Expected behavior and actual behavior.

When saving a GeoPackage with no CRS set, `fiona` with GDAL 3.3.0 now reads it back with an `Undefined geographic SRS`. With older GDAL (3.2.2), the crs attribute of the Collection is empty. GPKG is the only driver of those I tested with this behaviour, other return None (which is what I would expect).

## Steps to reproduce the problem.

Creating a GPKG with empty CRS:

```py
import geopandas as gpd
from shapely.geometry import Point

df = gpd.GeoDataFrame(
    {
        "a": [1, 2, 3],
        "geometry": [Point(0, 0), Point(1, 1), Point(2, 2)],
    }
)

df.to_file("tempfilename.gpkg", driver='GPKG')
```

Reading it back:
```py
import fiona

with fiona.Env():
    with fiona.open("tempfilename.gpkg") as features:
        print(features.crs)
        print(features.crs_wkt)
```
```
{'proj': 'longlat', 'ellps': 'WGS84', 'no_defs': True}
GEOGCS["Undefined geographic SRS",DATUM["unknown",SPHEROID["unknown",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST]]
```
## Operating system

I've been able to reproduce it on Ubuntu and macOS, it doesn't seem to be related to OS.

## Fiona and GDAL version and provenance

All packages installed via conda from conda-forge. 

fiona 1.8.20
gdal 3.3.0 (incorrect behaviour) or 3.2.2 (correct behaviour)

**Comment by martinfleis** [comment]
It seems to be caused by https://github.com/OSGeo/gdal/pull/3286, which fixes the handling of undefined SRS to match the GPKG specification.

> GeoPackage 1.2.1
1.1.1.1.1. File Format
Requirement 11
The record with an srs_id of -1 SHALL be used for undefined Cartesian coordinate reference systems.
The record with an srs_id of 0 SHALL be used for undefined geographic coordinate reference systems.

I guess the question is then not "how to return None" since it is (I guess) not supposed to be returned but how to handle these two options for undefined CRS in fiona (or maybe GeoPandas in this case?). Shall we default to 0 or -1?

**Comment by sgillies** [comment]
@martinfleis I think it's an odd change for GDAL to switch from returning NULL to returning a string that says "this value is undefined", but I think it would be a mistake to paper over the change. Other software will begin to expect the new WKT. Besides, I don't want to see this project spend its energy on format-specific details. We need to focus on the core design and its implementation.

**Comment by martinfleis** [comment]
> Besides, I don't want to see this project spend its energy on format-specific details. We need to focus on the core design and its implementation.

Agree with that. I'll try to figure out the best approach to handling this elsewhere. Thanks.
