### ISSUE TITLE
Apply fix for kwarg to fiona.open in a 1.8.x release?

### ISSUE THREAD

**Issue by chriselion** [Toblerity/Fiona#1025]
Hi,
A bug was reported in https://github.com/Toblerity/Fiona/issues/781 and fixed on master in https://github.com/Toblerity/Fiona/pull/782 almost two years ago. However, the issue has not been fixed in a released version; it is still present as of 1.8.20:
https://github.com/Toblerity/Fiona/blob/1464bc2cf14d64dfac0aa0ba967a4f525381ffe2/fiona/__init__.py#L208-L209

The fix PR was added to the 1.9 milestone, but would it be possible to get it added to a (presumably sooner) 1.8.x release? It  looks like it would be considered a bug fix as far as semantic versioning is concerned.

## Expected behavior and actual behavior.
(copied from the original issue)
_Expected_: Opening a Bytes stream with `fiona.open` and a specific named layer returns a collection for the named layer.

_Actual_: Returns the first (default layer) as specified by `fiona.listlayers`

## Steps to reproduce the problem.
(copied from the original issue)
``` python
# Where afile is any file and mylayer is NOT the default layer
with fiona.open('afile', layer='mylayer') as f:
    print(f.name)

with open('afile', 'rb') as f:
    with fiona.open(f, layer='mylayer') as ff:
        print(ff.name)
```

## Operating system
```
>>> import platform
>>> platform.platform()
'Linux-5.10.25-linuxkit-x86_64-with-glibc2.2.5'
```

## Fiona and GDAL version and provenance
fiona==1.8.18 via pip 21.1.3

**Comment by sgillies** [comment]
Resolved by c4ec419.
