### ISSUE TITLE
fiona.open returns empty data for some GPX files with tracks (trk/trkseg/trkpt)

### ISSUE THREAD

**Issue by mostfamiliar** [Toblerity/Fiona#1033]
## Expected behavior and actual behavior.

I expect a .GPX file with <trk><trkseg><trkpt> data to open and include data with geometry. I can open a .GPX file with tracks but no data is returned.

## Steps to reproduce the problem.

I'm new to fiona and so far its been working well for most .gpx files with wpt data, however i'm getting no features or geometry data returned for files with tracks data. An empty [] is returned via:
`print(list(geo))`

How I'm opening the file:

`with fiona.open(file) as geo:`

I also tried:
adding `driver='GPX'` as well as 
`with fiona.open(file, layer='tracks') as geo:` and `with fiona.open(file, layer='track_points') as geo:` per this thread: 
https://github.com/Toblerity/Fiona/issues/921 but I still am not able to return data with fiona.open

Here's an example file source which has valid tracks data but will not return data on open:

https://www.alltrails.com/trail/us/oregon/tumalo-creek-trail-to-tumalo-falls 

Goto: "More" > "Download Route" > "GPX" 

This also returns an empty array on open: https://github.com/Toblerity/Fiona/blob/master/tests/data/test_gpx.gpx

The GPX file(s) open fine in QGIS.

Anyone know how I can fix this? Is there a function to validate the layer before I try to open it? I tried `listlayers` and I can see that the tracks layer exists.

## Operating system

Mac OSX 11.5.2

## Fiona and GDAL version and provenance

Fiona ver 1.8.20 installed via poetry

GDAL ver  3.3.2

**Comment by sgillies** [comment]
Belatedly, I can't reproduce this with 1.9.1.

```
python
Python 3.11.0 (main, Nov  2 2022, 11:35:09) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>> with fiona.open("tests/data/test_gpx.gpx", layer="tracks") as collection:
...     print(list(collection))
... 
[<fiona.model.Feature object at 0x7f731e2e7190>]
>>> fiona.show_versions()
Fiona version: 1.9.2dev
GDAL version: 3.5.3
PROJ version: 9.0.0

OS: Linux 5.14.0-1057-oem
Python: 3.11.0
Python executable: '/home/seangillies/projects/Fiona/venv/bin/python'
```

Nor with 1.8.20

```
Python 3.11.0 (main, Nov  2 2022, 11:35:09) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>> with fiona.open("tests/data/test_gpx.gpx", layer="tracks") as collection:
...     print(list(collection))
... 
[{'type': 'Feature', 'id': '0', 'properties': OrderedDict([('name', 'Running 6/11/14 8:19 am'), ('cmt', None), ('desc', None), ('src', None), ('link1_href', None), ('link1_text', None), ('link1_type', None), ('link2_href', None), ('link2_text', None), ('link2_type', None), ('number', None), ('type', None)]), 'geometry': {'type': 'MultiLineString', 'coordinates': [[(-71.108203, 42.361951), (-71.10837, 42.361797), (-71.108543, 42.361615), (-71.108731, 42.361451), (-71.108968, 42.361341), (-71.109162, 42.361474), (-71.10933, 42.361612), (-71.109529, 42.361751), (-71.109774, 42.36188), (-71.109991, 42.362007), (-71.110213, 42.362115), (-71.110484, 42.36218), (-71.110728, 42.362205), (-71.110988, 42.36232), (-71.11117, 42.362467), (-71.111344, 42.36264), (-71.111519, 42.362799), (-71.111772, 42.362837), (-71.111994, 42.362716)]]}}]
>>> fiona.show_versions()
Fiona version: 1.8.20
GDAL version: 3.5.3
PROJ version: 9.0.0

OS: Linux 5.14.0-1057-oem
Python: 3.11.0
Python executable: '/home/seangillies/projects/Fiona/venv/bin/python'
```

It might have been a defect in the 1.8.20 wheel. I'm marking this "invalid" only because it's not a fiona bug, I'm not saying that your report or experience is invalid.
