### ISSUE TITLE
Drop Python 3.6

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Fiona#1034]
According to [PEP 494](https://www.python.org/dev/peps/pep-0494/), Python 3.6 will reach it's EOL in December 2021. I'd like to suggest removing support for Python 3.6.

The CI tests should also start testing [Python 3.9](https://docs.python.org/3/whatsnew/3.9.html), which has been out for nearly a year already.

**Comment by snowman2** [comment]
Python 3.10 is coming in October [ref](https://devguide.python.org/#status-of-python-branches). Also, it might not be bad to also consider dropping support for Python 3.7.

Community references:
- [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) says numpy will drop support of Python 3.7 in December 2021. pandas/xarray will likely follow suit.
- opendatacube is Python 3.8+ already [ref](https://github.com/opendatacube/datacube-core/pull/1190)
- pyproj will drop support soon [ref](https://github.com/pyproj4/pyproj/issues/930)

**Comment by mwtoews** [comment]
Closed by b4dcc4001e91d6cbd9530471b0de599f5b83bd48
