### ISSUE TITLE
AppVeyor failures on master

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Fiona#1040]
It would be nice to see all CI tests pass on the master branch, the remaining blocker is with AppVeyor. It was more-or-less working until https://github.com/Toblerity/Fiona/commit/a6ed5b2e6972e4dad438b85e6f4b4ac8db1154c6#diff-92ab9a36df5d8e9f7076f2fdec59492d1ac2d9cf27ea046767a7fc4d542ef3dc

The error is the same for all version combinations in the job matrix, and are similar, e.g.:
```
_________________________ test_env_gdal_data_environ __________________________
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x000000E473CD67C8>
    def test_env_gdal_data_environ(monkeypatch):
        monkeypatch.setenv('GDAL_DATA', '/foo/bar')
        runner = CliRunner()
        result = runner.invoke(main_group, ['env', '--gdal-data'])
>       assert result.exit_code == 0
E       assert 2 == 0
E        +  where 2 = <Result SystemExit(2)>.exit_code
tests\test_data_paths.py:45: AssertionError
```
that is `fio env --gdal-data` does not work, returning error code 2. These kinds of issues are usually PATH-related and/or bad DLL combinations. I'm unable to reproduce this error locally, so any help would be kindly received.

**Comment by sgillies** [comment]
In the past AppVeyor was the option for Windows runners. GitHub Actions are good enough now, we'll go with that.
