### ISSUE TITLE
Memory leak when using MemoryFile

### ISSUE THREAD

**Issue by jbkoch7** [Toblerity/Fiona#1041]
I am using Fiona via GeoPandas to write a large number of geopackage files to S3.
The application passes a `io.BytesIO` object to `geopandas.GeoDataFrame.to_file()` which in turn calls `fiona.open`.
Over time, the application memory grows until all system resources are consumed.
I believe I have narrowed down the issue to the `fiona.io.MemoryFile` class; I have included a small code sample below to reproduce the problem.
Poking around in the Rasterio repository, I noticed they made a fix to their MemoryFile class not too long ago for a similar issue [https://github.com/mapbox/rasterio/commit/8436b0920b3a24fe918c091f0f5d529266b81b13](https://github.com/mapbox/rasterio/commit/8436b0920b3a24fe918c091f0f5d529266b81b13).
I also noticed that there is some ongoing work pertaining to the MemoryFile class, so I apologize if this has already been addressed with [https://github.com/Toblerity/Fiona/pull/901](https://github.com/Toblerity/Fiona/pull/901) and [https://github.com/Toblerity/Fiona/pull/960](https://github.com/Toblerity/Fiona/pull/960).

## Expected behavior and actual behavior.

I expected the memory to be freed after each context manager block, but the memory continually builds until all system resources are consumed.

## Steps to reproduce the problem.

```python
import fiona
import psutil

cnt = 1
schema = {
  'geometry': 'Polygon',
  'properties': {} }
with fiona.Env() as env:
  while True:
    with fiona.io.MemoryFile() as memfile:
      with memfile.open( driver = 'GPKG', schema = schema ) as dataset:
        print( f"CNT: {cnt} | MEM: {psutil.virtual_memory().percent}%" )
        cnt = cnt + 1
```
## Operating system

Ubuntu 20.04.3 LTS

## Fiona and GDAL version and provenance

Fiona 1.8.20 and GDAL 3.3.0 installed from PyPI using pip 21.2.4 and python 3.8.

**Comment by sgillies** [comment]
@jbkoch7 thanks for the report and analysis!
