### ISSUE TITLE
Command errored out with exit status 1: while installing the package in python 3.9.7

### ISSUE THREAD

**Issue by ndganesan** [Toblerity/Fiona#1044]
## Expected behavior and actual behavior.

Error while installing the library 

installing using pip install Fiona
"
 ERROR: Command errored out with exit status 1:
  command: 'C:\Users\Ganesan\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ganesan\\AppData\\Local\\Temp\\pip-install-_kj9hn6q\\fiona_8af7dbc19e494c6083f4f60ff0261881\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ganesan\\AppData\\Local\\Temp\\pip-install-_kj9hn6q\\fiona_8af7dbc19e494c6083f4f60ff0261881\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Ganesan\AppData\Local\Temp\pip-pip-egg-info-8iqz_mbo'
       cwd: C:\Users\Ganesan\AppData\Local\Temp\pip-install-_kj9hn6q\fiona_8af7dbc19e494c6083f4f60ff0261881\
  Complete output (1 lines):
  A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable."

## Operating system

Window 10

## Fiona and GDAL version and provenance

PyPI using pip version 21.3.1., Python 3.9.7

**Comment by rbuffat** [comment]
Please read https://github.com/Toblerity/fiona/tree/maint-1.8#windows

For Windows, it is recommended to use a binary distribution, such as Gohlke's wheels or conda.
