### ISSUE TITLE
Hardcoded encoding utf-8 for BytesCollection

### ISSUE THREAD

**Issue by irvcaza** [Toblerity/Fiona#1048]
## Expected behavior and actual behavior.

**Expected behavior**:  Th stream is read correctly

CVEGEO | CVE_ENT | CVE_MUN | NOMGEO | geometry
-- | -- | -- | -- | --
09002 | 09 | 002 | Azcapotzalco | POLYGON ((2794859.977 837218.408, 2794861.690 ...
09003 | 09 | 003 | Coyoacán | POLYGON ((2800218.995 820661.624, 2800250.439 ...
09004 | 09 | 004 | Cuajimalpa de Morelos | POLYGON ((2787229.791 825329.285, 2787272.744 ...

**Actual behavior**: 
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/LCiD/.local/lib/python3.8/site-packages/geopandas/io/file.py", line 201, in _read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/home/LCiD/.local/lib/python3.8/site-packages/fiona/collection.py", line 555, in __init__
    super(BytesCollection, self).__init__(self.virtual_file, vsi=filetype,
TypeError: __init__() got multiple values for keyword argument 'encoding'
```

## Steps to reproduce the problem.

Download [sample zip shapefile](https://github.com/Toblerity/Fiona/files/7619302/MG.zip) 
```
import geopandas
import fsspec
with fsspec.filesystem("file").open("MG.zip") as fs_file:
    geopandas.read_file(fs_file, driver= 'ESRI Shapefile',   encoding= "Latin-1")
```
This kind of flows are used by [kedro's](https://kedro.readthedocs.io/en/stable/index.html) [geojson_dataset](https://kedro.readthedocs.io/en/stable/_modules/kedro/extras/datasets/geopandas/geojson_dataset.html#GeoJSONDataSet)

## Operating system

Debian GNU/Linux 11 bullseye (docker container) 

## Fiona and GDAL version and provenance

python 3.8
Fiona==1.8.20 from PyPI using pip version 21.2.4
geopandas==0.10.2 from PyPI using pip version 21.2.4
fsspec==2021.9.0 from PyPI using pip version 21.2.4

## Additional Info
the error is not reproduced using ` gpd.read_file("MG.zip", encoding="Latin-1") `

and without encoding parameter returns object but with incorrect encoding 
```
import geopandas
import fsspec
with fsspec.filesystem("file").open("MG.zip") as fs_file:
    geopandas.read_file(fs_file, driver= 'ESRI Shapefile')
```

```
2021-11-29 17:32:15,916 - fiona.ogrext - INFO - Failed to auto identify EPSG: 7
2021-11-29 17:32:15,929 - fiona.ogrext - WARNING - Failed to decode b'Coyoac\xe1n' using utf-8 codec
2021-11-29 17:32:15,967 - fiona.ogrext - WARNING - Failed to decode b'\xc1lvaro Obreg\xf3n' using utf-8 codec
2021-11-29 17:32:15,978 - fiona.ogrext - WARNING - Failed to decode b'Tl\xe1huac' using utf-8 codec
2021-11-29 17:32:15,995 - fiona.ogrext - WARNING - Failed to decode b'Benito Ju\xe1rez' using utf-8 codec
2021-11-29 17:32:16,003 - fiona.ogrext - WARNING - Failed to decode b'Cuauht\xe9moc' using utf-8 codec
```

## Fix suggestions 

Deleting `encoding='utf-8',` at [line 727](https://github.com/Toblerity/Fiona/blob/master/fiona/collection.py#L727) seems to solve the issue. 

Of course, only doing that might break other scenarios. A fix that might be possible would be adding `encoding='utf-8'` as optional parameter to [ BytesCollection `__init__`](https://github.com/Toblerity/Fiona/blob/master/fiona/collection.py#L702) and accessing it on [`super` call ](https://github.com/Toblerity/Fiona/blob/master/fiona/collection.py#L726)

**Comment by sgillies** [comment]
Thanks for the report and diagnosis @irvcaza ! This will be fixed in 1.8.21.

The hard-coded "utf-8" slipped in around 1.7.4.
