### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3

### ISSUE THREAD

**Issue by juanxo90** [Toblerity/Fiona#1052]
at the time to import fiona (or geopandas) i got this error
`File "windows-path\lib\site-packages\fiona\env.py", line 289, in defenv
    local._env.start()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 100: invalid continuation byte
Exception ignored in: 'fiona._env.log_error'`

The library was working fine but it crashes from nothing (probably some update). I have everything in conda-forge channel. I change the package version, remove and re install anaconda and nothing is removing the error.

I am using windows 10.

This is my `conda list`
# Name                    Version                   Build  Channel
access                    1.1.3              pyhd8ed1ab_0    conda-forge
affine                    2.3.0                      py_0    conda-forge
amply                     0.1.4                      py_0    conda-forge
anyio                     3.4.0            py38haa244fe_0    conda-forge
argon2-cffi               21.1.0           py38h294d835_2    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.4.2            py38haa244fe_0    conda-forge
boost-cpp                 1.74.0               h5b4e17d_5    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotlipy                  0.7.0           py38h294d835_1003    conda-forge
bs4                       4.10.0               hd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
cffi                      1.15.0           py38hd8c33c5_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
contextily                1.2.0              pyhd8ed1ab_0    conda-forge
coverage                  6.2              py38h294d835_0    conda-forge
cryptography              36.0.0           py38hb7941b4_0    conda-forge
curl                      7.80.0               h789b8ee_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cykhash                   2.0.0            py38h885f38d_0    conda-forge
cython                    0.29.25          py38h885f38d_0    conda-forge
debugpy                   1.5.1            py38h885f38d_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
deprecation               2.1.0              pyh9f0ad1d_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
docutils                  0.18.1           py38haa244fe_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
esda                      2.4.1              pyhd8ed1ab_0    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
fiona                     1.8.20           py38h7ae963e_1    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonttools                 4.28.3           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
gdal                      3.3.0            py38hacca965_3    conda-forge
geographiclib             1.52               pyhd8ed1ab_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_1    conda-forge
geopandas-base            0.9.0              pyhd8ed1ab_1    conda-forge
geopy                     2.2.0              pyhd8ed1ab_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                ha8a8a2d_6    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
giddy                     2.3.3                      py_0    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.24             pyhd8ed1ab_0    conda-forge
glpk                      5.0                  h8ffe710_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.8.2            py38haa244fe_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
inequality                1.0.0                      py_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
ipykernel                 6.5.1            py38h595d716_0    conda-forge
ipython                   7.30.1           py38haa244fe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py38haa244fe_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.2.1              pyhd8ed1ab_1    conda-forge
jupyter-server-mathjax    0.2.3              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38haa244fe_1    conda-forge
jupyter_server            1.13.0             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.4              pyhd8ed1ab_0    conda-forge
jupyterlab-git            0.34.0             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
kiwisolver                1.3.2            py38hbd9d945_1    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.80.0               h789b8ee_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.3.0                ha6cada3_3    conda-forge
libglib                   2.70.2               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libnetcdf                 4.8.0           nompi_hf689e7d_103    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.5                 hfcc5ef8_1    conda-forge
libpysal                  4.5.1              pyhd8ed1ab_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1                h762a7f4_6    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.36.0           py38h57a6900_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h294d835_1    conda-forge
matplotlib                3.5.0            py38haa244fe_0    conda-forge
matplotlib-base           3.5.0            py38h1f000d6_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mercantile                1.2.1              pyhd8ed1ab_0    conda-forge
mgwr                      2.1.2                      py_0    conda-forge
mistune                   0.8.4           py38h294d835_1005    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mock                      4.0.3            py38haa244fe_2    conda-forge
more-itertools            8.12.0             pyhd8ed1ab_0    conda-forge
mplleaflet                0.0.5                      py_4    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py38haa244fe_1    conda-forge
nbdime                    3.1.1              pyhd8ed1ab_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.4.6              pyha770c72_0    conda-forge
numba                     0.53.0           py38h5c177ec_0    conda-forge
numexpr                   2.7.3            py38h5d928e2_2    conda-forge
numpy                     1.21.4           py38h089cfbf_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
osmnx                     1.1.2              pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py38h5d928e2_1    conda-forge
pandas-bokeh              0.5                      py38_0    patrikhlobil
pandoc                    2.16.2               h8ffe710_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py38h794f750_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pluggy                    1.0.0            py38haa244fe_2    conda-forge
pointpats                 2.2.0                      py_0    conda-forge
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.5                 h1c22c4f_1    conda-forge
proj                      8.0.1                h1cfcee9_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulp                      2.6.0            py38haa244fe_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygeos                    0.10.2           py38h127f298_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0            py38habcafb0_0    conda-forge
pyqt                      5.12.3           py38haa244fe_8    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_8    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_8    conda-forge
pyqtchart                 5.12             py38h885f38d_8    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_8    conda-forge
pyrobuf                   0.9.3            py38h885f38d_3    conda-forge
pyrosm                    0.6.1            py38h885f38d_0    conda-forge
pyrsistent                0.18.0           py38h294d835_0    conda-forge
pysal                     2.5.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38haa244fe_4    conda-forge
pytables                  3.6.1            py38h153c448_3    conda-forge
pytest                    6.2.5            py38haa244fe_1    conda-forge
pytest-cov                3.0.0              pyhd8ed1ab_0    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-rapidjson          1.5              py38h885f38d_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywin32                   302              py38h294d835_2    conda-forge
pywinpty                  1.1.6            py38hd3f51b4_0    conda-forge
pyyaml                    6.0              py38h294d835_3    conda-forge
pyzmq                     22.3.0           py38h09162b1_1    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
quantecon                 0.5.2            py38haa244fe_0    conda-forge
rasterio                  1.2.6            py38h352701c_2    conda-forge
rasterstats               0.16.0             pyhd8ed1ab_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
rtree                     0.9.7            py38h8b54edf_3    conda-forge
rvlib                     0.0.6            py38h6f4d8f0_0    conda-forge
scikit-learn              1.0.1            py38hb60ee80_2    conda-forge
scipy                     1.7.3            py38ha1292f7_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
segregation               2.1.0              pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.4.0           py38haa244fe_0    conda-forge
shapely                   1.8.0            py38h127f298_0    conda-forge
simplejson                3.17.6           py38h294d835_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sniffio                   1.2.0            py38haa244fe_2    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
spaghetti                 1.6.4              pyhd8ed1ab_0    conda-forge
spglm                     1.0.8                      py_0    conda-forge
spint                     1.0.7              pyhd8ed1ab_0    conda-forge
splot                     1.1.4              pyhd8ed1ab_0    conda-forge
spopt                     0.2.1              pyhd8ed1ab_1    conda-forge
spreg                     1.2.4              pyhd8ed1ab_0    conda-forge
spvcm                     0.3.0                      py_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
statsmodels               0.13.1           py38h6f4d8f0_0    conda-forge
sympy                     1.9              py38haa244fe_1    conda-forge
tbb                       2021.4.0             h2d74725_1    conda-forge
terminado                 0.12.1           py38haa244fe_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tiledb                    2.3.4                h78dabda_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
tobler                    0.8.2              pyhd8ed1ab_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h294d835_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              13.0.0.post2     py38h294d835_4    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.2            py38haa244fe_1    conda-forge
win_inet_pton             1.1.0            py38haa244fe_3    conda-forge
winpty                    0.4.3                         4    conda-forge
xerces-c                  3.2.3                h0e60522_4    conda-forge
xyzservices               2021.11.0          pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge

**Comment by sgillies** [comment]
@juanxo90 I'm sorry you're having difficulties. There's nothing we can do about a broken environment.

**Comment by GPoirierECCC** [comment]
Did you ever resolve this problem? I'm having the same issue, but it's not the environment. It's working on Anaconda prompt or with Spyder. This issue seems to be related to Pycharm

**Comment by juanxo90** [comment]
> Did you ever resolve this problem? I'm having the same issue, but it's not the environment. It's working on Anaconda prompt or with Spyder. This issue seems to be related to Pycharm

Nop. I started to use Linux haha

**Comment by harningle** [comment]
> Did you ever resolve this problem? I'm having the same issue, but it's not the environment. It's working on Anaconda prompt or with Spyder. This issue seems to be related to Pycharm

Same! I just had the same issue. It's fine with cmd but not in PyCharm. No idea why...
