### ISSUE TITLE
DriverError: Operation timed out when opening shapefile with geopandas from S3 bucket

### ISSUE THREAD

**Issue by gcaria** [Toblerity/Fiona#1055]
I am getting this error inside a docker container built with the only command `FROM pangeo/pangeo-notebook:latest`, I hope this helps defining the environment, but I'm happy to provide more explicit information if needed.

I have verified that I have access to the private S3 bucket where the file is located, and I can correctly open parquet files (for example) from the same bucket with geopandas, so this issue seems specific to fiona (and/or gdal).

```python

In [1]: import geopandas as gpd

In [2]: gpd.read_file("s3://path/to/shapefile.shp")
---------------------------------------------------------------------------
CPLE_AppDefinedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_AppDefinedError: Operation timed out after 1001 milliseconds with 0 bytes received

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
<ipython-input-2-068760f4508f> in <module>
----> 1 gpd.read_file("s3://path/to/shapefile.shp").geometry

/srv/conda/envs/notebook/lib/python3.9/site-packages/geopandas/io/file.py in _read_file(filename, bbox, mask, rows, **kwargs)
    199
    200     with fiona_env():
--> 201         with reader(path_or_bytes, **kwargs) as features:
    202
    203             # In a future Fiona release the crs attribute of features will

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/env.py in wrapper(*args, **kwargs)
    406     def wrapper(*args, **kwargs):
    407         if local._env:
--> 408             return f(*args, **kwargs)
    409         else:
    410             if isinstance(args[0], str):

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    254
    255         if mode in ('a', 'r'):
--> 256             c = Collection(path, mode, driver=driver, encoding=encoding,
    257                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    258         elif mode == 'w':

/srv/conda/envs/notebook/lib/python3.9/site-packages/fiona/collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    160             if self.mode == 'r':
    161                 self.session = Session()
--> 162                 self.session.start(self, **kwargs)
    163             elif self.mode in ('a', 'w'):
    164                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: Operation timed out after 1001 milliseconds with 0 bytes received
```

**Comment by rbuffat** [comment]
The error message `Operation timed out after 1001 milliseconds with 0 bytes received` suggests that there are connection issues to access the data. Does it work with accessing the file directly with boto3? 

You could try to wrap your call to `fiona.open` call with `with fiona.Env(CPL_DEBUG=True):`. This might enable more debug output. See https://fiona.readthedocs.io/en/latest/manual.html#ogr-configuration-options

**Comment by gcaria** [comment]
I can definitely access files in the S3 bucket, but I have just discovered that I can read the file using only fiona:

```python
In [3]: fiona.open(path_shp)
<open Collection 'path/to/shapefile', mode 'r' at 0x7f9d0558be20>
```

so there seems to be a problem in the interplay between `geopandas` as `fiona`.

Wrapping the call to `geopandas.read_file` adds more debug messages:
```python
HTTP: Fetch(http://000.000.000.000/latest/api/token)
HTTP: These HTTP headers were set: X-aws-ec2-metadata-token-ttl-seconds: 10
HTTP: Fetch(http://000.000.000.000/latest/meta-data/iam/security-credentials/)
HTTP: Fetch(http://000.000.000.000/latest/api/token)
HTTP: These HTTP headers were set: X-aws-ec2-metadata-token-ttl-seconds: 10
HTTP: Fetch(http://000.000.000.000/latest/meta-data/iam/security-credentials/)
HTTP: Fetch(http://000.000.000.000/latest/api/token)
HTTP: These HTTP headers were set: X-aws-ec2-metadata-token-ttl-seconds: 10
HTTP: Fetch(http://000.000.000.000/latest/meta-data/iam/security-credentials/)
HTTP: Fetch(http://000.000.000.000/latest/api/token)
HTTP: These HTTP headers were set: X-aws-ec2-metadata-token-ttl-seconds: 10
HTTP: Fetch(http://000.000.000.000/latest/meta-data/iam/security-credentials/)
```

**Comment by jorisvandenbossche** [comment]
That's strange that it works with fiona but not geopandas. As far as I see, if you pass a string with s3 URI, we should pass that through to fiona as is (https://github.com/geopandas/geopandas/blob/76e886ec23ddd12a032c933ab08b18693a8144a1/geopandas/io/file.py#L170-L199). We check for urls (to download the file), or file like objects (to read the data) and for file paths for zipped files (to add a zip scheme). But for "s3://.." paths, that should be passed to `fiona.open` unmodified.

One thing that is different compared to your `fiona.open(..)` is that in geopandas this is wrapped in a Env():

```
with fiona.Env():
    fiona.open("s3://path/to/shapefile.shp")
```

That might change some settings / env variables?

**Comment by gcaria** [comment]
That's a useful point you're making @jorisvandenbossche 

Indeed I can reproduce the error with the two lines of code you posted

**Comment by rbuffat** [comment]
I never used Fiona with S3, and I currently don't have access to a S3 bucket. This makes it a bit difficult to test.

@gcaria  Could you check if both of these work:

```
import boto3

from fiona.session import AWSSession
import fiona

with fiona.Env(session=AWSSession(boto3.Session())):
    fiona.open("s3://path/to/shapefile.shp")
```

and 

```
import boto3

from fiona.session import AWSSession
import fiona

with fiona.Env(session=AWSSession(boto3.Session())):
    with fiona.Env():
        fiona.open("s3://path/to/shapefile.shp")
```

See also https://fiona.readthedocs.io/en/latest/manual.html#cloud-storage-credentials

**Comment by gcaria** [comment]
Both the snippets run fine and open correctly the shapefile. I have also tested that setting explicitly the AWS credentials (as in the link you've posted) works:


```
from fiona.session import AWSSession
import fiona

with fiona.Env(
    session=AWSSession(aws_access_key_id="key", aws_secret_access_key="secret")
):
    fiona.open("s3://path/to/shapefile.shp")
```

so I guess it boils down to how `fiona.Env` sets credentials for accessing data stored in AWS S3.

**Comment by rbuffat** [comment]
If the following works

```
import boto3

from fiona.session import AWSSession
import fiona

with fiona.Env(session=AWSSession(boto3.Session())):
    with fiona.Env():
        fiona.open("s3://path/to/shapefile.shp")
```

I would expect that the following should work too:

```
from fiona.session import AWSSession
import fiona

with fiona.Env(session=AWSSession(boto3.Session())):
    gpd.read_file("s3://path/to/shapefile.shp")
```

**Comment by LewisJarrod** [comment]
Just chiming in to describe the deployment a little, we seem to be only having issues on our JupyterHub where we are using temporary credentials generated for the IAM Role assigned to the compute resource.  In other places where Access Key/Secret Keys are being directly used the issue does not seem to arise.

**Comment by sgillies** [comment]
@LewisJarrod I wonder if this is related to https://github.com/rasterio/rasterio/issues/1521? The fiona 1.8.x series lacks that fix, and I will look into that.

@rbuffat's suggestion of creating a new session object for each use of fiona is the workaround for now.

**Comment by LewisJarrod** [comment]
Thanks, and I can confirm we are using version 1.8.21.  We will implement the workaround for now!

**Comment by RichardScottOZ** [comment]
Thanks for the tips - currently using 1.8.18 [I think], helped with a file not recognised error.
