### ISSUE TITLE
Fiona 1.8.21 installation issues in Docker

### ISSUE THREAD

**Issue by kapoor1992** [Toblerity/Fiona#1062]
## Expected behavior and actual behavior.

Fiona 1.8.21 fails to install on Docker using pip command. Actual resulting error:

```
Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /azureml-envs/azureml_7840fb85c0c6f77a3d0d23e7a62ca83b/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8fumux68/fiona/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8fumux68/fiona/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m59wolxf
         cwd: /tmp/pip-install-8fumux68/fiona/
    Complete output (2 lines):
    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Steps to reproduce the problem.

The reproduction steps are when Fiona is installed as part of an Azure ML inference script deployment. For this reason, I unfortunately can't give a stripped down version of easy-to-follow steps.

## Operating system

Docker image: `mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04`

## Fiona and GDAL version and provenance

Fiona - 1.8.21 installed via pip
GDAL - Not installed

## Important notes

GDAL was never explicitly specified for installation and so it might seem obvious to add that to the pip installation file as well. That threw other errors (sorry, I don't have them anymore), but what does work in installing Fiona 1.8.21 is to change my dockerfile from:
```
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
RUN echo "test"
```
to:
```
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y libgdal-dev && rm -rf /var/lib/apt/lists/*
RUN export CPLUS_INCLUDE_PATH=/usr/include/gdal
RUN export C_INCLUDE_PATH=/usr/include/gdal
```
But this significantly slows down deployment time (doubles easily).
Also, just using Fiona 1.8.20 works perfectly fine, without having to install GDAL explicitly.

Is there some problem with how Fiona 1.8.21 searches for the GDAL config in Docker?

**Comment by sgillies** [comment]
We didn't change the way fiona's setup script searches for GDAL in 1.8.21. It's exactly the same as in 1.8.20.

**Comment by philsc** [comment]
@sgillies , do you have a recommended work around? For now I'm pinning Fiona at 1.8.20 in our environment because that one builds fine. 1.8.21 does not.

**Comment by sgillies** [comment]
@philsc thanks for writing back! I thought about this again and realized that I'd missed a pair of potentially important points. While fiona's setup code hasn't changed, we *did* make a change for the wheels we publish to PyPI. Fiona 1.8.20 wheels use the "manylinux1" profile (based on CentOS 5). We could no longer build new versions of dependencies for this very old profile of Linux and have switched (for 1.8.21) to "manylinux2014". We also did not build wheels for Python 3.6 (EOL), trading it for Python 3.10.

I think the lack of Python 3.6 wheels explains the situation between than the Linux baseline. Is upgrading to 3.7 an option for you?

**Comment by philsc** [comment]
Ah, that would explain it!   We're in the process of upgrading, but things are slow.
What do you think about marking 1.8.21 as Python 3.7+ only? I don't know how reasonable that is, but it would be one relatively clean solution.
Either way, I appreciate the update! Pinning to 1.8.20 on our end works for now :+1:

**Comment by rbuffat** [comment]
I can't reproduce this:

Dockerfile:
```
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
RUN pip install Fiona
RUN pip freeze
 
```

```
Step 1/3 : FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
latest: Pulling from azureml/openmpi4.1.0-ubuntu20.04
08c01a0ec47e: Pull complete 
3e61f87463dc: Pull complete 
bc47582c1ece: Pull complete 
0c47788ed6b9: Pull complete 
a8d8bcf26956: Pull complete 
576c76df97bd: Pull complete 
bcfb688095e6: Pull complete 
e806c109b0a9: Pull complete 
b3003b67731f: Pull complete 
Digest: sha256:3b083020dd28487ef3b7a772aa7ca03a281458c5e1dfab603afe88adf0b36893
Status: Downloaded newer image for mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
 ---> 71bed7a30f12
Step 2/3 : RUN pip install Fiona
 ---> Running in a0e002ceac87
Collecting Fiona
  Downloading Fiona-1.8.21-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)
Collecting click>=4.0
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: six>=1.7 in /opt/miniconda/lib/python3.7/site-packages (from Fiona) (1.15.0)
Requirement already satisfied: setuptools in /opt/miniconda/lib/python3.7/site-packages (from Fiona) (50.3.1.post20201107)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Collecting attrs>=17
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Requirement already satisfied: certifi in /opt/miniconda/lib/python3.7/site-packages (from Fiona) (2020.6.20)
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-4.10.1-py3-none-any.whl (17 kB)
Collecting zipp>=0.5
  Downloading zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting typing-extensions>=3.6.4; python_version < "3.8"
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Installing collected packages: zipp, typing-extensions, importlib-metadata, click, munch, click-plugins, cligj, attrs, Fiona
Successfully installed Fiona-1.8.21 attrs-21.4.0 click-8.0.3 click-plugins-1.1.1 cligj-0.7.2 importlib-metadata-4.10.1 munch-2.5.0 typing-extensions-4.0.1 zipp-3.7.0
Removing intermediate container a0e002ceac87
 ---> 3d6badc86580
Step 3/3 : RUN pip freeze
 ---> Running in 14809ad98b31
attrs==21.4.0
brotlipy==0.7.0
certifi==2020.6.20
cffi @ file:///tmp/build/80754af9/cffi_1605538037615/work
chardet @ file:///tmp/build/80754af9/chardet_1605303159953/work
click==8.0.3
click-plugins==1.1.1
cligj==0.7.2
conda==4.9.2
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018138503/work
cryptography @ file:///tmp/build/80754af9/cryptography_1605544449973/work
Fiona==1.8.21
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
importlib-metadata==4.10.1
munch==2.5.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1605545627475/work
PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
ruamel-yaml==0.15.87
six @ file:///tmp/build/80754af9/six_1605205313296/work
tqdm @ file:///tmp/build/80754af9/tqdm_1605303662894/work
typing-extensions==4.0.1
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
zipp==3.7.0
Removing intermediate container 14809ad98b31
 ---> c2054d84c3c8
```

**Comment by rbuffat** [comment]
It looks like the docker image installs a conda environment with python 3.7:
https://github.com/Azure/AzureML-Containers/blob/master/base/cpu/openmpi4.1.0-ubuntu20.04/Dockerfile#L61-L68

**Comment by kapoor1992** [comment]
@philsc, check out the dockerfile in my original question if you really want to make 1.8.21 work and see how it goes. I like your idea on making the new version compatible with 3.7+ too, is this a reasonable change @sgillies?
