### ISSUE TITLE
Windows PyPi Wheels needed imminently ( <= 9 days ) to avoid major developer disruption

### ISSUE THREAD

**Issue by tigerhawkvok** [Toblerity/Fiona#1119]
## Expected behavior and actual behavior.

- Expected: Native PyPi wheels
- Actual: [Redirects to Christoph Gohlke's site](https://github.com/Toblerity/Fiona#windows), which is out of funding and will shut down in less than or equal to 9 days

> Binary installers are available at https://www.lfd.uci.edu/~gohlke/pythonlibs/#fiona and coming eventually to PyPI.

![image](https://user-images.githubusercontent.com/165937/174888702-ae04bc61-a35c-454b-a1f6-a4036d66ea39.png)

## Steps to reproduce the problem.

Attempt to install Fiona on Windows

## Operating system

Windows, any

## Fiona and GDAL version and provenance

GDAL 3.4.2 via precompiled binary from Gohlke's site

**Comment by jorisvandenbossche** [comment]
See also https://github.com/Toblerity/Fiona/discussions/1073
