### ISSUE TITLE
Improve API for unsupported drivers

### ISSUE THREAD

**Issue by rbuffat** [Toblerity/Fiona#1124]
[Currently, we document how to use "unsupported" GDAL drivers by manually patching  `fiona.drvsupport.supported_drivers`](https://github.com/Toblerity/Fiona/blob/maint-1.9/docs/manual.rst#78unsupported-drivers). While this works, this is more sort of a hack and supported_drivers was not intended to be modified by users.  

A "nicer" API would be to add a flag to fiona.open. If such a flag is set, driver checks are ignored. E.g.

```
with fiona.open("file.kmz", allow_unsupported_drivers=True) as collection:
    pass
```

@sgillies if you are in favor of this I could create a PR.

**Comment by sgillies** [comment]
Once upon a time, "unsupported" meant that I considered a driver to be a source of headaches and user pain. Some OGR drivers have bad default behavior, giving unexpected results unless they are tuned with multiple config options, options which aren't always documented thoroughly. GML or GMLAS, for example (which we've enabled!), or PostGIS https://gdal.org/drivers/vector/pg.html. The user experience of OGR drivers varies. The situation is better now that GDAL is removing unmaintained drivers, but some difficult to use drivers remain.

`allow_unsupported_drivers` would be handy. Users will definitely use it and if they use it all the time, maybe it becomes a defacto default. And then, do we really want to have to support all of, for example, PostGIS's config options in our documentation and support efforts. Wouldn't Python programmers be better off using psycopg or something?
