### ISSUE TITLE
Session starts too fast, crs is not set

### ISSUE THREAD

**Issue by AniaKru95** [Toblerity/Fiona#1129]
## Expected behavior and actual behavior.

Fiona sometimes sets crs property to None. 
Fiona should sets the variable properly. 

## Steps to reproduce the problem.

I found an issue by calling geopandas function.
```
x = geopandas.read_file(response) # variable response's type is BytesIO
```
I debbuged that problem occures in fiona/collection.py
![obraz](https://user-images.githubusercontent.com/84393751/180953330-aa91e07c-e109-48d5-aceb-3695906d824f.png)
When I'm in debug mode and I execute code step by step, self.crs property sets to {}.
When I'm turn off debug mode and execute code, self.crs property sets to None and lead to exception:
![obraz](https://user-images.githubusercontent.com/84393751/180955241-26194920-c903-4301-8edb-92ec2179bcb9.png)
After starting session, Collection class's properties have been set properly, but sometimes not. I think, it could be assiociated with computer parameters. 

## Operating system

System: Windows 10 Pro, 21H2
Installed: 24.08.2021
OS Build: 19044.1826, Windows Feature Experience Pack 120.2212.4180.0
Processor: 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz   1.50 GHz
RAM: 16,0 GB (available: 15,7 GB)
System: 64-bit, processor x64

**In above system, an issue occured. 
I tested on other computers. Below works properly:**

System: Windows 10 Pro, 21H2
Installed: 25.‎03.‎2021
OS Build: 19044.1826, Windows Feature Experience Pack 120.2212.4180.0
Processor: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
RAM: 16,0 GB (available: 15,9 GB)
System: 64-bit, processor x64

AND

System: Windows 10 Pro, 21H2
Installed: 13.‎04.‎2021
OS Build: 19044.1826, Windows Feature Experience Pack 120.2212.4180.0
Processor: AMD EPYC 7551 32-Core Processor  2.00 GHz
RAM: RAM 8,00 GB (dostępne: 6,04 GB)
System: 64-bit, processor x64

## Fiona and GDAL version and provenance
Python 3.7.9
Fiona 1.8.21
GDAL 3.4.1
Pyproj 3.2.1
Geopandas 0.10.2

**Libraries are the same on every computer**

**Comment by rbuffat** [comment]
I currently can't think of anything that should work differently in Fiona in "Debug" mode, except that your setup differs between normal execution and debugging. 

```
`proj_create: no database context specified`
````
This error message implies that there is probably something wrong with the setup of proj.  Could you check if your environment variables are the same, especially `PROJ_LIB`.

**Comment by AniaKru95** [comment]
Yes, it works. 
On one computer, I had different PROJ_LIB path than the others.
I set PROJ_LIB variable to appropriate path and issue dissapeared.

Thanks a lot!
