### ISSUE TITLE
libarrow.so.800: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by josefson** [Toblerity/Fiona#1144]
## Expected behavior and actual behavior.

Upon ```import fiona``` 
I get:
```
libarrow.so.800: cannot open shared object file: No such file or directory
libarrow.so.800: cannot open shared object file: No such file or directory
libarrow.so.800: cannot open shared object file: No such file or directory
libarrow.so.800: cannot open shared object file: No such file or directory
libarrow.so.800: cannot open shared object file: No such file or directory
libarrow.so.800: cannot open shared object file: No such file or directory
libarrow.so.800: cannot open shared object file: No such file or directory
libarrow.so.800: cannot open shared object file: No such file or directory
```

## Operating system

Archlinux 5.19.11-arch1-1

## Fiona and GDAL version and provenance

Fiona 1.8.21 from archlinux repositories
GDAL 3.5.1 from archlinux repositories

**Comment by sgillies** [comment]
@josefson there is no code in Fiona that accesses libarrow directly. It's a dependency of GDAL/OGR. I suspect this is an archlinux packaging issue, or a GDAL bug that manifests on archlinux. I'm going to close this as it's not solvable here.
