### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [Toblerity/Fiona#1146]
[Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html) is now in release candidate phase and will be released in two weeks. Support is ramping up, both in the scientific suite (with NumPy, Pandas, SciPy, Matplotlib and Seaborn already supporting 3.11, among others), as well in the geospatial suite (with Shapely CI is passing). It would be great if Fiona also supported Python 3.11 and made wheels available on PyPI.

#1145 might be a first step.

**Comment by EwoutH** [comment]
Duplicate of #1146

**Comment by sgillies** [comment]
@EwoutH thanks for advocating for this and leading the way! The latest stable shapely and rasterio releases have wheels for 3.11 and fiona 1.9a3 does, too.

**Comment by EwoutH** [comment]
Awesome! I just installed Fiona, Shapely, Rasterio and GeoPandas all on Python 3.11, before the official release.

With 3.10 we were already in the new year before that was the case, so this offers a lot of potential for Python 3.11 adoption on the geospatial stack!

Do you think a backport to the 1.8 branch is possible, and release a stable patch version of Fiona with 3.11 wheels?

**Comment by sgillies** [comment]
@EwoutH I've spent 110% of my monthly wheel building budget already :smile:

If the naive attempt at https://github.com/sgillies/fiona-wheels/actions/runs/3291788577 works, I will upload the artifacts. If not can you think about trying the 1.9a3 wheels?
