### ISSUE TITLE
slow layer writes when writing features with hundreds of columns

### ISSUE THREAD

**Issue by fcostin** [Toblerity/Fiona#1158]
## Expected behavior and actual behavior.

I attempted to write a 35,000 record polygon dataset with 400 columns to FlatGeobuf using Fiona 1.8.21 (via geopandas). It took a couple of minutes to query and download this dataset from a remote server, and turn it into a geopandas GeoDataFrame in ram, so I expected it might take a minute or so to write. The write operation using geopandas engine="fiona" kept running for 10 minutes, until I interrupted it.

The current unreleased Fiona in master branch (rev 9c8fe736) appears to be substantially faster than Fiona 1.8.21.

## Steps to reproduce the problem.

I am unable to share the original dataset, but here is a script to create synthetic data with similar characteristics and write it:

```python3
# pip install geopandas
# pip install pyogrio

import numpy
import pandas as pd
import geopandas as gpd
import random
import shapely
import string

ALPHABET = list(string.ascii_lowercase)


def make_vocab(n, w):
    return numpy.asarray([''.join(random.sample(ALPHABET, w)) for _ in range(n)], dtype=object)


def make_random_data(n_rows: int, n_cols: int, w: int):
    k = 4321
    vocab = make_vocab(n=k, w=16)
    data = {}
    for i in range(n_cols):
        col_values = [vocab[((i + (i*j))%k)] for j in range(n_rows)]
        col_name = 'col_%d' % (i, )
        data[col_name] = pd.Series(col_values)

    x_coords = numpy.random.uniform(-1.0, 1.0, (n_rows, ))
    y_coords = numpy.random.uniform(-1.0, 1.0, (n_rows, ))

    geom = [shapely.geometry.Point((x, y)) for (x, y) in zip(x_coords, y_coords)]

    return gpd.GeoDataFrame(data=data, geometry=geom)


def main():
    print('making random data...')
    n_rows = 25000
    n_cols = 400
    w = 16
    gpd = make_random_data(n_rows, n_cols, w)
    print('writing...')
    driver='FlatGeobuf'
    engine='fiona'
    # engine='pyogrio'
    gpd.to_file('data.fgb', driver=driver, engine=engine)


if __name__ == '__main__':
    main()
```

## Operating system

Ubuntu 22.04.1 LTS

## Fiona and GDAL version and provenance

Slow write performance noticed with Fiona 1.8.21  installed from PyPI using pip version 9.0.1.

## Potential speedups

There appear to be some opportunities to make these writes faster with small, incremental patches:

`OGRFeatureBuilder` `build` method in `fiona/ogrext.pyx` is called for each record during writes, but some of the computation - determining field indices or normalising type names, is not specific to the record, it is specific to the layer schema, and could be cached instead of repeatedly computing it per record.

**Comment by sgillies** [comment]
@fcostin I appreciate the report! Even though GeoPandas will probably stop using Fiona in the future, I agree that some optimizations would be good.
