### ISSUE TITLE
test_no_append_driver_cannot_append fails

### ISSUE THREAD

**Issue by dotlambda** [Toblerity/Fiona#1164]
https://gist.github.com/risicle/2631e23beaf492e95d6d1ef44d3d789e

## Operating system

NixOS 22.11

## Fiona and GDAL version and provenance

Fiona 1.8.22 installed via Nix
GDAL 3.6.0.1 installed via Nix

**Comment by rbuffat** [comment]
Will be fixed with https://github.com/Toblerity/Fiona/pull/1122
