### ISSUE TITLE
Update README.rst with infos regarding to GDAL embedded wheels for windows

### ISSUE THREAD

**Issue by tgrandje** [Toblerity/Fiona#1166]
## Expected behavior and actual behavior.

No bug here, but an out of date documentation (see. discussion on [fiona.groups.io](https://fiona.groups.io/g/main/topic/95321716)).

The actual documentation doesn't acknowledge that there are now windows wheels on pypi and that they include a GDAL shared library. 

The documentation might also benefit from a paragraph stating what could and what couldn't be done regarding to diverse GDAL's bindings (osgeo and all it's dependencies).

**Comment by sgillies** [comment]
Done!
