### ISSUE TITLE
Fiona *silently* fails to write to s3 when bucket doesn't exist.

### ISSUE THREAD

**Issue by spolloni** [Toblerity/Fiona#1169]
**NOTE**:  _I suspect this may actually be a [GDAL](https://github.com/OSGeo/gdal) issue, so please advise accordingly_!

## Expected behavior and actual behavior.

I would expect Fiona to fail explicitly when attempting to write to an s3 bucket that doesn't exist. I was dumbfounded by this behavior as I inadvertently misspelled the bucket name but got no feedback about my mistake -- the script executed as if it had succeeded.

## Steps to reproduce the problem.

```
import fiona

with fiona.Env(), fiona.open(
    f's3://non-existing-bucket/test.geojson',
    mode='w',
    driver='GeoJSON',
    schema={'geometry': 'Point'},
) as f:
    f.writerecords([
        {
            'id': '0', 
            'type': 'Feature', 
            'geometry': {'type': 'Point', 'coordinates': (1.0, 2.0)}
        }
    ])
```

## More Context

GDAL does give me some feedback when attempting to do something similar:
```
❯ ogr2ogr /vsis3/non-existing-bucket/test.geojson ./test.geojson
ERROR 1: DoSinglePartPUT of /vsis3/non-existing-bucket/test.geojson failed
``` 
**However**,  the above returns a zero exit code.  [Here](https://github.com/OSGeo/gdal/blob/8633aa6f0c57d38b768059ac5dc137531421b9d7/port/cpl_vsil_s3.cpp#L1536-L1538) is the only instance in the GDAL source code that mentions `DoSinglePartPUT` and it appears to raise a `CPLError`. I'm therefore wondering why this block: 

https://github.com/Toblerity/Fiona/blob/22d5b8fd7f85ce72bf1b6552babf50e3844d4240/fiona/_shim3.pyx#L109-L116

does not raise anything when called within `WritingSession.start()`

## Operating system & Fiona and GDAL version and provenance

Testing with docker I found this behavior to occur pretty consistently across Ubuntu and Fiona and GDAL versions.

**Comment by rouault** [comment]
There was indeed a ogr2ogr issue, solved per https://github.com/OSGeo/gdal/pull/6885, but that won't fix Fiona. Fiona needs to do something similar. I've also filed https://github.com/OSGeo/gdal/issues/6886 as the current situation is non-ideal

**Comment by sgillies** [comment]
@spolloni in this case, GDALCreate doesn't cause any S3 API methods to be called, so no error can happen. The S3 PUT happens later, during GDALClose. It would be good if GDAL would fail faster, but it would have to make an extra request to do so and that would slow down the happy path.

**Comment by spolloni** [comment]
> The S3 PUT happens later, during GDALClose.

gotcha! and thanks for https://github.com/Toblerity/Fiona/commit/04ad6c8960c84ee6a2d29acd9e35e79bde193750

**Comment by rouault** [comment]
Cf proposed GDAL "RFC 91: GDALDataset::Close() method": https://github.com/OSGeo/gdal/pull/7108
