### ISSUE TITLE
fatal error: 'longintrepr.h' file not found

### ISSUE THREAD

**Issue by rgreinho** [Toblerity/Fiona#1185]
## Expected behavior and actual behavior.

When trying to install our project, `poetry install`  fails with the following error:

```bash
building 'fiona.schema' extension
        creating build/temp.macosx-13-arm64-cpython-311
        creating build/temp.macosx-13-arm64-cpython-311/fiona
        clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/Cellar/gdal/3.6.2_2/include -I/Users/rgreinhofer/projects/PeopleForBikes/brokenspoke-analyzer/.venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c fiona/schema.c -o build/temp.macosx-13-arm64-cpython-311/fiona/schema.o
        fiona/schema.c:222:12: fatal error: 'longintrepr.h' file not found
          #include "longintrepr.h"
                   ^~~~~~~~~~~~~~~
        1 error generated.
        error: command '/usr/bin/clang' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for Fiona
  Failed to build Fiona
```

## Steps to reproduce the problem.

The project is located here: https://github.com/PeopleForBikes/brokenspoke-analyzer, so to reproduce this issue, simply run:

```bash
cd /tmp
git clone git@github.com:PeopleForBikes/brokenspoke-analyzer.git
poetry install
```

## Operating system

System Version: macOS 13.1 (22C65) with M1 chip.
Python 3.11.1

## Fiona and GDAL version and provenance

 GDAL 3.6.2 installed via Homebrew

```bash
╭ brokenspoke-analyzer on  main via 🐍
╰❯ brew info gdal
==> gdal: stable 3.6.2 (bottled), HEAD
Geospatial Data Abstraction Library
https://www.gdal.org/
Conflicts with:
  avce00 (because both install a cpl_conv.h header)
  cpl (because both install cpl_error.h)
/opt/homebrew/Cellar/gdal/3.6.2_2 (448 files, 27.4MB) *
  Poured from bottle on 2023-01-26 at 08:25:20
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gdal.rb
License: MIT
==> Dependencies
Build: cmake ✘, pkg-config ✔
Required: apache-arrow ✔, cfitsio ✔, epsilon ✔, expat ✔, freexl ✔, geos ✔, giflib ✔, hdf5 ✔, jpeg-turbo ✔, jpeg-xl ✔, json-c ✔, libdap ✔, libgeotiff ✔, libheif ✔, libpng ✔, libpq ✔, libspatialite ✔, libtiff ✔, libxml2 ✔, netcdf ✔, numpy ✔, openexr ✔, openjpeg ✔, pcre2 ✔, poppler ✔, proj ✔, python@3.11 ✔, sqlite ✔, unixodbc ✔, webp ✔, xerces-c ✔, xz ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 22,567 (30 days), 69,175 (90 days), 262,259 (365 days)
install-on-request: 19,457 (30 days), 59,194 (90 days), 223,799 (365 days)
build-error: 101 (30 days)
```

**Comment by sgillies** [comment]
@rgreinho we don't have any wheels for M1 on PyPI yet, which means that pip (used by poetry) will try to install from the source distribution. In that case, you need to do a little extra build configuration that poetry won't do for you. We're in the middle of a documentation overhaul, so https://github.com/Toblerity/Fiona/blob/maint-1.9/docs/install.rst#advanced-installation hasn't made it to the stable docs yet, but the info you need is there.

**Comment by jorisvandenbossche** [comment]
FWIW we have Mac arm64 (M1) wheels for [pyogrio](https://github.com/geopandas/pyogrio/), so @rgreinho that might potentially be a short-term alternative to prevent having to install from source, and @sgillies feel free to reuse that approach (it's using the same workflow as the windows wheels, which you are already using)

**Comment by Schamschula** [comment]
While trying to add `py311-fiona` to MacPorts I ran into the same issue.

See: https://trac.macports.org/ticket/66782

Build log: https://build.macports.org/builders/ports-12_arm64-builder/builds/84345/steps/install-port/logs/stdio

**Comment by Schamschula** [comment]
The update to version 1.8.22 fixed this. See: https://github.com/macports/macports-ports/commit/4fb784bdc08b027bb89ebd3524bfa06058d63a72

**Comment by sgillies** [comment]
So, a quick search yielded this: https://github.com/aio-libs/aiohttp/issues/6600. @Schamschula is there a chance that your Cython version is < 0.29.5?

**Comment by Schamschula** [comment]
Nope:

> port installed py311-cython
> The following ports are currently installed:
>   py311-cython @0.29.33_0 (active)

However, as I mentioned above, there is no such issue with the latest release.

**Comment by sgillies** [comment]
@rgreinho we've got `macosx_11_0_arm64` wheels on PyPI now for Pythons 3.8-3.11. Their tests passed on a Cirrus CI M1 Monterey runner (macos 12), so I'm optimistic they'll work for you.

**Comment by rgreinho** [comment]
Awesome! It worked. Thank you very much!
