### ISSUE TITLE
Tags won't show in QGIS like Rasterio tags

### ISSUE THREAD

**Issue by CharlesAuthier** [Toblerity/Fiona#1207]
Hi, I am using the new tags function from 1.9.1 and I noticed that when we save a tag inside a gpkg using Fiona it doesn’t show up in the layer properties like Rasterio. 

When using Rasterio tag function, we can see that the tag information shows up in QGIS properties layer under the `Information - Information from provider - More Information`. But when we use the Fiona tag function, we don’t see it appear under `Information - Information from provider - More Information`. I still can go fetch the information using a python script, but I was wondering if it was possible to make it appear in the metadata or properties in QGIS?

I am opening an issue here but if its a QGIS issue let me know I will close it and open one in QGIS.

Thanks

**Comment by sgillies** [comment]
@CharlesAuthier are you able to set metadata that appears in QGIS using other means? What tag name are you using?

I'm not familiar with the QGIS code. I found this one instance of QGIS using GDALGetMetadataItem to get a "DESCRIPTION" tag from the default namespace at https://github.com/qgis/QGIS/blob/108934648f2d7e8d4edace3888d910e6a8e1e83f/src/core/providers/ogr/qgsogrproviderconnection.cpp#L241. If there were a DESCRIPTION tag set on your Fiona collection I would naively expect that code to find it.

**Comment by CharlesAuthier** [comment]
HI @sgillies, I can see other metadata just not the added tag. I have try multiples name as namespace but nothing. 
Tomorrow I will try  "DESCRIPTION" tag thanks for your help.

**Comment by CharlesAuthier** [comment]
@sgillies It work thanks
