### ISSUE TITLE
"CPLE_AppDefinedError: buildEllipsoid: non double value" when trying to read a shapefile using geopandas.read_file()

### ISSUE THREAD

**Issue by Royal4224** [Toblerity/Fiona#1208]
## Expected behavior and actual behavior.

I expected to read a shapefile and get a dataframe, but I received a CPLE_AppDefinedError: buildEllipsoid: non double value
![image](https://user-images.githubusercontent.com/68200979/220200634-3e6bff0f-f751-42b1-9c9c-6980596c8152.png)

## Steps to reproduce the problem.

Download the folder from this website and choose a shapefile from it to run with the code below: https://zenodo.org/record/5831940#.Y9QmOuLMK3I
This is a decently large file (a couple GB's at least), so apologies. I suspected that there was an issue with the shapefiles in this folder, but I've grabbed the fields from the ones I've tested and they look fine. Let me know if I can clarify anything and I appreciate any help!

import geopandas as gpd

df = gpd.read_file("/Users/roy/Downloads/2014_nei_isrm_emissions/pt_oilgas.shp")

The following code, for me, reproduced the same error:

import fiona

with fiona.open("/Users/roy/Downloads/2014_nei_isrm_emissions/pt_oilgas.shp") as src:
    print(src.crs_wkt)
  
## Operating system

For example: Mac OS Monterey [12.6]( #url)

## Fiona and GDAL version and provenance

Fiona  1.9.1  installed via  conda-forge
GDAL 3.6.2 installed via  conda-forge

**Comment by rouault** [comment]
This is non-conformant WKT content in Shapefile .prj using "inf" as the value for inverse flattening. A google search shows that there are a number of references to such syntax, hence a fix in PROJ per https://github.com/OSGeo/PROJ/pull/3626

**Comment by Royal4224** [comment]
I see; does that mean I should download the new version of PROJ once that fix is committed? I guess I'm just wondering what my next steps are!

**Comment by sgillies** [comment]
@Royal4224 a possible workaround is to replace the string `SPHEROID["Spherical_Earth",6370997,"inf"]` with `SPHEROID["Spherical_Earth",6370997,0]` in the .prj files. According to https://docs.ogc.org/is/18-010r7/18-010r7.html we are supposed to use `0` for spherical ellipsoids, not `"inf"`.

**Comment by Royal4224** [comment]
Changing that "inf" to 0 in the .prj files let me read the corresponding shapefiles with geopandas. Thank you!

**Comment by sgillies** [comment]
Excellent! Thanks for confirming @Royal4224.

**Comment by arushisharma92** [comment]
Hi everyone, 

How do we replace the string SPHEROID["Spherical_Earth",6370997,"inf"] with SPHEROID["Spherical_Earth",6370997,0] in the .prj files? I am facing a similar issue.

**Comment by Royal4224** [comment]
@arushisharma92 You should be able to directly edit the .prj file(s) with any text editor (ie. TextEdit on Mac, Notepad on Windows). That's how I was able to use the workaround.

**Comment by arushisharma92** [comment]
@Royal4224, thanks so much. It works.
