### ISSUE TITLE
Enable CLI commands that open datasets to take open options such as allow_unsupported_drivers

### ISSUE THREAD

**Issue by eric-g-97477** [Toblerity/Fiona#1209]
I know it is possible when using Fiona via python directly, but how about when using fio?

**Comment by sgillies** [comment]
@eric-g-97477 good question! In #1126 we made it easier to use any format driver, but we haven't adapted all the CLI commands to take this file opening option. I'm going to rename this issue to reflect that we should do that for the next release.
