### ISSUE TITLE
Changelog is out-of-date

### ISSUE THREAD

**Issue by allanlewis** [Toblerity/Fiona#1210]
## Expected behavior and actual behavior.

The changelog should be up-to-date, including v1.9.1 at time of writing.

## Steps to reproduce the problem.

Go to https://fiona.readthedocs.io/en/latest/README.html#changes and see that the changelog only goes up to v1.8.11.

## Operating system

n/a

## Fiona and GDAL version and provenance

n/a

**Comment by sgillies** [comment]
Thanks for the report @allanlewis !

**Comment by sgillies** [comment]
The docs will be up to date again when 1.9.2 is tagged.

**Comment by allanlewis** [comment]
Thanks, @sgillies 🙏
