### ISSUE TITLE
Feature is not JSON serializable

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Fiona#1229]
This is a regression with Fiona 1.9, e.g. [here](https://github.com/perrygeo/python-rasterstats/blob/57c99fa269e7b4e450f2466b820c0afded7afebf/tests/test_io.py#L139), where Fiona <1.9 could do this:
```python
with fiona.open(polygons, "r") as src:
    indata = [f for f in src]
indata = json.dumps(indata[0])
```
but with Fiona 1.9.x it will raise:
> TypeError: Object of type Feature is not JSON serializable

This is because Feature is inherited from MutableMapping. See this [discussion here](https://discuss.python.org/t/json-does-not-support-mapping-and-mutablemapping/2829).

Attempts like this don't get there either:
```python
with fiona.open(polygons, "r") as src:
    feat = next(iter(src))
dfeat = dict(feat)
# {'geometry': <fiona.model.Geometry at 0x...>, 'id': '0', 'properties': <fiona.model.Properties at 0x...>}
json.dumps(dfeat)
```
> TypeError: Object of type Geometry is not JSON serializable

**Comment by perrette** [comment]
Possibly related to this, I'm also puzzled by recent (?) changes to fiona:

    countries = list(fiona.open('datasets/gaul0_asap', encoding='utf-8'))
    
would load a list of geojson dictionaries in a previous version of fiona (I'm having trouble to roll back so I can't tell in which). Now each element is a class:

    <fiona.model.Feature at 0x7fb847887d90>

and the same goes for properties etc. While it certainly allows an abstract data model and a variety of I/O drivers, I do not find any obvious method how to convert it to modifiable (and serializable) python objects, though I can see shapely finds its way. It's also different from what you'd expect from [the documentation](https://fiona.readthedocs.io/en/stable/manual.html#reading-vector-data).

**Comment by perrette** [comment]
Ok thanks. Can something like `ObjectEncoder().default(feature)` work or is a json round trip necessary to convert to genuine, modifiable python objects? (besides doing the conversion by hand as @mwtoews suggested elsewhere).

**Comment by sgillies** [comment]
@perrette that should work.
