### ISSUE TITLE
Document that model classes rely on ObjectEncoder for JSON serialization

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#1230]
And other details about the model classes as well. A follow up on #1229.

**Comment by mwtoews** [comment]
Related content request is how to convert model classes to mutable dict objects. This is currently my best attempt to convert a Feature:
```python
if not isinstance(feat, dict):
    feat = dict(feat, type=feat.__class__.__name__)
    feat["properties"] = dict(feat["properties"])
    feat["geometry"] = dict(feat["geometry"])
```
a better method is welcome to add to docs.

**Comment by sgillies** [comment]
@mwtoews I will document [fiona.model.to_dict](https://github.com/Toblerity/Fiona/blob/master/fiona/model.py#L413).
