### ISSUE TITLE
Unsupported geometry type error when using OpenFileGDB driver and GDAL >=3.6.2

### ISSUE THREAD

**Issue by philiporlando** [Toblerity/Fiona#1231]
The [OpenFileGDB](https://gdal.org/drivers/vector/openfilegdb.html) driver now supports write operations with GDAL >= 3.6.x. 

## Expected behavior and actual behavior:

I am trying to use fiona to write to a `.gdb`. I expect the below code to run without error, but I'm seeing that fiona was compiled against an older version of GDAL which throws an error:

```python
import geopandas as gpd
import fiona

# Create a GeoDataFrame and save it to the File GeoDatabase
gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
gdf.to_file("test.gdb", layer="test_fc", driver="OpenFileGDB")
 ```

Error when running this interactively:

```
# Traceback (most recent call last):
#   File "fiona/ogrext.pyx", line 1238, in fiona.ogrext.WritingSession.start
# File "fiona/ogrext.pyx", line 1239, in fiona.ogrext.WritingSession.start
# File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
# fiona._err.CPLE_NotSupportedError: Unsupported geometry type
#
# During handling of the above exception, another exception occurred:
#   
#   Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1203, in to_file
# _to_file(self, filename, driver, schema, index, **kwargs)
# File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/geopandas/io/file.py", line 545, in _to_file
# _to_file_fiona(df, filename, driver, schema, crs, mode, **kwargs)
# File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/geopandas/io/file.py", line 572, in _to_file_fiona
# with fiona.open(
#   File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/fiona/env.py", line 457, in wrapper
#   return f(*args, **kwds)
#   File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/fiona/__init__.py", line 347, in open
#   colxn = Collection(
#     File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/fiona/collection.py", line 237, in __init__
#     self.session.start(self, **kwargs)
#     File "fiona/ogrext.pyx", line 1247, in fiona.ogrext.WritingSession.start
#     fiona.errors.DriverIOError: Unsupported geometry type

```

~~Error when using pytest:~~
**Edit:** this GDAL compilation error is due to accidentally running pytest outside of the desired pipenv. Calling pytest from the desired pipenv produces the same `Unsupported geometry type` error as the interactive test above.
```
# fiona.errors.DriverError: OpenFileGDB driver requires at least GDAL 3.6.0 for mode 'w', Fiona was compiled against: 3.5.3
```

## Operating System

```
# Ubuntu 22.04.2 LTS x86_64
```

## Fiona and GDAL version provenance

Installed fiona from PyPi via `pipenv install fiona`:

```
# fiona==1.9.2 ; python_version >= '3.7'; pipenv version 2023.3.20
```
Installed GDAL from the unstable version of the ubuntugis personal package archives:

```
add-apt-repository ppa:ubuntugis/ubuntugis-unstable
apt-get update
apt-get install gdal-bin libgdal-dev

gdalinfo --version
# GDAL 3.6.2, released 2023/01/02

gdal-config --version
# 3.6.2
```

Is there anything I can do to compile fiona against the latest version of GDAL? Please let me know if I can provide any additional details.

**Comment by rbuffat** [comment]
@philiporlando the binary wheel of Fiona includes a GDAL version. You can install Fiona against a GDAL installation by not using the wheel: `pip install --no-binary fiona fiona`. You can check which version Fiona is using with `fiona.show_versions()`.

**Comment by philiporlando** [comment]
@rbuffat, thanks for the suggestion!

I was able to install fiona without the binary via pipenv and it looks like it is using the newer version of GDAL: 

```
pipenv uninstall fiona
export PIP_NO_BINARY=fiona && pipenv install fiona
```
```
import fiona
fiona.show_versions()
# Fiona version: 1.9.2
# GDAL version: 3.6.2
# PROJ version: 9.1.1
#
# OS: Linux 5.15.0-67-generic
# Python: 3.10.6
```

However, I'm still seeing the same error when running the reprex above:

```
# fiona.errors.DriverError: OpenFileGDB driver requires at least GDAL 3.6.0 for mode 'w', Fiona was compiled against: 3.5.3
```

Could this be a bug with fiona, or do you think I'm missing some additional environment config? Thanks again for the help!

**Comment by rbuffat** [comment]
My first thought would be that something is broken with your environment. The function for the error message uses the same methods as fiona.show_versions(): https://github.com/Toblerity/Fiona/blob/eaf6e0a5948b2b7585b7b216c90e8704e1d88904/fiona/collection.py#L116-L130

**Comment by philiporlando** [comment]
Thanks for the suggestion. I completely wiped my pipenv and started over from scratch. I installed fiona and geopandas using the `--no-binary` flag. 

I think the previous GDAL compilation issue  was due to operator error on my part. I am using pipenv to setup my environment and pytest for testing, but I forgot to call pytest from my activated pipenv via `pipenv run pytest tests`. When I call pytest from my pipenv I'm getting the same unsupported geometry error that I was originally seeing when running the reprex interactively.

```
# E   fiona.errors.DriverIOError: Unsupported geometry type
# fiona/ogrext.pyx:1247: DriverIOError
```

It looks like my environment is configured correctly and fiona is using GDAL 3.6.

```
import fiona
fiona.show_versions()

# Fiona version: 1.9.2
# GDAL version: 3.6.2
# PROJ version: 9.1.1

# OS: Linux 5.15.0-67-generic
# Python: 3.10.6
```

Any support with troubleshooting this unsupported geometry type error would be greatly appreciated!

**Comment by philiporlando** [comment]
I've added some additional checks within my reprex to better understand the geometry types of our test geodataframe:

```python
import geopandas as gpd
import fiona

gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
print(gdf.geom_type.unique())
print(gdf.is_valid.all())
gdf.to_file(fgdb_path, layer="test", driver="OpenFileGDB")

# ['MultiPolygon' 'Polygon']
# True
```

It looks like all of our input geometries are valid. However, I'm seeing that there is a mix of MultiPolygon and Polygon geometries within the same vector. While both of these are listed as valid values within the GEOMETRY_TYPES dictionary, I'm beginning to wonder if mixing two different geometries within the same geodataframe may be causing problems when trying to write to File GeoDataBase. Coercing all MultiPolygons into Polygons appears to resolve the issue!!

```python
import geopandas as gpd
import fiona

gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))

gdf = gdf.explode()
print(gdf.geom_type.unique())
print(gdf.is_valid.all())

# ['Polygon']
# True


gdf.to_file(fgdb_path, layer="test", driver="OpenFileGDB")
```

**Comment by sgillies** [comment]
@philiporlando thanks for the follow up. "Unsupported geometry type" is the error Fiona propagates from OGR https://github.com/OSGeo/gdal/blob/5d75d7e95d0bc479611fb7a67f5c0e452ca36500/ogr/ogrsf_frmts/openfilegdb/ogropenfilegdblayer_write.cpp#L430. Curiously, the driver supports a "multipatch" type but not "multipolygon".

What do you see if you coerce all your data to be multipolygon instead of polygon?

**Comment by philiporlando** [comment]
@sgillies thanks for the details here. 

Coercing from polygon to multipolygon is working for me!

```python
import geopandas as gpd
from shapely.geometry.polygon import Polygon
from shapely.geometry.multipolygon import MultiPolygon

# Create a GeoDataFrame and save it to the File GeoDatabase
gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))

# Convert MultiPolygon to Polygon
# gdf = gdf.explode()

# Convert Polygon to MultiPolygon
gdf["geometry"] = [
    MultiPolygon([feature]) if isinstance(feature, Polygon) else feature
    for feature in gdf["geometry"]
]

print(gdf.geom_type.unique())
print(gdf.is_valid.all())

gdf.to_file("test.gdb", layer="test_fc", driver="OpenFileGDB")

# ['MultiPolygon']
# True
```

**Comment by sgillies** [comment]
@philiporlando thanks for the followup! As you suspected, the mix of types is where trouble begins. I think Fiona could try to be better about this and offer an option to normalize geometries (towards multi) when writing, as some OGR utilities do with their `-nln` options. I still don't understand why this error occurs during layer creation.

Meanwhile, we have available workarounds. Are you okay with those for now?

**Comment by philiporlando** [comment]
@sgillies, an option to promote geometries to their multi equivalent would be a helpful feature. I wish I had the expertise needed to develop something like this. 

Yes, I think we're good to close this issue for now. Thanks again for your help troubleshooting!
