### ISSUE TITLE
Fiona 1.9.4 segmentation fault on macOS

### ISSUE THREAD

**Issue by adamjstewart** [Toblerity/Fiona#1268]
## Expected behavior and actual behavior.

I would expect fiona 1.9.4 to work on all platforms, including macOS.

## Steps to reproduce the problem.

This problem was discovered by dependabot when it tried to update our repo from fiona 1.9.3 to 1.9.4. See https://github.com/microsoft/torchgeo/actions/runs/5008584270/jobs/8976614802?pr=1345 for the failing tests. Unfortunately I haven't yet managed to reproduce this outside of CI, using either wheels or building from source. It doesn't seem to affect Linux, only macOS. The tests fail every time, it isn't intermittent. Affects both Python 3.9 and 3.10.

## Operating system

macOS 12.6.5.

## Fiona and GDAL version and provenance

Fiona 1.9.4 x86_64 wheel installed from PyPI using pip version 22.0.4.

Whatever GDAL comes with the wheel.

**Comment by sgillies** [comment]
@adamjstewart Fiona's tests are run when the wheels are built https://github.com/sgillies/fiona-wheels/actions/runs/4998122459/jobs/8953218237#step:4:2339, so this may be specific to your setup. That said, the fiona wheels do now contain GDAL 3.6.4 and the rasterio wheels will have 3.5.2.

**Comment by adamjstewart** [comment]
Thanks, that could possibly explain it. I'm hoping someone else will report the same issue and figure out how to reliably reproduce it locally.

**Comment by sgillies** [comment]
@adamjstewart rasterio 1.3.7 now also has GDAL 3.6.4, so the two packages should be more compatible.

**Comment by adamjstewart** [comment]
Thanks, I'll try this in CI and see if the issue goes away.

**Comment by adamjstewart** [comment]
Just wanted to confirm that updating rasterio first did indeed solve the issue we were seeing. Thanks again for the help!
