### ISSUE TITLE
Problem reading geopackage with NAD83 CRS

### ISSUE THREAD

**Issue by isaiahwarnke** [Toblerity/Fiona#1274]
I'm analysing a geopackage of AIS data provided by MarineCadastre.gov.
The specfic dataset (approx 7 GB)  can be found at https://marinecadastre.gov/downloads/data/ais/ais2021/AISVesselTransitCounts2021.zip

## Expected behavior and actual behavior.

I expected to read the geopackage with fiona and examine/transform the data.
Fiona will read the file, and recongize the feature columns, but any action that would parse the geometry causes an error, specifically:

`CRSError: The WKT could not be parsed. SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name`

In the geopackage, the CRS is defined as ESPG:4269, and includes the following WKT definition (whitespaced for readabilty:
```
GEOGCS["GCS_North_American_1983",
            DATUM["D_North_American_1983",
                          SPHEROID["GRS_1980",
                                             6378137.0,
                                             298.257222101
                                            ]
                           ],
                PRIMEM["Greenwich",
                                 0.0
                              ],
                 UNIT["Degree",
                           0.0174532925199433
                          ]
              ] 
```
When examining what fiona is recognizng the CRS as by querying 'colxn.crs_wkt'  I see the following:
```
GEOGCS["NAD83",
              DATUM["North_American_Datum_1983",
                            SPHEROID["GRS 1980",
                                               6378137,
                                               298.257222101, 
                                               AUTHORITY["EPSG",
                                                                    "7019"
                                                                     ]
                                                ],
                              AUTHORITY["EPSG","6269"]
                            ],
              PRIMEM["Greenwich",
                              0
                             ],
              UNIT["Degree",
                        0.0174532925199433
                       ],
              AXIS["Longitude",
                        EAST
                       ],
              AXIS["Latitude",
                       NORTH]
              ]
```

## Steps to reproduce the problem.

```{python}
import fiona
geo_file = AISVesselTracks2021.gpkg
with fiona.open(geo_file, 'r') as db:
    print(db.driver)
    pprint(db.schema)
    print(len(db))
### above this, everything works. Fiona reads the file, reports schema and length correctly ###
with fiona.open(geo_file, 'r') as db:
    print(db.crs)   # this call to db.crs causes the error pasted above

```
## Operating system

Windows 11 Pro, build 22621.1702

## Fiona and GDAL version and provenance

fiona 1.9.1, installed with conda
gdal 3.6.2 installed with conda

**Comment by sgillies** [comment]
@isaiahwarnke the fiona project delegates GeoPackage details to GDAL. The message

> no such column: area_of_use_auth_name

Tells me that this is a GDAL issue, not a Fiona issue. See, for example, https://github.com/OSGeo/gdal/issues/2900.
