### ISSUE TITLE
Add option recursive to listdir

### ISSUE THREAD

**Issue by adriantre** [Toblerity/Fiona#1275]
https://github.com/Toblerity/Fiona/blob/b23fd3b94741599d4dec4f7d85238a54d362bd97/fiona/ogrext.pyx#L1921

Would it be a quick fix to use [VSIReadDirRecursive](https://gdal.org/doxygen/cpl__vsi_8h.html#ac97f19989bb33bdd54c91d3c7c1db58f) in `fiona.listdir` to enable recursive listing within VSI?

Current workaround:

```python
def listdir_vsi_recursive(root: str) -> list[str]:
    """Walk directory and return list of all files in subdirectories.
    Also supports listing filenames within a GDAL Virtual File System like
    cloud buckets. https://gdal.org/user/virtual_file_systems.html
    Args:
        root: root directory or blob in bucket
    Returns
        List of absolute filepaths withing the root
    """
    dirs = [root]
    files = []
    while dirs:
        dir = dirs.pop()
        try:
            subdirs = fiona.listdir(dir)
            dirs.extend([os.path.join(dir, subdir) for subdir in subdirs])
        except FionaValueError:
            files.append(dir)
    return files
```

Should maybe return file paths relative to root to be consistent with listdir as is. (In my workaround I include root).

**Comment by sgillies** [comment]
@adriantre I'm interested. Can you tell me more about how you would use this?

**Comment by sgillies** [comment]
@adriantre after some reflection, I'm inclined not to do this. First of all, the workaround isn't terrible, and not adding a new feature to fiona (or rasterio) saves us testing, documentation, &c. But mostly I don't want fiona and rasterio to become cloud storage APIs. GDAL's VSI system has a whole cloud storage API, but I believe Python developers are much better off using their cloud's Python SDK (boto3, for example) or a dedicated cross-cloud library like https://libcloud.apache.org/.
