### ISSUE TITLE
geopandas slowdown with latest Fiona

### ISSUE THREAD

**Issue by GNU-Dawn** [Toblerity/Fiona#1289]
## Expected behavior and actual behavior.

I have noticed slowdown opening geopackages with geopandas: If geopandas uses Fiona 1.8.22 as a dependency it takes several seconds to open a geopackage, but takes several minutes with Fiona 1.9+. I tried to investigate why this is, and it seems to be related to the Feature.__geo_interface__  property. Geopandas checks for this property using an if statement within a loop, and it seems  that this if statement is not triggered with Fiona 1.8.22 but is triggered with Fiona 1.9+. Unfortunately I could not pin down the specifics better than that.

## Steps to reproduce the problem.

Create a clean python environment and pip install latest geopandas and Fiona (1.9+), then open a geopackage. Then downgrage the Fiona version to 1.8.22 and open the same geopackage.

## Operating system

Ubuntu 20.04.

## Fiona and GDAL version and provenance

Python             3.8.10
Fiona                1.9.4.post1
geopandas      0.13.2
pip                    23.2.1
gdal                  3.4.1

**Comment by sgillies** [comment]
@GNU-Dawn do you mean this test here https://github.com/geopandas/geopandas/blob/main/geopandas/_vectorized.py#L139? That doesn't have anything to do with Fiona.

GeoPandas has two different implementations of read_file(). One uses Fiona, one uses pyogrio. You might want to check to see if you were using the latter previously and are now using the former.

There's not enough detail in this issue to begin to understand what's going on.

**Comment by jorisvandenbossche** [comment]
The fiona-based reader uses `GeoDataFrame.from_features` (passing the fiona collection to that). So I assume the relevant code for this is: https://github.com/geopandas/geopandas/blob/91d18898d770254f460adf2260da238acb501553/geopandas/geodataframe.py#L636-L642

Comparing fiona 1.8.22 and 1.9, I see some slowdown, but not one that would explain going from a few seconds to several minutes:

```
In [1]: import fiona

In [2]: col = fiona.open("test.gpkg")

In [3]: feat = next(iter(col))

In [4]: feat["geometry"]
Out[4]: {'type': 'Point', 'coordinates': (1.0, 2.0)}

In [5]: from shapely.geometry import shape

In [6]: shape(feat["geometry"])
Out[6]: <POINT (1 2)>

In [7]: %timeit shape(feat["geometry"])
8.23 µs ± 533 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

That's with fiona 1.8.22, and with fiona 1.9.4 it gives around 26µs for me (so a bit more than 3x slowdown for this part of `read_file`). 


(in general, if you want the fastest option for bulk reading, I would recommend using pyogrio with the `use_arrow=True` keyword (which requires GDAL 3.6+))

**Comment by sgillies** [comment]
Thanks for checking @jorisvandenbossche !
