### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [Toblerity/Fiona#1298]
Hello!

I may have found a security issue in latest version of Fiona. Following responsible disclosure, is there an email or other private channel where I could share the details? 
Thank you

**Comment by sgillies** [comment]
@SCH227 thank you for being careful! Please email me at sean.gillies@gmail.com.

**Comment by sgillies** [comment]
Fiona isn't vulnerable, but rasterio is to a small degree. See https://github.com/rasterio/rasterio/discussions/2924.
