### ISSUE TITLE
Broken online doc

### ISSUE THREAD

**Issue by loicdtx** [Toblerity/Fiona#1306]
Looks like the API documentation on ReadTheDocs is broken; [here](https://readthedocs.org/projects/fiona/builds/21407518/) is the latest working build I could find 

The sphinx logs of more recent build are full of
```
WARNING: autodoc: failed to import module 'collection' from module 'fiona'; the following exception was raised:
No module named 'fiona'
```

**Comment by sgillies** [comment]
@loicdtx recently, RTD stopped provisioning builds with common packages, and we needed to add sphinx_rtd_theme specifically. This has been fixed in the maint-1.9 branch and now that I've merge 1.9.5 to the master branch, I expect it will be fixed there as well.

**Comment by sgillies** [comment]
Yep, there we go: https://readthedocs.org/projects/fiona/builds/22283040/.

**Comment by loicdtx** [comment]
From the build logs it looks like fiona itself does not get installed.

How about adding this to `.readthedocs.yaml` (I just looked it up in rasterio)?

```yaml
python:
  install:
    - method: setuptools
      path: .
```

**Comment by sgillies** [comment]
@loicdtx Do you have a minute to make a PR?
