### ISSUE TITLE
Module documentation missing from readthedocs

### ISSUE THREAD

**Issue by andersea** [Toblerity/Fiona#1310]
All the API documentation is missing from readthedocs.

See:

https://fiona.readthedocs.io/en/stable/fiona.html#fiona-module

Only headlines are included.

**Comment by sgillies** [comment]
@andersea Thanks for the report! There have been some changes at RTD and we have yet to adjust in all our builds. Fix coming soon.

**Comment by sgillies** [comment]
Fixed in the maint-1.9 branch, but needs a tag to appear live on RTD.

**Comment by sgillies** [comment]
Fixed (see https://fiona--1312.org.readthedocs.build/en/1312/modules.html). This will become the stable version of the docs when we release 1.9.6.
