### ISSUE TITLE
WIndows 7 compatibility broken for a single missing symbol

### ISSUE THREAD

**Issue by bartoli** [Toblerity/Fiona#1326]
Hello,
I guess this is just an informative issue that will not be worked on. At least it provides a workaround if someone else has the issue.

On a windows 7, The 1.9.5 pypi package fails to load on Win7, because the shipped gdal.dll depends on libpq.dll 16.0.0 that needs the symbol GetSystemTimePreciseAsFileTime(), which needs at least WINdows 8.

Libpq.dll 10.x, which still has win7 support, seems to have all the symbols gdal.dll needs. So installing this version (and its few additonal deps) makes Fiona work on a win7

**Comment by sgillies** [comment]
@bartoli this is good to know! As Windows 7 seems to be not supported since 2020, I will close this issue.
