### ISSUE TITLE
muslinux wheel missing

### ISSUE THREAD

**Issue by jrauschenbusch** [Toblerity/Fiona#1330]
## Expected behavior and actual behavior.

There should be a wheel for `musllinux`, to speed up CI build times significantly when using Alpine-based Python base images.

## Steps to reproduce the problem.

pip install fiona

## Operating system

Alpine Linux

## Fiona and GDAL version and provenance

at least until fiona 1.9.5

**Comment by sgillies** [comment]
@jrauschenbusch are you asking on behalf of a particular open source project?

**Comment by jrauschenbusch** [comment]
What about using GitHub Actions-hosted runners which are free for public OSS projects? Together with using the same release concepts as shapely or numpy use i think it should be easier to release wheels for a large amount of OS platforms with no increase of costs (except the time to implement the accordion GitHub actions). Of course i cannot say anything about possible compile issues.

Check out cibuildwheel (musllinux support) and free runners.
