### ISSUE TITLE
Drop support for Python 3.7 and 3.8

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#1333]
Numpy 1/2 compatibility will require Python 3.9. We will make that the minimum version for Fiona 1.10 as it will be for Rasterio 1.4.

**Comment by mwtoews** [comment]
Python 3.7 reached EOL in 2023 ([PEP 537](https://peps.python.org/pep-0537/)), so yes, it's time to go.
Python 3.8 will reach EOL in Oct 2024 ([PEP 569](https://peps.python.org/pep-0569/)), so is on the way out. (And related to that, I hope we may expect Fiona 1.10 sometime this year?)

**Comment by sgillies** [comment]
@mwtoews I'm going to tag and build 1.10a1 this weekend.

**Comment by jorisvandenbossche** [comment]
> Numpy 1/2 compatibility will require Python 3.9.

I am not fully sure that is the case. At least in shapely, we still support Python 3.8 at the moment, and for example build wheels with numpy 2.0 that are compatible with both numpy 1.x and 2.0 and that still work for Python 3.8

Now, that said, if the release is targetted for later this year, I think it's also perfectly fine to drop Python 3.8 support, but regardless of numpy requiring it.

**Comment by jorisvandenbossche** [comment]
I added some comments on https://github.com/Toblerity/Fiona/pull/1331 related to this

**Comment by sgillies** [comment]
@jorisvandenbossche thank you! I've added some tickets to follow up on.
