### ISSUE TITLE
Add name keyword argument to fiona.open() and Collection constructor

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#1351]
And pass it through to GDALDatasetCreateLayer().

See also https://github.com/Toblerity/Fiona/discussions/1348.

**Comment by sgillies** [comment]
Now that I think about it more, `name` is reserved for the filename/URI given to the constructor. The `layer` keyword, which already exists, is the thing to rely on.

**Comment by nk9** [comment]
It's certainly what I initially expected to work! Thanks for opening this, looking foward to being able to use it.
