### ISSUE TITLE
`fiona.listdir` not recognising url as 'directory'

### ISSUE THREAD

**Issue by adriantre** [Toblerity/Fiona#1429]
## Expected behavior and actual behavior.

`fiona.listdir` is able to list files in VSI, but I have not gotten it working on curl. It might not be possible due to the nature of https, but I figured it is worth a shot asking here.

## Steps to reproduce the problem.

```python
# Found to be existing but not recognised as a directory 
# -> incorrectly recongised as a file
fiona.listdir("https://github.com/Toblerity/Fiona/raw/main/tests/data")
> FionaValueError: Path is not a directory.

# Found to be existing but not recognised as a directory 
# -> correctly recognised as a file
fiona.listdir("https://github.com/Toblerity/Fiona/raw/main/tests/data/coutwildrnp.shp")
> FionaValueError: Path is not a directory.

# Lists files as expected
fiona.listdir("zip+https://github.com/Toblerity/Fiona/raw/main/tests/data/coutwildrnp.zip!")
> ['coutwildrnp.shp', 'coutwildrnp.shx', 'coutwildrnp.dbf', 'coutwildrnp.prj']

```

## Fiona and GDAL version and provenance

Fiona 1.9.6

GDAL 3.6.4 installed through fiona

**Comment by sgillies** [comment]
@adriantre can you try the latest 1.10 pre-release, 1.10b3?

**Comment by adriantre** [comment]
Thanks for your swift reply!
Looks to behave the same on the pre-release.

```python
fiona.__version__
'1.10b3'
fiona.__gdal_version__
'3.9.1'

fiona.listdir("https://github.com/Toblerity/Fiona/raw/main/tests/data")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "/.../fiona/__init__.py", line 508, in listdir
    return _listdir(_vsi_path(pobj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fiona/ogrext.pyx", line 2174, in fiona.ogrext._listdir
fiona.errors.FionaValueError: Path '/vsicurl/https://github.com/Toblerity/Fiona/raw/main/tests/data' is not a directory.
```

**Comment by sgillies** [comment]
@adriantre thanks for the report! The problem is that HTTP, by itself, unlike FTP or S3, has no directory convention for GDAL to use. We can't, using only HTTP, detect from a URL or its representation whether it is a container for geospatial data. `listdir()` will work for more specialized protocols/formats that do have directory or container concepts. For example:

```
>>> listdir("s3://fiona-testing/")
['coutwildrnp.zip']
```

**Comment by adriantre** [comment]
Thanks, @sgillies!
