### ISSUE TITLE
Reading shapefile with vertical datum results in "Windows fatal exception: access violation"

### ISSUE THREAD

**Issue by NicolasCadieux** [Toblerity/Fiona#1444]
## Description
I have a file with the following datum:
COMPD_CS["NAD83(CSRS) / UTM zone 10N + CGVD28 height",
    PROJCS["NAD83(CSRS) / UTM zone 10N",
        GEOGCS["NAD83(CSRS)",
            DATUM["NAD83_Canadian_Spatial_Reference_System",
                SPHEROID["GRS 1980",6378137,298.257222101,
                    AUTHORITY["EPSG","7019"]],
                AUTHORITY["EPSG","6140"]],
            PRIMEM["Greenwich",0,
                AUTHORITY["EPSG","8901"]],
            UNIT["degree",0.0174532925199433,
                AUTHORITY["EPSG","9122"]],
            AUTHORITY["EPSG","4617"]],
        PROJECTION["Transverse_Mercator"],
        PARAMETER["latitude_of_origin",0],
        PARAMETER["central_meridian",-123],
        PARAMETER["scale_factor",0.9996],
        PARAMETER["false_easting",500000],
        PARAMETER["false_northing",0],
        UNIT["metre",1,
            AUTHORITY["EPSG","9001"]],
        AXIS["Easting",EAST],
        AXIS["Northing",NORTH],
        AUTHORITY["EPSG","3157"]],
    VERT_CS["CGVD28 height",
        VERT_DATUM["Canadian Geodetic Vertical Datum of 1928",2005,
            AUTHORITY["EPSG","5114"]],
        UNIT["metre",1,
            AUTHORITY["EPSG","9001"]],
        AXIS["Gravity-related height",UP],
        AUTHORITY["EPSG","5713"]]]

Reading it with fiona crashes python with a "Windows fatal exception: access violation".  If I save the file and remove the vertical datum, all is well. Reading directly using gdal driver.Open() works.

## Steps to reproduce the problem.

import fiona
file0 = r"C:\Users\njaca\Desktop\GIS2DJI_Testfiles\FL1_bf20m\NAD83(CSRS)_UTM_10_CGVD28.shp"
input_file0 = fiona.open(file0)

## Operating system

Windows 11

## Fiona and GDAL version and provenance
Fiona 1.9.5
GDAL 3.8.4
Installed in Anaconda with geopandas library.

<img width="634" alt="crash" src="https://github.com/user-attachments/assets/d5564e11-3b82-4a2b-868c-808505aa5cd3">

**Comment by sgillies** [comment]
@NicolasCadieux thanks for the report! Fiona 1.9.5 isn't supported anymore. Can you try the latest release, 1.10.0?

**Comment by NicolasCadieux** [comment]
Will try!

**Comment by NicolasCadieux** [comment]
Same problem in 1.10.0.
Thanks!|

**Comment by sgillies** [comment]
Confirmed! I didn't even have to open a dataset. `CRS.from_wkt(...)` using your value caused a segmentation fault in 1.10.0 on my macbook using a wheel installed from PyPI.

**Comment by sgillies** [comment]
This will be fixed in 1.10.1, on Monday afternoon.

**Comment by NicolasCadieux** [comment]
Wow!  Thanks! Good job!
