### ISSUE TITLE
Have to use OpenFileGDB

### ISSUE THREAD

**Issue by r-barnes** [Toblerity/Fiona#192]
Using Fiona 1.4.8 with GDAL 1.11.0, I get the following error message when trying to open and ESRI GDB directory:

    >>> fin      = fiona.open(filename)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/fiona/__init__.py", line 139, in open
        encoding=encoding, layer=layer, vsi=vsi, archive=archive)
      File "/usr/local/lib/python2.7/dist-packages/fiona/collection.py", line 148, in __init__
        self.guard_driver_mode()
      File "/usr/local/lib/python2.7/dist-packages/fiona/collection.py", line 160, in guard_driver_mode
        raise DriverError("unsupported driver: %r" % driver)
    fiona.errors.DriverError: unsupported driver: u'OpenFileGDB'

Opening `/usr/local/lib/python2.7/dist-packages/fiona/collection.py` and replacing `("FileGDB", "raw")` with `("OpenFileGDB", "r")` resolves the issue for me.

My expected behavior is that there would be no error and the file would simply open, as it does when using `("OpenFileGDB", "r")`. Therefore, I would suggest making the switch part of the codebase.

Are there Good Reasons not to? Or is there some way to use both drivers by having Fiona fall back `OpenFileGDB` if `FileGDB` fails?

**Comment by sgillies** [comment]
@r-barnes @snorfalorpagus here's what I came up with: https://github.com/Toblerity/Fiona/blob/ef1d3f7f5e35c62e6d4ff157ec2725c279044683/tests/test_read_drivers.py#L20-L25. You can specify exactly one driver to try when opening or you can try several drivers in a specified order.

So, `fiona.open(filename, driver='GeoJSON')` is the equivalent of osgeo.ogr's `ogr.GetDriverByName('GeoJSON').Open(filename)` and `fiona.open(filename, enabled_drivers=['GeoJSON', 'ESRI Shapefile'])` is the equivalent of:

```python
for name in ['GeoJSON', 'ESRI Shapefile']:
    ds = ogr.GetDriverByName(name).Open(filename)
    if ds:
        break
```

I decided not to take on selective driver registration as it goes hard against the grain of OGR's C API. A call to `fiona.open()` continues to register all drivers if they haven't already been registered.

**Comment by r-barnes** [comment]
This looks quite nice to me. If the `driver` argument is unspecified does it fallback to letting OGR try to handle it (or whatever the previous behaviour was)?

**Comment by sgillies** [comment]
@r-barnes yes.

Btw, I tried to do something like this for Rasterio but got blocked by GDAL. Will be possible to do and be easier for Fiona with GDAL 2.0.

**Comment by clutariomark** [comment]
Is this supported in windows? I tried installing Fiona from http://www.lfd.uci.edu/~gohlke/pythonlibs/#fiona

but when I do:

    fiona.supported_drivers

It's not there

    {'ESRI Shapefile': 'raw', 'FileGDB': 'raw', 'PCIDSK': 'r', 'AeronavFAA': 'r', 'SUA': 'r',
     'GPSTrackMaker': 'raw', 'ARCGEN': 'r', 'PDS': 'r', 'DGN': 'raw', 'GeoJSON': 'rw', 
     'GPKG': 'rw', 'MapInfo File': 'raw', 'Idrisi': 'r', 'GPX': 'raw', 'DXF': 'raw', 'BNA': 'raw', 
     'SEGY': 'r', 'GMT': 'raw'}
