### ISSUE TITLE
Clarify fiona.open's encoding keyword arg

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#197]
I told @NelsonMinar that the intent of this argument was to override encodings found in data when reading, but after reviewing docs, code, and my notes I realize that's not correct. This is what the argument is about:

In 'w' mode, it defines the encoding of the new dataset. If unspecified, the dataset's encoding will be ISO-8859-1 (for shapefiles) or `sys.getpreferredencoding()`.

In 'r' mode, the encoding argument is intended to make up for encoding detection defects in GDAL < 1.9. See the closing paragraph of http://toblerity.org/fiona/manual.html#reading-vector-data. In GDAL versions >= 1.9 it shouldn't be needed and generally has no effect.

**Comment by NelsonMinar** [comment]
Thanks for the follow-up! FWIW of about 6 non-ASCII shapefiles we've seen in OpenAddresses, GDAL 1.11 detects encodings of 5 of them correctly. The 6th one it does not but Fiona then assumes ISO-8859-1 which seems to be correct for this file.

For writing files, have you considered making UTF-8 the default encoding? I don't know what's most likely to be what your users want, I just hate to see anything that's not Unicode as a default.

**Comment by sgillies** [comment]
UTF-8 instead of the preferred system encoding? I've been trying to stick as closely as possible to the [text file processing of Python 3](http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html#text-file-processing) but I agree that UTF-8 would be better.

**Comment by NelsonMinar** [comment]
Oh I forgot about the preferred system encoding, that's probably better. FWIW it's UTF-8 in every Python environment I have.
