### ISSUE TITLE
ValueError: No data available at path

### ISSUE THREAD

**Issue by allhailwesttexas** [Toblerity/Fiona#199]
I'm having trouble with Fiona 1.4.8 on OSX Yosemite. I get a `ValueError: No data available at path "test.shp"`. If I switch to version 1.4.7, I get a bunch of polygons printed to screen, as expected.

Here is my test program:
```python
import fiona

vecfile = "test.shp"
with fiona.open(vecfile, 'r') as fi:
    features = [x for x in fi]
print features
```
Here is the traceback:
```python
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    with fiona.open(vecfile, 'r') as fi:
  File "/Users/stensmyr/.virtualenvs/fionatest/lib/python2.7/site-packages/fiona/__init__.py", line 139, in open
    encoding=encoding, layer=layer, vsi=vsi, archive=archive)
  File "/Users/stensmyr/.virtualenvs/fionatest/lib/python2.7/site-packages/fiona/collection.py", line 135, in __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 359, in fiona.ogrext.Session.start (fiona/ogrext.c:6649)
ValueError: No data available at path 'test.shp'
```

I'm installing with pip. My best lead is that 1.4.8 installs from a wheel, whereas previous versions install from setup.py.

**Comment by snorfalorpagus** [comment]
Do you experience the same issue if you provide an absolute path? e.g. `/Users/snorf/Desktop/test.shp`?

**Comment by allhailwesttexas** [comment]
Yes, same error.

**Comment by sgillies** [comment]
Until I'm able to confirm, the work around is `pip install --no-use-wheels fiona` to compile the extension modules locally using your system's GDAL.

**Comment by sgillies** [comment]
@allhailwesttexas confirmed. Details soon.

**Comment by sgillies** [comment]
So, this is only a problem with my wheel builds. I'm going to yank the wheels and re-upload once I've got them straightened out. Sorry for the trouble, @allhailwesttexas!

**Comment by sgillies** [comment]
After https://github.com/sgillies/frs-wheel-builds/commit/f444f4a60af77383e11dada8d08c26e63c1041ce, I've built and uploaded new *tested* wheels.

**Comment by allhailwesttexas** [comment]
No problem, happy to help! Thanks for the quick response.
