### ISSUE TITLE
longint field type

### ISSUE THREAD

**Issue by ungarj** [Toblerity/Fiona#209]
Hi,

I'm trying to write data to a shapefile which exceeds the standard integer range. OGR seems to [support](http://www.gdal.org/ogr__core_8h.html#a787194bea637faf12d61643124a7c9fc) 64bit integers but it is not mapped to the Fiona [field types](https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext.pyx#L35).

Is there any reason this is not supported?

And is there anything you can recommend me so I can try to fix it? I've never been so deep into Python so I don't really have an idea where to start with.

Thanks, Joachim

**Comment by rbuffat** [comment]
It looks like 64bit Integers will be introduced in gdal 2.0
https://trac.osgeo.org/gdal/wiki/rfc31_ogr_64

In 1.11 they are not there yet:
http://gdal.org/1.11/ogr/ogr__core_8h.html#a787194bea637faf12d61643124a7c9fc

**Comment by snorfalorpagus** [comment]
This issue was previous raised as https://github.com/Toblerity/Fiona/issues/117.

**Comment by ungarj** [comment]
Thanks for your quick responses. And sorry for missing the previous issue.
