### ISSUE TITLE
Incompatibility with Cython 0.22

### ISSUE THREAD

**Issue by youngpm** [Toblerity/Fiona#212]
Fiona is currently incompatible with the newest release of Cython (v0.22); this is only an issue for development using v0.22 and it compiles fine with v0.21.2.  Cython spits out a bunch of errors of the form
```
Cythonizing fiona/_geometry.pyx

Error compiling Cython file:
------------------------------------------------------------
...


cdef class OGRGeomBuilder:
    """Builds OGR geometries from Fiona geometries.
    """
    cdef void * _createOgrGeometry(self, int geom_type) except NULL:
        ^
------------------------------------------------------------

fiona/_geometry.pyx:138:9: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cdef build(self, void *geom)
    cpdef build_wkb(self, object wkb)


cdef class OGRGeomBuilder:
    cdef void * _createOgrGeometry(self, int geom_type)
             ^
------------------------------------------------------------
```

The problem is with non-Cython `cdef` declarations that end with `except NULL`, like [here](https://github.com/Toblerity/Fiona/blob/master/fiona/_geometry.pyx#L40).  Apparently the new version of Cython is stricter about such declarations, see [here](http://docs.cython.org/src/reference/language_basics.html#checking-return-values-for-non-cython-functions).

**Comment by sgillies** [comment]
@youngpm I ran into this with Rasterio, too. My temporary solution there was to pin cython==0.21.2 in requirements-dev.txt. Let's do that for Fiona and I'll take on the migration to Cython 0.22 when we get closer to a 1.6 release.
