### ISSUE TITLE
1.5.0 release misses test data

### ISSUE THREAD

**Issue by hroncok** [Toblerity/Fiona#216]
The tar downloaded from https://pypi.python.org/pypi/Fiona misses some test files, such as coutwildrnp.shp and other files with other file extension than txt.

**Comment by hroncok** [comment]
I believe it's because of https://github.com/Toblerity/Fiona/blob/master/MANIFEST.in#L8

**Comment by sgillies** [comment]
@hroncok thanks! I didn't update the manifest after changing our test data.
