### ISSUE TITLE
Specifying invalid width for string field causes segfault

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#222]
The following code causes Python to crash. Only tested on Windows (Python 2.7).
```
import fiona
meta = {
    'driver': 'ESRI Shapefile',
    'schema': {
        'geometry': 'Point',
        'properties': [('fail', 'str:255')],  # crash with 255, not with 254
    }
}
src = fiona.open('test.shp', 'w', **meta)
```
In this case, it was me misremembering the maximum shapefile field length. Should we be sense checking this input before passing to GDAL? If so, how do we determine which inputs are valid?

**Comment by snorfalorpagus** [comment]
I can't reproduce this on OS X (python 2.7.9, ogr 1.11.1, both from homebrew). Instead it silently only creates a field of 254 width, which I think is acceptable? Either way, more debugging on my Windows machine needed.

**Comment by snorfalorpagus** [comment]
This is happening using the binary distribution of GDAL + Fiona from Christoph Gohlke:

http://www.lfd.uci.edu/~gohlke/pythonlibs/

Windows 7 Professional
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Fiona 1.5.1
GDAL 1.11.2

**Comment by sgillies** [comment]
@snorfalorpagus The Shapefile driver truncates field widths in ogrshapelayer.cpp:

```c++

        case OFTString:
            chType = 'C';
            nWidth = oModFieldDefn.GetWidth();
            if (nWidth == 0) nWidth = 80;
            else if (nWidth > OGR_DBF_MAX_FIELD_WIDTH)
            {
                CPLError( CE_Warning, CPLE_AppDefined,
                        "Field %s of width %d truncated to %d.",
                        szNewFieldName, nWidth, OGR_DBF_MAX_FIELD_WIDTH );
                nWidth = OGR_DBF_MAX_FIELD_WIDTH;
            }
            break;
```

And, yes, it does work for me on OS X (with some logging added to your script):

```
DEBUG:Fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:Option CPL_DEBUG=ON
DEBUG:Fiona:CPLE_None in Shape: DBF Codepage = ISO-8859-1 for test.shp
DEBUG:Fiona:CPLE_None in Shape: Treating as encoding 'ISO-8859-1'.
DEBUG:Fiona:Created layer
DEBUG:Fiona:Creating field: fail str:255
WARNING:Fiona:CPLE_AppDefined in Field fail of width 255 truncated to 254.
DEBUG:Fiona:Created fields
DEBUG:Fiona:Writing started
```

I'm unsure what the problem is on Windows.

**Comment by sgillies** [comment]
@snorfalorpagus anything to report? Do you mind if we don't fix this in 1.6.0?

**Comment by snorfalorpagus** [comment]
@sgillies Yes it's still an issue for me, but I don't mind if it's not in 1.6.0.

I need to find out if this is just my machine, just the Gohlke binaries, or a general issue on Windows.

**Comment by sgillies** [comment]
@snorfalorpagus Okay if we defer this to a post 1.7 release?

**Comment by snorfalorpagus** [comment]
I think this must have been a build issue. I've just tested it with Fiona 1.6.4 on Windows with Python 3, using Fiona installed from conda-forge and it works fine.
