### ISSUE TITLE
GML support?

### ISSUE THREAD

**Issue by shongololo** [Toblerity/Fiona#223]
Is there a way to use Fiona to access [GDAL's support for GML](http://www.gdal.org/drv_gml.html)?

Here is the error I encounter when trying:

<code>
File "ogrext.pyx", line 588, in fiona.ogrext.Session.start (src/fiona/ogrext.c:10587)
File "_err.pyx", line 67, in fiona._err.GDALErrCtxManager.__exit__ (src/fiona/_err.c:938)
OSError: b'Unable to open EPSG support file gcs.csv.\nTry setting the GDAL_DATA environment variable to point to the\ndirectory containing EPSG csv files.'
</code>

I am using the Anaconda distribution of GDAL and Fiona.

**Comment by sgillies** [comment]
No, Fiona doesn't support GML. GML requires a complete XML toolchain and GDAL's support for it is limited.

ContinuumIO's GDAL Anaconda package has been broken for a long time. There's an issue filed about it at https://github.com/ContinuumIO/anaconda-issues/issues/221.
