### ISSUE TITLE
CLI commands as plugins

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#224]
Let's do for Fiona what I did for Rasterio: make existing commands into plugins and allow plugins to be developed as external projects (https://github.com/mapbox/rasterio/pull/346).

As an example, I've got a `fio buffer` command sitting in a branch https://github.com/Toblerity/Fiona/blob/sequence-processing/fiona/fio/ops.py. Because of the Shapely dependency, this would be better as an external project.

If we design interfaces well, our plugins could implement the multicommand pipelining described in https://github.com/Toblerity/Fiona/issues/173.

/cc @geowurster

**Comment by geowurster** [comment]
Took a shot at this in PR #225.

Command chaining was one of the first things I thought of.  Being able to avoid the JSON serialization hit and QGIS temp-files would be nice and a buffer command seems like a good place to start since its a streaming operation and `ogr2ogr` doesn't do it.

**Comment by geowurster** [comment]
Re-implement according to https://github.com/mapbox/rasterio/commit/225179d30db07205108364c424d4094d61ebc4d3 and https://github.com/mapbox/rasterio/commit/2ef9e4815b05a35352f47298417ba223db2ca7d9

@sgillies can you assign this to me so I don't lose track?
