### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by groutr** [Toblerity/Fiona#230]
I noticed that rasterio and fiona share the same setup.py

Could these changes that were applied to rasterio also be applied to fiona?
https://github.com/mapbox/rasterio/pull/355
https://github.com/mapbox/rasterio/pull/362

**Comment by sgillies** [comment]
Yep!

(The separation is a bit artificial, it's true. Both depend on GDAL and there's a bit of duplication between them, but I think the projects have benefited from evolving semi-separately.)

**Comment by groutr** [comment]
Should I submit PRs to this repo then?

**Comment by sgillies** [comment]
@groutr will you please? I'm completely slammed right now and it would just slip.

**Comment by groutr** [comment]
Sure thing :+1:
