### ISSUE TITLE
ImportError: No module named ogrext

### ISSUE THREAD

**Issue by clutariomark** [Toblerity/Fiona#235]
I installed Fiona using pip install Fiona (Linux Mint) but when I try to import it in python it gives this error:

    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "fiona/__init__.py", line 72, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
    File "fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
    ImportError: No module named ogrext

Anyone having trouble with this?

**Comment by sgillies** [comment]
Please follow the instructions at https://github.com/Toblerity/Fiona/blob/master/README.rst#unix-like-systems. Fiona has system dependencies that must be installed first.

**Comment by odidev** [comment]
@sgillies , I followed the steps mentioned in [above comment](https://github.com/Toblerity/Fiona/issues/235#issuecomment-109312149) but getting same error in aarch64 platform. I am not sure if we need to install any different dependencies for AArch64. Can you please help me solving this issue?

**Comment by rbuffat** [comment]
@odidev 
This is quite an old issue. For the future, I would recommend opening a new issue.  The error message `ImportError: No module named ogrext` is quite general. It simply means that the compiled extension modules used by Fiona cannot be imported. There can be quite a few reasons for that: maybe they are not installed, maybe there is something wrong with the environment variables, maybe they are incompatible with the installed gdal binaries etc. Thus it is really important to document how you installed Fiona, what error messages you encountered on the way, what your system looks like, etc.

Currently, Fiona is not tested on aarch64. I managed to install Fiona on a Raspberry Pi 3b running Arch Linux ARM aarch64 using `pip install Fiona`. You need to have gdal installed as well as cython.

However, when I ran Fionas test suite the following tests failed:
```
FAILED tests/test_geometry.py::test_ogr_builder_exceptions - ValueError: Unsupported geometry type Bogus
FAILED tests/test_memoryfile.py::test_read_multilayer_memoryfile - AssertionError: assert 'layer1' == 'layer2'
FAILED tests/test_transactions.py::TestTransaction::test_transaction - assert 0 == (250 // 100)
```
Fiona is a wrapper around GDAL. At first glance, these issues look like GDAL related issues. I'm not sure how well the support of GDAL is for aarch64 is. I don't think it is tested on aarch64.

**Comment by JohnWatsonFd** [comment]
You should install Cpython before that

**Comment by giantchen2012** [comment]
Got the same problem while setup from source with gdal version 2.1.3, python 3.5, VS 2017 on windows 10. and tried to figure out the dependencies by dependency walker, it seems gdal and python could be found.
