### ISSUE TITLE
Documentation: 6.3 Coordinates and Geometry Types

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#237]
https://github.com/Toblerity/Fiona/blob/master/docs/manual.rst#63coordinates-and-geometry-types

Is it worth adding a couple of examples to this section, and perhaps putting something about '3D' in the section title? It took me a while to figure out what I was doing wrong yesterday (trying to write 3D geometries to a `'Point'` layer, instead of  a `'3D Point'` layer).

**Comment by sgillies** [comment]
Sure! Anything you want to add would be very welcome.
