### ISSUE TITLE
Generalize feature sequence I/O and RS support

### ISSUE THREAD

**Issue by geowurster** [Toblerity/Fiona#251]
Currently these features are implemented partially in `fio cat` and `fio load` but adding them to the Fiona API as something like `fiona.SequenceStream()` would make features like https://github.com/geowurster/fio-buffer/issues/4 easier to support.  

We could maybe have `fiona.open()` return this object with something like:

```python
with fiona.open(file or '-', mode, sequence=bool, rs=bool) as f:
    ...
```

although properties like `crs` and `bounds` would behave differently than `Collection()`. 

At the very least we could support:

```python
with fiona.SequenceStream(infile) if i_sequence else fiona.open(infile) as src:
    with fiona.SequenceStream(outfield, 'w', rs=use_rs) if o_sequence else fiona.open(outfile, 'w', **meta) as dst:
        for feature in src:
            dst.write(feature)
```

**Comment by geowurster** [comment]
Closing this in favor of a more generic external implementation.  See comment in #252 for reference.

**Comment by sgillies** [comment]
@geowurster what would you think about working on it in the https://github.com/geojson org?

**Comment by geowurster** [comment]
Definitely seems like the most appropriate place to me!
