### ISSUE TITLE
IndexError in fiona.ogrext.Session.get_schema

### ISSUE THREAD

**Issue by bekozi** [Toblerity/Fiona#255]
We are getting an IndexError when loading a schema from shapefile on OSX (file available at http://bit.ly/1IHZ6Mp). There is no issue loading the schema on Ubuntu Linux. I don't have direct access to the machine this is failing on, but I can work with the developer there to provide more details if needed.

* OSX 10.10
* Fiona 1.6.0 (installed via Macports)

```sh
...
line 139, in get_meta
    return source.meta
  File "build/bdist.macosx-10.10-x86_64/egg/fiona/collection.py", line 208, in meta
    'schema': self.schema,
  File "build/bdist.macosx-10.10-x86_64/egg/fiona/collection.py", line 186, in schema
    self._schema = self.session.get_schema()
  File "fiona/ogrext.pyx", line 470, in fiona.ogrext.Session.get_schema (fiona/ogrext.c:8453)
IndexError: list index out of range
```

Thanks!

**Comment by sgillies** [comment]
@bekozi I can't reproduce the problem. 

```bash
$ fio info ~/Downloads/state_boundaries/state_boundaries.shp
{"count": 51, "crs": "EPSG:4326", "driver": "ESRI Shapefile", "bounds": [-178.21759836236586, 18.92178634508703, -66.96927125875779, 71.40623539396698], "schema": {"geometry": "Polygon", "properties": {"UGID": "int:10", "STATE_FIPS": "str:2", "ID": "float:11", "STATE_NAME": "str:25", "STATE_ABBR": "str:2"}}}
```

I think this is something that the Macports maintainers will have to deal with.

I recommend simply doing `pip install -U fiona` on OS X. Pip should fetch one of these wheels from PyPI: https://pypi.python.org/pypi/Fiona#downloads and they're well tested.

**Comment by bekozi** [comment]
Thanks for looking into it @sgillies. I'll make your recommendations and get back to you if we learn anything interesting.

**Comment by jachym** [comment]
Hm, looks I have exactly the same error on ubuntu:

```
>>> from osgeo import gdal
>>> gdal.VersionInfo()
'1110200'
>>> import fiona
>>> fiona.__version__
'1.6.1'
>>> 
```

installed via
```
 pip install fiona
```

it was working some time ago, but now it "just stopped"

Truth is, I have also gdal 2.1.0dev in my system (/usr/local/) - could that be the problem?

**Comment by rbuffat** [comment]
I think fiona supports gdal 2.0 not yet, see https://github.com/Toblerity/Fiona/issues/239

**Comment by jachym** [comment]
OK, it really seems, that there was an conflict between fiona and gdal 2.x 

take it as solved

thanks

**Comment by rbuffat** [comment]
you can check the gdal version fiona uses with:
>>> import fiona
>>> fiona.ogrext.get_gdal_release_name()

**Comment by hrebchuk-oleh** [comment]
File "fiona/ogrext.pyx", line 680, in fiona.ogrext.Session.__getitem__
  File "fiona/ogrext.pyx", line 1215, in fiona.ogrext.Iterator.__next__
  File "fiona/ogrext.pyx", line 214, in fiona.ogrext.FeatureBuilder.build
ValueError: year is out of range
fiona 7.11
