### ISSUE TITLE
Automatic doc builds

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#258]
Let's figure out how to build and publish the manual on release.

http://docs.travis-ci.com/user/deployment/

Won't be much more complicated than what I did for Rasterio wheels at https://github.com/mapbox/rasterio/blob/master/.travis.yml#L18-L29.

See #257 

/cc @geowurster

**Comment by geowurster** [comment]
:+1: I was going to suggest the same.

**Comment by Juanlu001** [comment]
Would you be interested in using Read the Docs instead?

https://readthedocs.org/

OTOH, I think the fragment you linked is outdated. Are you referring to this one?

https://github.com/mapbox/rasterio/blob/0511736/.travis.yml#L18-L29

**Comment by Juanlu001** [comment]
And while we are at it: perhaps we could update the online version of the docs before having the automatic process? They are already a bit dated...

**Comment by sgillies** [comment]
@Juanlu001 I would prefer RTD but last time I checked it wasn't capable of building our C extension modules, which it wants to do to build and publish docs.

**Comment by Juanlu001** [comment]
They improved their conda support a lot and they install `build-essential`, so perhaps one could install `libgdal` inside a conda environment and test the build there. I will try that approach and see how it goes.

**Comment by sgillies** [comment]
@geowurster @rbuffat @snorfalorpagus what do you think about publishing the docs at readthedocs (#466)? What do you think about readthedocs being the primary documentation site?

**Comment by geowurster** [comment]
Based on how easy it is to push to RTD and how likely it is that some users are looking for docs there, I'm 👍 on publishing, especially since it makes it easy to see docs for alpha versions.  I'm neutral on making it the canonical documentation source and care more that the docs for Fiona, Shapely, and Rasterio end up in the same place.

**Comment by Juanlu001** [comment]
> We could automate doc builds to `toblerity.org` with GitHub pages and redirects, which would also offer some redundancy in the event that one service goes down

Or perhaps you can setup a CNAME:

http://docs.readthedocs.io/en/latest/alternate_domains.html#cname-support
