### ISSUE TITLE
Datum information lost when converting file with datum D_Amersfoort

### ISSUE THREAD

**Issue by mattwigway** [Toblerity/Fiona#265]
If I use Fiona to read a file in a coordinate system with D_Amersfoort as the datum and copy the metadata into a new file, I get D_Unknown as the datum.

Original .prj file:
```
PROJCS["RD_New",GEOGCS["GCS_Amersfoort",DATUM["D_Amersfoort",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Double_Stereographic"],PARAMETER["False_Easting",155000.0],PARAMETER["False_Northing",463000.0],PARAMETER["Central_Meridian",5.38763888888889],PARAMETER["Scale_Factor",0.9999079],PARAMETER["Latitude_Of_Origin",52.15616055555555],UNIT["Meter",1.0]]
```

.prj file after conversion:

```
PROJCS["Double_Stereographic",GEOGCS["GCS_Bessel 1841",DATUM["D_unknown",SPHEROID["bessel",6377397.155,299.1528128]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Double_Stereographic"],PARAMETER["latitude_of_origin",52.1561605556],PARAMETER["central_meridian",5.38763888889],PARAMETER["scale_factor",0.9999079],PARAMETER["false_easting",155000],PARAMETER["false_northing",463000],UNIT["Meter",1]]
```

This leads to a pretty significant shift in the location of the geodata.

Using ogr2ogr to convert the same file behaves correctly, so it looks like this is a Fiona problem (or a bug in my use of Fiona). The code I'm using is [here](https://gist.github.com/mattwigway/18799e8d56e20f81a4ba).

Finally, the file I'm using is from Statistics Netherlands (page in dutch, but it's the buurt_2014.shp file inside the first link): http://www.cbs.nl/nl-NL/menu/themas/dossiers/nederland-regionaal/publicaties/geografische-data/archief/2015/wijk-en-buurtkaart-2014-art.htm .

**Comment by mattwigway** [comment]
Oh, should add that this is with fiona 1.6.1 and gdal 1.11.2 on OS X 10.10.5.

**Comment by sgillies** [comment]
@mattwigway in your code, I see that the new file is given a coordinate reference system obtained from the `crs` property of the original dataset. It's possible that some information is lost in converting the original projection to a PROJ4 representation (see https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext.pyx#L560).

Can you confirm for me that the following code gives you the coordinate reference system you expect? And if there's a difference between `infile.crs_wkt` and `infile.crs`?

```
with fiona.open(argv[1]) as infile:
    print(infile.crs_wkt)
```

We could look into using `crs_wkt` when creating new files if it will always be more precise than `crs`.

**Comment by mattwigway** [comment]
Yes it does:

```
>>> with fiona.open('buurt_2014.shp') as inf:
...     print inf.crs_wkt
... 
PROJCS["RD_New",GEOGCS["GCS_Amersfoort",DATUM["Amersfoort",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Oblique_Stereographic"],PARAMETER["False_Easting",155000.0],PARAMETER["False_Northing",463000.0],PARAMETER["Central_Meridian",5.38763888888889],PARAMETER["Scale_Factor",0.9999079],PARAMETER["Latitude_Of_Origin",52.15616055555555],UNIT["Meter",1.0]]
>>> 
```

**Comment by sgillies** [comment]
I propose to fix this bug by adding a new `crs_wkt` keyword argument to `fiona.open()` and also adding a crs_wkt item to `meta`. As far as I can tell, the WKT crs form is more precise than the PROJ4 form: if `crs_wkt` and `crs` are both passed, as would be the case when you take a `meta` dict and pass it back to `open()`, `crs_wkt` would trump `crs`.

/cc @Toblerity/pushers

**Comment by mattwigway** [comment]
Sounds good to me, thanks!

**Comment by mattwigway** [comment]
Ah hmm. The crs_wkt has the datum listed as Amersfoort rather than D_Amersfoort, but that may be equivalent.

**Comment by sgillies** [comment]
@mattwigway your code is exactly right, and my proposed change requires no changes on your part. I hope the datum name change is just a GDAL implementation detail. We'll see!
