### ISSUE TITLE
Benchmarking json vs msgpack vs geobuf/protobuf

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#271]
Relevant to some discussion we're having about processing pipelines. Results here: https://gist.github.com/sgillies/bfeb6b479bfd2e6a0a38.

The standard lib json is significantly faster than umsgpack or geobuf.

Nothing compares to marshal.

**Comment by jwass** [comment]
@sgillies Not a big deal but code in the gist doesn't contain pickle, cPickle, or marshal but the results do.

Also, seen ujson? (https://github.com/esnme/ultrajson). About 5x faster for me than stdlib json even when increasing double_precision.

Ran on my machine to compare and umsgpack is ~6x faster than stdlib json, which is weird because it's much slower in your results. Otherwise results are similar.

**Comment by sgillies** [comment]
Yeah, I'm baffled. I know protobuf is slow, but I expected msgpack to be faster than this. Can you share your times?

**Comment by jwass** [comment]
Added ujson section.
```
json loads/dumps
436.29 usec/pass

ujson loads/dumps
101.16 usec/pass

marshal loads/dumps
28.62 usec/pass

cPickle loads/dumps
315.27 usec/pass

pickle loads/dumps
2373.05 usec/pass

umsgpack loads/dumps
56.66 usec/pass

shapely loads/dumps
531.05 usec/pass

geobuf decode/encode
3228.35 usec/pass
```
Your computer is better than mine :)

**Comment by sgillies** [comment]
Any chance that umsgpack is a no-op or fast failure in your case? If you printed `umsgpack.loads(umsgpack.dumps(geom))` what would you get?

**Comment by jwass** [comment]
Looks okay. The polygon does get serialized and the dictionary comes back out.
I did a `pip install umsgpack` - not sure if we're using different libraries here.

**Comment by perrygeo** [comment]
I get similar numbers for umsgpack and the geoms look OK. I added this to confirm all geoms were the same after the round trip:

    newgeom = eval(statement)
    print(shape(newgeom).almost_equals(shape(geom)))

And the only one that failed was `geobuf`.

**Comment by sgillies** [comment]
Somehow I scanned over msgpack-python in the listing at http://msgpack.org/index.html and went straight to the much slower u-msgpack-python. New results at https://gist.github.com/sgillies/bfeb6b479bfd2e6a0a38. Msgpack looks fast enough that we can stick to our simple existing pipelines and put off the internally streaming ones (a la https://github.com/mitsuhiko/click/tree/master/examples/imagepipe) for now.

**Comment by geowurster** [comment]
I have been dealing with this in a high-volume marine AIS processing pipeline and went with a core I/O library with a [driver model](https://github.com/SkyTruth/gpsdio/blob/master/gpsdio/drivers.py) so we could read/write data from/to different formats as needed.  Hadoop wants text, but only does one lame map per file if its compressed but raw JSON is too big for experimenting with local files, so do a quick transform to GZIP MsgPack, etc.

Trying to put off benchmarking until the pipeline is more mature, but the `json` vs. `ujson` vs. `python-msgpack` is relatively about what I think what we're getting.  Am also surprised by how slow `protobuf` is.

**Comment by rbuffat** [comment]
I'm not familiar with the Python geojson library. For protobuf different implementations can be used, a slow Python one and a faster c++ implementation: http://yz.mit.edu/wp/fast-native-c-protocol-buffers-from-python/

**Comment by geowurster** [comment]
@sgillies What do you think about letting the user specify which JSON library to use from the command line?  Maybe something like `fio -D json_lib=ujson cat file.geojson`.  We could stick the imported library into `ctx.obj['json_lib']` for sub-commands and plugins.

**Comment by sgillies** [comment]
@geowurster for ones that share this pickle-like interface, maybe this would work. Want to give it a try and see how it feels? This feels like an option that you'd probably want to stick in a config file instead of command line, though.
