### ISSUE TITLE
Refactor extension classes

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#277]
After #275 is finished, I'd like to try refactoring to eliminate redundant code. Ideally, ogrext1.pyx would have GDAL 1.x compatible Session and Iterator classes that derive from a base classes and ogrext2.pyx would have GDAL 2.x compatible classes that derive from the same base classes.

**Comment by snorfalorpagus** [comment]
What's the best way to do this? Concatenate an `ogrext_base.pyx` and the relevant `ogrext1.pyx` or `ogrext2.pyx` in `setup.py`?

**Comment by snorfalorpagus** [comment]
There is only 1 line different in the `writerec` method between the two versions. Does this mean the entire function needs to be duplicated? In C you would use an `#ifdef` but there isn't an equivalent in Cython. Do we just have to put up with this?

https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext1.pyx#L936
https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext2.pyx#L1000

**Comment by micahcochran** [comment]
There are two approaches that I can think of. Write a common base class with all the functions that will compile in both versions of GDAL.  Then have your GDAL version specific classes derive from a those common base classes.

The other is to write an emulation layer.  So, the Fiona code may target GDAL 2.0, but have wrapper functions for GDAL 1.x in the version 2 API's names. This could present a problem in the future if there are functions that Fiona wants to use in GDAL 2.x that aren't easily supported by GDAL 1.x API.

There are a few other ways to do this that add more layers of abstraction. There are probably a few other ways to go.  Both of the approaches should reduce the lines of code.  Which approach is less confusing?

**Comment by snorfalorpagus** [comment]
It looks like Cython does support some preprocessor-like functionality. I wasn't aware of this.

http://docs.cython.org/src/reference/language_basics.html#compile-time-definitions

**Comment by sgillies** [comment]
I'm going to push this one off to a future milestone unless there are objections. It's time to get 1.7 out there!

**Comment by snorfalorpagus** [comment]
I agree that this shouldn't hold back the release of 1.7 as there is a real need to have GDAL 2.x support now.

**Comment by snorfalorpagus** [comment]
Closed by #461.
