### ISSUE TITLE
files don't open when there is a bad driver

### ISSUE THREAD

**Issue by demiurg** [Toblerity/Fiona#281]
I have come upon a strange issue. It manifests itself when using fiona in a method, in a class, in another module and one of the gdal drivers generates GDAL_ERROR. What happens is that ogr raises exception which bubbles up to Fiona basically saying 'dataset not found', which took me half a day to fix by removing the bad driver. 

The error happens with Fiona 1.6 but NOT Fiona 1.4.
The error doesn't happen when importing fiona from console, but happened when I had a django project with views.py (worked in views) import form from forms.py, it happened anywhere in forms.py.

After I downgraded to fiona 1.4, things began to work, but I saw in the console:

```
GDAL_ERROR 1: dlopen(/usr/local/lib/gdalplugins/ogr_FileGDB.dylib, 1): Symbol not found: __ZN11OGRSFDriver14CopyDataSourceEP13OGRDataSourcePKcPPc
  Referenced from: /usr/local/lib/gdalplugins/ogr_FileGDB.dylib
  Expected in: flat namespace
 in /usr/local/lib/gdalplugins/ogr_FileGDB.dylib
```

Which prompted me to delete the driver, after which things worked. This made me think the driver could be the problem, and after upgrading back to 1.6, everything did work. I'm not sure I can provide more input on this, but I thought I'd at least document.

**Comment by micahcochran** [comment]
Did you test any of the OGR command line utilities for how it handled the bad driver?

**Comment by demiurg** [comment]
Yes, and I even tested the python ogr bindings, and they worked in the code immediately after the exception.

**Comment by sgillies** [comment]
I don't have enough information here for a solution, or for a work around other than "don't install busted driver plugins".

Good news is that once support for GDAL 2.0 lands, we'll have a lot more power to toggle drivers at runtime and navigate the FileGDB/OpenFileGDB gap.

**Comment by sgillies** [comment]
I regret dismissing your bug report, @demiurg. The least I can do is to not hide the useful dlopen error message. Sorry.

**Comment by demiurg** [comment]
Thanks, that would be informative to see OGR errors. They're usually indicative of 'pretty bad' things.

**Comment by sgillies** [comment]
I've figured out why this appeared in Fiona 1.6.

Here https://github.com/Toblerity/Fiona/blob/1.6.0/fiona/_drivers.pyx#L96-L100 we registered drivers *before* we set the error handler that turns GDAL/OGR errors into Python exceptions. This was a reversal from 1.4.

We've been doing the correct thing since 1.7. I'm certain that this bug is no more.
