### ISSUE TITLE
mportError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

### ISSUE THREAD

**Issue by wybert** [Toblerity/Fiona#283]
In [1]: import fiona
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cc872b235141> in <module>()
----> 1 import fiona

/home/hapyybeetle/anaconda/lib/python2.7/site-packages/fiona/__init__.py in <module>()
     70 from six import string_types
     71 
---> 72 from fiona.collection import Collection, BytesCollection, vsi_path
     73 from fiona._drivers import driver_count, GDALEnv, supported_drivers
     74 from fiona.odict import OrderedDict

/home/hapyybeetle/anaconda/lib/python2.7/site-packages/fiona/collection.py in <module>()
      5 import sys
      6 
----> 7 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
      8 from fiona.ogrext import Session, WritingSession
      9 from fiona.ogrext import (

ImportError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

**Comment by rbuffat** [comment]
https://gis.stackexchange.com/questions/72530/gdal-loads-in-python-but-not-ipython-linux
related?

**Comment by sgillies** [comment]
@wybert This is not a Fiona issue. You should report this in the issue tracker for the Conda channel that gave you the Fiona Conda package.
