### ISSUE TITLE
Add support for deleting datasets

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#285]
Fiona does not currently support deleting a dataset. I think this would be a useful feature, as when working with ESRI shapefiles there are a number of different files that need to be removed, which is a pain with `os.unlink`.

OGR/GDAL provides a method for this, `OGR_Dr_DeleteDataSource` (deprecated in 2.0) and `GDALDeleteDataset`.

http://www.gdal.org/ogr__api_8h.html#a4d2314e22acd846e7e31ff5a5c5ec27f
http://www.gdal.org/gdal_8h.html#a97939d588e2b350b9ec7a440f3e06a7c

If this feature was implemented, I'm not sure what the API should be. Perhaps `fiona.delete` as a counterpart to `fiona.open`?

**Comment by rbuffat** [comment]
Finding the right files to delete with glob should be fairly easy.

**Comment by jwass** [comment]
Maybe `fiona.remove` as an analog to [`os.remove`](https://docs.python.org/2/library/os.html#os.remove) - instead of `delete`? I've always preferred remove to unlink but they are identical.

**Comment by sgillies** [comment]
@snorfalorpagus sure, why not? I think @jwass's analogy to `os.remove` is right on. There's already a `fiona.listlayers()` function that acts like `os.listdir`, so a function that removed a layer (think multi-layer datasets) would fit right in.

**Comment by snorfalorpagus** [comment]
Closed by #288

**Comment by MathiasBaumgartinger** [comment]
Hello - stumbled across this ancient issue when i was trying to remove a subdataset from a GPKG using fiona. Is there any way to remove a feature subdataset from a geopackage using fiona? If no, are there any ambitions for such an implementation? 

I wouldve suggested the syntax `f"GPKG:{geopackage}:{feature_layer_name}"`

**Comment by sgillies** [comment]
@MathiasBaumgartinger that's a good idea. I think we'll do it for 2.0.
