### ISSUE TITLE
'fiona.ogrext.ItemsIterator' has no len()

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#296]
For normal Python dictionaries the `.items()` iterator has a length:

```
>>> data = {'a': 1, 'b': 2, 'c': 3}
>>> print(len(data))
>>> print(len(data.items()))
```

However, the `Collection` iterator doesn't work like this.

```
>>> src = fiona.open('test.shp', 'r')
>>> print(len(src))
192804
>>> print(len(src.items()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'fiona.ogrext.ItemsIterator' has no len()
```

Is this a design decision, or just oversight? Looks like it should be easy to implement - I'll give it a go when I find some time.

**Comment by sgillies** [comment]
@snorfalorpagus the `Collection` class implements `__len__()` already, so that could be used *except* when a query is passed to `items()`. In that case, you couldn't find the length except by iterating over all the items. In general, it might not be useful for the iterator to implement `__len__()`.

**Comment by snorfalorpagus** [comment]
The context for me expecting this was a progress bar function I had written, which wraps an iterator:

```
def progress(iterator):
    '''A simple text-based progress bar that wraps '''
    count = float(len(iterator))
    progress = -1
    formatter = lambda p: '...'.join(['{}'.format(n*10) for n in range(0, p / 10 + 1)]) + '.'*int(p % 10 / 2.5)
    for n, item in enumerate(iterator):
        new_progress = int(n / count * 100)
        if new_progress > progress:
            progress = new_progress
            print '\r' + formatter(progress),
        yield item
    progress = 100
    print '\r' + formatter(progress)
```

Usage is as follows:
```
for feature in progress(collection):
    pass # do something
```

Which produces a GDAL-like progress bar in the console:
```
0...10...20...30...40...50...60...70...80...90...100
```

I've tweaked the progress bar to accept a `length` parameter, which I can pass `len(collection)` when using `collection.items()`, but I wondered why is this needed and wouldn't it be easier (for me) if the iterator just provided `__len__()`. Is there a context for which the iterator doesn't know it's length? With a filter maybe? If that is the case then I agree it shouldn't provide `__len__`.

**Comment by sgillies** [comment]
@snorfalorpagus there's no `__len__()` in the [iterator protocol](https://docs.python.org/2/library/stdtypes.html#iterator-types) and iterators do not in general know their length. The length might be infinite or subject to additions from the other end (a queue, for example). As I said above, OGR doesn't know how many items pass through the filter until it's stepped through and compared all of them. That's why I implemented an iterator.

**Comment by snorfalorpagus** [comment]
OK I understand now.
