### ISSUE TITLE
loop within a loop bug... or type 16 error?

### ISSUE THREAD

**Issue by NicolasCadieux** [Toblerity/Fiona#297]
Hi,
I don't know if this is a bug but i noticed this issue.
I have been doing multiple (loops B inside of  loop A).  Basically the idea is this.
1: with fiona.open('c:/temp1.shp',"r", 'ESRI Shapefile') as "temp":
 -loop through "temp1" and find info (loop A)
-----reloop through "temp1" and find more info (loop B inside loop A)
When I access the file the second time, the program ends but breaks out of loop A and stops (But there is no reason for this.)

Currently my solution is this:
1: temp2 = fiona.open('c:/temp.shp', "r", 'ESRI Shapefile')
2: with fiona.open('c:/temp.shp',"r", 'ESRI Shapefile') as "temp1":
 -loop through "temp1" and find info (loop A)
-----reloop through "temp2" and find more info (loop B inside loop A)
This cause the program to work as it should. Same code but 2 a

Is this a bug? A normal python behavior or a type 16 error? (the error being sitting 16 inches in front of the screen:)
Cheers!

**Comment by geowurster** [comment]
@NicolasCadieux Yes this is the expected behavior - the object returned by `fiona.open()` is an iterator, which can only be used once.  The first loop consumes all the features so the second has nothing to process.  The difference between iterators and iterable objects can be confusing, so if you're not familiar this [document](http://anandology.com/python-practice-book/iterators.html) covers just about everything related to iteration.

Another way to illustrate this behavior is:

```python
iterator  = iter(range(5))

for i1 in iterator:
    print("Loop1", i1)

for i2 in iterator:
    print("Loop2", i2)

('Loop1', 0)
('Loop1', 1)
('Loop1', 2)
('Loop1', 3)
('Loop1', 4)
```

None of the `print()` statements in the second loop are executed.

There are a few solutions:

1. As you mention, each loop can operate on a different handle., although both should be opened using the [`with`](http://stackoverflow.com/questions/1990373/nesting-with-statements-in-python) statement.  This works because you are operating on two different unrelated iterators that are just looking at the same file.
2. If the input data is small enough, cache all of it in memory in a list, which can be iterated over multiple times.
3. Modify your algorithm.

**Comment by NicolasCadieux** [comment]
Hi,

Thank you for this info. I will read it carefully.  Obviously the problem sit 16 inches in front of the screen...

It's never to late to learn!
Nicolas

On Nov 12, 2015 12:53 AM, Kevin Wurster <notifications@github.com> wrote:
@NicolasCadieux Yes this is the expected behavior - the object returned by `fiona.open()` is an iterator, which can only be used once.  The first loop consumes all the features so the second has nothing to process.  The difference between iterators and iterable objects can be confusing, so if you're not familiar this [document](http://anandology.com/python-practice-book/iterators.html) covers just about everything related to iteration.

Another way to illustrate this behavior is:

```python
iterator  = iter(range(5))

for i1 in iterator:
    print("Loop1", i1)

for i2 in iterator:
    print("Loop2", i2)

('Loop1', 0)
('Loop1', 1)
('Loop1', 2)
('Loop1', 3)
('Loop1', 4)
```

None of the `print()` statements in the second loop are executed.

There are a few solutions:

1. As you mention, each loop can operate on a different handle., although both should be opened using the [`with`](http://stackoverflow.com/questions/1990373/nesting-with-statements-in-python) statement.  This works because you are operating on two different unrelated iterators that are just looking at the same file.
2. If the input data is small enough, cache all of it in memory in a list, which can be iterated over multiple times.
3. Modify your algorithm.

---

**Comment by NicolasCadieux** [comment]
Hi,
My original idea was to do "2. If the input data is small enough, cache all of it in memory in a list, which can be iterated over multiple times."  But I have not found a way to send the entire content of a shape file into a list and then to read it back with Shapely.  (For now, I am looping the shapefile and filtering it using the [id]).  Can you offer some help?  
Thanks in advance!
Nicolas

**Comment by sgillies** [comment]
@geowurster Excellent explanation, thanks!

@NicolasCadieux do something like this:

```
import fiona

with fiona.open('c:/temp1.shp') as src:
    features = list(src)
```

After this, `features` is a Python list that you can filter and process as you see fit.

**Comment by NicolasCadieux** [comment]
Thanks,
That was very useful (and I did not know we could create a list that way without using list.append().)
  
I really don't know what I was doing wrong... but it works now... I was getting error with shapely not being able to read the list shapes...

 (could be that coding at 3h00 in the morning is a bad idea....) 

====
for others that are lost...

import fiona
from shapely.geometry import shape
import time
ptList = []
classpolyList =[]
with fiona.open("c:/pytemp/polygoneFile.shp", "r") as classPoly:
    classpolyList = list(classPoly)
with fiona.open("c:/pytemp/pointFile.shp", "r") as inputLidarPt:
    ptList = list(inputLidarPt)

    for polyg in classpolyList:
        for pts in ptList:
            if shape(polyg['geometry']).contains(shape(pts['geometry'])):
                print 'in'
            else:
                print 'out'
