### ISSUE TITLE
Unable to set the correct CRS for new Shapefile

### ISSUE THREAD

**Issue by leowmjw** [Toblerity/Fiona#300]
Trying to copy over a shapefile after modifying the properties; using Fiona 1.6.2

Code snippet as below after processing and before writing out: 
```
        sink = fiona.open(
            ModifiedShapefile.shape_filename + '.shp', 'w',
            crs=from_epsg(3857),
            driver=ModifiedShapefile.sink_driver,
            schema=ModifiedShapefile.sink_schema,
            )
        ...
        ...
                    sink.write(new_feature_map[norm_dm])

```

Shapefile is being setup correctly except for CRS.  I have to manually go in QGIS to setup the correct CRS.  It is confirmed manually as per below:
```
leow$ fio insp ogr/results/new-Sarawak.shp
Fiona 1.6.2 Interactive Inspector (Python 2.7.5)
Type "src.schema", "next(src)", or "help(src)" for more information.
>>> src.crs
{u'lon_0': 0, u'k': 1, u'datum': u'WGS84', u'y_0': 0, u'no_defs': True, u'proj': u'merc', u'x_0': 0, u'units': u'm'}
```

Original Shapefile is as per below:
```
leow$ fio insp ogr/source/Sarawak/16_Swk_13_Ori.shp 
Fiona 1.6.2 Interactive Inspector (Python 2.7.5)
Type "src.schema", "next(src)", or "help(src)" for more information.
>>> src.crs
{'init': u'epsg:4326'}
```

Any ideas why it does not work?  I have also tried by referring the new CRS to the CRS from the original shapefile but it shows the same result.

**Comment by micahcochran** [comment]
I would probably read everything into memory and close the Fiona handle (end the with block). Then do my reprojection and other operations. Open the shapefile again and write to it.

My suspicion is that there is a lock on the .prj file due to something in happening in the reading process.

Please provide a example code that shows the problem in action.

**Comment by leowmjw** [comment]
Thanks @micahcochran; that is actually what I did; open the original shapefile; read everything to memory and do the necessary changes; then open a whole new shapefile to write it down then closing the new shapefile.

What are possible reasons for the .prj files being locked?  I would have thought opening a whole new shapefile will prevent all possible lock issues.

I try it on a smaller subset to see if I can reproduce.

**Comment by sgillies** [comment]
Thanks for helping out, @micahcochran!

@leowmjw a small test case that I can run on my own computer would be super helpful.
