### ISSUE TITLE
Handling date fields

### ISSUE THREAD

**Issue by micahcochran** [Toblerity/Fiona#302]
Reading from a shapefile date fields are handled as string.  I assume that this was a design decision in order to support the `__geo_interface__`.

Is there a good way to redesign the the api to date fields to be represented as Python datetime objects?  Perhaps setting a SUPER_SECRET_API_FLAG_BREAKING_GEOJSON to True.  (Possibly not my most well thought through idea.)

Here is code and [data (link)](https://github.com/micahcochran/GeospatialTestData/tree/master/dates/shp) that I am using for those who want to test this out themselves:
```python
import pprint
import fiona

fh = fiona.open("us_historic_capitals.shp", "r")
print('---- SCHEMA ---- ')
pprint.pprint(fh.schema)

feat = next(fh)

print( 'Date field value: {0}'.format(feat['properties']['FirstDate']) )
print( 'Type: {0}'.format(type(feat['properties']['FirstDate'])) )

fh.close()
```

These are the results:
```python
---- SCHEMA ----
{'geometry': 'Point',
 'properties': OrderedDict([(u'X', 'float:24.15'), (u'Y', 'float:24.15'), (u'Building', 'str:50'),
(u'City', 'str:50'), (u'FirstDate', 'date')])}
Date field value: 1774-09-05
Type: <type 'str'>
```

**Comment by sgillies** [comment]
@micahcochran I'm leaning in favor of supporting this. As you can see in https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext1.pyx#L202, the ISO8601 strings that come out of Fiona pass through `datetime` already. If you gave us a pull request with adequate tests, I don't think I could say no.

I'd insist that this feature be enabled in Python code and not via environment variable, however. Something like `fiona.open('example.shp', datetime=True)`.

**Comment by sgillies** [comment]
Closing as it's been inactive for too long. We can reopen if needed.

![giphy 2](https://cloud.githubusercontent.com/assets/33697/15050207/835a9c4a-12af-11e6-84f2-5ac6a7fa61e8.gif)
