### ISSUE TITLE
Disappearing PROJ parameters

### ISSUE THREAD

**Issue by bekozi** [Toblerity/Fiona#315]
I've encountered a couple issues when working with fiona CRS dictionaries. I wanted to make sure this is not expected behavior. PROJ often suprises me! I put a test file here: https://gist.github.com/bekozi/5327574ccf356811c41e.

1. The ``+wktext`` parameter disappears after using ``from_string``: https://gist.github.com/bekozi/5327574ccf356811c41e#file-test_fiona_proj4_parms-py-L24.
2. The ``+towgs84`` parameter disappears following a write: https://gist.github.com/bekozi/5327574ccf356811c41e#file-test_fiona_proj4_parms-py-L56.

I would expect the parameters to be preserved...

Thanks in advance!

**Comment by micahcochran** [comment]
For (1): Perhaps [`+wktext`](https://trac.osgeo.org/proj/wiki/FAQ#ChangingEllipsoidWhycantIconvertfromWGS84toGoogleEarthVirtualGlobeMercator) should be added to the [`_param_data`](https://github.com/Toblerity/Fiona/blob/d17a028908e5ed00ae1710a764663ba58e20a944/fiona/crs.py#L70) list.

**Comment by sgillies** [comment]
@bekozi I believe #352 is the fix for #1 above (and thanks, @micahcochran, that was it). As far as I can tell, #2 is an issue with PROJ and OGR and Shapefiles and has not been resolved (see https://trac.osgeo.org/grass/ticket/1988).

**Comment by bekozi** [comment]
Thanks @sgillies and @micahcochran. Good to know about the ``+towgs84`` OGR issue too.
