### ISSUE TITLE
version 1.6.3 fails on import

### ISSUE THREAD

**Issue by rossfadely** [Toblerity/Fiona#317]
collection.py tries to import from ogrext but there is no longer such a module.  Now there appears to be ogrext1 and ogrext2

**Comment by geowurster** [comment]
@rossfadely Could you please explain how you are installing Fiona?

**Comment by sgillies** [comment]
@rossfadely it's still just a single ogrext.pyx in https://github.com/Toblerity/Fiona/tree/1.6.3/fiona. The split is in the master branch.
