### ISSUE TITLE
UnicodeDecodeError error when using pip install

### ISSUE THREAD

**Issue by cmlakhan** [Toblerity/Fiona#320]
I recently spun up an ec2 instance using Ubuntu 14.04 and Python2.7.6.  I created a virtual environment where I am trying to install fiona but am running into this pip install error

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

Here is the full error, any thoughts?

Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from fiona)
Downloading/unpacking click>=4.0 (from cligj->fiona)
  Downloading click-6.2-py2.py3-none-any.whl (70kB): 70kB downloaded
Installing collected packages: fiona, cligj, click-plugins, click
  Running setup.py install for fiona
    WARNING:root:Failed to get options via gdal-config: [Errno 2] No such file or directory
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'metadata_version'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'requires_python'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'requires_external'
      warnings.warn(msg)
    building 'fiona._transform' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c fiona/_transform.cpp -o build/temp.linux-x86_64-2.7/fiona/_transform.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    fiona/_transform.cpp:269:18: fatal error: gdal.h: No such file or directory
     #include "gdal.h"
                      ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/fiona/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KaKLoo-record/install-record.txt --single-version-externally-managed --compile:
    WARNING:root:Failed to get options via gdal-config: [Errno 2] No such file or directory

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'metadata_version'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'requires_python'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'requires_external'

  warnings.warn(msg)

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/fiona

copying ./fiona/errors.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/collection.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/odict.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/tool.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/inspector.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/rfc3339.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/__init__.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/transform.py -> build/lib.linux-x86_64-2.7/fiona

copying ./fiona/crs.py -> build/lib.linux-x86_64-2.7/fiona

creating build/lib.linux-x86_64-2.7/fiona/fio

copying ./fiona/fio/cat.py -> build/lib.linux-x86_64-2.7/fiona/fio

copying ./fiona/fio/options.py -> build/lib.linux-x86_64-2.7/fiona/fio

copying ./fiona/fio/main.py -> build/lib.linux-x86_64-2.7/fiona/fio

copying ./fiona/fio/bounds.py -> build/lib.linux-x86_64-2.7/fiona/fio

copying ./fiona/fio/__init__.py -> build/lib.linux-x86_64-2.7/fiona/fio

copying ./fiona/fio/helpers.py -> build/lib.linux-x86_64-2.7/fiona/fio

copying ./fiona/fio/info.py -> build/lib.linux-x86_64-2.7/fiona/fio

running build_ext

building 'fiona._transform' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/fiona

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c fiona/_transform.cpp -o build/temp.linux-x86_64-2.7/fiona/_transform.o

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

fiona/_transform.cpp:269:18: fatal error: gdal.h: No such file or directory

 #include "gdal.h"

                  ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/fiona/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KaKLoo-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/fiona
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
(venv) ubuntu@ip-172-31-63-206:/scratch/environmentalPICI_ETL/pythonETL$

**Comment by rbuffat** [comment]
> fiona/_transform.cpp:269:18: fatal error: gdal.h: No such file or directory

Probably you are missing libgdal1-dev

**Comment by cmlakhan** [comment]
That seems to have worked thank you so much!

**Comment by sgillies** [comment]
Thanks, @rbuffat!
