### ISSUE TITLE
fio filter not included in 1.6.3

### ISSUE THREAD

**Issue by smnorris** [Toblerity/Fiona#321]
`fio filter` looks very useful. It is in the docs but not included in the latest release (1.6.3). I'll download the source and install that way but wonder if this is by design?

**Comment by smnorris** [comment]
I'll close this because installing from source worked fine.

**Comment by sgillies** [comment]
It's just that GitHub shows you the master branch of Fiona (fio-filter is coming in 1.7) by default while 1.6.3 comes from the maint-1.6 branch.
