### ISSUE TITLE
Fiona is only opening polygon files when function run in a celery task

### ISSUE THREAD

**Issue by huevosabio** [Toblerity/Fiona#323]
**Background**
I have an application that needs to read user shapefiles compressed into a zip file in order to create the project. Currently, the workflow is as follows:

- User uploads zip file containing all shapefiles
- Server stores zipfile into Mongo DB (I know, should be using someting like S3)
- Server then places a task into a RabbitMQ queue for unpacking and storing the layers.
- A celery worker picks up the task, downloads the zip file from Mongo DB and stores it temporarily in the file system (until there's a better way #318 ), then the worker reads it out each layer and stores it as a GeoJSON in the DB.

Ideally this would work flawlessly, and it used to before using the queuing approach. Now I have an odd error: only polygon features (or at least that's what it seems to be) get read. My application takes Point, MultiPoint, LineString,  and Polygon features, and somehow only the latter are detected.

I checked the temporary zip file saved in the file system and it does seem to include all the files. 

The code I am using to read them out:

```python
 with fiona.drivers():
                for i, layername in enumerate(
                fiona.listlayers(
                    '/',
                    vfs='zip://'+zipfile)):
                    feature = GeoFeat()
                    feature.read_shapefile(layername, zipfile)
                    feature.name = layername
                    try:
                        feature.save()
                        crane_project.features.append(feature)
                    except:
                        messages.append(layername + ': not saved')
                        continue
```

```feature.read_shapefile``` is working fine. The issue seems to be in ```fiona.listlayers```, which is the one detecting only the polygon feature.

Any ideas or pointers as how can I pinpoint the source of this issue?

**Comment by sgillies** [comment]
Can you link me to a small zipfile that demonstrates the problem? I'd be happy to take a look.

**Comment by huevosabio** [comment]
Sure, [shapefiles.zip](https://files.zenhub.io/56ba386b1f38467923f7ceba)
Uploaded using [**ZenHub.io**](http://www.zenhub.io).

**Comment by huevosabio** [comment]
The only one that gets read is the "boundary" file. The other get ignored. However, if running directly within flask (instead of celery) it works flawlessly.

**Comment by sgillies** [comment]
I'll take a look. I'm no celery expert but this feels like a difference in GDAL runtime env between your flask and your celery processes. Maybe one supports formats the other doesn't?

**Comment by huevosabio** [comment]
Hmmm they are both being run in the same computer (or docker container when deployed). I am no GDAL expert, but could it be that two "independent" python processes that are using Fiona are obstructing each other? 

For the Celery workers, I use the same repository/virtualenv/machine so it should in theory work the same..

**Comment by huevosabio** [comment]
I thought maybe it was the process of storing into and retrieving from MongoDB, but it doesn't seem like it, the temp zip file I generate works fine if I open it from an ipython instance.

**Comment by huevosabio** [comment]
Perhaps a dumn question, what is the benefit of using

```python
with fiona.drivers():
```
?

**Comment by sgillies** [comment]
@huevosabio `fiona.drivers()` registers the GDAL format drivers, but you don't need to call it, it's call within `listlayers()`.

I'm stumped. Are you by any chance using GDAL's Python bindings along with fiona?

**Comment by huevosabio** [comment]
I am not. Perhaps a quick look at the code could help? The guilty file is here https://github.com/huevosabio/windopt/blob/queuing/app/cranepath.py

**Comment by geowurster** [comment]
@huevosabio Looks like you have a [return inside the for loop](https://github.com/huevosabio/windopt/blob/queuing/app/cranepath.py#L135) so the loop never gets past the first layer, which is `boundary`.

**Comment by snorfalorpagus** [comment]
Nice spot @geowurster!

**Comment by sgillies** [comment]
@geowurster :dart:

**Comment by huevosabio** [comment]
Well this is embarrasing! Thanks @geowurster !
