### ISSUE TITLE
Failed to sync to disc when using zip vfs

### ISSUE THREAD

**Issue by mccarthyryanc** [Toblerity/Fiona#325]
I am trying to read from a zipped shapefile (only one layer) and write back out to another shapefile. Here is a simplified example:
```python
src_filename = '/full/path/to/shapefile.zip'
dst_filename = '/full/path/to/output'
with fiona.open(src_filename,'r',vfs='zip://') as src_dataset:
    count = len(src_dataset)
    meta = src_dataset.meta
    with fiona.open(dst_filename,'w',**meta) as dst_dataset:
        for item in src_dataset:
            dst_dataset.write(item)
```
This gives a runtime error:
```
Traceback (most recent call last):
  File "/home/user/src/python_scripts/junk.py", line 11, in <module>
    dst_dataset.write(item)
  File "/home/user/anaconda2/lib/python2.7/site-packages/fiona/collection.py", line 413, in __exit__
    self.close()
  File "/home/user/anaconda2/lib/python2.7/site-packages/fiona/collection.py", line 397, in close
    self.flush()
  File "/home/user/anaconda2/lib/python2.7/site-packages/fiona/collection.py", line 387, in flush
    self.session.sync(self)
  File "fiona/ogrext.pyx", line 985, in fiona.ogrext.WritingSession.sync (fiona/ogrext.c:17250)
RuntimeError: Failed to sync to disk
```

However, it does look like the contents of the output shapefile are correct.

**Python Version:** Python 2.7.11 |Anaconda 2.4.1 (64-bit)
**Fiona Version:** 1.6.3

**Comment by micahcochran** [comment]
I modified filled in some sample data to try to replicate that.

First I zipped the sample dataset coutwildrnp.shp into archive.zip. I left the archive.zip in the same folder.
```
../Fiona/tests/data$  zip archive.zip coutwildrnp.*
```
I modified the code a little.  the current working directory is just above the Fiona directory:
```Python
import fiona
zip_src_filename = 'zip://./Fiona/tests/data/archive.zip'
dst_filename = './output.shp'
with fiona.open('/coutwildrnp.shp','r',vfs=zip_src_filename) as src_dataset:
    count = len(src_dataset)
    meta = src_dataset.meta
    with fiona.open(dst_filename,'w',**meta) as dst_dataset:
        for item in src_dataset:
            dst_dataset.write(item)
```
The output.shp looks like it matches.  No RuntimeError occurred.  I'll try this on Windows soon.

Ubuntu 14.04 / Python 2.7.6 & 3.4.3 / Fiona 1.6.3  / GDAL 1.11.2.

**Comment by mccarthyryanc** [comment]
@micahcochran I created my archive in the same way and then modified my test code to follow yours. However, I still get the RuntimeError. I forgot to mention OS/GDAL version:
**OS:** Ubuntu 14.04
**GDAL:** 2.0.0

**Comment by sgillies** [comment]
@mccarthyryanc Fiona 1.6 doesn't support GDAL 2.0. Support is coming in 1.7.

**Comment by mccarthyryanc** [comment]
@sgillies, got it. I'll hold off on using GDAL 2.0 until the 1.7 release. Thanks!
