### ISSUE TITLE
error reading Null date time - breaks iteration

### ISSUE THREAD

**Issue by ifly4pie** [Toblerity/Fiona#326]
Hi, when reading a file that has datetime field types, encountering a NULL will break the iterator.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/fiona/collection.py", line 323, in __getitem__
    return self.session.__getitem__(item)
  File "fiona/ogrext.pyx", line 672, in fiona.ogrext.Session.__getitem__ (fiona/ogrext.c:11911)
  File "fiona/ogrext.pyx", line 205, in fiona.ogrext.FeatureBuilder.build (fiona/ogrext.c:4115)
ValueError: year is out of range
```
I'm using version 1.6.3, the latest from pip? I believe it's breaking around here: 
https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext1.pyx#L205

Instead of breaking iteration, can you simply return `{date_field: None}` like you did in issue #31? 

Thanks in advance.

**Comment by geowurster** [comment]
@ifly4pie I am unable to re-create your issue and based on the error you posted I suspect the data you are working with is malformed.  `NULL` property values are caught by the [first](https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext1.pyx#L174) condition in that `if` block and are translated to `None`, so if you're hitting the line you mentioned then you must be getting some value.

```python
import datetime
datetime.date(-1, 1, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year is out of range
```

**Comment by ifly4pie** [comment]
Thanks for the quick reply. You are correct - the data file I have is corrupted. 

After digging deeper, a few bytes of spaces were missing in the middle of our problem record in the DBF file, causing the remaining data to be shifted by three characters.  

I'm sorry I didn't catch it at first. I tried to read the DBF file with two other tools to replicate the error, and they both led me astray. They both read the file, silently ignored the misalignment, and continued to display future records, showing NULL for datetimes they could not parse, and blindly parsing the remaining numbers shifted off by three characters.   I finally had another guy look at it with me, and he caught the missing characters in a hex editor.

**Comment by sgillies** [comment]
Gnarly! Thanks for the post-mortem, @ifly4pie, it might save someone else.
