### ISSUE TITLE
No conda builds of fiona seem to work in development environments

### ISSUE THREAD

**Issue by nickeubank** [Toblerity/Fiona#329]
I'm looking for a conda build of Fiona that will work on OSX in an anaconda development environment, but can't seem to find one anywhere. (though `pip install fiona` works, and conda installs work in the root environment -- trying to figure out conda build so I can include it in the new release of *geopandas*). 

I've tried:

* conda install fiona
* conda install -c ioos fiona
* conda install  -c conda-forge fiona

(If you want to do yourself, the flow is just:
    
    conda create -y --name test_fiona python=3.4
    source activate test_fiona
    [conda install command]
    python -c 'import fiona'

Output of standard build:

    conda create -y --name test_fiona4 python=3.4
    Fetching package metadata: ....
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona4:

    The following NEW packages will be INSTALLED:

        openssl:    1.0.2g-0      defaults
        pip:        8.1.1-py34_0  defaults
        python:     3.4.4-0       defaults
        readline:   6.2-2         defaults
        setuptools: 20.3-py34_0   defaults
        sqlite:     3.9.2-0       defaults
        tk:         8.5.18-0      defaults
        wheel:      0.29.0-py34_0 defaults
        xz:         5.0.5-1       defaults
        zlib:       1.2.8-0       defaults

    Linking packages ...
    [      COMPLETE      ]|###################################################################################################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate test_fiona4
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    ➜  ~ source activate test_fiona4
    discarding /Users/Nick/anaconda/bin from PATH
    prepending /Users/Nick/anaconda/envs/test_fiona4/bin to PATH
    (test_fiona4)➜  ~ conda install -y fiona
    Fetching package metadata: ....
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona4:

    The following NEW packages will be INSTALLED:

        click:     6.3-py34_0        defaults
        cligj:     0.2.0-py34_0      defaults
        curl:      7.45.0-0          defaults
        fiona:     1.6.0-np110py34_0 defaults
        hdf5:      1.8.15.1-2        defaults
        libgdal:   2.0.0-0           defaults
        libnetcdf: 4.3.3.1-3         defaults
        mkl:       11.3.1-0          defaults
        numpy:     1.10.4-py34_0     defaults
        six:       1.10.0-py34_0     defaults

    Linking packages ...
    [      COMPLETE      ]|###################################################################################################################################| 100%
    (test_fiona4)➜  ~ python -c 'import fiona'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/Nick/anaconda/envs/test_fiona4/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
        from fiona.collection import Collection, BytesCollection, vsi_path
      File "/Users/Nick/anaconda/envs/test_fiona4/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
        from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
    ImportError: dlopen(/Users/Nick/anaconda/envs/test_fiona4/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: @loader_path/./libgssapi_krb5.2.2.dylib
      Referenced from: /Users/Nick/anaconda/envs/test_fiona4/lib/libgdal.20.dylib
      Reason: image not found

Output with ioos channel:

    conda install -c ioos fiona
    Proceed ([y]/n)? y

    Linking packages ...
    [      COMPLETE      ]|###################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate test_fiona
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    ➜  ~ source activate test_fiona           
    discarding /Users/Nick/anaconda/bin from PATH
    prepending /Users/Nick/anaconda/envs/test_fiona/bin to PATH
    (test_fiona)➜  ~ conda install -c ioos fiona          
    Fetching package metadata: ......
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona:

    The following NEW packages will be INSTALLED:

        click:         6.3-py34_0        
        click-plugins: 1.0.3-py34_0      
        cligj:         0.4.0-py34_0      
        curl:          7.45.0-0          
        fiona:         1.6.3-np110py34_0 
        gdal:          1.11.3-np110py34_2
        geos:          3.4.2-4           
        hdf4:          4.2.11-0          
        hdf5:          1.8.15.1-2        
        jpeg:          8d-1              
        krb5:          1.13.2-0          
        libnetcdf:     4.3.3.1-3         
        mkl:           11.3.1-0          
        munch:         2.0.4-py34_0      
        numpy:         1.10.4-py34_0     
        openjpeg:      2.1.0-0           
        proj.4:        4.9.1-1           
        six:           1.10.0-py34_0     
        xerces-c:      3.1.2-0           

    Proceed ([y]/n)? y

    Linking packages ...
    [      COMPLETE      ]|###################################################| 100%
    (test_fiona)➜  ~ python
    Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan  9 2016, 17:30:09) 
    [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import fiona
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/Nick/anaconda/envs/test_fiona/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
        from fiona.collection import Collection, BytesCollection, vsi_path
      File "/Users/Nick/anaconda/envs/test_fiona/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
        from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
    ImportError: dlopen(/Users/Nick/anaconda/envs/test_fiona/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
      Referenced from: /Users/Nick/anaconda/envs/test_fiona/lib/libgdal.1.dylib
      Reason: image not found    

Output with conda-forge:

    conda create -y --name test_fiona3 python=3.4
    Fetching package metadata: ....
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona3:

    The following NEW packages will be INSTALLED:

        openssl:    1.0.2g-0      defaults
        pip:        8.1.1-py34_0  defaults
        python:     3.4.4-0       defaults
        readline:   6.2-2         defaults
        setuptools: 20.3-py34_0   defaults
        sqlite:     3.9.2-0       defaults
        tk:         8.5.18-0      defaults
        wheel:      0.29.0-py34_0 defaults
        xz:         5.0.5-1       defaults
        zlib:       1.2.8-0       defaults

    Linking packages ...
    [      COMPLETE      ]|#############################################################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate test_fiona3
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    ➜  ~ source activate test_fiona3
    discarding /Users/Nick/anaconda/bin from PATH
    prepending /Users/Nick/anaconda/envs/test_fiona3/bin to PATH
    (test_fiona3)➜  ~ conda install -y -c conda-forge fiona
    Fetching package metadata: ......
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona3:

    The following NEW packages will be INSTALLED:

        click:         6.3-py34_0         defaults   
        click-plugins: 1.0.3-py34_0       conda-forge
        cligj:         0.4.0-py34_0       defaults   
        curl:          7.45.0-0           defaults   
        fiona:         1.6.3-np110py34_0  conda-forge
        gdal:          1.11.4-np110py34_0 conda-forge
        geos:          3.4.2-0            conda-forge
        hdf4:          4.2.11-0           defaults   
        hdf5:          1.8.15.1-2         defaults   
        jbig:          2.1-0              defaults   
        jpeg:          8d-1               defaults   
        kealib:        1.4.5-0            defaults   
        krb5:          1.13.2-0           defaults   
        libnetcdf:     4.3.3.1-3          defaults   
        libpng:        1.6.17-0           defaults   
        libtiff:       4.0.6-1            defaults   
        mkl:           11.3.1-0           defaults   
        munch:         2.0.4-py34_0       conda-forge
        numpy:         1.10.4-py34_0      defaults   
        openjpeg:      2.1.0-1            conda-forge
        proj.4:        4.9.1-2            conda-forge
        six:           1.10.0-py34_0      defaults   
        xerces-c:      3.1.2-0            defaults   

    Linking packages ...
    [      COMPLETE      ]|#############################################################################################| 100%
    (test_fiona3)➜  ~ python -c 'import fiona'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
        from fiona.collection import Collection, BytesCollection, vsi_path
      File "/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
        from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
    ImportError: dlopen(/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
      Referenced from: /Users/Nick/anaconda/envs/test_fiona3/lib/libgdal.1.dylib
      Reason: image not found
    (test_fiona3)➜  ~

**Comment by ocefpaf** [comment]
This was solved in conda-forge by adding `giflib` as a dependency. The key to solving this was:

`ImportError: dlopen(/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib`

I guess that `giflib` could be documented as a fiona dependency to properly compiled `ogrext`.

**Comment by micahcochran** [comment]
> I guess that `giflib` could be documented as a fiona dependency to properly compiled `ogrext`.

[giflib seems to be a GDAL requirement](http://www.gdal.org/frmt_gif.html) depending upon how GDAL is compiled.  Fiona's travis [build script for GDAL](https://github.com/Toblerity/Fiona/blob/3ebef78f2d1af1e306ad2a1df043511bfc55c13b/scripts/travis_gdal_install.sh) uses a --without-gif flag.  If you search for "gif" and "giflib" on Fiona's github search, currently you will only find this issue and scripts/travis_gdal_install.sh

**Comment by ocefpaf** [comment]
Thanks @micahcochran I will take a closer look at out gdal package and why we are having that issue.
