### ISSUE TITLE
Switch to pytest for unittests

### ISSUE THREAD

**Issue by geowurster** [Toblerity/Fiona#374]
I have missed `@pytest.mark.parametrize()` for the last few PR's I submitted in addition to some other features.  Any objections?  I think just switching to `$ py.test` is little to no work, and we can migrate individual tests as needed moving forward.

**Comment by sgillies** [comment]
It won't be zero work, because nosetests runs a setup script that creates GeoJSON and archives from the testing shapefile, and py.test doesn't run this script. It would need to be replaced by fixtures. This is the reason I've been putting it off.
