### ISSUE TITLE
What is the relation between the fiona.supported_drivers and OGR drivers?

### ISSUE THREAD

**Issue by AlexArcPy** [Toblerity/Fiona#377]
I have a fresh installation of `fiona` in Anaconda, `fiona 1.7.0               np110py27_2`.

Running 
`
import fiona
pprint(fiona.supported_drivers)
`
gives
```
{'ARCGEN': 'r',
 'AeronavFAA': 'r',
 'BNA': 'raw',
 'DGN': 'raw',
 'DXF': 'raw',
 'ESRI Shapefile': 'raw',
 'GPSTrackMaker': 'raw',
 'GPX': 'raw',
 'GeoJSON': 'rw',
 'Idrisi': 'r',
 'MapInfo File': 'raw',
 'OpenFileGDB': 'r',
 'PCIDSK': 'r',
 'SEGY': 'r',
 'SUA': 'r'}
```

Looking at http://www.gdal.org/ogr_formats.html. There are some formats there that have Yes in the `Compiled by default`, such as `GMT`, `HTF`, `TIGER` and a bunch of others that are not present in the Fiona supported drivers list.

Are those supported in Fiona or not?

**Comment by micahcochran** [comment]
If you look at [drvsupport.py](https://github.com/Toblerity/Fiona/blob/master/fiona/drvsupport.py), there is a dictionary supported_drivers.  Many are not enabled at all.  There are some comment about why some were not enabled.

If you need those formats, it would be easy enough to uncomment the lines and test them out.  Please do submit a PR if they do seem to work (and include unit tests).

In the bottom of the file the _filter_supported_drivers() function asks GDAL if a particular driver is supported, if GDAL the driver is unsupported that driver is removed from the dictionary.

**Comment by AlexArcPy** [comment]
@micahcochran , great, thank you for sharing this.

**Comment by sgillies** [comment]
Thanks for the explanation, @micahcochran.

The main criteria for whether format X is turned on or off is: how much time do I have to support users of format X? The completeness and user experience of OGR drivers vary. Some work with almost no extra configuration needed and are relatively cheap to support. Some will not work at all without complicated configuration (environmental variables, etc) and extra libraries and are expensive to support. As the project becomes more mature we might be able to officially support more format drivers, but we should be very parsimonious about it.

**Comment by AlexArcPy** [comment]
@sgillies , I agree with you, good point. Most of the formats that commented out are very specific, so I understand that supporting them can be a burden.
