### ISSUE TITLE
bug? fiona.transform.transform() and fiona.transform.transform_geom() don't work

### ISSUE THREAD

**Issue by AlexArcPy** [Toblerity/Fiona#378]
Running this
```

import fiona

from fiona import transform

res = transform.transform_geom('EPSG:4326', 'EPSG:3857',
                               {'type': 'Point', 'coordinates': [-105.0, 40.0]})
res
```

returns unmodified `{'type': 'Point', 'coordinates': (-105.0, 40.0)}`.

Running this

```
res = transform.transform('EPSG:4326', 'EPSG:26953', [-105.0], [40.0])
res
```

crashes Python:

> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.

Sample code copied from https://github.com/Toblerity/Fiona/blob/master/fiona/transform.py

I have 
```
    fiona 1.7.0 np110py27_1
    Python 2.7.10

installed in Anaconda 2-4.1.1-Windows-x86 environment
```

**Comment by micahcochran** [comment]
I tried it on my Linux box, and it worked for me.

Python 2.7.11  (and I tested 3.5.1)
Fiona 1.7.0.post2
GDAL 1.11.3

```Python
In [1]: from fiona import transform

In [2]: transform.transform_geom('EPSG:4326', 'EPSG:3857',
                               {'type': 'Point', 'coordinates': [-105.0, 40.0]})
Out[2]: {'coordinates': (-11688546.533293728, 4865942.279503176), 'type': 'Point'}

In [3]: transform.transform('EPSG:4326', 'EPSG:26953', [-105.0], [40.0])
Out[3]: ([957097.0952383667], [378940.8419189226])
```

**Comment by geowurster** [comment]
@AlexArcPy Fiona/OGR uses [`PROJ.4`](https://github.com/OSGeo/proj.4) for coordinate reference system transformations so you may be missing that library.  I don't have any experience with Anaconda so unfortunately I can't help debug that environment.  `PROJ.4` comes with a `$ proj` utility that might help you figure out if its installed and you could also try the command below, but I don't know what will happen if `PROJ.4` is missing:

```console
$ echo "-105.0 40.0" | gdaltransform -s_srs EPSG:4326 -t_srs EPSG:3857
-11688546.5332937 4865942.27950318 0
```

**Comment by AlexArcPy** [comment]
@micahcochran , thanks for testing this, great. @geowurster , thanks for pointing this out. I do have `pyproj` installed and able to operate it properly. I had problems running this specifically from `fiona`. Oddly enough, now the code I posted executes. Should have been some dirty read or something. Sorry and never mind.
