### ISSUE TITLE
Add support for binary field type

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#381]
Today I needed to read some binary data stored in a BLOB column of an Esri geodatabase. I had to resort to using the SWIG OGR bindings (*gasp*).

https://gis.stackexchange.com/questions/208182/reading-blob-data-from-an-esri-gdb-with-ogr

I don't think this would be too difficult to implement in Fiona. The data would be returned as a `bytes` type, something like:

```
feature = {"name": "some data", "geometry": {...}, "blob_col": b"..."}
```

I'll give this a go when I next find some time.

**Comment by snorfalorpagus** [comment]
Initial attempt is here: https://github.com/Toblerity/Fiona/compare/master...snorfalorpagus:binary_field

The only drivers supported by Fiona that also support binary fields are OpenFileGDB (r) and GPKG (raw). This makes testing on the CI difficult. I don't know the history behind excluding GPKG from tests on Travis.

So far I've only implemented this for GDAL 2.x. I haven't checked, but it may be a 2.x only feature (it was missing from my install of 1.11.4).

The included test creates some binary data, writes it to a test file, then reads it back.

What should the binary type be called in the schema? "binary" or "bytes"?

**Comment by sgillies** [comment]
@snorfalorpagus let's do 'bytes' to fit with 'int', 'float', 'str'.

Can you make a PR? Things are looking pretty good, but I'm unable to comment on the commits in your repo.
