### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by simberaj** [Toblerity/Fiona#389]
Fiona does not support Pyton 3.5. When installing it through the Anaconda package manager, it fails as follows:

    $ conda install fiona
    Using Anaconda API: https://api.anaconda.org
    Fetching package metadata ...........
    Solving package specifications: ....
    The following specifications were found to be in conflict:
      - fiona
    Use "conda info <package>" to see the dependencies for each package.

The info command, however, lists the 3.5 version as supported:

    fiona 1.7.0 np111py35_2
    -----------------------
    file name   : conda-forge::fiona-1.7.0-np111py35_2.tar.bz2
    name        : fiona
    version     : 1.7.0
    build number: 2
    build string: np111py35_2
    channel     : conda-forge/win-64
    size        : 291 KB
    arch        : x86_64
    binstar     : {'package_id': '56ed85a3147ebb53b80aa469', 'owner_id': '5528f42ce1
    dad12974506e8d', 'channel': 'main'}
    fn          : fiona-1.7.0-np111py35_2.tar.bz2
    license     : BSD 3-Clause
    machine     : x86_64
    md5         : 9363d70908792c0588ff615720b0cf3d
    operatingsystem: win32
    platform    : win
    priority    : 1
    schannel    : conda-forge
    subdir      : win-64
    target-triplet: x86_64-any-win32
    url         : https://conda.anaconda.org/conda-forge/win-64/fiona-1.7.0-np111py3
    5_2.tar.bz2
    dependencies:
        click-plugins
        cligj
        gdal 2.1.*
        munch
        numpy 1.11*
        python 3.5*
        setuptools
        six

Is adding the support a simple case, or is there a deeper underlying problem?

**Comment by sgillies** [comment]
@simberaj I'm happy to say that Fiona works just fine with Python 3.5. I develop Fiona using Python 3.5.2 and Fiona's tests are run with Python 3.5 on Travis-CI: https://travis-ci.org/Toblerity/Fiona. I think you might just have some conflicting conda packages. If you ask the https://conda-forge.github.io/ folks for help, I think they'll be able to get you back on track quickly.

**Comment by simberaj** [comment]
Thanks a lot, Sean!
