### ISSUE TITLE
Windows python crash - GDAL 2.1.0 - Fiona 1.7.0 - 32 bits

### ISSUE THREAD

**Issue by chefren** [Toblerity/Fiona#391]
Found the following bug in the tests when running under Fiona 1.7.0 current maint-1.7 and from the binaries of the 1.7.0 release, under Python 2.7 (32 bits) in Windows

GDAL version: 2.1.0 (also crashes with binaries of 2.0.3)
1. Setup dev env (with gdal paths)
2. Setup PATH to gdal bin
3. Run py.test tests\test_collection.py
   -> PointWritingTest : fails
   -> GeoJSONCRSWritingTest: Crashes python

**Comment by chefren** [comment]
Attaching env and pytest failure output

[set_fiona_env_win.txt](https://github.com/Toblerity/Fiona/files/540485/set_fiona_env_win.txt)
[fiona_pytest_collection_fail.txt](https://github.com/Toblerity/Fiona/files/540486/fiona_pytest_collection_fail.txt)

**Comment by DanielKinsman** [comment]
In further debugging we have noticed that it only seems to crash when using `with fiona.drivers()`, see [this gist](https://gist.github.com/DanielKinsman/cb2efa2c534a7d0c29abc55a95be0579) for test code.

**Comment by sgillies** [comment]
@chefren when you say "binaries of the 1.7.0 release", do you mean from http://www.lfd.uci.edu/~gohlke/pythonlibs/#fiona?

I don't have a Windows system for development and debugging so I'm going to need extra help on this issue. Can you find for me the Python or GDAL/OGR function that is called when the program crashes?

**Comment by DanielKinsman** [comment]
Yes, it happens from both Gohlke's binaries and those we build for ourselves.

**Comment by sgillies** [comment]
@chefren @DanielKinsman In 1.7.3 I've done the same for Fiona as I did in Rasterio: https://github.com/mapbox/rasterio/pull/982. It fixes a category of crashing bugs in Rasterio and I expect it to fix a similar category in Fiona. I'd be in your debt if you'd try with 1.7.3 after it appears on PyPI.
