### ISSUE TITLE
Fiona 1.7.1 missing GeoPackage & FileGDB support?

### ISSUE THREAD

**Issue by keithamoss** [Toblerity/Fiona#400]
Fiona 1.7.1 no longer lists GeoPackages or ESRI FileGDB as supported drivers. All other drivers are present and correct.

This is against GDAL 2.1.1 compile with ESRI FileGDB support.

1.7.0-post2 is fine.
```
root@c52baefe32b9:/app# fio --version
fio, version 1.7.0.post2
root@c52baefe32b9:/app# python
Python 2.7.12 (default, Aug  9 2016, 20:18:05)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>> print fiona.supported_drivers
{'ESRI Shapefile': 'raw', 'OpenFileGDB': 'r', 'SUA': 'r', 'ARCGEN': 'r', 'GeoJSON': 'rw', 'GPKG': 'rw', 'Idrisi': 'r', 'GPX': 'raw', 'SEGY': 'r', 'BNA': 'raw', 'FileGDB': 'raw', 'AeronavFAA': 'r', 'GPSTrackMaker': 'raw', 'DGN': 'raw', 'PCIDSK': 'r', 'MapInfo File': 'raw', 'DXF': 'raw'}
```

In 1.7.1 they're missing.
```
(venv-fiona-1.7.1) root@c52baefe32b9:/app# fio --version
fio, version 1.7.1
(venv-fiona-1.7.1) root@c52baefe32b9:/app# python
Python 2.7.12 (default, Aug  9 2016, 20:18:05)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>> print fiona.supported_drivers
{'ESRI Shapefile': 'raw', 'OpenFileGDB': 'r', 'SUA': 'r', 'ARCGEN': 'r', 'GeoJSON': 'rw', 'Idrisi': 'r', 'GPX': 'raw', 'SEGY': 'r', 'BNA': 'raw', 'AeronavFAA': 'r', 'GPSTrackMaker': 'raw', 'DGN': 'raw', 'PCIDSK': 'r', 'MapInfo File': 'raw', 'DXF': 'raw'}
```

**Comment by sgillies** [comment]
@keithamoss this would be a regression and I'll fix it in 1.7.2.

**Comment by sgillies** [comment]
@keithamoss nothing has changed in the code. What *has* changed is that we're beginning to distribute binary wheels for Fiona with GDAL included, see the files tagged `manylinux1` at https://pypi.python.org/pypi/Fiona/1.7.1#downloads. The GDAL libs in these files don't include GPKG (an oversight) or Esri FileGDB (licensing restrictions). To get all the drivers you want on Linux, you need to do this

`pip install -I fiona --no-binary fiona`

This will compile Fiona and link it against your system's GDAL library that has all the drivers you need.

**Comment by keithamoss** [comment]
Great, thanks for letting us know Sean :)
