### ISSUE TITLE
Expose OGR_Dr_DeleteDataSource() / GDALDeleteDataset()

### ISSUE THREAD

**Issue by geowurster** [Toblerity/Fiona#401]
Maybe something like `$ fio rm` and `fiona.rm()` or `fiona.delete()`.  I think prompting the user for confirmation by default for `$ fio rm` would be responsible if we provide a `--force` or `--yes` flag for scripting purposes.

This would be useful for general data management and dealing with drivers that do not support update, like GeoJSON.  Currently, running this twice produces an exception.:

```python
import fiona as fio

profile = {
    'crs': 'EPSG:4326',
    'schema': {
        'geometry': 'Point',
        'properties': {}
    },
    'driver': 'GeoJSON'
}


with fio.open('test.geojson', 'w', **profile) as dst:
    dst.write({
        'type': 'Feature',
        'properties': {},
        'geometry': {
            'type': 'Point',
            'coordinates': [0, 0]
        }
    })
```

Dropping this above `fio.open()` would alleviate the problem:

```python
fio.rm('test.geojson')
```

**Comment by geowurster** [comment]
Just found `fiona.remove()`.  Presumably the required driver name for paths is why `$ fio rm` does not exist.  Is there any reason we can't just open the datasource in `remove()` to get the driver?

**Comment by sgillies** [comment]
@geowurster no reason why not. A `fio rm` would be great.
