### ISSUE TITLE
Fiona supported within Anaconda ?

### ISSUE THREAD

**Issue by richardsr-saccounty** [Toblerity/Fiona#406]
Is fiona expected to work within Anaconda? 

Created an Anaconda environment and ran "conda install fiona". When the environment is launched running:
import fiona 
print fiona.supported_drivers
returns 'module' object has no attribute 'supported_drivers'

Any ideas?

Anaconda2 4.2.0 32bit

**Comment by sgillies** [comment]
If it doesn't work, it's because the Anaconda packages are built improperly. The conda-forge project is where you should go to get Fiona, its packages are correct: https://conda-forge.github.io/.
