### ISSUE TITLE
long_description does not render properly on PyPI

### ISSUE THREAD

**Issue by geowurster** [Toblerity/Fiona#408]
PyPI only renders RST, but invalid syntax is introduced when concatenating `README.rst + CHANGES.txt + AUTHORS.txt`.  I remember looking at PyPI in the recent past and seeing properly rendered text, so I think this breakage is relatively recent.

**Comment by cmcnutt1** [comment]
How can this issue be recreated? Looking on the PyPI website shows README, CHANGES, and AUTHORS in the correct order and correctly rendered (as far as I can tell).

**Comment by geowurster** [comment]
@cmcnutt1 The content is present, but rendered as plain text instead of HTML.  Compare to Rasterio's PyPI page: https://pypi.python.org/pypi/rasterio

**Comment by sgillies** [comment]
The https://pypi.python.org/pypi/Fiona/1.7.1 page looks fine and I didn't change anything. I wonder if the problem is that the 1.7.1.post1 sdist didn't make it to PyPI? See https://pypi.python.org/pypi/Fiona/1.7.1.post1#downloads. I think the wheels are just blobs as far as PyPI is concerned.

**Comment by sgillies** [comment]
Turns out the problem was the asterisks at https://github.com/Toblerity/Fiona/blob/maint-1.7/CHANGES.txt#L28. I hacked a PKG_INFO file and uploaded it to PyPI to fix.
