### ISSUE TITLE
Support for Python 3.6

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#412]
Python 3.6 was released in December 2016. I don't think it should be too difficult to add support (if anything is needed). Add to Travis?

This may be something we need to add support for:
https://docs.python.org/3.6/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol

**Comment by geowurster** [comment]
@snorfalorpagus I opened https://github.com/Toblerity/Fiona/pull/405 a few weeks ago and forgot about it.  The Windows build is broken, but hasn't that been the case for a while?

**Comment by snorfalorpagus** [comment]
I didn't see the PR before creating this issue. Yes, it looks like Travis is OK on 3.6 but the Windows build is failing (it's testing 3.4 anyway). I'm not sure why without looking into it further. The existing problem should probably be fixed first. I've created #414.

**Comment by geowurster** [comment]
@snorfalorpagus Ah right.  I think I tried upgrading Windows to 3.6 as well and when it failed I reverted.  👍 to the issue tracking Windows failures.
