### ISSUE TITLE
Write big polygon

### ISSUE THREAD

**Issue by paulopires16** [Toblerity/Fiona#413]
Hello
I intent to copy a big polygon but without success:

```python
from shapely.geometry import mapping, shape
import fiona
with fiona.open(r'D:\temp\big_polygon.shp', 'r') as input:
    with fiona.open(r'D:\temp\big_polygon_copy.shp', 'w', 'ESRI Shapefile', crs=input.crs, schema=input.schema.copy()) as output:
        for elem in input:
            output.write({'properties': elem['properties'],'geometry': mapping(shape(elem['geometry']))})
```

shapefile: https://ufile.io/30f6e

**Comment by geowurster** [comment]
@paulopires16 Can you provide some more information, like what version of Python, GDAL, and Fiona?  The text and traceback from the error would also help.

**Comment by paulopires16** [comment]
Hello geowurster, 
Fiona-1.7.1-cp27-cp27m-win32.whl
GDAL-2.1.2.win32-py2.7.msi
gdal-201-1500-core.msi

thanks

**Comment by geowurster** [comment]
Could you please provide the error message as well?

**Comment by paulopires16** [comment]
There is no error at all, create shapefile with some records but no
geometry...

Em 25/01/2017 23:12, "Kevin Wurster" <notifications@github.com> escreveu:

**Comment by sgillies** [comment]
@paulopires16 can you provide the shapefile? via Dropbox or something?

I've seen other recent reports of problems with Windows wheels. I think you'll need to contact the source of the files you downloaded for help with them.

The Fiona project has no official Windows wheels at the moment. On the other hand, I've heard that you can use the Linux wheels with the Linux subsystem in Windows 10.

**Comment by paulopires16** [comment]
Already upload: https://ufile.io/30f6e

Em 26/01/2017 09:45, "Sean Gillies" <notifications@github.com> escreveu:

**Comment by sgillies** [comment]
@paulopires16 I can't reproduce your problem on my computer (A Mac, with Fiona 1.7.1.post1 and Shapely 1.5.17.post1 downloaded from PyPI). The input file has 36 features and so does the output. I even sent the output to geojson.io to view it like this

`fio cat /tmp/big_polygon_copy.shp --dst-crs epsg:4326 | fio collect | geojsonio`

![untitled](https://cloud.githubusercontent.com/assets/33697/22327601/53480184-e3b8-11e6-9786-0e195d7a5a7e.png)

It's certainly a problem with the binaries you downloaded and not something that we can fix here. I'm sorry about that.
