### ISSUE TITLE
Appveyor build is failing

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#414]
The current appveyor builds are failing. It looks like just a single test:

```
================================== FAILURES ===================================
______________________________ test_multi_layer _______________________________
    def test_multi_layer():
        layerdef = "1:coutwildrnp,1:coutwildrnp"
        runner = CliRunner()
        result = runner.invoke(
            cat.cat, ['--layer', layerdef, 'tests/data/'])
>       assert result.output.count('"Feature"') == 134
E       assert 0 == 134
E        +  where 0 = <built-in method count of str object at 0x00000000047F68B0>('"Feature"')
E        +    where <built-in method count of str object at 0x00000000047F68B0> = 'Aborted!\n'.count
E        +      where 'Aborted!\n' = <Result SystemExit(1,)>.output
tests\test_fio_cat.py:80: AssertionError
---------------------------- Captured stderr call -----------------------------
DEBUG:Fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:Option CPL_DEBUG=b'OFF'
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "C:\projects\fiona\fiona\fio\cat.py", line 69, in cat
    with fiona.open(path, layer=lyr) as src:
  File "C:\projects\fiona\fiona\__init__.py", line 169, in open
    enabled_drivers=enabled_drivers, **kwargs)
  File "C:\projects\fiona\fiona\collection.py", line 147, in __init__
    self.session.start(self)
  File "fiona\ogrext.pyx", line 435, in fiona.ogrext.Session.start (fiona/ogrext.c:9107)
    raise FionaValueError(
fiona.errors.FionaValueError: No dataset found at path 'tests/data/' using drivers: *
========= 1 failed, 525 passed, 44 skipped, 4 xpassed in 9.56 seconds =========
```

https://ci.appveyor.com/project/sgillies/fiona/build/1.0.178

**Comment by rbuffat** [comment]
Looks like replacing tests/data/ with os.path.join('tests', 'data') did the trick (See https://github.com/Toblerity/Fiona/pull/415).

However there are a bunch of other tests in tests/test_fio_cat.py disabled for windows.

**Comment by rbuffat** [comment]
I started looking into the on windows disabled tests in this branch: https://github.com/rbuffat/Fiona/tree/fix_windows_tests
It looks that most of them fail due to the different path separator.

**Comment by rbuffat** [comment]
@sgillies 
Currently the path of vsimem is constructed as follows:

`vsi_filename = os.path.join('/vsimem', uuid.uuid4().hex)`

on Windows this results in paths like /vsimem\something, which then fails the test:

`self.assertTrue(repr(self.c).startswith("<closed BytesCollection '/vsimem/"))`

I think mixing / and \ in a path is not a good idea. This leaves two options, using "/" as seperator for vsimem paths or stick to either / or \ depending on the platform. What is your opinion about that?

**Comment by rbuffat** [comment]
I brought down the number of skipped tests to 10. Most of it in test_multiconxn.py. This fails with "The process cannot access the file because it is being used by another process"

Currently my commit history of https://github.com/rbuffat/Fiona/tree/fix_windows_tests is a bit of a mess, because I was debugging on appveyor. If somebody has some hints how I could merge these commits into 2-3 nice ones, it would be very helpful.

**Comment by geowurster** [comment]
@rbuffat You could do a `$ git rebase` and `squash` related commits together.

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

If you're not familiar with rebasing, you can start an interactive session with:

```console
$ git rebase -i ef9a7a6d7d04b600844c65164f672fe23e84dca6 
```

which lets you modify every commit after `ef9a7a6d7d04b600844c65164f672fe23e84dca6`.

Just skimming the commit history, your rebase might look something like:

```
pick da524f1 fix windows tests
pick 5ecd248 clean
pick 8381c89 change paths
pick 53de6ed transform paths test_collection.py
squash c19e420 transform paths test_collection.py
pick 2fc72c0 transform paths test_vfs.py
squash 950298b transform paths test_vfs.py
squash 9db9b30 transform paths test_vfs.py
pick 4769cc2 transform paths test_collection.py
squash 30393aa transform paths test_collection.py
squash dc9ff54 transform paths test_collection.py
pick 5710c9f fio load
pick dab0d10 fio info
pick 145701f fio bytescollection
pick 297a5d1 remove all skip fixme windows
pick 6fbd583 bytescollection debug output
squash c8507ec bytescollection debug output
pick df1946c fix /vsimem
pick 0dbb269 debug output
squash 8918d16 debug output
squash 95ac657 debug output
squash f6490f4 debug output
squash 1680d9e debug output
pick 3a5ff56 test_layer paths
pick 1350c54 force utf8 bytescollection
pick 5c0a9b8 remove skips test_collection.py
pick 8436903 test_fio_collect
pick 2ff6a1b remove fixme
pick 28a449b revert test_multiconxn.py
```

The rebase is processed from top to bottom, so the first 4 commits used as is, the 5th is combined into the 4th, the 6th is used as is, and then the 7th and 8th are combined into the 6th.

If anything goes wrong you can do `$ git rebase --abort`.  Finally, the rebase must be pushed with `--force` as the commit ID's have changed.

**Comment by rbuffat** [comment]
@geowurster thanks for the tip with rebase! I had some problems with merge conflicts, so I ended up creating a new branch and checkout the changed files. But I'm sure this knowledge will be helpful to me in the future.
