### ISSUE TITLE
BytesCollection cannot open ESRI flavored JSON 

### ISSUE THREAD

**Issue by youngpm** [Toblerity/Fiona#422]
I've got some strange behavior when trying to get a `BytesCollection` to open some ESRI flavored JSON.  Using [esri.json](https://gist.githubusercontent.com/youngpm/347b8a0a3ea724afa616ea2387104972/raw/1b95631f684d0bf03d585a7c52e9c31dbf8bacc6/esri.json) as my input file and running 
```
fio dump esri.json
```
I get the expected result. Similarly, 
```
In [1]: import fiona
In [2]: with fiona.open('esri.json') as src:
   ...:     recs = [r for r in src]
In [3]: len(recs)
Out[3]: 93
```
works great.  However, when trying to do it with `BytesCollection`, 
```
In [1]: import fiona
In [2]: with open('esri.json') as src:
   ...:     buf = src.read()
In [3]: fiona.BytesCollection(buf)
---------------------------------------------------------------------------
FionaValueError                           Traceback (most recent call last)
<ipython-input-3-1ccda61140ae> in <module>()
----> 1 fiona.BytesCollection(buf)

.../lib/python2.7/site-packages/fiona/collection.pyc in __init__(self, bytesbuf)
    427
    428         # Instantiate the parent class.
--> 429         super(BytesCollection, self).__init__(self.virtual_file)
    430
    431     def close(self):

.../lib/python2.7/site-packages/fiona/collection.pyc in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, **kwargs)
    138             self.encoding = encoding
    139             self.session = Session()
--> 140             self.session.start(self)
    141
    142             # If encoding param is None, we'll use what the session

fiona/ogrext.pyx in fiona.ogrext.Session.start (fiona/ogrext.c:7197)()

FionaValueError: No dataset found at path '/vsimem/30332495866d43b3b7e8f63f74d68474' using drivers: *
```
Interestingly, if you first convert the esri stuff to geojson via `fio dump esri.json > not-esri.json`, then everything is copacetic: 
```
In [1]: import fiona
In [2]: with open('not-esri.json') as src:
   ...:     buf = src.read()
In [3]: c = fiona.BytesCollection(buf)
In [4]: len(c)
Out[4]: 93
```
I've tried this with fiona 1.6 and 1.7 on OSX and Ubuntu, as well as the binary wheels and building against my own gdal, all with the same result, so I think its real.  Strangely, GDAL's python bindings work alright on this set:
```
In [1]: from osgeo import gdal, ogr
In [2]: with open('esri.json') as src:
   ...:     buf = src.read()
In [3]: vsi_filename = '/vsimem/esri.json'
In [4]: gdal.FileFromMemBuffer(vsi_filename, buf)
In [5]: ds = ogr.Open(vsi_filename)
In [6]: lyr = ds.GetLayer()
In [7]: len(lyr)
Out[7]: 93
```
I am perplexed!  Could BytesCollection somehow be circumventing GDAL's attempts at opening the file with the GeoJSON driver?

**Comment by sgillies** [comment]
@youngpm I'm not a big fan of Esri-JSON and think that the way GDAL conflates it with GeoJSON is a shame, but I see one thing to check: `'/vsimem/esri.json'` (above, GDAL python) works for you, but `'/vsimem/30332495866d43b3b7e8f63f74d68474'` (Fiona) does not... maybe we need to add a `'.json'` extension to the `/vismem` filenames?

**Comment by youngpm** [comment]
@sgillies Agreed on the Esri-JSON, the bane of my existence.  It's even worse trying to go from GeoJSON to Esri!

You are correct on the fix!  Hacking `ext = '.zip' if filetype == 'zip' else '.json'` into the `BytesCollection` constructor and sure enough, it opens.  I had thought GDAL ignored extensions and just tried all the drivers one after another; even specifying `driver=GeoJSON` didn't solve the problem.

**Comment by sgillies** [comment]
@youngpm thanks for checking. I'll ask about this on gdal-dev tomorrow and see if there's a best practice to follow.

**Comment by youngpm** [comment]
Sounds good.  The code where they're checking extensions appears to be here FWIW:

https://github.com/OSGeo/gdal/blob/901ce5be4d8a3ba85224134e80375ae70bbd7104/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L128-L136

Insanely, it looks from there like they can directly open the raw bytes without any of the vsimem stuff; e.g. the following works in gdal!
```
In [1]: from osgeo import gdal, ogr
In [2]: with open('esri.json') as src:
   ...:     buf = src.read()
In [3]: ds = ogr.Open(buf)
In [4]: lyr = ds.GetLayer()
In [5]: len(lyr)
Out[5]: 93
```

In fact, this works in fiona!
```
In [1]: import fiona
   ...: with open('esri.json') as src:
   ...:     buf = src.read()
   ...: c = fiona.Collection(buf)
   ...: recs = [r for r in c]
In [2]: len(recs)
Out[2]: 93
```

**Comment by sgillies** [comment]
@youngpm I can't reproduce the error with my computer (Fiona 1.7.3, GDAL 1.11.1 and 2.1.3, Python 3.5).

I retrieved some Esri JSON from a URL I found on GIS SE:

`curl "http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Hydrography/Watershed173811/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json" > /tmp/file.json`

and then read it into a `BytesCollection`.

```python
>>> with open('/tmp/file.json', 'rb') as f:
...     data = f.read()
...
>>> with fiona.BytesCollection(data) as c:
...     print(len(c))
...
1000
```

Yes, you can pass a GeoJSON string directly into GDAL, see http://www.gdal.org/drv_geojson.html. This is only accidentally support by Fiona and may break in the future.

**Comment by sgillies** [comment]
@youngpm I can't reproduce the error with my computer (Fiona 1.7.3, GDAL 1.11.1 and 2.1.3, Python 3.5).

I retrieved some Esri JSON from a URL I found on GIS SE:

`curl "http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Hydrography/Watershed173811/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json" > /tmp/file.json`

and then read it into a `BytesCollection`.

```python
>>> with open('/tmp/file.json', 'rb') as f:
...     data = f.read()
...
>>> with fiona.BytesCollection(data) as c:
...     print(len(c))
...
1000
```

Yes, you can pass a GeoJSON string directly into GDAL, see http://www.gdal.org/drv_geojson.html. This is only accidentally support by Fiona and may break in the future.

**Comment by youngpm** [comment]
@sgillies Thanks so much for looking into this, I really appreciate it.  

Your example works for me as well.  The json in that gist still doesn't work for me, must be something about its format or some such.  I'll continue my yak shaving and report back if I figure anything more out.

Thanks again!

**Comment by youngpm** [comment]
@sgillies I think I've figured it out.

First, I grab the offending json and make a copy without the extension:
```
curl "https://gist.githubusercontent.com/youngpm/347b8a0a3ea724afa616ea2387104972/raw/1b95631f684d0bf03d585a7c52e9c31dbf8bacc6/esri.json" > /tmp/esri.json
cp /tmp/esri.json /tmp/esri-no-ext
```
`ogrinfo` is happy to report it can open the one with the `json` extension, but fails on the copy without:
```
ogrinfo -ro -so /tmp/esri.json OGRGeoJSON | grep "Feature Count"
Feature Count: 93
```
```
ogrinfo -ro -so /tmp/esri-no-ext OGRGeoJSON | head -n2
FAILURE:
Unable to open datasource `/tmp/esri-no-ext' with the following drivers.
```
Here's the tricky bit; if you edit `/tmp/esri-no-ext` and move `"geometryType": "esriGeometryPolygon"` to the top of the json struct (its at the bottom in that file, in your example its near the top), it works!
```
ogrinfo -ro -so /tmp/esri-no-ext OGRGeoJSON | head -n2
INFO: Open of `/tmp/esri-no-ext'
      using driver `GeoJSON' successful.
```

Looking at the GeoJSON driver code, we see [here](https://github.com/OSGeo/gdal/blob/901ce5be4d8a3ba85224134e80375ae70bbd7104/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L128-L148) that when there is no json/geojson extension, GDAL reads the first 6000 bytes [here](https://github.com/OSGeo/gdal/blob/901ce5be4d8a3ba85224134e80375ae70bbd7104/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L89-L99) and then checks for certain keys [here](https://github.com/OSGeo/gdal/blob/901ce5be4d8a3ba85224134e80375ae70bbd7104/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L72-L79), including they key/value I moved to the top of the file, in order to figure out if the driver can open it.  Since the key/value that GDAL is looking for is at the bottom, its not in that first chunk of bits and the driver thinks it can't open it. 

This also explains why Fiona can read the bytes directly and why it works when the `vsimem` path has the correct extension; in these situations the driver never gets to [GeoJSONFileIsObject test](https://github.com/OSGeo/gdal/blob/901ce5be4d8a3ba85224134e80375ae70bbd7104/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L145-L147) as one of the others above it will have already exceeded.

It looks like you have plans to extend fiona with the rasterio style memfile goodness https://github.com/Toblerity/Fiona/issues/409 at the 1.8 release?  If there was a way of giving an optional extension hint when creating the memfile, that would let the user pop a `.json` onto the path and avoid this issue.  It looks like maybe [6 drivers in gdal](https://github.com/OSGeo/gdal/search?utf8=%E2%9C%93&q=TryToIngest) do this trick where they read parts of a file to figure out if they can open it.

**Comment by youngpm** [comment]
Another thought would be to append the `.json` extension to the vsimem file path when the user specifies the driver as `GeoJSON`.
