### ISSUE TITLE
Selecting a subset of fields while reading (for speed up)

### ISSUE THREAD

**Issue by oztalha** [Toblerity/Fiona#429]
This is a feature request. Porting a SO question: [Only read specific attribute columns of a shapefile with [...] Fiona](http://gis.stackexchange.com/questions/129414/only-read-specific-attribute-columns-of-a-shapefile-with-geopandas-fiona) to speed up reading from a shapefile.

**Comment by snorfalorpagus** [comment]
This could be supported using the `SetIgnoredFields` functionality in OGR. The argument is a blacklist of fields to ignore. A whitelist (more akin to usecols in pandas) could be supported using a difference from a list of all the fields. Additionally, it's possible to ignore the special geometry field - I've had a situation before were I wasn't really interested in the geometry, just the attributes.

http://www.gdal.org/classOGRLayer.html#a5e0c3427f64249d1c35cefb487546b10

**Comment by sgillies** [comment]
@oztalha @snorfalorpagus It looks like we have a choice between specifying fields to get or fields to skip. A big advantage of the latter seems to be that it can easily be a no-op when the field doesn't exist, whereas there's a decision to be made if I ask for field "foo" and it's not in the file: pass or raise an exception?

**Comment by snorfalorpagus** [comment]
I agree that blacklisting would be easier to implement and is actually the interface that OGR provides. I think I'd find whitelisting more useful. Can we do both? Or is that confusing?

**Comment by snorfalorpagus** [comment]
This was implemented in #488.

#469 is related.
