### ISSUE TITLE
Overwriting a file fails

### ISSUE THREAD

**Issue by egorf** [Toblerity/Fiona#436]
Another, question. I have faced the same issue as mentioned [here](https://github.com/geopandas/geopandas/issues/367).

Fiona raises a `ValueError: null layer` inside `session.start()` call. That seems like a weird bug.

Also, what is there a guide on debugging Fiona? At least a tip on enabling debug logs.

**Comment by sgillies** [comment]
@egorf confirmed. There are two things going on. The GDAL/OGR GeoJSON driver in versions < 2 refuses to overwrite existing GeoJSON files. This error isn't handled correctly by Fiona and that opaque exception is raised instead.  The GDAL driver has changed a bit in 2.1, but as far as I know, only to allow update of GeoJSON files. Deleting an existing file is left up to the caller (Fiona lib, in this case).

I'll try to fix the GDAL error handling bug in the 1.7 branch and overwriting behavior in 1.8.

No, I haven't written a debugging guide. Fiona does use the Python logger and if you configure the root logger to make DEBUG the log level you will see a lot of output from the library.

**Comment by sgillies** [comment]
I'm closing this one after splitting it out into #437 and #438.

**Comment by egorf** [comment]
Thanks, I'll be watching those threads
