### ISSUE TITLE
mandatory schema validation prevents writing mixed geometries to formats where the underlying driver supports it (e.g. MapInfo TAB, MIF)

### ISSUE THREAD

**Issue by fcostin** [Toblerity/Fiona#446]
## Expected behaviour:

It should be possible for Fiona to write features with different geometry types to a single layer, if the underlying driver supports it.

Further, it should ideally be easy for a user to do this in the special simple case where they are trying to write out a copy of a layer they have just read in using Fiona.

I ran into this problem for MapInfo files, but this expected behaviour seems reasonable for any file format / data source that can store mixed geometry types. MapInfo TAB and MIF layers can store mixed geometry types in a single layer and the formats do not appear to have any concept of a per-layer expected geometry type. Reading and writing mixed geometry MapInfo layers is supported by the underlying driver used by Fiona.

## Actual behaviour:

Fiona can read in features from a MapInfo TAB / MIF file containing mixed geometry types, but then by default refuses to write them out due due to failed schema validation of the geometry types.

Fiona does not appear to provide a documented way to disable schema validation of geometry types or define a schema that can hold mixed geometry types (e.g. Points and LineStrings and Polygons). There doesn't appear to be an undocumented way to disable it either, short of patches/hacks.

## Steps to reproduce the problem.

Please see attached script and example MapInfo MIF data file containing a Point, LineString and Polygon:

[mapinfo_multigeometry_issue.tar.gz](https://github.com/Toblerity/Fiona/files/1022205/mapinfo_multigeometry_issue.tar.gz)

To reproduce

0.   assuming you are in a fiona dev environment
1.   extract the attached `mix_geometry.mif`, `mixed_geometry.mid` and `test_mapinfo.py` somewhere
2.   cd into directory that contains `test_mapinfo.py`
3.   `py.test .`

Observe `test_by_default_we_can_write_a_copy_of_a_mixed_geometry_mapinfo_layer_we_read_in` xfails.

Observe `test_using_ugly_hacks_we_can_write_a_copy_of_a_mixed_geometry_mapinfo_layer_we_read_in` passes, proving that writing the layer actually works if we bypass Fiona's schema validation.

## Operating system, Fiona version, provenance

Ubuntu 16.04 LTS
Fiona 1.7.5
Fiona cloned from this github repo, b9eb1b5545a7e10f33c2967ec15d2e7abb2978c3

Python 2.7.12
GDAL 1.11.3

Same behaviour on Windows 7 using Fiona version 1.5-ish of unknown provenance.

## Possible ways to support this.

I am happy to contribute a pull request to improve support for this, if this enhancement in functionality is desired and there's a clean way it can work.

Here's a sketch of one design to extend Fiona's schema validation to support this:

Define a new value of `schema['geometry']`, e.g. `'anything'`, that means any geometry type is permitted. Perhaps another way of encoding this would be to make the `geometry` item of a schema itself optional.

Modify Fiona's code for writing features to skip validation of feature geometry types if the schema indicates that any geometry type is permitted.

Modify Fiona's code for inferring the schema geometry type when reading a layer to assume that the layer may contain any geometry type if the layer doesn't explicitly specify a uniform geometry type and the user has not explicitly specified a schema geometry type.

* Easy case: when reading a MapInfo file that contains points and linestrings and polygons, infer the geometry type as "any geometry type is permitted"
* Trickier case: when reading a MapInfo file that contains only points, infer the geometry type as "any geometry type is permitted" because by default for MapInfo format one is allowed to put whatever geometry in a layer regardless of what is already in there (assuming no schema external to the MapInfo file has been explicitly defined and provided by the user).

The overall principle of this suggestion is to make the default schema validation behaviour maximally permissive in terms of letting the user perform operations that are potentially supported by the underlying driver if Fiona has not been explicitly given a schema.

**Comment by sgillies** [comment]
@fcostin thanks for the great report. I think this well worth doing.

**Comment by fcostin** [comment]
Fantastic.

I'm still a bit uncertain about the best way the schema could be extended to be able to encode "any geometry type is accepted". A few ideas:

```
# (a) define a special string value of geometry type
{'geometry':'anything', ...}

# (b) omit the geometry key
{...} 

 # (c) let multiple geometry types be given in a list
{'geometry': ['LineString', 'Polygon', 'Point'], ...}

# (d) don't extend the schema, just provide an optional flag to disable schema validation somewhere

# (e) something else?

```

I think something like (c) feels cleaner, an option that explicitly lets you specify multiple geometry types, as that makes the schema more expressive in a fairly natural way. If we went with (c) I think we'd want to keep backwards compatibility and still accept `{'geometry':'LineString', ...}` style schemas as well.

I've only really used Fiona for reading/writing SHP and TAB files so I don't have intuition about how much this would impact other use cases.

What do you think?

**Comment by sgillies** [comment]
Hey @fcostin I'm circling back to this. Thanks for your patience. Part of me thinks that, instead of adding to Fiona's one-off schema language, it might be time to adopt the use of a more full-featured schema system like https://github.com/keleshev/schema. That already has the concept of "Or". Either that or we borrow "Or", making a set-like class and using it like

```python
from fiona.schema import Or
{'geometry': Or('LineString', 'Polygon', ...)}
```

What would you think about that?

**Comment by snorfalorpagus** [comment]
So far Fiona manages to represent everything using the standard Python types. To me this is a big selling point compared to other APIs (e.g. OGR SWIG or QGIS). My preference would be toward a list or set (option "c") with a special case to represent all types (e.g. "unknown" or "*").

```
schema = {"geometry": "Point"}
schema = {"geometry": ["Point", "LineString", "Polygon"]}
schema = {"geometry": {"Point", "LineString", "Polygon"}}
schema = {"geometry": "*"}
```

**Comment by sgillies** [comment]
@snorfalorpagus this is a good idea. Let's borrow from `isinstance()` and take a single name or a list or tuple of names.
