### ISSUE TITLE
Can not install fiona in windows (trying for a days)

### ISSUE THREAD

**Issue by sharifulgeo** [Toblerity/Fiona#449]
building 'fiona._transform' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\fiona
    C:\Users\Progectolab\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC /Tpfiona/_transform.cpp /Fobuild\temp.win32-2.7\Release\fiona/_transform.obj
    _transform.cpp
    fiona/_transform.cpp(473) : fatal error C1083: Cannot open include file: 'cpl_conv.h': No such file or directory
    error: command 'C:\\Users\\Progectolab\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\progec~1\\appdata\\local\\temp\\pip-5decej-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, _file_, 'exec'))" install --record c:\users\progec~1\appdata\local\temp\pip-9qjrbd-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\progec~1\appdata\local\temp\pip-5decej-build\

**Comment by sgillies** [comment]
Here are the Windows install instructions: https://github.com/Toblerity/Fiona#windows. You won't be able to run `pip install fiona` on Windows without having the GDAL library installed. I recommend using Gohlke's wheels or getting Fiona with Anaconda and conda-forge.

**Comment by FarFromBoston** [comment]
I have GDAL installed it still doesnt work... ^^^^^

**Comment by rbuffat** [comment]
@FarFromBoston Directly installing Fiona from sources on Windows requires advanced knowledge. As @sgillies advised, it is strongly recommended! to use prebuilt packages such as https://www.lfd.uci.edu/~gohlke/pythonlibs/

If you insist on doing it yourself, you can look at our windows CI config file: https://github.com/Toblerity/Fiona/blob/master/appveyor.yml

**Comment by FarFromBoston** [comment]
yeh i installed fiona and gdal through "https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal: successfully in my directory but Fiona still doesnt run.


----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: DLL load failed: The specified module could not be found.

**Comment by rbuffat** [comment]
Fiona should run fine with Python versions greater 3.4. The Anaconda3 directory indicates that you use Anaconda. Do not mix Gohlke's and Anaconda binary files.

**Comment by FarFromBoston** [comment]
> Fiona should run fine with Python versions greater 3.4. The Anaconda3 directory indicates that you use Anaconda. Do not mix Gohlke's and Anaconda binary files.

yeh well fiona wheel 36 although installing correctly faces the exact same issue. FIONA STILL ISNT IMPORTING. Also. I dont understand by what you mean don't mix binary files?

**Comment by rbuffat** [comment]
I don't use Windows or Anaconda, therefore I can be wrong. But if you are using the anaconda python distribution, stick to the binaries provided / made for anaconda., as packages from other sources, e.g. Gohlke, might not be compatible.

Uninstall all packages you installed from Gohlke and use anaconda packages.

**Comment by chethan-bm** [comment]
error while installing geopandas 
tried with pip,pip3 also.
`Installing collected packages: fiona, geopandas
    Running setup.py install for fiona ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\admin\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-sggfl_ka\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\admin\appdata\local\programs\python\python38\Include\fiona'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-wm1plrzn\fiona\
    Complete output (54 lines):
    c:\users\admin\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'metadata_version'
      warnings.warn(msg)
    c:\users\admin\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
      warnings.warn(msg)
    c:\users\admin\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'requires_external'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\fiona
    copying .\fiona\collection.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\compat.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\crs.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\drvsupport.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\env.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\errors.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\inspector.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\io.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\logutils.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\path.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\rfc3339.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\session.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\transform.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\vfs.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\__init__.py -> build\lib.win-amd64-3.8\fiona
    creating build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\bounds.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\calc.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\cat.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\collect.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\distrib.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\dump.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\env.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\filter.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\helpers.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\info.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\insp.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\load.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\ls.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\main.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\options.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\rm.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\__init__.py -> build\lib.win-amd64-3.8\fiona\fio
    running build_ext
    building 'fiona.schema' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\fiona
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\admin\appdata\local\programs\python\python38\include -Ic:\users\admin\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcfiona/schema.c /Fobuild\temp.win-amd64-3.8\Release\fiona/schema.obj
    schema.c
    fiona/schema.c(620): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\admin\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-sggfl_ka\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\admin\appdata\local\programs\python\python38\Include\fiona' Check the logs for full command output.
`
