### ISSUE TITLE
Presence of cpg in shapefile causes TypeError

### ISSUE THREAD

**Issue by ojdo** [Toblerity/Fiona#455]
## Expected behavior and actual behavior.

With a shapefile that comes with a `.cpg` file that contains the value "System", I encountered the following error when trying to read the file through geopandas. I am not 100% sure that the problem is not just caused by my setup, or is further upstream (i.e. in GDAL), but maybe someone here can at least shine some light on a possible cause for this apparent regression. (I read this dataset successfully on older setups, but with a different environment.)

If I remove the `.cpg` file, everything works fine.

## Steps to reproduce the problem and work-around

```bash
$ git clone https://github.com/tum-ens/rivus
$ cd rivus/data/haag15
$ fio info building.shp
[TypeError, see below]
$ rm building.cpg
$ fio info building.shp
{"bounds": ...}
```

### Error message

```python
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fiona/fio/info.py", line 50, in info
    with fiona.open(input, layer=layer) as src:
  File "/usr/local/lib/python3.5/dist-packages/fiona/__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "/usr/local/lib/python3.5/dist-packages/fiona/collection.py", line 153, in __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 394, in fiona.ogrext.Session.start (fiona/ogrext2.c:8430)
  File "fiona/_err.pyx", line 183, in fiona._err.GDALErrCtxManager.__exit__ (fiona/_err.c:1809)
  File "fiona/_err.pyx", line 58, in fiona._err.CPLE_BaseError.__init__ (fiona/_err.c:1242)
TypeError: __init__() takes exactly 4 positional arguments (2 given)
Aborted!
```

## Operating system

Ubuntu 16.04

## Fiona version and provenance

Fiona 1.7.6 on Python 3, installed via pip3. `fio --gdal-version` reports GDAL, version 2.1.3, while a system `gdalinfo --version` tells me that I have GDAL 1.11.3 installed.

Is it possible that I just have a buggy setup? I would be glad if someone could confirm (or not), whether it's just my setup that is causing the problem.

**Comment by micahcochran** [comment]
> With a shapefile that comes with a `.cpg` file that contains the value "System"

The `.cpg` files specify the codepage of the text fields in DBF file.  Just off the top of my head, I don't think "System" is a valid value. 

dBase IV is one of the warts for supporting the shapefiles, and the format that predates UTF-8.  The `.cpg` file is a workaround.

**Comment by micahcochran** [comment]
I did your above `$ fio info building.shp` test with multiple versions of Fiona.

Fiona version 1.7.5 and before don't have the exception, it just works.  But versions 1.7.6 and 1.7.7 result in an exception.

`ogrinfo` doesn't seem to have any issues with building.shp.

**Comment by ojdo** [comment]
@micahcochran: thank you for taking the time to reproduce my issue. Yes, I agree that `System` is not a particularly helpful (or valid) value in a `.cpg` file. Based on discussion to issue [gdal#4920](https://trac.osgeo.org/gdal/ticket/4920), I found a work-around for the command line:

    SHAPE_ENCODING="UTF-8" fio info building.shp

In short: your suggestion for a **bad codepage warning/exception** might be a good approach for handling this problem here.

**Comment by micahcochran** [comment]
@ojdo 
I refereshed myself on how GDAL handle shapefiles.  This may not be that helpful.

shapelib's [dbfopen.c](https://github.com/OSGeo/gdal/blob/trunk/gdal/ogr/ogrsf_frmts/shape/dbfopen.c) really doesn't seem to have any validation of the CodePage.  Shapelib just passes the CodePage information along.

GDAL has ogrshaplayer.cpp, which is GDAL's wrapper for shapelib.  There is [CodePageConvert function](https://github.com/OSGeo/gdal/blob/2.2/gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp#L316) that tries to make sense of what shapelib told it was the codepage.  If it can't figure it out, it just returns what it was given... perhaps  `System` in this case.

**Comment by micahcochran** [comment]
I think I've found the cause PR #444 updated CPLE_BaseError and as of merging that PR requires more arguments.  
[_err.pyx Line 185](https://github.com/Toblerity/Fiona/blame/master/fiona/_err.pyx#L185)  `raise exception_map[err_no](msg)`  
This does not appear to be providing enough arguments.

When I replace that line with this one
`raise exception_map[err_no](err_type, err_no, msg)`

It gives a better exception, but it probably should be a warning.
`fiona._err.CPLE_AppDefinedError: b'Recode from System to UTF-8 failed with the error: "Invalid argument".'`

**Comment by sgillies** [comment]
@micahcochran good eye! Could you send me a PR to review?

**Comment by sgillies** [comment]
@ojdo I'd be much obliged if you could try the new 1.7.8.

**Comment by ojdo** [comment]
@sgillies: With 1.7.8, `fio info` now yields a much more informative error message:

```python
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fiona/fio/info.py", line 50, in info
    with fiona.open(input, layer=layer) as src:
  File "/usr/local/lib/python3.5/dist-packages/fiona/__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "/usr/local/lib/python3.5/dist-packages/fiona/collection.py", line 153, in __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 395, in fiona.ogrext.Session.start (fiona/ogrext2.c:8432)
  File "fiona/_err.pyx", line 185, in fiona._err.GDALErrCtxManager.__exit__ (fiona/_err.c:1861)
fiona._err.CPLE_AppDefinedError: b'Recode from System to UTF-8 failed with the error: "Invalid argument".'
Aborted!
```
The message also propagates to geopandas (where I first encountered the error when trying `geopandas.read_file('buildings.shp')`. So :+1: from me and thanks!

**Comment by jorisvandenbossche** [comment]
> now yields a much more informative error message:

As somebody not too known to shapefiles / gdal inner workings, the error message is not that clear to me :-) (is it a user error? is it a wrongly-written file? or a problem with one of the libraries?)

If you get something like that error message, what is the action you need to take to solve this?

In https://github.com/geopandas/geopandas/issues/629 we get "CPLE_AppDefinedError: b'Recode from CP437 to UTF-8 failed with the error: "Invalid argument".'"

**Comment by sgillies** [comment]
@jorisvandenbossche sorry about the confusion. What's happening is that Fiona/GDAL detect that your shapefile is encoded using CP437 (from a value in a .cpg file, or maybe from your system's default encoding), that value is set on the dataset object, and then in reading features from the shapefile GDAL calls methods of libiconv to recode CP437 to UTF-8. The libiconv function fails, probably because the shapefile's encoding is not *actually* CP437. For some reason, "invalid argument" is all that CPLRecode() gets from libiconv. CPLRecode() then puts a GDAL error with the message "Recode from CP437 to UTF-8 failed with the error: x" and type "AppDefinedError" on the GDAL error stack. Fiona pops this error off the stack and turns it into a Python exception. A rather opaque one. Sometimes native Python programs emit UnicodeDecodeError from out of nowhere, and it can be confusing to be sure.

It's my intent that users never see `CPLE_*` exceptions, but we don't always succeed.

Because the GDAL error comes from deep in GDAL when you iterate over a collection's features and has a very generic type, we need to catch and handle CPLE_AppDefinedError in the iterator's __next__() method. In the handler we'll need to scrape details from the GDAL error message in order to raise a more helpful exception, which is gross but I don't see any way around that.

Exceptions raised during iteration are awkward, but scanning all features for coding errors before iteration will penalize users with proper data sources.

**Comment by jorisvandenbossche** [comment]
Thanks for the clear explanation! 
What is not yet clear to me is for this specific case (https://github.com/geopandas/geopandas/issues/629, trying to read the geopandas included dataset on Ney York boroughs), is whether there is something wrong with the file or whether it is an installation issue. As depending on the environment, we see this error or not.
It's certainly possible that the shapefile we included in geopandas (or downloaded from NY's open data) has an error in the cpg file), but eg on travis (and locally also in a clean env) it is not failing.

**Comment by bidhya** [comment]
I also have the same error on using geopandas.read_file(). It looks like the file I am trying to open was modified and saved using arcpy UpdateCursor, wherein a cpg with ISO 88591 was saved. Upon deleting this cpg file, everything seems to work fine.

**Comment by mehran66** [comment]
importing the shapefile into QGIS and exporting as a new shp file fixed my issue.
