### ISSUE TITLE
Issues with pip install fiona

### ISSUE THREAD

**Issue by athanasi** [Toblerity/Fiona#459]
Hi,

I have some issues to install fiona on ubuntu 14.04

I always get the error `Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-b4ng2wm0/fiona/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uj6y8dyt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-b4ng2wm0/fiona/`

I already tried: `sudo -H pip install fiona` as well as `sudo pip install -U setuptools`, `python -m pip install fiona`, `sudo apt-get install python-software-properties`, `sudo add-apt-repository ppa:ubuntugis/ppa`

Any other idea what could be tried out?

Many thanks in advance.

**Comment by sgillies** [comment]
@athanasi you didn't show me enough of the error to diagnose the problem. Can you paste in the full terminal output?
