### ISSUE TITLE
OGR_F_IsFieldSet() changes in GDAL 2.2

### ISSUE THREAD

**Issue by rouault** [Toblerity/Fiona#460]
Since GDAL 2.2, the behaviour of OGR_F_IsFieldSet() slightly changed. Fields can now be unset, NULL or set. OGR_F_IsFieldSet() in GDAL 2.2 will now consider that a NULL field is set. So generally with GDAL 2.2, you should use OGR_F_IsFieldSetAndNotNull() in places where OGR_F_IsFieldSet() was used if you want to process null and unset the same way. If you want to specially process NULL fields in a specifc way, you can use OGR_F_IsFieldNull()

To reproduce use a GeoJSON feature wil a property_name: null . If no change is done, it will likely be reported as an empty string or 0 value depending on the field type

**Comment by sgillies** [comment]
@rouault thanks for the reminder!
