### ISSUE TITLE
configure uses the wrong emulation mode for ppc64el  

### ISSUE THREAD

**Issue by jjvvff** [Toblerity/Fiona#464]
## Expected behavior and actual behavior.

(For example: I expected to read 10 features from a file and an exception occurred on the 3rd.)

## Steps to reproduce the problem.

(For example, a script with required data)

## Operating system

(For example, Mac OS X 10.12.3)

## Fiona version and provenance

(For example, the 1.7.4 manylinux1 wheel installed from PyPI using pip)

**Comment by jjvvff** [comment]
on line 8560 of configure there is
LD="${LD-ld} -m elf64ppc"  -- should be  LD="${LD-ld} -m elf64lppc 
Just noticed that build issues are not bugs??

**Comment by sgillies** [comment]
@jjvvff well, it's more that it's a [GDAL](https://github.com/OSGeo/gdal) build issue, not a Fiona build issue. Fiona has no configure script.

**Comment by jjvvff** [comment]
oops -- sorry
