### ISSUE TITLE
3D geometry schema lost when writing and reading shapefile

### ISSUE THREAD

**Issue by ChrisVolz** [Toblerity/Fiona#465]
Hello,

I am wondering if something changed lately dealing with 3D geometries?  Writing 3D geometries with Fiona and reading the results leads to degeneration to 2D geometry? In earlier versions (1.6.x) I haven't encountered this issue.
  

```
import fiona
from shapely.geometry import Point, mapping

schema = {'geometry':'3D Point', 'properties':{'name':'str'}}
with fiona.open('test.shp', 'w', driver='ESRI Shapefile', schema=schema) as shp:
    pt = Point(1,1,1)
    shp.write({'geometry':mapping(pt), 'properties':{'name':'test'}})
with fiona.open('test.shp') as shp:
     print shp.schema
```

I expect to be written:
`{'geometry': '3D Point', 'properties': OrderedDict([(u'name', 'str:80')])}`

but I get:
`{'geometry': 'Point', 'properties': OrderedDict([(u'name', 'str:80')])}`

(Fiona version 1.7.8, shapely version 1.5.12, tested on Linux and Windows)

PS: ArcGIS seems to reckognize the written file as 3D Shapefile. Hence, it may be rather a problem with reading than writing.

EDIT: No one has a solution to this problem? Or can't you reproduce the error? This seems quite a big thing to me...

**Comment by sgillies** [comment]
@ChrisVolz I'm sorry about the confusion. We have eliminated the distinction between 2D and 3D geometry types. If you open a 'Point 3D' shapefile with Fiona, the geometry type in the schema is 'Point'. 'Point 3D' is accepted when you create a shapefile, but it's now only an alias for 'Point'.

**Comment by ChrisVolz** [comment]
Thanx for your answer.

But I must say, I am not totally happy with the new behaviour. The following use case makes me a lot of problems in my projects:

- I open a shapefile with 3D Geometries, store the meta information and read all features
- I write a new shapefile with the stored meta information and write all features

Then I have **lost** all 3D information; only 2D geometries are written. Apparently I have to explicitely set the geometry to '3D Polygon' (or '3D Point') to preserve the 3D information. That is quite strange. However, I can live with it ;)

**Comment by jorisvandenbossche** [comment]
> 'Point 3D' is accepted when you create a shapefile, but it's now only an alias for 'Point'.

@sgillies Is this change documented somewhere? Because the documentation still seems to mention '3D Point' et al as schema types (http://toblerity.org/fiona/manual.html#geometry-types, http://toblerity.org/fiona/manual.html#coordinates-and-geometry-types for writing files). Also in practice (https://github.com/geopandas/geopandas/issues/612) '3D Point' does not seem to be an alias for 'Point' in the collection schema type. (or am I totally confusing two different things?)

**Comment by jorisvandenbossche** [comment]
@sgillies Can you have a look at my question above?

**Comment by sgillies** [comment]
My change seems to be confounding many of you and that's a good sign that it was a mistake. I'm going to consider reverting in 1.8.
