### ISSUE TITLE
Fiona does not flush and sync GeoJSON files for some reason

### ISSUE THREAD

**Issue by egorf** [Toblerity/Fiona#467]
## Expected behavior and actual behavior.
I am using Geopandas. Fiona and GDAL should sync to disk when calling to_file. That does not seem to happen when writing GeoJSON files for some reason.

## Steps to reproduce the problem.

1. Create a non-empty GeoDataFrame
2. Call `gdf.to_file("test1")`
3. Call `gdf.to_file("test2", "GeoJSON")`

If you break at `fiona.collection.py` method `flush()`, you will see that for some reason  `self.session.get_length()` always returns -1, when it should return the object length, therefore not syncing anything.

code to reproduce:
```
import geopandas
import shapely
point = shapely.geometry.Point([0, 0, 0])

data_frame = geopandas.GeoDataFrame({"geometry": [], "name": []})
print(data_frame)
data_frame = data_frame.append({"geometry": point, "name": "first"}, ignore_index=True)
print("new")
print(data_frame)
data_frame.to_file("test", "ESRI Shapefile")
data_frame.to_file("test2", "GeoJSON")
```

## Operating system

Linux

## Fiona version and provenance

1.7.8 installed via pip

**Comment by sgillies** [comment]
Closed via 98f3ca7

**Comment by egorf** [comment]
Thanks a lot!
When can I expect a new release?

**Comment by sgillies** [comment]
Target is later today, only #465 stands in the way.
