### ISSUE TITLE
Getting warning but not sure what it means: Warning 6: dataset foo.json does not support layer creation option ENCODING

### ISSUE THREAD

**Issue by jliebrand** [Toblerity/Fiona#468]
Apologies if this is not the correct place for this error, but I *think* it's coming from Fiona. By all means let me know if that's not the case and if I should report this elsewhere

The following minimal repro case shows my problem (I appreciate this doesn't use Fiona directly - sorry, just found this the quickest way to reproduce):

```
import geopandas as gpd
from shapely.geometry import shape
geom = { "type": "Polygon", "coordinates": [ [ [0, 0], [1, 1], [1, 0] ] ] }
df = gpd.GeoDataFrame(geometry=[shape(geom)])
df.to_file('foo.json', driver='GeoJSON')
```

Gives me the following warning message:
```
Warning 6: dataset foo.json does not support layer creation option ENCODING
```

But there are no further errors, and as far as I can see, the foo.json is written out correctly. Is this something I should be concerned about? 

Using Fiona: 1.7.8
GDAL 1.10.1 released 2013/08/26

(That sounds like an old GDAL to me, but it's the latest I get via apt-get install)

**Comment by sgillies** [comment]
@jliebrand thanks for the report! This is not a bug and has an easy solution.

The reason you see `Warning 6: dataset foo.json does not support layer creation option ENCODING` is that your script hasn't registered a handler for GDAL errors and warnings and so they go directly to stderr.

A Python logging handler is registered using the `fiona.drivers()` context manager. See this modified version of your script.

```python
# chk468.py

import logging
import geopandas as gpd
from shapely.geometry import shape
import fiona

logging.basicConfig(level=logging.DEBUG)

geom = { "type": "Polygon", "coordinates": [ [ [0, 0], [1, 1], [1, 0] ] ] }
df = gpd.GeoDataFrame(geometry=[shape(geom)])
with fiona.drivers():
    df.to_file('foo.json', driver='GeoJSON')
```

As shown in the output below, this time the GDAL error message gets intercepted and re-routed to Python's logger.

```
$ python chk468.py
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:GDAL_DATA: /Users/sean/code/Fiona/fiona/gdal_data
DEBUG:Fiona:PROJ_LIB: /Users/sean/code/Fiona/fiona/proj_data
DEBUG:Fiona:GDAL_DATA: /Users/sean/code/Fiona/fiona/gdal_data
DEBUG:Fiona:PROJ_LIB: /Users/sean/code/Fiona/fiona/proj_data
WARNING:Fiona:CPLE_NotSupported in b'dataset /Users/sean/code/Fiona/foo.json does not support layer creation option ENCODING'
DEBUG:Fiona:Created layer OgrGeoJSON
DEBUG:Fiona:Created fields
DEBUG:Fiona:Writing started
DEBUG:Fiona:Creating feature in layer: {'id': '0', 'type': 'Feature', 'properties': {}, 'geometry': {'coordinates': (((0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0)),), 'type': 'Polygon'}}
DEBUG:Fiona:Adding ring ((0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0))
DEBUG:Fiona:Adding point (0.0, 0.0)
DEBUG:Fiona:Adding point (1.0, 1.0)
DEBUG:Fiona:Adding point (1.0, 0.0)
DEBUG:Fiona:Adding point (0.0, 0.0)
DEBUG:Fiona:Closing ring
DEBUG:Fiona:Built ring
DEBUG:Fiona:Added ring ((0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0))
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
```

It has a level of warning, which is maybe a little high in this case, but if you remove the logging configuration from your script you won't see anything in stderr.

**Comment by mattayes** [comment]
@sgillies Do you know the cause of the "does not support layer creation option ENCODING" portion of the warning? The geopandas changes you made changed `Warning 6` to `WARNING:Fiona:CPLE_NotSupported` (thanks for that!), however the warning itself still shows up.
