### ISSUE TITLE
GDAL 2.2.1 Python 3.5 / 64 bit build

### ISSUE THREAD

**Issue by apiszcz** [Toblerity/Fiona#471]
Has anyone compiled Fiona for GDAL 2.2.1 Python 3.5 / 64 bit on Linux/Centos?

**Comment by sgillies** [comment]
The wheels I uploaded to PyPI were made with GDAL 2.2.0 on Centos: https://github.com/sgillies/frs-wheel-builds/blob/master/Dockerfile.wheels#L70-L104.

Let's reserve the Fiona issue tracker for actionable items.

**Comment by sgillies** [comment]
Update: I've just uploaded Fiona 1.7.9.post1 to PyPI. These wheels have GDAL 2.2.1: https://github.com/sgillies/frs-wheel-builds/blob/master/CHANGES.txt#L4-L7.

**Comment by apiszcz** [comment]
Impressive, will review/test, THANK You.
