### ISSUE TITLE
str:[n] property does not get truncated, instead schema gets changed

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#473]
## Expected behavior and actual behavior.
In my schema I set the property "twochars" to a str type with a maximum width of 2. http://toblerity.org/fiona/manual.html#field-types says "If this value is used in the schema of a file opened for writing, values of that property will be truncated at [2] characters." Instead I see the schema of the newly written file being adapted to whatever string length a feature might have had.

## Steps to reproduce the problem.
Here is minimal example code. 
```
import fiona
from shapely.geometry import *
from fiona.crs import from_epsg
from fiona import prop_width
import tempfile
import os.path

feature = {
    "geometry": mapping(Point(0,0)),
    "properties": {"twochars": "ABCDEFG"}
}

print("Feature property: {}".format(feature['properties']['twochars']))

schema = {
    "geometry": "Point",
    "properties": {"twochars": "str:2"}
}
print("Schema property: {}".format(schema['properties']['twochars']))
print("Schema property width: {}".format(prop_width(schema['properties']['twochars'])))

driver = "ESRI Shapefile"
extension = ".shp"

with tempfile.TemporaryDirectory() as directory:
    temporary_file = os.path.join(directory, "file"+extension)
    
    with fiona.open(temporary_file, "w", driver=driver, schema=schema, crs=from_epsg(4326)) as f:
        f.write(feature)
    
    with fiona.open(temporary_file) as f:
        print("File's schema property: {}".format(f.schema['properties']['twochars']))
        print("File's Schema property width: {}".format(prop_width(f.schema['properties']['twochars'])))
        for feature in f:
            print("File's feature property: {}".format(feature['properties']['twochars']))
```

From my understanding it should print
```
Feature property: ABCDEFG
Schema property: str:2
Schema property width: 2
File's schema property: str:2
File's Schema property width: 2
File's feature property: AB
```
with the "ABCDEFG" being truncated to just two characters, "AB", but instead it prints
```
Feature property: ABCDEFG
Schema property: str:2
Schema property width: 2
File's schema property: str:7
File's Schema property width: 7
File's feature property: ABCDEFG
```
## Operating system
Archlinux

## Fiona version and provenance
Fiona-1.7.9.post1-cp36-cp36m-manylinux1_x86_64.whl from pip.

**Comment by sgillies** [comment]
This is clearly a bug. Thanks for the report.

**Comment by sgillies** [comment]
@kannes it is not so clearly a bug after all – it is a GDAL feature. See http://www.gdal.org/drv_shapefile.html

> Starting with GDAL/OGR 1.10, the driver knows to auto-extend string and integer fields (up to the 255 bytes limit imposed by the DBF format) to dynamically accommodate for the length of the data to be inserted.

There's nothing we can do about this now in Fiona. It looks like the work around is to use a more strict format driver.

**Comment by kannes** [comment]
Dang! Well, I guess it is safe to say that people who use Shapefiles won't care about attribute consistency too much anyways >:)

Thanks for looking into it!
