### ISSUE TITLE
Reading GeoJSON file with null date field break iteration 

### ISSUE THREAD

**Issue by JesseCrocker** [Toblerity/Fiona#477]
## Expected behavior and actual behavior.
GeoJSON file has 2 features in a feature collection, feature 1 has a property that contains an iso8601 date string, feature 2 has the same property but with a null value. Fiona should be able to iterate the features in this file, instead it throughs an exception while iterating.
`ValueError: year is out of range`

This is similar to issues #326 and #454 which were closed because the root cause in #326 was determined to be an invalid shapefile. This involves a valid, and fairly simple, GeoJSON file.

## Steps to reproduce the problem.

test.geojson
```JSON
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "edit_date": "2017-04-18T08:30:12.000Z"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [0,0]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "edit_date": null
      },
      "geometry": {
        "type": "Point",
        "coordinates": [0,0]
      }
    }
  ]
}
```

test.py:
```python
#!/usr/bin/env python
import fiona
print fiona.__file__
print fiona.__version__
with fiona.open("test.geojson") as source:
    for feature in source:
        print feature
```

output:
```
/usr/local/lib/python2.7/site-packages/fiona/__init__.pyc
1.7.9.post1
{'geometry': {'type': 'Point', 'coordinates': (0.0, 0.0)}, 'type': 'Feature', 'id': '0', 'properties': OrderedDict([(u'edit_date', '2017-04-18T08:30:12')])}
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    for feature in source:
  File "fiona/ogrext.pyx", line 1187, in fiona.ogrext.Iterator.__next__
  File "fiona/ogrext.pyx", line 214, in fiona.ogrext.FeatureBuilder.build
ValueError: year is out of range
```

## Operating system
Mac OS 10.12.6

## Fiona version and provenance
1.7.9.post1 installed from pip, Fiona-1.7.9.post1-cp27-cp27m-macosx_10_6_intel.whl

**Comment by JesseCrocker** [comment]
Update:
I just installed the current master branch in development mode, and this now works properly, and logs the error.

Updated script to show logging output:
```python
#!/usr/bin/env python
import fiona
import logging
logging.basicConfig(level=logging.INFO)

print fiona.__file__
print fiona.__version__
with fiona.open("test.geojson") as source:
    for feature in source:
        print feature
```

new output:
```
/Users/jesse/projects/Fiona/fiona/__init__.pyc
1.7.9
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
{'geometry': {'type': 'Point', 'coordinates': (0.0, 0.0)}, 'type': 'Feature', 'id': '0', 'properties': OrderedDict([(u'edit_date', '2017-04-18T08:30:12')])}
ERROR:Fiona:year is out of range
Traceback (most recent call last):
  File "fiona/ogrext.pyx", line 219, in fiona.ogrext.FeatureBuilder.build (fiona/ogrext.c:4818)
    props[key] = datetime.datetime(
ValueError: year is out of range
{'geometry': {'type': 'Point', 'coordinates': (0.0, 0.0)}, 'type': 'Feature', 'id': '1', 'properties': OrderedDict([(u'edit_date', None)])}
```

**Comment by hrebchuk-oleh** [comment]
File "/home/olehhrebchuk/.virtualenvs/gas/lib/python3.5/site-packages/fiona/collection.py", line 327, in __getitem__
    return self.session.__getitem__(item)
  File "fiona/ogrext.pyx", line 680, in fiona.ogrext.Session.__getitem__
  File "fiona/ogrext.pyx", line 1215, in fiona.ogrext.Iterator.__next__
  File "fiona/ogrext.pyx", line 21

**Comment by wwoods** [comment]
With 1.7.12, I am still getting this issue when trying to load [Portland's Streets GeoJSON](http://gis-pdx.opendata.arcgis.com/datasets/streets) (APIs -> GeoJSON).

If I just use the `json` module and load the GeoJSON file, Fiona is choking on a record like this:

	{'type': 'Feature',
	 'properties': {'OBJECTID': 29708,
	  'LENGTH': 2717.1843381283775,
	  'LOCALID': 185760,
	  'ZERO': 0,
	  'PREFIX': ' ',
	  'STREETNAME': 'I5',
	  'FTYPE': 'FWY',
	  'DIRECTION': 2,
	  'LEFTADD1': 0,
	  'LEFTADD2': 0,
	  'RGTADD1': 0,
	  'RGTADD2': 0,
	  'LEFTZIP': '97219',
	  'RIGHTZIP': '97219',
	  'TYPE': 1110,
	  'LCOUNTY': 'MULT',
	  'RCOUNTY': 'MULT',
	  'LCITY': 'Portland',
	  'RCITY': 'Portland',
	  'SUFFIX': 'NB',
	  'FULL_NAME': 'I5 FWY NB',
	  'SIDE': 3,
	  'SOURCE': 'R',
	  'CFCC': 'A15',
	  'SUBAREA': 'P',
	  'STRUC_TYPE': 10,
	  'LEFT_JUR': 'PORT',
	  'RIGHT_JUR': 'PORT',
	  'PRI_NM_ID': 17868,
	  'LFT_NM_ID': 17868,
	  'RGT_NM_ID': 17868,
	  'BTM_SEG_ID': None,
	  'PDX_F_NODE': 74522,
	  'PDX_T_NODE': 73377,
	  'UPD_DATE': None,
	  'CREATE_DAT': '2011-09-09T07:00:00.000Z',
	  'F_ZLEV': 1,
	  'T_ZLEV': 1,
	  'Shape_Length': 1180.341146096502},
	 'geometry': {'type': 'LineString',
	  'coordinates': [[-122.7125441210284, 45.45590488246211],
	   [-122.71056631464042, 45.4569692540697],
	   [-122.70563296922097, 45.45977199888833],
	   [-122.70425011884228, 45.46053768637704]]}}

**Comment by sgillies** [comment]
@wwoods would you be willing to try version 1.8a2 to see if the problem persists there?
