### ISSUE TITLE
"WARNING:Fiona:PROJ data files not located, PROJ_LIB not set"

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#485]
The error message that appears in the example at https://github.com/Toblerity/Fiona/pull/483#issuecomment-339982623 is a symptom of a problem we've tried to avoid. The PROJ data files *should* be included in Fiona wheels and *should* have their location configure via the environment variable. This may be a regression.

**Comment by sgillies** [comment]
Hmm: https://github.com/Toblerity/Fiona/blob/master/CHANGES.txt#L57.

**Comment by geowurster** [comment]
@sgillies That Fiona install might be a little wonky, but I typically install with `--no-binary` in order to use my global GDAL install.

**Comment by sgillies** [comment]
@geowurster thanks for the data point. I'm seeing the error with OS X wheels and would like to fix this.

**Comment by sgillies** [comment]
Closing this. Fixing the path in the wheel builds took care of it.

**Comment by PhilipeRLeal** [comment]
Hello sgillies.

I am new in computing, and I am facing exactly the same problem as you have had. The only difference is that I am using Windows, instead of OS X.

How does one fix a path in the whell builds?

**Comment by stevencollinscn** [comment]
I'm also having trouble with it and tried to update Fiona to solve it but got the following error.

![image](https://user-images.githubusercontent.com/33796896/50542717-545ca800-0b92-11e9-80d9-4041e06456c2.png)
