### ISSUE TITLE
CPLE_AppDefinedError on OSX 10.11 after upgrade to Fiona>=1.7.9

### ISSUE THREAD

**Issue by ozak** [Toblerity/Fiona#486]
Hi,

I am getting an import error due to encoding after upgrading to ``fiona-1.7.9`` or ``fiona-1.7.10``. I have the same setup on 3 systems (based on ``conda``): MBP with OSX 10.11, MBP with OSX 10.12 and a Linux cluster. After upgrading from ``fiona-1.7.5`` to ``1.7.9`` or ``1.7.9post1`` or ``1.7.10``, on the OSX 10.11 I have been getting the following error

```python
CPLE_AppDefinedError: b'Recode from CP1252 to UTF-8 not supported, treated as ISO8859-1 to UTF-8.'
```
whenever I try to import a shapefile. Depending on the file I try to open I get different code for the encoding that fails, but all are basically the same issue. On the other two systems all works ok. I have downgraded back to ``1.7.5`` in OSX 10.11, but I wonder if this is a system specific issue or something else. To ensure this is not a ``conda`` issue I ``pip install``ed ``fiona-1.7.10`` and got the same result. Any one else has observed this issue?

**Comment by ozak** [comment]
Ok...this may be a ``conda`` issue after all. I just tried with ``homebrew``'s ``python-3.6`` and it worked fine. Unless it is a ``python-3.5`` issue. Will test some more and post.

**Comment by snorfalorpagus** [comment]
@ozak Are you still having an issue with this?

**Comment by ozak** [comment]
Yes, see #510.
