### ISSUE TITLE
Check GDAL version at runtime

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#496]
## Expected behavior and actual behavior.

Since #482 Fiona can be build against three different versions of GDAL: 1.x, 2.0 and 2.2. It's possible for a user to build Fiona against 2.0, update to GDAL 2.2, then try to use Fiona. At this point bad things will happen.

## Operating system

Testing on Windows raised an `ImportError` immediately.

Linux imports OK, but many things are broken (129 tests fail). I assume macOS will be similar.

## Proposed solution

We should check the GDAL version at runtime against the build version. If there is a mismatch, raise an exception. I propose a function in each of the shim modules `check_runtime_version` which is called on import. Should this raise an `ImportError`, or some other class?

**Comment by sgillies** [comment]
@snorfalorpagus I think `ImportError` would be good, as long as it's raised only at import.

**Comment by rbuffat** [comment]
I thought about doing something similar for the old gdal1/2 implementation.

If I remember correctly, the issue was, that before get_gdal_version_num() could be called the c modules need to be loaded, which failed to import on my machine due to missing libraries errors.

**Comment by snorfalorpagus** [comment]
Which OS are you using @rbuffat?

**Comment by rbuffat** [comment]
When I played around with that idea it was an Ubuntu 16.04.  I think I compiled then fiona against the ubuntugis repo version of gdal, then reverted back to the old standard ubuntu version of gdal and it detonated (or vice versa). But it was a year ago, thus what I remember can be completely false!

**Comment by sgillies** [comment]
@rbuffat is right. You can't import ogrext without the linker trying to load libgdal. So these kind of ImportErrors happen too early. I think this is a documentation and packaging concern.
