### ISSUE TITLE
GDAL 2.2 support in 1.7 version?

### ISSUE THREAD

**Issue by msarahan** [Toblerity/Fiona#498]
I'm working on getting Fiona into Anaconda's core collection of packages.  We're using the conda-forge recipe, which adds a test for null values.  This test is failing.

I've found https://github.com/Toblerity/Fiona/issues/460 and friends

the solution (https://github.com/Toblerity/Fiona/commit/38f8104b1779e2deb087c1336c286d7b358cc07e) appears to be available on the 1.8a1 release, but not any 1.7 release.  Can this fix be applied to 1.7 too, please?  Especially since you seem to be distributing 1.7.x wheels with gdal 2.2 binaries (https://github.com/Toblerity/Fiona/issues/471#issuecomment-323803683)?

**Comment by msarahan** [comment]
For Anaconda's purposes, I backported the fix at https://github.com/AnacondaRecipes/fiona-feedstock/commit/899952cb770f8d63c0ef61123604710e7cf89b90

If there's interest here, I can put up a PR.

**Comment by snorfalorpagus** [comment]
The fix in 38f8104b1779e2deb087c1336c286d7b358cc07e (using Cython compile-time conditionals) was later reverted as it breaks the source distribution (see comments in #463). The accepted solution for 1.8 avoids these definitions by using shim modules for different GDAL versions (#482). This change was tied to a merge of `ogrext1.pyx`/`ogrext2.pyx`, which was a significant refactor. I don't think there is any intention to port this change to 1.7.x as we focus on 1.8.x. I'm not sure about the GDAL 2.2 binaries on PyPI - this seems an error to me (given the NULL field bug), @sgillies?

For Anaconda's purposes the patch you've done looks good to me. I think stick with this for now, then drop the patch for Fiona 1.8 which will support GDAL 2.2 officially.

**Comment by sgillies** [comment]
@snorfalorpagus yes, I would prefer not to backport and focus on shipping 1.8.0.

**Comment by msarahan** [comment]
Sounds good.  I'll close this issue now.

**Comment by sgillies** [comment]
Thanks @msarahan !
