### ISSUE TITLE
Overflow error when calling OGR_F_SetFieldInteger64

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#502]
At https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext.pyx#L304.

Reported in https://github.com/conda-forge/fiona-feedstock/pull/59.

I'm not sure yet why this is biting us now (perhaps Cython version dependent?). My first thought is to explicitly cast `<long long>value` in the call.

**Comment by snorfalorpagus** [comment]
See my comment in https://github.com/conda-forge/fiona-feedstock/pull/59

I can reproduce the test failure with 1.8a1 but it doesn't seem to be happening in master.

**Comment by sgillies** [comment]
@snorfalorpagus I can't reproduce this one and will close it.
