### ISSUE TITLE
VFS changes broke build on Windows

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#505]
Some changes in #426 broke the build on Windows. I can reproduce this locally. https://ci.appveyor.com/project/sgillies/fiona

The error occurs when trying to open any file:

```
        if vsi:
            if not isinstance(vsi, string_types) or not vfs.valid_vsi(vsi):
>               raise TypeError("invalid vsi: %r" % vsi)
E               TypeError: invalid vsi: 'c'
fiona\collection.py:69: TypeError
```

I think the problem might be in `parse_paths` and the handling of Windows-style paths.

**Comment by snorfalorpagus** [comment]
The problem seems to be that `urlparse` doesn't like the drive in Windows paths, e.g.:

```
>>> urlparse(r"C:\this\is\a\test.shp")
ParseResult(scheme='c', netloc='', path='\\this\\is\\a\\test.shp', params='', query='', fragment='')
```

The "C:\" is detected as the scheme and removed from the path.

I haven't been following along with the VFS/VSI changes. Any thoughts @youngpm?

**Comment by sgillies** [comment]
@snorfalorpagus we could get help from pathlib on Python 3 (and the backport https://pypi.python.org/pypi/pathlib2 for Python 2) maybe?

```
>>> import pathlib
>>> pathlib.PureWindowsPath(r"C:\this\is\a\test.shp").as_uri()
'file:///C:/this/is/a/test.shp'
>>> from urllib.parse import urlparse
>>> url = pathlib.PureWindowsPath(r"C:\this\is\a\test.shp").as_uri()
>>> urlparse(url)
ParseResult(scheme='file', netloc='', path='/C:/this/is/a/test.shp', params='', query='', fragment='')
```

So maybe the first thing we do in `fiona.open` is this:

```
try:
    path = pathlib.PurePath(path).as_uri()
except ValueError:
    # as_uri() will fail if path isn't a filename
    # continue, treating path as a URI
    pass

# Parse the vfs into a vsi and an archive path.
path, vsi, archive = parse_paths(path, vfs)
```

As a side benefit, we'd then support `Path` objects as input to `fiona.open`.

**Comment by youngpm** [comment]
Does this crop up in rasterio as well?  If not, we could probably borrow what is done there.

**Comment by sgillies** [comment]
@youngpm no, it doesn't, but only because we've been overlooking the Windows platform.

**Comment by snorfalorpagus** [comment]
```
>>> urlparse(url)
ParseResult(scheme='file', netloc='', path='/C:/this/is/a/test.shp', params='', query='', fragment='')
```

The forward slash at the start of the path would break things, e.g.

```
>>> os.listdir(r"/C:/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/C:/'
```

**Comment by sgillies** [comment]
@snorfalorpagus that looks like a pathlib bug to me.

**Comment by snorfalorpagus** [comment]
> Can we check for a drive letter and remove the leading slash in that case?

Presumably we should do this when running on Windows only, as it could be a valid (albeit unusual) path on *nix. Something like:

```
if sys.platform == "win32" and path[0] == "/":
    path = path[1:]
```
