### ISSUE TITLE
VFS output

### ISSUE THREAD

**Issue by mdklatt** [Toblerity/Fiona#508]
## Expected behavior and actual behavior

I don't think this is a bug, but rather a misunderstanding on my part and perhaps an area where more documentation is needed. I am trying to created a ZIP compressed shapefile in a manner analogous to reading such a file:

```
with fiona.open("/", "w", vfs="zip://shptest, driver="ESRI Shapefile", schema=...) as collection:
    # Write records
```

Opening the collection fails with this exception:
`fiona._err.CPLE_AppDefinedError: Failed to create directory /vsizip/shptest/ for shapefile datastore`

I have looked through `collection.py` for some additional insight, but it's not obvious if I'm doing something wrong or if VFS support is only for reading.

## Operating system

Mac OS X 10.11.6

## Fiona version and provenance

Fiona-1.7.10.post1-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.whl installed using pip v9.0.1 in a Python 2.7 virtualenv environment.

**Comment by sgillies** [comment]
@mdklatt I'm sorry, but Fiona is a bit behind it's raster sibling, Rasterio. This feature isn't available yet, but we've got a ticket for the future at https://github.com/Toblerity/Fiona/issues/500.
