### ISSUE TITLE
Support C++11

### ISSUE THREAD

**Issue by geowurster** [Toblerity/Fiona#514]
Relates to https://github.com/mapbox/rasterio/issues/1230 and https://github.com/sgillies/frs-wheel-builds/issues/25

GDAL 2.3 will [require C++11](https://trac.osgeo.org/gdal/changeset/40984).  I don't think a Fiona build has been triggered on Travis since the change, but [Rasterio's GDAL trunk builds are failing with a bunch of warnings](https://travis-ci.org/mapbox/rasterio/jobs/315171560) like:

```
/home/travis/gdalinstall/gdal-trunk/include/ogr_geometry.h:974:9: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
             const CPL_OVERRIDE;
             ^
```

The [Travis builds against GDAL trunk](https://travis-ci.org/Toblerity/Fiona/jobs/316454091) are currently failing with the same issues.

**Comment by snorfalorpagus** [comment]
I think this will need some further investigating for Python 2.7 on Windows.

**Comment by sgillies** [comment]
@snorfalorpagus after #558 passes and I merge it, I'm going to start another branch and add Python 2.7 to the Appveyor matrix. It's commented out now, but I don't understand why.

**Comment by sgillies** [comment]
I've added the combination of Python 2.7 + GDAL trunk (allowed to fail) to the matrix and now we have a view of that issue: https://ci.appveyor.com/project/sgillies/fiona/build/1.0.516/job/blan0ypumud555nn#L304.

**Comment by snorfalorpagus** [comment]
Appveyor: Python 2.7 + GDAL 2.3
```
c:\gdal\include\cpl_port.h(187) : fatal error C1189: #error :  Must have C++11 or newer.
```

I don't think we'll ever be able to support GDAL 2.3 in Python 2.x on Windows. This doesn't bother me too much, given 2.7 EOL is 2020. https://legacy.python.org/dev/peps/pep-0373/

**Comment by sgillies** [comment]
I doesn't bother me a lot either, but I'd like to understand why.

**Comment by rbuffat** [comment]
Ok, I was not aware that https://github.com/Toblerity/Fiona/blob/master/fiona/_transform.pyx uses the C++ API.

**Comment by snorfalorpagus** [comment]
> Ok, I was not aware that https://github.com/Toblerity/Fiona/blob/master/fiona/_transform.pyx uses the C++ API.

Yes. This is the reason. @sgillies do you remember why this was written in C++ rather than C? A quick glance at the documentation suggests these methods are available in the C API so it could potentially be ported.

http://www.gdal.org/osr_tutorial.html

**Comment by sgillies** [comment]
@snorfalorpagus I did it to get access to a method of the GeometryFactory class:

https://github.com/Toblerity/Fiona/blob/master/fiona/_transform.pyx#L18-L19

**Comment by sgillies** [comment]
Resolved. We're giving up on Windows + Python 2.7 + GDAL 2.3.
