### ISSUE TITLE
Deprecate (remove?) fiona.tool?

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#521]
I'm not all that familiar with `fio` but it seems like the behavior in `fiona/tool.py` is covered? It's written using argparse and isn't passed as an entry point in `setup.py`.

**Comment by geowurster** [comment]
@snorfalorpagus I'm in favor of removing.  I bet it was inspired by `$ python -m json.tool`.

**Comment by sgillies** [comment]
Indeed, this was before the Fiona command line grew. It can go.
