### ISSUE TITLE
_transform_geom fails with coordinate depths of more than 2

### ISSUE THREAD

**Issue by dnomadb** [Toblerity/Fiona#523]
## Expected behavior and actual behavior.

When transforming coordinates from geometries that have a coordinate depth of more than 2, the transformation fails on account of unpacking more than 2 coordinates:
- https://github.com/Toblerity/Fiona/blob/9d76ab5d711e7edb54bf903036590a1f68be79c3/fiona/_transform.pyx#L156
- https://github.com/Toblerity/Fiona/blob/9d76ab5d711e7edb54bf903036590a1f68be79c3/fiona/_transform.pyx#L161
- https://github.com/Toblerity/Fiona/blob/9d76ab5d711e7edb54bf903036590a1f68be79c3/fiona/_transform.pyx#L168
- https://github.com/Toblerity/Fiona/blob/9d76ab5d711e7edb54bf903036590a1f68be79c3/fiona/_transform.pyx#L178

## Steps to reproduce the problem.

```python
from fiona.transform import transform_geom

geoms = {'coordinates': [[(-83.4466595538912, 42.1870870548379, 0.0),
   (-83.4466595538912, 42.5277921894222, 0.0),
   (-82.8423302755413, 42.5277921894222, 0.0),
   (-82.8423302755413, 42.1870870548379, 0.0),
   (-83.4466595538912, 42.1870870548379, 0.0)]],
 'type': 'Polygon'}

crs = {'init': 'epsg:4326'}

transform_geom(crs, crs, geoms, precision=3)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-f7013ee32ad6> in <module>()
     10 crs = {'init': 'epsg:4326'}
     11 
---> 12 transform_geom(crs, crs, geoms, precision=3)

/Users/dnomadb/Fiona/fiona/transform.py in transform_geom(src_crs, dst_crs, geom, antimeridian_cutting, antimeridian_offset, precision)
     91     return _transform_geom(
     92         src_crs, dst_crs, geom,
---> 93         antimeridian_cutting, antimeridian_offset, precision)

/Users/dnomadb/Fiona/fiona/_transform.pyx in fiona._transform._transform_geom()
    166             new_coords = []
    167             for piece in g['coordinates']:
--> 168                 xp, yp, *_ = zip(*piece)
    169                 xp = [round(v, precision) for v in xp]
    170                 yp = [round(v, precision) for v in yp]

ValueError: too many values to unpack (expected 2)
```

## Operating system

For example: Mac OS X 10.12.6.

## Fiona version and provenance

pip installed from master

## Fix

By specifying a starred, empty unpacking object _after_ the x and y coords we can unpack tuples of any length, ignoring anything beyond the 2nd index:
```python
xp, yp, *_ = zip(*[
                (0, 1),
                (0, 1)
                ])

print(xp, yp)

# (0, 0) (1, 1)

xp, yp, *_ = zip(*[
                (0, 1, 2),
                (0, 1, 2)
                ])

print(xp, yp, b)

# (0, 0) (1, 1)

xp, yp, *_ = zip(*[
                (0, 1, 2, 3),
                (0, 1, 2, 3)
                ])

print(xp, yp)

# (0, 0) (1, 1)
```

@sgillies could I submit a PR with tests to support this and the solution outlined above?

**Comment by sgillies** [comment]
@dnomadb because we don't have star unpacking in Python 2.7 and Python 2.7 isn't dead yet, we'll need to do something like

`xp, yp = zip(*coords)[:2]`

**Comment by dnomadb** [comment]
@sgillies ya, good call -- I always neglect to think about python 2.7. I believe we'd have to do:
```python
xp, yp = list(zip(*coords))[:2]
```
In order to use indexing.

**Comment by amirouche** [comment]
Is it possible somehow to keep the 3rd dimension in the final geometry?

**Comment by sgillies** [comment]
@amirouche shouldn't be difficult. We don't really do vertical datums, so it would be a matter of stripping the z values and then zipping them back in. What do you think @dnomadb ?

**Comment by amirouche** [comment]
It's not a strong requirement, because at the end of the day, I use `transform_geom` to convert coordinates to WGS84 for geographical indices which only take into account lat and long. That said, in my opinion it will be future proof to not strip the third (or fourth dimension), so if it's doable in a backward compatible way, I propose to support it.

**Comment by sgillies** [comment]
Early :christmas_tree: :gift: @dnomadb . This is in 1.8.4.
