### ISSUE TITLE
cannot specify boolean type in schema

### ISSUE THREAD

**Issue by raalst** [Toblerity/Fiona#524]
## Expected behavior and actual behavior.
JSON and GeoJSON seem to know the type 'boolean' with values true and false.
However, when specifying a schema from scratch I cannot specify a boolean. 'bool', 'Boolean' and 'boolean' are not recognized.

## Steps to reproduce the problem.

in pythonanywhere.com, python 3.6:
```
from shapely.geometry import mapping, Polygon, shape
import fiona

filename = '/home/raalst/output/buurtparts.shp'

# Define a GeoJSON polygon feature geometry with attributes
schema = {
    'geometry': 'Polygon',
    'properties': {'inw': 'int', 'urban': 'boolean'}
}

def create_output_record(vorm, inwoneraantal, urban):
    if vorm.is_valid and (vorm.geom_type == 'Polygon' or vorm.geom_type == 'MultiPolygon') and inwoneraantal >= 0 and urban in [True,False]:
        return {'geometry' : mapping(vorm), 'properties' : {'inw' : inwoneraantal, 'urban': urban}}
    else:
        print("error in creating record from shape {} and attribute {}. record with empty polygon returned".format(vorm.wkt,inwoneraantal))
        return {'geometry' : mapping(Polygon()), 'properties' : {'inw' : 0, 'urban': False}}

def write_shapes(features, crs):
    """Write a new Shapefile using constant filename"""
    with fiona.open(filename, 'w', driver='ESRI Shapefile', crs=crs , schema=schema) as c:
        for f in features:
            #print(f)
            c.write(f)

def main():
    """test write_shapes() on testfile"""
    write_shapes([create_output_record(Polygon([(0, 0), (1, 1), (1, 0)]), 13,  True),
                  create_output_record(Polygon([(0, 1), (1, 1), (1, 0)]),  0, False)
                 ],
                 {'proj': 'sterea', 'lat_0': 52.15616055555555, 'lon_0': 5.38763888888889,
                 'k': 0.9999079, 'x_0': 155000, 'y_0': 463000, 'ellps': 'bessel', 'units': 'm', 'no_defs': True
                 }
                )


if __name__ == '__main__':
    main()
```
results in 

Traceback (most recent call last):
  File "/home/raalst/IGAssignment2/write_shape.py", line 38, in <module>
    main()
  File "/home/raalst/IGAssignment2/write_shape.py", line 32, in main
    'k': 0.9999079, 'x_0': 155000, 'y_0': 463000, 'ellps': 'bessel', 'units': 'm', 'no_defs': True
  File "/home/raalst/IGAssignment2/write_shape.py", line 21, in write_shapes
    with fiona.open(filename, 'w', driver='ESRI Shapefile', crs=crs , schema=schema) as c:
  File "/usr/local/lib/python3.6/dist-packages/fiona/__init__.py", line 179, in open
    enabled_drivers=enabled_drivers, crs_wkt=crs_wkt)
  File "/usr/local/lib/python3.6/dist-packages/fiona/collection.py", line 158, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 964, in fiona.ogrext.WritingSession.start (fiona/ogrext2.c:16842)
ValueError: 'boolean' is not in list 

I was unable to determine if a boolean was or was not supported by the underlying OGR C code. it is in JSON and GeoJSON I believe (after a mild googling)
- either add to the docs the fact that booleans should be recoded as ints or strings
- or add a boolean variable to the example of a schema in the docs

## Operating system
>>> import platform
>>> platform.platform()
'Linux-4.4.0-101-generic-x86_64-with-Ubuntu-14.04-trusty'
>>> 
## Fiona version and provenance
>>> fiona.__version__
'1.7.4'

**Comment by sgillies** [comment]
The OGR API supports boolean values as a subtype of integers since 2.0: https://trac.osgeo.org/gdal/wiki/rfc50_ogr_field_subtype. We should add `bool` to Fiona in 1.8.

**Comment by StefanBrand** [comment]
It seems that `bool` is missing from `fiona.FIELD_TYPES_MAP)`:

```py
>>> pprint.pprint(fiona.FIELD_TYPES_MAP)
  {'List[str]': typing.List[str],
   'bytes': <class 'bytes'>,
   'date': <class 'fiona.rfc3339.FionaDateType'>,
   'datetime': <class 'fiona.rfc3339.FionaDateTimeType'>,
   'float': <class 'float'>,
   'int': <class 'int'>,
   'int32': <class 'int'>,
   'int64': <class 'int'>,
   'str': <class 'str'>,
   'time': <class 'fiona.rfc3339.FionaTimeType'>}
```

Is this intentional?

**Comment by sgillies** [comment]
@StefanBrand it is. OGR's support for booleans is quirky and thus so is Fiona's. OGR boolean is a sub-type of int https://gdal.org/development/rfc/rfc50_ogr_field_subtype.html#summary. That mapping in Fiona can't exactly carry the meaning of bool. My recommendation is to ignore fiona.FIELD_TYPES_MAP.

**Comment by StefanBrand** [comment]
@sgillies Ok, I'll ignore it then. :grin: Is there another canonical list of values that can be specified in a `schema` for `type`?
