### ISSUE TITLE
Issues with encoding

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#526]
The following test is failing on Appveyor:

`tests/test_unicode.py::UnicodeStringFieldTest::test_write_gb18030`

https://ci.appveyor.com/project/sgillies/fiona/branch/master/job/9m2ojvuj936jauih

The issue seems to be related to:

```
CPLE_AppDefined in b"Failed to create field name 'label': cannot convert to gb18030"
```

The same test passes on Travis:

https://travis-ci.org/Toblerity/Fiona/jobs/322290466

I get the same failure on macOS using either Fiona build from master (using conda-forge GDAL) or using the macOS binary available from PyPI.

At this point I'm not sure if the issue is with my install of iconv, GDAL or something with Fiona itself.

**Comment by snorfalorpagus** [comment]
I've submitted an issue upstream. I think it's a problem with the install of the library, rather than anything we're doing, as I can reproduce the issue using the SWIG OGR module.

**Comment by sgillies** [comment]
@snorfalorpagus thanks ! Until it gets fixed, do you think we should mark this test as an xfail on windows?

**Comment by snorfalorpagus** [comment]
> Until it gets fixed, do you think we should mark this test as an xfail on windows?

The issue isn't specific to Windows - I get this on macOS too. I think it's indicating a faulty gdal/iconv install.

I think it might be more appropriate to skip the test specifically on our Appveyor instance (by modifying the call to pytest in `appveyor.yml`. That'll give us a green light on the other unrelated PRs.

**Comment by snorfalorpagus** [comment]
I've confirmed this is an issue with the way GDAL is compiled. https://github.com/conda-forge/libgdal-feedstock/issues/32

**Comment by sgillies** [comment]
Resolved. We're skipping this test on AppVeyor.
