### ISSUE TITLE
Reading date field with NULL value causes "ValueError: year is out of range"

### ISSUE THREAD

**Issue by theej** [Toblerity/Fiona#536]
Fiona throws an error "ValueError: year is out of range" when reading a date field with null value. I made this very simple test script and test data (attached): both shapefiles contain one feature and one data field. Shapefile "has_date.shp" causes no error, shapefile "null_date.shp" causes the ValueError.

```
# -*- coding: utf-8 -*-
import fiona
import sys

print sys.platform  # win32
print sys.version  # 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
print fiona.__version__  # 1.7.11

with fiona.open('has_date.shp', 'r') as source:
    for feature in source:
        pass

with fiona.open('null_date.shp', 'r') as source:
    for feature in source:  # error: ValueError: year is out of range
        pass
```

[data.zip](https://github.com/Toblerity/Fiona/files/1646506/data.zip)

**Comment by snorfalorpagus** [comment]
I am unable to reproduce this issue. Which version of GDAL/OGR do you have installed? You can check with:

`fiona.get_gdal_release_name()`

Fiona 1.7.x does not support GDAL 2.2 and has issues with NULL fields, which could be what you're seeing. If this is the problem I recommend either upgrading to the pre-release Fiona 1.8, or downgrading to GDAL 2.1.x.

**Comment by theej** [comment]
I'm using Fiona 1.7.11 and GDAL 2.2.2. Good to know that they don't work together. I'd like to test your suggestions, to upgrade Fiona or downgrade GDAL. However, I'm on Windows and pip-install Fiona and GDAL causes errors (ironically, only those 2). I have to rely on Christoph Gohlke's Windows binaries for Fiona and GDAL. Unfortunately, he distributes incompatible versions (1.7 and 2.2). But I guess this is not an issue then: fine for me to close it. Thank you.
