### ISSUE TITLE
Creating a features collection of points from scratch

### ISSUE THREAD

**Issue by h4k1m0u** [Toblerity/Fiona#546]
Apologies if what I'm facing has already been reported but I couldn't find an issue to answer it in here.

I want to create a sort of `FeaturesCollection` (collection of points) with `Fiona`, so I'm looping over all the points I have and I'm trying to add them to a list that will be saved to a single file:

```python
schema = {
    'geometry': 'Point',
    'properties': {'id': 'int'},
}
with fiona.open(path_samples, 'w', 'ESRI Shapefile', schema) as c:
    points = []

    for i in range(len(map_coords)):
        point = {
            'geometry': mapping(Point(map_coords[i])),
            'properties': {'id': i},
        }
        points.append(Point(map_coords[i]))

    print('Points:', points)
    c.writerecords(points)
```

The error I'm getting right now is `TypeError: 'Point' object is not subscriptable`, which is expected since the type of geometry should be a list of `Point` (not a single `Point`).

The problem is that I'm not sure which type of [Geometry type](https://toblerity.org/fiona/manual.html#geometry-types) I should use in the schema. I've used a `MultiPoint` before but I would end up with a single feature in the vector file produced (the last point saved).

Thanks.
Hakim.

**Comment by sgillies** [comment]
`'Point'`, as you have in your example, is the correct geometry type. The schema argument describes individual records in the serialized feature collection, not the feature collection as a whole.
