### ISSUE TITLE
minor gdal version needed for linux build

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#547]
I tried to build Fiona on Linux according to https://github.com/Toblerity/Fiona/blob/master/README.rst#unix-like-systems and got

Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    gdal_minor_version = int(gdal_version_parts[1])
IndexError: list index out of range

I had to specify the major and minor version, so e.g. not `--gdalversion 2` but `--gdalversion 2.3`.

**Comment by sgillies** [comment]
I'll update the docs.

Most of the time, the easiest thing to do when building from source is to specify the path to gdal-config:

`GDAL_CONFIG=/path/to/gdal-config pip install Fiona-$version.tar.gz`

I'll move that up in the installation directions.
