### ISSUE TITLE
Error message recommends using SHAPE_RESTORE_SHX which doesn't work

### ISSUE THREAD

**Issue by sbrandwoo** [Toblerity/Fiona#548]
## Expected behavior and actual behavior.

I tried running Fiona on a shapefile that does not have a corresponding shx file:

```
$ fio info myshapefile.shp 
ERROR:Fiona:CPLE_OpenFailed in b'Unable to open myshapefile.shx or myshapefile.SHX.Try --config SHAPE_RESTORE_SHX true to restore or create it'
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "[...]/env/lib/python3.6/site-packages/fiona/fio/info.py", line 50, in info
    with fiona.open(input, layer=layer) as src:
  File "[...]/env/lib/python3.6/site-packages/fiona/__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "[...]/env/lib/python3.6/site-packages/fiona/collection.py", line 153, in __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 405, in fiona.ogrext.Session.start
  File "fiona/_err.pyx", line 185, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_OpenFailedError: b'Unable to open myshapefile.shx or myshapefile.SHX.Try --config SHAPE_RESTORE_SHX true to restore or create it'
Aborted!
```

But there seems to be no way to use `--config SHAPE_RESTORE_SHX`:

```
$ fio info --config SHAPE_RESTORE_SHX myshapefile.shp 
Error: no such option: --config
```

I can't find any mention of `SHAPE_RESTORE_SHX` in the documentation or even in the codebase.

## Operating system

Ubuntu 16.04.3 LTS

## Fiona and GDAL version and provenance

Fiona 1.7.11.post1
PIP 9.0.1
Python 3.6.3
GDAL 1.11.3+dfsg-3build2 via apt

**Comment by sgillies** [comment]
@sbrandwoo this is an issue with GDAL. I've filed a ticket in that project's tracker: https://trac.osgeo.org/gdal/ticket/7246#ticket. 

`SHAPE_RESTORE_SHX` is documented at https://trac.osgeo.org/gdal/wiki/ConfigOptions#SHAPE_RESTORE_SHX. It's new, which suggests to me that your Fiona installation is actually using GDAL 2.2 and not 1.11. If you installed Fiona using pip, you are likely to have downloaded a binary wheel with GDAL 2.2. built in.

Here's the workaround for you:

`$ SHAPE_RESTORE_SHX=YES fio info myshapefile.shp`

**Comment by habibabirached** [comment]
You are a genius sgillies.

**Comment by solwan** [comment]
> @sbrandwoo this is mainly an issue with GDAL. I've filed a ticket in that project's tracker: https://trac.osgeo.org/gdal/ticket/7246#ticket and have a PR: [OSGeo/gdal#311](https://github.com/OSGeo/gdal/pull/311).
> 
> `SHAPE_RESTORE_SHX` is documented at https://trac.osgeo.org/gdal/wiki/ConfigOptions#SHAPE_RESTORE_SHX. It's new, which suggests to me that your Fiona installation is actually using GDAL 2.2 and not 1.11. If you installed Fiona using pip, you are likely to have downloaded a binary wheel with GDAL 2.2. built in.
> 
> Here's the workaround for you:
> 
> `$ SHAPE_RESTORE_SHX=YES fio info myshapefile.shp`


how can i set this configuration?
