### ISSUE TITLE
Encoding Issue with emoji-unicode in column of ESRI shapefile, written from Fiona, not displayed correctly

### ISSUE THREAD

**Issue by Sieboldianus** [Toblerity/Fiona#549]
I wrote this question originally on [Stackexchange](https://gis.stackexchange.com/questions/273359/arcgis-10-4-strange-phenomenon-with-special-unicode-characters-column#), but didn't get an answer. Perhaps someone here knows why the Shapefile written from Fiona isn't displayed correctly in ArcGIS. I worked on this problem for a while and I have localized it pretty well now to ArcGIS 10.4 at its core (haven't tested 10.5): **A column that contains special Unicode Characters (emojis) is not read correctly from the Shapefile.** 

It looks like this:

[![Unicode column with emojis and corresponding unicode_name of character in left column][1]][1]

The Left Column contains the unicode-special-characters (emojis), the right column the corresponding unicoce-names of codepoints (`unicode_name(emoji_str)`). I am writing this Shapefile with fiona (explicit encoding in UTF-8):
`with fiona.open('output.shp', mode='w', encoding='utf-8', driver='ESRI Shapefile', schema=schema,crs=from_epsg(epsg_code)) as c:`

The `output.cpg` explicitly states `UTF-8`.

No other program seems to have this problem with the DBF or Shapefile. QGIS has problems printing the emoji (not suprisingly), but it is still correctly read:
[![QGIS view of table][2]][2]

If I open the `output.dbf` of the shapefile in LibreOffice, everything looks perfect:
[![LibreOffice View of table][3]][3]

**A workaround for me was the following:**

 - open DBF in LibreOffice
 - export to `output.CSV`
 - add `output.CSV` to ArcGIS:
    - [![CSV imported to ArcGIS][4]][4]
    - looks good!
 - join Table to original Shapefile:
    - [![CSV joined to original shapefile][5]][5]
    - joined column (selected) looks still good!
    - I can export the Shapefile now with the joined column, and this I find really strange, it still looks good:
    - [![JoinedCSVExportedShapefile][6]][6]
    - this tells me that ArcGIS Shapefile **can** handle such characters, but the original Shapefile seems to have some problems that I cannot locate at the moment
 - in case you wonder if I could export the Shapefile from QGIS:
    - this does not work, the exported Shapefile appears to have the same problems in ArcGIS, despite that it is correctly viewed in QGIS

The text that appears in the problematic columns seems to originate from surrounding columns, some sort of substitution going on. It is not just visual, I can copy the text and if I export the shapefile, it gets hard-coded/written.

I followed [this tech article](https://support.esri.com/de/technical-article/000013192) and set my default codepage for ArcGIS to UTF-8 - no changes. I have done all sorts of checks in Python and Fiona, but the Charactersets appear all to be ok and the correct view in LibreOffice and CSV corroborate my assumption that there is something completely going wrong in ArcGIS.

If you want to try yourself, here is the test shapefile from above:
[output_shapefile.zip (https://file.io/oyz87D)](https://file.io/oyz87D)
Or you can try writing a shapefile with Fiona and an example Emoji such as this one: 😍

**How can I create an ESRI Shapefile from Python that can be loaded to ArcGIS with Unicode-Emojis showing correctly?**

This is an example Python program to reproduce the issue:
```python
#!/usr/bin/env python
# coding: utf-8
# emojiShapeUnicodeArcGISTest
import fiona
from fiona.crs import from_epsg
import emoji
from unicodedata import name as unicode_name

def extract_emojis(str):
    return list(c for c in str if c in emoji.UNICODE_EMOJI)

#Example Emojis
emojistring = '😍 test text ❤️👨‍⚕️'
emojilist = extract_emojis(emojistring)

#Define polygon feature geometry
schema = {
    'geometry': 'Polygon',
    'properties': {'emoji': 'str',
                'emoji_text': 'str'},
}
#write Shapefile
with fiona.open('output.shp', mode='w', encoding='UTF-8', driver='ESRI Shapefile', schema=schema,crs=from_epsg(4326)) as c:
    for emoji in emojilist:            
        c.write({'geometry': {'coordinates': [[(-4.663611, 51.158333),
                                (-4.669168, 51.159439),
                                (-4.673334, 51.161385),
                                (-4.674445, 51.165276),
                                (-4.67139, 51.185272),
                                (-4.669445, 51.193054),
                                (-4.665556, 51.195),
                                (-4.65889, 51.195),
                                (-4.656389, 51.192215),
                                (-4.646389, 51.164444),
                                (-4.646945, 51.160828),
                                (-4.651668, 51.159439),
                                (-4.663611, 51.158333)]],
                'type': 'Polygon'},
                'properties': {'emoji': emoji, 
                                'emoji_text': str(unicode_name(emoji))},
        })
```
The Shapefile-table it produces looks like this in ArcGIS 10.4 (with bug visible in row 1 and 3):
[![Result of Test Code][7]][7]

I also put the code on [Pastebin](https://pastebin.com/ekQmseYH)

  [1]: https://i.stack.imgur.com/ffx9k.png
  [2]: https://i.stack.imgur.com/SymZt.png
  [3]: https://i.stack.imgur.com/4BgaL.png
  [4]: https://i.stack.imgur.com/mKYAa.png
  [5]: https://i.stack.imgur.com/gIYwI.png
  [6]: https://i.stack.imgur.com/0g66Z.png
  [7]: https://i.stack.imgur.com/neY8o.png

**Comment by sgillies** [comment]
@Sieboldianus thanks for the script, it is excellent. I'm able to read the emojis back out of the shapefile using Fiona, which is a good sign.

```
$ fio insp output.shp
Fiona 1.7.11.post1 Interactive Inspector (Python 3.6.4)
Type "src.schema", "next(src)", or "help(src)" for more information.
>>> for feat in src:
...     print(feat['id'], feat['properties']['emoji'])
...
0 😍
1 ❤
2 👨
3 ⚕
```

Please note that in 1.7.11 we fixed an encoding-related bug. Which version of Fiona are you using? If not the latest, can you see if updating will help?

**Comment by Sieboldianus** [comment]
Thanks for the quick answer! I am using Fiona-1.7.9 - I somehow thought this is newer than 1.7.11 but it could be a misunderstanding. Pip didn't upgrade, so I assume I have to install it from github?

**Comment by sgillies** [comment]
@Sieboldianus how did you install Fiona? From PyPI or conda or what?

**Comment by sgillies** [comment]
@Sieboldianus how did you install Fiona? From PyPI or conda or what? What operating system?

I'm unable to reproduce the problem (no ArcGIS for me) and wonder if it comes down to slightly different software.

**Comment by Sieboldianus** [comment]
Many apologies for my late response. I installed fiona using the precompiled wheel from Christian Golke's library.

You could also send me a shapefile produced with my code on you computer and I can test it in ArcGis

**Comment by Sieboldianus** [comment]
I thought about a solution how you could check this problem without ArcGIS. There's the free [ArcReader](http://www.esri.com/software/arcgis/arcreader) which can open *.pmf files (published ArcGIS *.mxd maps) with data. I published a map with the above shapefile: [https://file.io/BJwAON](https://file.io/BJwAON). If you open it, you can get to the table view by using the identify tool, it shows the same problem:
[url=https://imgbb.com/][img]https://image.ibb.co/dona07/img_arcreader.png[/img][/url]

**Comment by sgillies** [comment]
@Sieboldianus there's one more thing I'd like to ask you to try.

At the end of 2017, there was this issue reported about Fiona + character encoding: https://github.com/Toblerity/Fiona/issues/526. It turned out to be a problem with the conda-forge build of GDAL/OGR: https://github.com/conda-forge/libgdal-feedstock/issues/32. I think it's possible that the same thing could be going on with Gohlke's Windows builds. Would you be willing to try installing Fiona using conda and conda-forge as explained at https://github.com/conda-forge/fiona-feedstock#installing-fiona?

**Comment by Sieboldianus** [comment]
Yes, many thanks. I'll try this right away and get back to you!

**Comment by Sieboldianus** [comment]
Sorry for the many responses, but I am trying to test different things here to identify where the problem is, and perhaps this may also help you:

If I do `'properties': {'emoji': emoji.encode('unicode-escape').decode('ASCII'),`, I get the following output:
![wrong_utf](https://user-images.githubusercontent.com/13646666/37168244-166649c4-22b9-11e8-9e92-b4d86432e615.png)

As stated [here](https://codepoints.net/U+1F60D?lang=en)
> On Youtube this character is sometimes wrongly displayed as U0001f60d.

I also wonder why the two problematic Unicode-Characters have lower-case `u` and the correctly displayed Unicode Emojis have Uppercase `U`.

My knowledge of Unicode and Encoding are limited though, so this doesn't have to mean anything..

**Comment by sgillies** [comment]
@Sieboldianus to see if this is an iconv issue, can you try the shapefile I've written on my computer using your program?

[fiona_issue_549.zip](https://github.com/Toblerity/Fiona/files/1804646/fiona_issue_549.zip)

**Comment by Sieboldianus** [comment]
@sgillies I tested, unfortunately, it looks the same:
![fiona_issue_549_arcmap104](https://user-images.githubusercontent.com/13646666/37322576-a8d33abc-263b-11e8-9bc2-ef9c8e85df37.png)

Today I had a gut feeling that [Zero-Width Joiners](https://en.wikipedia.org/wiki/Zero-width_joiner) or other invisible Unicode characters could be the cause. So I tested the following code to remove any, if existent (despite not seeing any in my test code though):

```python
def checkEmojiType(strEmo):
    if unicodedata.name(strEmo).startswith(("EMOJI MODIFIER","VARIATION SELECTOR","ZERO WIDTH")):
        return False
    else:
        return True
def cleanEmoji(c):
    tuple = (u'\ufeff',u'\u200b',u'\u200d')
    for ex in tuple:
        c.replace(ex,"")
    return(c)
def extract_emojis(str):
  return list(cleanEmoji(c) for c in str if c in emoji.UNICODE_EMOJI and checkEmojiType(c) is True)
```

Didn't help either! This drives me mad :(

**Comment by sgillies** [comment]
@Sieboldianus I've come to the conclusion that this is something we're not going to be able to solve in Fiona. Support for ArcGIS's understanding of unicode emoji characters will need to be added to GDAL's shapefile format driver. I looked at the EmojiColumn_ArcGIS_CSVJoined.zip file and the DBF in there isn't exactly UTF-8, there are a bunch of UTF-16 surrogate pairs in it, and I'm not sure how GDAL would deal with that.

**Comment by Sieboldianus** [comment]
Thanks so much, sgillies! This is interesting, and I had the same feeling. Fiona isn't the cause of this problem, but more likely ArcGIS and GDAL. I will test Shapefile creation on other computers and with other ArcGIS versions - although my hopes are small that this is an issue limited to my computer or specific ArcGIS version.
As it seems, unfortunately, ESRI doesn't provide much information as to the exact conventions they use when writing/reading shapefiles. Your observation of UTF-16 surrogates found in that ESRI-generated shapefile corroborate this ..

I totally like Fiona, and it is a great toolset. I would use free GIS Software if it wasn't for ArcGIS really good label engine. The shapefiles I'm producing are based on Instagram and Flickr data and ArcGIS is used in the last step of mapping data, to create visualizations that show tag/emoji-clustering, e.g. [Charlottesville](https://www.flickr.com/photos/64974314@N08/40730164232/in/dateposted-public/)

Anyway, many thanks for your help. You can close this issue - I will report back if I found out any news that are relevant to this!
