### ISSUE TITLE
Problems with format guessing when writing Shapefile/GeoJSON

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#568]
I am sorry in advance, because this is dumb, but it is a bug.

If I have a shapefile of name `foo.shp` (plus auxiliary files) and try to create a GeoJSON file named `foo.shp` (because I forgot to update the filename), I will get a Shapefile named `OgrGeoJSON.shp` (plus aux. files) instead. Here is a test script:

```
import fiona
from fiona.crs import from_epsg
import glob

outdir = "/tmp"
file = "O"  # "O" so that we will see the OgrGeoJSON files in globbing

p = {
    'geometry': {'coordinates': (370262, 5615696), 'type': 'Point'},
    'id': '0', 'properties': {}, 'type': 'Feature'
}

schema = {'geometry': 'Point', 'properties': {}}

with fiona.open(f"{outdir}/{file}.shp", "w", crs=from_epsg(25832), schema=schema, driver="ESRI Shapefile") as sink:
    sink.write(p)
        
print(glob.glob(f"{outdir}/{file}*"))
# -> ['/tmp/O.prj', '/tmp/O.cpg', '/tmp/O.dbf', '/tmp/O.shx', '/tmp/O.shp']

# here we have .shp but driver="GeoJSON"
with fiona.open(f"{outdir}/{file}.shp", "w", crs=from_epsg(25832), schema=schema, driver="GeoJSON") as sink:
    sink.write(p)
        
print(glob.glob(f"{outdir}/{file}*"))
# -> ['/tmp/OgrGeoJSON.prj', '/tmp/OgrGeoJSON.cpg', '/tmp/OgrGeoJSON.dbf', '/tmp/OgrGeoJSON.shx', '/tmp/OgrGeoJSON.shp', '/tmp/O.prj', '/tmp/O.cpg', '/tmp/O.dbf', '/tmp/O.shx', '/tmp/O.shp']
```

I would have expected either an error or the foo.shp file being overwritten (aux. files left in place for extra confusion because screw the Shapefile format clutter).

The other way around is not much better as Fiona now tries to overwrite the existing foo.geojson with another GeoJSON even though ESRI Shapefile was set as the driver.

```
import fiona
from fiona.crs import from_epsg
import glob

outdir = "/tmp"
file = "O"  # "O" so that we will see the OgrGeoJSON files in globbing

p = {
    'geometry': {'coordinates': (370262, 5615696), 'type': 'Point'},
    'id': '0', 'properties': {}, 'type': 'Feature'
}

schema = {'geometry': 'Point', 'properties': {}}

with fiona.open(f"{outdir}/{file}.geojson", "w", crs=from_epsg(25832), schema=schema, driver="GeoJSON") as sink:
    sink.write(p)
        
print(glob.glob(f"{outdir}/{file}*"))
# -> ['/tmp/O.geojson']

# here we have .geojson but driver="ESRI Shapefile"
with fiona.open(f"{outdir}/{file}.geojson", "w", crs=from_epsg(25832), schema=schema, driver="ESRI Shapefile") as sink:
    sink.write(p)
        
print(glob.glob(f"{outdir}/{file}*"))
# -> DriverIOError: GeoJSON driver doesn't support creating a layer on a read-only datasource
```

To me, the driver parameter should have precedence as it is such an explicite declaration of the user.

**Comment by snorfalorpagus** [comment]
@kannes Which version of Fiona and GDAL are you using, and where were they installed from?

**Comment by snorfalorpagus** [comment]
I think this is an issue with GDAL 1.x only. I can reproduce on both 1.7.11 and master.

https://travis-ci.org/snorfalorpagus/Fiona/builds/362853277

**Comment by kannes** [comment]
pip downloaded Fiona-1.7.11.post1-cp36-cp36m-manylinux1_x86_64.whl and I have Fiona==1.7.11.post1 from it.
gdal is on 2.3, r41888 from svn.
Archlinux.

I will check on another machine later.

**Comment by kannes** [comment]
The other system is:
Fiona==1.7.10.post1 and GDAL 2.2.3, released 2017/11/20
Also Arch.

**Comment by sgillies** [comment]
What a wacky bug @kannes . Thanks for the report. We should get this fixed, but doing a good job of it will take some work. We will also need to discuss whether creating a GeoJSON named `foo.shp` should overwrite just the .shp file or completely clean up the shapefiles of the same basename.

**Comment by sgillies** [comment]
I'm going to close this one as we are many GDAL versions on. We can reopen or create a new issue if needed.

**Comment by kannes** [comment]
Sure thing! If someone runs into it again they will hopefully find the issue and shout.
