### ISSUE TITLE
Support for date/datetime/time fields

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#572]
As explored in #563 the support in GDAL for date, datetime and time fields varies between versions and formats. I think we should be raising warnings when a user could be impacted by these issues.

Summary of support in the tables below:

| GDAL 1.x | ESRI Shapefile | GPKG   | GeoJSON | MapInfo File |
|----------|----------------|--------|---------|--------------|
| Date     | Yes            | Yes    | No (1)  | Yes          |
| Datetime | No (2)         | No (2) | No (3)  | Yes          |
| Time     | No (4)         | No (5) | No (6)  | Yes          |

| GDAL 2.x | ESRI Shapefile | GPKG   | GeoJSON | MapInfo File |
|----------|----------------|--------|---------|--------------|
| Date     | Yes            | Yes    | Yes     | Yes          |
| Datetime | No (2)         | Yes    | Yes     | Yes          |
| Time     | No (4)         | No (6) | Yes     | No (7)       |

(1) date silently converted to string and non-standard formatting used
(2) datetime silently converted to date
(3) datetime silently converted to string and non-standard formatting used
(4) attempting to write time field causes KeyError
(5) time field silently not written to file
(6) time field silently converted to string
(7) null time field interpreted as 00:00:00 (regression in GDAL 2?)

(4) and (7) need further investigation, as these seem to be bugs.

**Comment by sgillies** [comment]
Thanks for summarizing the issue! I'd be inclined to focus on improving the user experience with GDAL 2 first (by adding some warnings?) and let the issues with GDAL 1 slide for a bit.

**Comment by sgillies** [comment]
Hey, we finished this in 1.8.14 as far as I can tell.
