### ISSUE TITLE
Add GDAL version number as named tuple

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#575]
It would be useful if we had access to the GDAL version number in a named tuple, e.g.

```python
import fiona
print(fiona.gdal_version.major)
print(fiona.gdal_version.minor)
print(fiona.gdal_version.release)

assert fiona.gdal_version.major >= 2
assert fiona.gdal_version >= (2, 2, 0)
```

**Comment by rbuffat** [comment]
Fiona has already something similar, although not as nice:

`fiona.get_gdal_version_num() >= fiona.calc_gdal_version_num(2, 3, 0)`

It would be possible to convert the gdal version number to a tuple by reversing the calculation: https://github.com/Toblerity/Fiona/blob/a127ca17d9e5ab3ea63e9749341e526837b1d24a/fiona/ogrext.pyx#L132-L134


In the tests, also `from packaging.version import parse` is used. However, gdal does not follow [PEP440](https://www.python.org/dev/peps/pep-0440/), thus the gdal dev builds are only recognized as `LegacyVersion`.
