### ISSUE TITLE
S57 driver support?

### ISSUE THREAD

**Issue by freol35241** [Toblerity/Fiona#581]
Thank you for a nice and useful library!

Do you have any plans on supporting the S57 format in the (near) future?

**Comment by rbuffat** [comment]
You could test if gdals S57 driver works with fiona by uncomenting line 101: https://github.com/Toblerity/Fiona/blob/master/fiona/drvsupport.py#L101
in drvsupport.py. E.g. on linux this file will be located at /usr/lib/python*/site-packages/fiona

You need to ensure that your gdal installation has support for this format included (e.g. when it is included in ogrinfo --formats). I think gdal only supports reading and not writing: http://www.gdal.org/ogr_formats.html

There is no guarantee that this works. At the moment I think there are also no possibilities to set the control options from http://www.gdal.org/drv_s57.html, but it might work by setting environment variables manually.

**Comment by freol35241** [comment]
Thank you for the quick reply!

By uncommenting that line, fiona opens and reads the data into a collection, but only a single feature/layer with no geometry unfortunately.

And yes, my gdal installation supports the driver.

Any plans on supporting this format in the future?

**Comment by sgillies** [comment]
I wouldn't object to enabling S57. If it doesn't read your data properly, I think there's very little we can do: it's probably a deficiency of GDAL and OGR.

**Comment by freol35241** [comment]
@sgillies 
Thanks for taking an interest in this. The data format is supported by GDAL and I have an c++ application (using GDAL) reading the same file without problem. The only difference I can spot in the setup is:
* C++ application uses the GDAL bundled with OSGeo4W
* Fiona and GDAL (python) installed from Gohlke's collection of windows binaries (I am on Windows)

Resulting in a properly read file in the C++ application, seeing all the features/layers/geometries, whereas Fiona returns a single feature/layer with no geometry.

Any ideas what could be causing this?

**Comment by freol35241** [comment]
@sgillies @rbuffat 
Solution found, sorry for bothering you guys.

As S57 is a multilayer format, specifying a layer name works and returns a Collection object with geometries. Opening the file without a layer name just gives a Collection object with no geometries (at least I dont manage to find any geometries). It seems opening just the file, loads the data set "info layer" "DSID" which contains no geometries?

Is this the intended behavior? Anyway, would be grateful if you enabled S57 support by default.
Thanks in advance!

**Comment by sgillies** [comment]
@freol35241 Yes, it is intended. With multilayer formats, unless you specify a layer name or index, we take the layer at index 0.
