### ISSUE TITLE
Fiona installation on Mac by anaconda

### ISSUE THREAD

**Issue by linyunhe** [Toblerity/Fiona#582]
My python is installed under anaconda.
I try to install fiona using "pip install fiona". 

After intallation, when I try to "import fiona", I get the error 
"ImportError: dlopen(/Users/llhe/anaconda3/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Symbol not found: _sqlite3_column_table_name
  Referenced from: /Users/llhe/anaconda3/lib/python3.6/site-packages/fiona/.dylibs/libgdal.20.dylib
  Expected in: /usr/lib/libsqlite3.dylib
 in /Users/llhe/anaconda3/lib/python3.6/site-packages/fiona/.dylibs/libgdal.20.dylib"

I'm wondering this might be due to directory path of default file caused by anaconda. Then I tried "conda install -c conda-forge fiona 
conda install -c conda-forge/label/broken fiona " according to https://anaconda.org/conda-forge/fiona. However when I was installing, I received the error 
"Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/free/osx-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)"

Since the message says this connection error might be intermittent, I tried several times but all failed. 

Could someone help me to figure it out?

**Comment by sgillies** [comment]
It is not possible to pip install fiona from a conda environment. You must install conda packages only using "conda", not "pip." I think your best bet is to delete this conda environment and start over. If you have any more difficulties, please ask the conda-forge or conda projects.
