### ISSUE TITLE
transform_geom fails silently when src_crs is a rasterio CRS

### ISSUE THREAD

**Issue by j08lue** [Toblerity/Fiona#590]
## Expected behavior and actual behavior.

When I pass a `rasterio.crs.CRS` object as `src_crs` to `fiona.transform.transform_geom`, it just prints a (in some cases invisible) warning and returns the un-transformed geometry.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'CRS' object has no attribute 'encode'

Exception ignored in: 'fiona._transform._crs_from_crs'
AttributeError: 'CRS' object has no attribute 'encode'
```

I would expect `transform_geom` to fail in that case - or to support `rasterio.crs.CRS`.

The workaround is to convert the `CRS` into a dictionary with `dict(src_crs)`.

## Steps to reproduce the problem.

Please see [this notebook](https://gist.github.com/j08lue/f89c6477735a6abb5622131211ecc534)

## Operating system

* Windows 10 64 bit

## Fiona and GDAL version and provenance

all `conda-forge` builds

* `fiona` 1.7.10
* `gdal` 2.2.3

**Comment by sgillies** [comment]
@j08lue there's a problem in that CRS lacks the appropriate dunder str method.

```
>>> str(CRS.from_epsg(4326))
"CRS({'init': 'epsg:4326', 'no_defs': True})"
```

I'll add that for Rasterio 1.0, but until then we'll need to call `crs.to_string()`.
