### ISSUE TITLE
cURL certificate issues

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#598]
Following discussion in #576.

Appveyor currently has some failures related to libcurl and SSL certificates that look like this:

```
_______________________________ test_open_http ________________________________
>   ???
fiona\_shim.pyx:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   fiona._err.FionaNullPointerError: NULL pointer error
fiona\_err.pyx:239: FionaNullPointerError
During handling of the above exception, another exception occurred:
    @pytest.mark.network
    def test_open_http():
>       ds = fiona.open('https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/poly.shp')
tests\test_vfs.py:165: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Python36-x64\Lib\site-packages\fiona\__init__.py:246: in open
    enabled_drivers=enabled_drivers, **kwargs)
C:\Python36-x64\Lib\site-packages\fiona\collection.py:158: in __init__
    self.session.start(self, **kwargs)
fiona\ogrext.pyx:445: in fiona.ogrext.Session.start
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   fiona.errors.DriverError: Failed to open dataset (mode=0): /vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/poly.shp
fiona\_shim.pyx:62: DriverError
```

A quick check shows that GitHub redirects HTTP requests to HTTPS. I'm guessing this was not always the case, which is why we are now seeing errors?

```
$ curl -I http://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/poly.zip
HTTP/1.1 301 Moved Permanently
Server: Varnish
Retry-After: 0
Location: https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/poly.zip
Content-Length: 0
Accept-Ranges: bytes
Date: Sat, 09 Jun 2018 13:55:36 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-lcy19220-LCY
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1528552536.138625,VS0,VE0
Access-Control-Allow-Origin: *
Expires: Sat, 09 Jun 2018 14:00:36 GMT
Vary: Authorization,Accept-Encoding
```

For GDAL 2.1+ this can be fixed by putting the location of the certificate bundle in an environment variable:

```
set SSL_CERT_FILE=C:\gdal\bin\curl\curl-ca-bundle.crt
set CURL_CA_BUNDLE=C:\gdal\bin\curl\curl-ca-bundle.crt
```

https://ci.appveyor.com/project/sgillies/fiona/build/1.0.590

However, GDAL 1.x doesn't respect these environment variables.

https://github.com/OSGeo/gdal/blob/8cbc24cd6b1e6ddf9a63b0b4050c489185883c35/gdal/port/cpl_http.cpp#L592
http://www.gdal.org/gdal_virtual_file_systems.html

I have read that libcurl will search some default locations for this certificate bundle, but I'm not sure where this is on Windows. I guess that's why Travis is OK?

I think the easiest fix for now would be to provide the environment variables for GDAL 2.1, and mark the tests as xfail for earlier versions until we find a full solution.

@rbuffat @sgillies

**Comment by sgillies** [comment]
We're going to depend on certifi starting with 1.8.18. See 5743a96.
