### ISSUE TITLE
Breaking install with Python 3.7

### ISSUE THREAD

**Issue by apizzimenti** [Toblerity/Fiona#601]
## Expected behavior and actual behavior.
Geopandas requires Fiona as a dependency. Running `pip3 install geopandas` or `pip3 install fiona` should not error out and, at the worst, elicit warnings from Pip.

Currently, I receive the following error when installing:
```
fiona/_transform.cpp:606:10: fatal error: 'cpl_conv.h' file not found
  #include "cpl_conv.h"
           ^~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for fiona
```
Then, at the end of the install, I get this as well:
```
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private
/var/folders/b4/4t2z6gx968g4f28bkjcgtyjm0000gn/T/pip-install-6epat_by/fiona
/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', 
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders
/b4/4t2z6gx968g4f28bkjcgtyjm0000gn/T/pip-record-emn0sri_/install-record.txt --single-version-
externally-managed --compile" failed with error code 1 in /private/var/folders
/b4/4t2z6gx968g4f28bkjcgtyjm0000gn/T/pip-install-6epat_by/fiona/
```

## Steps to reproduce the problem.
Install Python 3.7.0, then run `pip3 install fiona`.

## Operating system
MacOS v10.13.5. Python 3.7.0 installed through Homebrew.

## Fiona and GDAL version and provenance
GDAL 2.3.0dev, released 2017/99/99. No Fiona version because I can't install it.

**Comment by sgillies** [comment]
@apizzimenti `fatal error: 'cpl_conv.h' file not found` means that you either don't have the GDAL library headers installed on your system or the gdal-config program isn't on your executable path. As described at https://github.com/Toblerity/Fiona#installation, GDAL is required.

We have binary wheels for Python 3.6 that include GDAL on PyPI, but not yet for 3.7.

**Comment by Juanlu001** [comment]
Is there anything major that blocks Python 3.7 support?

**Comment by perrygeo** [comment]
@Juanlu001 Fiona on py3.7 is blocked by https://github.com/Toblerity/Fiona/issues/619
