### ISSUE TITLE
Wildcard support in FIO?

### ISSUE THREAD

**Issue by d-diaz** [Toblerity/Fiona#602]
## Expected behavior and actual behavior.

I tried executing the following one-liner using to merge vector files as shown on the [Fiona-Rasterio-Shapely Cheat Sheet](https://github.com/sgillies/frs-cheat-sheet). I expected this to merge all my shapfiles in the working directory into a single shapefile. 
`fio cat *.shp | fio load --format Shapefile merged.shp`

Instead, I got:
```
(geo) >fio cat *.shp
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "...\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\fiona\fio\cat.py", line 71, in cat
    with fiona.open(path, layer=lyr) as src:
  File "...\AppData\Local\Continuum\anaconda3\envs\geo\lib\site-packages\fiona\__init__.py", line 162, in open
    raise IOError("no such file or directory: %r" % path)
OSError: no such file or directory: '*.shp'
Aborted!
```
I tried with variations on `*.shp` including `./*.shp` and `.\*.shp` and received the same error.

## Steps to reproduce the problem.

Try executing the cheat sheet command with one or more shapefiles in the working directory.

## Operating system

Microsoft Windows 10 Pro v.10.0.16299

## Fiona and GDAL version and provenance

Fiona 1.7.9 Build py36_1 installed using conda from conda-forge channel 
gdal 2.1.3 Build py36_vc14_7 installed using conda from conda-forge channel

**Comment by sgillies** [comment]
@d-diaz `fio cat *.shp` will only work with a posix-compliant shell. fio-cat requires the shell to do the expansion into an array of filenames. My understanding is that the standard Windows shell doesn't support globbing. I should make it this more clear in my cheat sheet.
