### ISSUE TITLE
Is fiona capable of encoding to WKB ?

### ISSUE THREAD

**Issue by guyisra** [Toblerity/Fiona#611]
hello

I couldn't find it in the docs whether its possible to use fiona to take a geometry in epsg 3857 and transform/encode it to its hexa/WKB string equivalent the same way libosmium does. Meaning writing (via fiona or not) the geometry in hexa/WKB string and not to a shapefile

thanks

**Comment by snorfalorpagus** [comment]
This can be done with Shapely: https://github.com/Toblerity/Shapely

For example:

```python
>>> from shapely.geometry import Point
>>> Point(1,2).wkb
b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@'
```

If your geometry data is in GeoJSON-like format (as Fiona uses) you can use `fiona.geometry.shape` to convert, e.g.

```python
>>> from shapely.geometry import shape
>>> shape({"type": "Point", "coordinates": [1, 2]}).wkb
b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@'
```

WKT is also supported (use `.wkt`). No coordinate transformation is done in this process - that is left to the user.
