### ISSUE TITLE
Using MemoryFile for formats involving several files

### ISSUE THREAD

**Issue by radiophysicist** [Toblerity/Fiona#613]
Is it possible to use MemoryFile i.e. for shapefiles, where data actually are stored in several files (.shp/.shx/.dbf, optional .prj for CRS data)? 
If not, maybe it would be worthwhile to support such an opportunity for applications like web servers to avoid unnecessarily saving files to the disc.

P.S. right now I use pyshp in my web application extensively and it is possible to specify file-like objects for every kind of file separately. Due to some issues with shape format support incompleteness I'm considering to switch to fiona library

**Comment by sgillies** [comment]
Version 1.8's `ZipMemoryFile` (see https://github.com/Toblerity/Fiona/blob/master/tests/test_memoryfile.py#L26-L30 for example usage) is what we've developed for reading from zip files uploaded to a server.

We can write to a `MemoryFile` using the GeoJSON format driver (disregard the erroneous "shapefile" in the test name) and then transfer the bytes elsewhere (https://github.com/Toblerity/Fiona/blob/master/tests/test_memoryfile.py#L33-L45) but this does not work for multi-file formats. It might be worth doing for 1.8 ... what do you think @snorfalorpagus ?

We have 1.8a2 on the Python package index now @radiophysicist , so you can try these new classes if you like.
