### ISSUE TITLE
Fiona behaving differently inside docker (transform_geom)

### ISSUE THREAD

**Issue by guyisra** [Toblerity/Fiona#614]
running the following code 

```
import fiona.transform
src_crs = 'epsg:4326'
dest_crs = 'epsg:3857'
r = {'type': 'Polygon','coordinates': [[(8.28342, 49.99571), (8.28339, 49.99564), (8.28342, 49.99571)]]}
dest = fiona.transform.transform_geom(src_crs, dest_crs, r)
print(dest)
```

inside docker and without causes different results

without docker I get
`{'type': 'Polygon', 'coordinates': [[(922106.0964268183, 6445532.921733793), (922102.7568420947, 6445520.800057326), (922106.0964268183, 6445532.921733793)]]}`

with the following dockerfile 

```
FROM python:2.7.15-alpine3.7

RUN apk update && \
    apk upgrade && \
    apk add make automake gcc g++ && \
    apk add --no-cache  \
     --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
     --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
     gdal \
     gdal-dev \
     geos \
     geos-dev \
     py-virtualenv

RUN pip install fiona
```

`{'type': 'Polygon', 'coordinates': [[(8.28342, 49.99571), (8.28339, 49.99564), (8.28342, 49.99571)]]}
`

It's as if transform_geom doesn't do anything.
both have version  1.7.13
Do I have a missing dependency, or something in the environment that is causing fiona to work differently?

**Comment by guyisra** [comment]
I see 
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set

is `pip install fiona` not the correct way to install it?

**Comment by sgillies** [comment]
I'm not sure where apk puts the GDAL and PROJ data files, but if they are not in /usr/local/share/gdal and /usr/local/share/proj, you will need to find the directory containing `gcs.csv` and `pcs.csv` and set GDAL_DATA to that directory's path and then find the directory containing `proj_def.dat` and set PROJ_LIB to that directory's path.
