### ISSUE TITLE
Link to website / docs gives old version (1.7.0)

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Fiona#626]
The link on the github home page at the top "Fiona is OGR's neat and nimble API http://toblerity.github.com/fiona/", and in the readme the same link is used to point to "Fiona docs and manual", ends up at http://toblerity.org/fiona/, which has the documentation for 1.7.0.

For the "latest" version, readthedocs is there: https://fiona.readthedocs.io/en/latest, but it might make sense to also build "stable" on readthedocs (which would be the docs for 1.7.13) ?

**Comment by jorisvandenbossche** [comment]
https://github.com/Toblerity/Fiona/pull/683 fixed the README link, the link in the description at the top of the home page (see https://github.com/Toblerity/Fiona/issues/681 for clearer screenshot) still needs to be updated.

**Comment by sgillies** [comment]
Got it. Thanks !
