### ISSUE TITLE
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set

### ISSUE THREAD

**Issue by sdmcclure** [Toblerity/Fiona#628]
## Expected behavior and actual behavior.

When importing Fiona I get the above error, similar to #485.

## Steps to reproduce the problem.

Importing Fiona or package that has Fiona as dependency (geopandas).

## Operating system

Windows 7.

## Fiona and GDAL version and provenance

    fiona:         1.7.13-py35h2fc6367_3 conda-forge.

    gdal:         2.2.4-py35h2fc6367_1  conda-forge

**Comment by jGaboardi** [comment]
@sdmcclure I am experiencing the same issue. See [this](https://github.com/pysal/spaghetti/issues/121#issue-361526394) for a possible solution.

**Comment by sgillies** [comment]
This isn't an issue with Fiona, so I will close it. @jGaboardi thanks for linking that pysal issue, it has good advice.
