### ISSUE TITLE
Fiona fails to read datasets containing TIN Z

### ISSUE THREAD

**Issue by rbuffat** [Toblerity/Fiona#632]
## Expected behavior and actual behavior.

Fiona can't open a dataset containing TIN Z geometries:

`~/swisstopo/musterdatenswissbuildings3d20lv03/LV03/SHP$ fio cat Musterdaten_swissBUILDINGS3D20_LV03_1166_44.shp
ERROR:fio:Exception caught during processing
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fiona/fio/cat.py", line 77, in cat
    for i, feat in src.items(bbox=bbox):
  File "fiona/ogrext.pyx", line 1257, in fiona.ogrext.ItemsIterator.__next__
  File "fiona/ogrext.pyx", line 235, in fiona.ogrext.FeatureBuilder.build
  File "fiona/_geometry.pyx", line 176, in fiona._geometry.GeomBuilder.build
fiona.errors.UnsupportedGeometryTypeError: 16
Aborted!
`

GeometryType 16 is not included in https://github.com/Toblerity/Fiona/blob/ed1874e5d4ebaaed726146d3b074094e36307b22/fiona/_geometry.pyx#L36

I'm no expert in the geojson specification, but after a quick search it seems that geojson does not contain a tin datatype. However, it seems as tin is a special case of multipolygon (where with TIN each polygon is a triangle and has 4 vertices).

## Steps to reproduce the problem.

The dataset can be obtained from [https://shop.swisstopo.admin.ch/en/products/landscape/build3D2](https://shop.swisstopo.admin.ch/en/products/landscape/build3D2) -> Read more --> Additional Information --> Sample data --> swissBUILDINGS3D_2.0_LV03

## Operating system

Arch, respectively ubuntu

## Fiona and GDAL version and provenance

fiona 1.7.13 installed using pip
gdal 2.2.4

From my current understanding support for tin would require the introduction of  a mapping of triangle to polygon and tin to multipolygon, as both of these datatypes are not supported by geojson.
Hopefully I will find time during the next few days to further look into this.

**Comment by snorfalorpagus** [comment]
Closed by #679.
