### ISSUE TITLE
RuntimeError: Failed to write record: 

### ISSUE THREAD

**Issue by fahadkhan469** [Toblerity/Fiona#645]
Hi everyone,

I'm trying to run a script to save the variable 'multi_line' of MultiLineString type into a shape file by using the following code:

`
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from shapely.geometry import Point, LineString, Polygon, MultiLineString, mapping
import geopandas as gpd
from osgeo import ogr
import fiona
from fiona.crs import from_epsg
from shapely.wkt import loads

crs = from_epsg(26918)

#creation of the resulting shapefile
schema2 = {'geometry': 'MultiLineString','properties': {'tag': 'int'},}

with fiona.open('C:/Users/fkk17001/Downloads/test_result.shp', 'w', 'ESRI Shapefile', schema2, crs)  as output:
    for i, line in enumerate(multi_line): 

       
        output.write({'geometry':mapping(multi_line),'properties': {'tag':i}})`

Now the problem is, first, it's taking a huge amount of time to write the shapefiles. I have about 18,000 records and after 1.5 hours I have around 6,000 records written into shapefile. Can I expedite the process because I have a lot of more records to be written in the shapefile. Then second, I encounter an error titled "RuntimeError: Failed to write record: ", then it lists all the records which have not been written. Is it a memory error (coz apparently the size of the shapefile which was written before I got the error was 4 GB, which seems a bit too much for me)?

Thanks for reading the long post. Any kind of help would be appreciated. I'm new to Fiona. If you know any other convenient way to write shapefiles from MultiLineString (without having to use Fiona), then please let me know.

**Comment by fahadkhan469** [comment]
Okay I've just checked, the input coordinates I had are in Connecticut State plane coordinate system. This is why may be the computations were taking too long and when I add the partial output in ArcMap nothing really shows up. Can anyone suggest if I can use the same code for writing shapefiles with State Plane Coordinate System projection?

**Comment by fahadkhan469** [comment]
I've resolved the issue, therefore am closing it. The mistake was with the coordinate system.

**Comment by sgillies** [comment]
Thanks for following up @fahadkhan469 ! Fiona will write state plane shapefiles. It doesn't transform input features, so they do have to be in the state plane coordinate system already. I see an error in your code above: you must pass a GeoJSON-ish feature object to `output.write()` like this:

```python
output.write({'type': 'Feature': 'id': str(i), 'geometry':mapping(multi_line), 'properties': {'tag':i}})
```

**Comment by fahadkhan469** [comment]
Hi @sgillies, thanks a lot!
