### ISSUE TITLE
Fiona sends CPL warnings to rasterio._gdal logger

### ISSUE THREAD

**Issue by Ariki** [Toblerity/Fiona#646]
## Expected behavior and actual behavior.

I'm not sure if it is a copy-paste error or intended behavior but Fiona sends CPL warnings to a logger named `'rasterio._gdal'`. It looks a bit misleading.

## Steps to reproduce the problem.

See https://github.com/Toblerity/Fiona/blob/master/fiona/_env.pyx:

```python
log = logging.getLogger('rasterio._gdal')
```

## Fiona and GDAL version and provenance

Fiona 1.8b1

**Comment by sgillies** [comment]
Thanks for the report @Ariki !
