### ISSUE TITLE
Feedback on Fiona 1.8

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Fiona#647]
I tried Fiona 1.8a3 (now also doing 1.8b1) with geopandas, and all tests are passing (not that I expected this not to be the case). 
Just the existing tests, I didn't yet use new features.

So nothing critical, but some other minor feedback:

- There is a:

    ```
    /home/travis/miniconda/envs/test/lib/python3.7/site-packages/fiona/compat.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
      DICT_TYPES = (dict, collections.Mapping, UserDict)
    ```

  warning (that could already be solved)

- We get, as expected, the following warning:

    ```
    /home/travis/build/jorisvandenbossche/geopandas/geopandas/io/file.py:108: 
    FionaDeprecationWarning: Use fiona.Env() instead.
      with fiona.drivers():
    ```

  And the warning is very clear about what to do. But still, I think it might be useful to mention this deprecation in the CHANGES.txt, and give some reasoning for why this deprecation happens (to give it some context to users of it). 
  Sidenote: the `Env` object itself is also nowhere mentioned or explained in the user manual (but I think this was also true for the previous `drivers`, so not a new issue).

**Comment by sgillies** [comment]
Thanks, @jorisvandenbossche !
