### ISSUE TITLE
Writing shapefile: Fiona can't find/open EPSG support file gcs.csv

### ISSUE THREAD

**Issue by jens2121** [Toblerity/Fiona#656]
I am trying to write out a geodataframe to shapefile and having problems with defining the projection of the output. Geopandas gives me the warning about Fiona being unable to find the EPSG support file, and therefore posting on here and not Geopandas:

> ERROR:Fiona:CPLE_OpenFailed in b'Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.'

I am using a conda envs, activated the env,s and have made sure the file is available in the GDAL_DATA variable:
![image](https://user-images.githubusercontent.com/23120545/47437009-f84b6100-d7a7-11e8-934c-e3b3f1cc5b7b.png)

![image](https://user-images.githubusercontent.com/23120545/47437044-12853f00-d7a8-11e8-95ab-6ba678c6395c.png)

I am not quite sure why Fiona is not picking up the EPSG support file gcs.csv 

I'm using the following versions:
gdal 2.2.4
geopandas 0.4.0
fiona 1.7.13

Please can someone assist in debugging further. How do I determine which path Fiona is using and how can I change this?

Thanks in advance.

**Comment by sgillies** [comment]
I'm sorry @jens2121, but this is almost certainly a conda or conda-forge issue and we don't accept those in this issue tracker. I have seen similar reports 

https://github.com/conda-forge/gdal-feedstock/issues/111
https://github.com/geopandas/geopandas/issues/363

and it seems like creating a new conda environment using packages exclusively from the conda-forge channel usually clears up the problems.

**Comment by jens2121** [comment]
Many thanks Sean! Let me try that.

Best Regards,

Jens Hiestermann
GEOTERRAIMAGE




On Wed, Oct 24, 2018 at 4:41 PM +0200, "Sean Gillies" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #656<https://github.com/Toblerity/Fiona/issues/656>.

**Comment by kannes** [comment]
FYI since conda is just weird:

If you *still* get the error above on a fresh, modern conda installation with a fresh, modern fiona, you might just need to "turn it off and on again". Deactivate your environment and activate it again. Maybe also dance around the shell window (and close and open that). Afterwards try again, it might just work then. Magic!
