### ISSUE TITLE
Fiona 1.8: Env default options includes RASTERIO_ENV

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Fiona#665]
Not something critical I suppose, but I was wondering if the `Env.default_options` including a rasterio one is a left-over from porting the code from rasterio, or is left there on purpose:

https://github.com/Toblerity/Fiona/blob/4f764d50163ad6ee3b96021b8159a5d9a36a5945/fiona/env.py#L99-L103

I would think that in principle fiona is not aware of rasterio (noticed it from looking at the debug logs)

**Comment by sgillies** [comment]
Thanks for pointing this out @jorisvandenbossche ! The value isn't used for anything in Fiona (or Rasterio), it's in there as a marker to help a small number of users who are mixing this module with the GDAL bindings.
