### ISSUE TITLE
Document MemoryFile

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#674]
I just discovered that MemoryFile was added in 1.8a2, awesome!

However there is no sign of it in the documentation yet. And the docstring could use a minimal (more minimal than below) example.

Below is a small example using the https://fiona.readthedocs.io/en/latest/manual.html#writing-new-files-from-scratch data. Not sure if good or reasonable but at least it works. :o) If it looks good, I will turn it into doc prose.

Feels weird to open an instance of MemoryFile and getting what fiona.open would give for a regular file, and being able to write to that, just to use the normal fiona.open to read from it later. For me a `MemoryFile.prepare(...)` where you set up the meta, then `fiona.open(..., "w")` would sound more intuitive. But I guess the existing approach is how it is standard?

```
from collections import OrderedDict
import pprint

eiffel_tower =  {
 'geometry': {
   'type': 'Point',
   'coordinates': (448252, 5411935)
 },
 'properties': OrderedDict([
    ('name', 'Eiffel Tower'),
    ('height', 300.01),
    ('view', 'scenic'),
    ('year', 1889)
  ])
}

landmarks_schema = {
  'geometry': 'Point',
  'properties': OrderedDict([
    ('name', 'str'),
    ('height', 'float'),
    ('view', 'str'),
    ('year', 'int')
  ])
}

with MemoryFile() as mem_file:
    with mem_file.open(driver="GeoJSON", 
                       schema=landmarks_schema, 
                       crs=from_epsg(25831)) as mem_sink:
        pprint.pprint(mem_sink.meta)
        mem_sink.write(eiffel_tower)

    with fiona.open(mem_file) as mem_source:
        pprint.pprint(mem_source.meta)
        for record in mem_source:
            pprint.pprint(record)
```

**Comment by sgillies** [comment]
@kannes yes, that looks like a good example, minus the `pprint()` calls.

I'd like to standardize new code examples using https://black.now.sh. Does that work for you?

You can use MemoryFile in a slightly different style if you like.

```python
with MemoryFile() as memfile:
    with rasterio.open(
        memfile.name, "w", **kwargs
    ) as collection:
        collection.writerecords(sequence_of_features)
```

**Comment by sgillies** [comment]
Initial docs added in 5507d31.
