### ISSUE TITLE
Documentation link points to an old version

### ISSUE THREAD

**Issue by drnextgis** [Toblerity/Fiona#681]
I mean this link in the repository description:
![image](https://user-images.githubusercontent.com/866124/48613453-09912300-e98c-11e8-865f-7b191df41fda.png)

**Comment by jorisvandenbossche** [comment]
The same old link in the README is updated now (https://github.com/Toblerity/Fiona/pull/683). 

The new link I used there, and that can be used here as well: https://fiona.readthedocs.io/en/stable/

**Comment by jorisvandenbossche** [comment]
Thanks!
