### ISSUE TITLE
Should fiona support or error on NaNs? (GeoJSON)

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Fiona#684]
## Expected behavior and actual behavior.

Currently, when there is a NaN in the data, fiona silently writes invalid data:

```
schema = {'geometry': 'Point', 'properties': {'a': 'float'}}

features = [
    {'id': '0', 'type': 'Feature',
     'properties': {'a': None},
     'geometry': {'type': 'Point',
     'coordinates': (0.12, 0.47)}},
]

with fiona.Env():
    with fiona.open("test_nulls1.geojson", 'w', driver="GeoJSON", schema=schema) as colxn:
        colxn.writerecords(features)
```

The above works fine, but when replacing the `None` with `float('nan')`, the generated GeoJSON file is invalid:

```
schema = {'geometry': 'Point', 'properties': {'a': 'float'}}

features = [
    {'id': '0', 'type': 'Feature',
     'properties': {'a': float('nan')},
     'geometry': {'type': 'Point',
     'coordinates': (0.12, 0.47)}}
]

with fiona.Env():
    with fiona.open("test_nulls2.geojson", 'w', driver="GeoJSON", schema=schema) as colxn:
        colxn.writerecords(features)
```

The file has "NaN" inside the values instead of the GeoJSON "null", and reading fails:

```
>>> geopandas.read_file("test_nulls2.geojson")
...
CPLE_OpenFailedError: Failed to read GeoJSON data
...
DriverError: Failed to read GeoJSON data
```

Full code example: http://nbviewer.jupyter.org/gist/jorisvandenbossche/1ee416fad461655d3e3f787986d69cc3

I don't have a strong opinion about whether NaN should be supported in addition to None or not, but silently writing an invalid file does not seem ideal (if it is not supported I would expect an error). 

For other formats I tried (GeoPackage and Shapefile), the handling of NaN actually works (read back in correctly), so this seems specific to GeoJSON.

## Operating system, Fiona and GDAL version and provenance

Ubuntu 16.04, Fiona 1.8.1, installed with conda-forge

**Comment by rbuffat** [comment]
The same issue arises with infinity. According to the json specification (https://tools.ietf.org/html/rfc8259#section-6) nan and infinity are not permitted:

> Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.

**Comment by rbuffat** [comment]
@sgillies  Should we create a bug report upstream that gdal produces invalid geojson?

https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp#L1513-L1521

**Comment by rbuffat** [comment]
@rouault implemented a solution for the above mentioned issue in gdal. 

Starting from GDAL/OGR 2.4 the Geojson driver will read Nan and Infinity and per default skip these when writing (except if the Option WRITE_NON_FINITE_VALUES is set).

See https://github.com/OSGeo/gdal/commit/8d362556f7455a12964d67da1ee39d2af4da1c30
