### ISSUE TITLE
Unsuccessful geometry transformation should error, not return untransformed geometry

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#691]
Due to software being complicated, it is easy for people to end up with a mess of GDAL and PROJ and what-not paths not matching. If that happens, coordinate transformations will fail due to gdal(?) throwing errors like

```
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
```

Fiona does not treat those errors as more than messages (I assume they are printed by gdal, not Fiona). 

## Expected behavior and actual behavior.

Fiona will not fail and raise an exception but return the original geometry instead.

```
In [1]: from fiona.crs import from_epsg                                         

In [2]: from fiona.transform import transform_geom                              

In [3]: p = {'type': 'Point', 'coordinates': (10, 53.5)}                        

In [4]: transform_geom(from_epsg(4326), from_epsg(25832), p)                    
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
Out[7]: {'type': 'Point', 'coordinates': (10.0, 53.5)}
```

In a notebook this might look like this:

```
from fiona.crs import from_epsg                                         
from fiona.transform import transform_geom                              
p = {'type': 'Point', 'coordinates': (10, 53.5)}                        
transformed_p = transform_geom(from_epsg(4326), from_epsg(25832), p)
print(transformed_p)
```
printing

> {'type': 'Point', 'coordinates': (10.0, 53.5)}

If set up correctly, the result would be

> {'type': 'Point', 'coordinates': (566331.5281884326, 5928359.088136172)}

This behaviour is very bad and bound to lead to silent bugs since the error messages might not even be visible to the user (e.g. in a Jupyter Notebook they print to the shell where the notebook was launched).

If there is any way for Fiona to know about the issue, please raise an Exception!

**Comment by kannes** [comment]
No idea how Github handles notification but I submitted the issue too early and only added the content now. Posting this comment to notify about that. ;)

**Comment by sgillies** [comment]
@kannes I've been able to reproduce this by setting GDAL_DATA to a bogus value:

```
$ GDAL_DATA=/tmp/foo python
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fiona.crs import from_epsg
>>> from fiona.transform import transform_geom
>>> p = {'type': 'Point', 'coordinates': (10, 53.5)}
>>> transform_geom(from_epsg(4326), from_epsg(25832), p)
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 6: No translation for an empty SRS to PROJ.4 format is known.
{'type': 'Point', 'coordinates': (10.0, 53.5)}
```

The reason why GDAL error messages are escaping to the terminal is that you don't have any GDAL error handlers set up. This is done by configuring Python's logger and running your code within a `with fiona.Env():` block. 

```
>>> import logging
>>> logging.basicConfig()
>>> with fiona.Env():
...     transform_geom(from_epsg(4326), from_epsg(25832), p)
...
ERROR:fiona._env:Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR:fiona._env:Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR:fiona._env:No translation for an empty SRS to PROJ.4 format is known.
{'type': 'Point', 'coordinates': (10.0, 53.5)}
```

The tricky thing is that OGR doesn't necessarily consider the lack of a known transformation an error and by default will go on without it. I've talked to Even about this and he feels that once the user gets the support files configured, all these problems are solved. I mostly agree.

Mainly, the thing to do is get accustomed to executing Fiona's methods within an Env. Then you'll see something in Jupyter (which configures the logger) about support files not being found.
