### ISSUE TITLE
Create a groups.io discussion group for user support

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#704]
It's worked well for the Rasterio project and would be useful here.

**Comment by kannes** [comment]
Consider using gitter.im, it is open-source and nicely bridged to Matrix.

**Comment by sgillies** [comment]
No, I'm not interested in a chat platform. I recently wrote down my feelings about support chat at https://sgillies.net/2019/02/28/on-not-using-slack-for-open-source.html.

**Comment by kannes** [comment]
Ah sorry, I thought groups.io would be something like that. Totally agree about your verdict on real-time chat.

**Comment by sgillies** [comment]
Alright, I've created two groups: https://fiona.groups.io/g/main and https://fiona.groups.io/g/dev.

```
main@fiona.groups.io
Group Description
This list is dedicated usage and support for Fiona, an open source Python library for reading and writing geospatial vector data. 

dev@fiona.groups.io
Group Description
A group to discuss development of Fiona. Issues and proposals will be introduced and socialized here before taking actionable issues to GitHub. 
```

@snorfalorpagus @kannes @jorisvandenbossche @snowman2 @rbuffat @QuLogic I encourage you to subscribe. I'll edit the project readme to add links.

**Comment by jorisvandenbossche** [comment]
Thanks for creating those!
