### ISSUE TITLE
Slow crs transform

### ISSUE THREAD

**Issue by mayanksuman** [Toblerity/Fiona#706]
The transform function is slow (about 5 times) compared to similar function from `pyproj`.

## Steps to reproduce the problem.
```python
import numpy as np
import pyproj
from fiona.transform import transform 

_sc_code = [4676, 4752, 4760, 4322, 4324, 4748, 4011, 4012, 4016, 4022, 4041, 4133]
_dc_code = [4821,4326, 4296,4628,4003, 2397, 2436, 2507, 26916, 32247, 6700]
src_crs = ['epsg:%d'%num for num in _sc_code]
des_crs = ['epsg:%d'%num for num in _dc_code]

crs_comb = [[src, des] for src in src_crs for des in des_crs]

lat = np.linspace(-60,60,100)
lon = np.linspace(-60,60,100)

%%timeit
for src, des in crs_comb:
	transform(src, des, lon, lat)
# 27 ms ± 139 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%%timeit
for src, des in crs_comb:
	proj_in = pyproj.Proj('+init='+src, preserve_units=True)
	proj_out = pyproj.Proj('+init='+des, preserve_units=True)
	pyproj.transform(proj_in, proj_out, lon, lat)
# 5.42 ms ± 4.77 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

## Operating system
Debian GNU/Linux buster/sid (Linux 4.18.0)

## Fiona and GDAL version and provenance

Fiona 1.7.13 installed from PyPI using pip version 18.0.
GDAL 2.3.3+dfsg-1
pyproj 1.9.6

**Comment by sgillies** [comment]
Yes, I would expect the Fiona method to be more heavyweight. Profiling could tell us exactly what is slower. By the way, Fiona 1.7.x is no longer supported, but I'm sure the situation is the same in the latest 1.8.x release.

**Comment by sgillies** [comment]
I'm going to close this one. Fiona, which uses OGR – and PROJ indirectly, isn't going to be as fast as pyproj.
