### ISSUE TITLE
Fiona fails to read "crs" property from .gml file when .gfs file is present

### ISSUE THREAD

**Issue by tfotis** [Toblerity/Fiona#708]
## Expected behavior and actual behavior.

I expected to read the crs from a gml file

## Steps to reproduce the problem.

Open a .gml file with fiona and read the crs. It works correctly. You can see that after opening the .gml file, a .gfs file is created. Try to open the .gml file again and read the crs. It comes up empty.

## Operating system

Linux Mint 19

## Fiona and GDAL version and provenance

Fiona 1.8.4 installed with pip 18.1
GDAL 2.2.3

## Attached files ##

[bug.zip](https://github.com/Toblerity/Fiona/files/2763490/bug.zip)

**Comment by sgillies** [comment]
Yes, I can reproduce this issue with Fiona 1.8.4 and GDAL 2.3.2. How strange. However, I can also reproduce it with ogrinfo 

```
$ ogrinfo MSK_CLOUDS_B00.gml MaskFeature -so
Had to open data source read-only.
INFO: Open of `MSK_CLOUDS_B00.gml'
      using driver `GML' successful.

Layer name: MaskFeature
Geometry: Polygon
Feature Count: 132
Extent: (600000.000000, 4490220.000000) - (709800.000000, 4600020.000000)
Layer SRS WKT:
(unknown)
gml_id: String (0.0)
maskType: String (6.0)
```

This means that it is not a Fiona bug. I don't see any signs of it being fixed, and so I recommend that you report the issue at https://github.com/OSGeo/gdal/issues.

According to what I read at https://www.gdal.org/drv_gml.html, the .gfs file is only created if GDAL can't reach or parse the data's XML schema files, so you may want to check to see if they are online and are conforming.

**Comment by tfotis** [comment]
Thanks for looking into this.

I have reported the issue [here](https://github.com/OSGeo/gdal/issues/1210)
