### ISSUE TITLE
GDAL 2.4 is released

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#711]
GDAL 2.4 was released in December 2018. GDAL trunk is now 2.5.

https://trac.osgeo.org/gdal/wiki/DownloadSource

The change in version is causing the trunk build to fail:

https://ci.appveyor.com/project/sgillies/fiona/branch/master/job/nlt79is2r1ti5nps

As a minimum we should update this test to work with 2.5. We should also consider adding a test build for 2.4.

**Comment by rbuffat** [comment]
For Unix, also gdal 2.5 needs to be added to the mock_debian function in test__env.py. 

In the gdal 1.8 compatibility PR https://github.com/Toblerity/Fiona/pull/696 I changed the function (https://github.com/Toblerity/Fiona/blob/master/tests/test__env.py#L31-L38) to 
`tmpdir.ensure("share/gdal/{}.{}/pcs.csv".format(gdal_version.major, gdal_version.minor))`, this would provide a more future proof variant (as long the path does not change over time).

**Comment by sgillies** [comment]
Resolved in 460da10.
