### ISSUE TITLE
[proposal] Add support for metadata read/write for GeoPackage

### ISSUE THREAD

**Issue by snowman2** [Toblerity/Fiona#713]
One feature that I think would be particularly useful is reading/writing metadata in GeoPackage files. I have seen that this is supported in [gdal python tests](https://trac.osgeo.org/gdal/browser/trunk/autotest/ogr/ogr_gpkg.py#L1653). However, I don't see it in the Fiona package. If it is already there and I missed it, feel free to point it out to me.

Is this a feature that you would be interested in? If so, I would be willing to create a prototype of a potential solution we could iterate on.

**Comment by sgillies** [comment]
@snowman2 yes, this would be a fine addition. I think the tags and get_tag_item methods in rasterio._base.DatasetBase could be a useful example.

**Comment by snowman2** [comment]
Great, I will try to make time for this.
