### ISSUE TITLE
[proposal] Add CRS class similar to the CRS in rasterio

### ISSUE THREAD

**Issue by snowman2** [Toblerity/Fiona#714]
Are there plans to update the CRS functionality in fiona to match the current version in rasterio?

**Comment by sgillies** [comment]
@snowman2 I consider it a must do for the next release, but haven't begun work on it.

**Comment by snowman2** [comment]
Good to hear 👍

**Comment by sgillies** [comment]
@snowman2 one thing to keep in mind: we'll need to coordinate with @jorisvandenbossche and the geopandas team to make sure that we don't cause trouble like we did for xarray: https://github.com/pydata/xarray/pull/2715. I would have advised the xarray project not to bind itself to the microformatting of CRS.to_string, we should do a check that geopandas isn't doing the same thing.

**Comment by jorisvandenbossche** [comment]
Currently, we rely on fiona's CRS in one place in `geopandas.read_file`, where we assume that the `crs` attribute of a Collection is a proj4-like dictionary.

I assume the idea would be that this would become a actual CRS class? Although this seems less backwards compatible than the change in rasterio where there was already such a class before as well (as far as I know fiona has not yet such a class but just works with a proj4 dict, at least as user interface?)

In any case, as long as we are aware of it in advance, we can easily add code in GeoPandas to do the correct thing depending on the Fiona version.

**Comment by sgillies** [comment]
@jorisvandenbossche @snowman2 I just submitted https://github.com/geopandas/geopandas/pull/913 to give geopandas more compatibility. Yes? No?

**Comment by snowman2** [comment]
@sgillies, I know you have many things you are working on, so if it would be useful for me to work on an implementation (or just a part of it), just let me know and I would be happy to help out.

**Comment by snowman2** [comment]
Thanks @sgillies 👍
