### ISSUE TITLE
Support for Python 2.x

### ISSUE THREAD

**Issue by snorfalorpagus** [Toblerity/Fiona#716]
Python 2.7 is reaching End Of Life and will no longer be supported by PSF from 1st January, 2020 (11 months from now).

* https://www.python.org/dev/peps/pep-0373/
* https://github.com/python/devguide/pull/344

We should have a plan for how we're going to handle support in Fiona (and related projects).

Could Fiona 1.8 be the last release that supports 2.x?

Relevant to #715.

**Comment by snowman2** [comment]
Should a similar issue be created for rasterio?

**Comment by sgillies** [comment]
@snorfalorpagus what would you think about dropping 2.7 from the appveyor build matrix instead of spending time solving that issue?

**Comment by sgillies** [comment]
Python 2.7 has been removed from both Appveyor and Travis-CI configuration files.
