### ISSUE TITLE
Please subclass DeprecationWarning for FionaDeprecationWarning

### ISSUE THREAD

**Issue by darrenleeweber** [Toblerity/Fiona#719]
RE https://github.com/Toblerity/Fiona/blob/master/fiona/errors.py

Please subclass `DeprecationWarning` to enable module level manipulation for third-party consumers who want to silence nagging warnings they have no control over, e.g. enable
```python
import warnings
warnings.filterwarnings(
    action='ignore',
    category=DeprecationWarning,
    module=r'geopandas\.io\.file'
)
```

**Comment by darrenleeweber** [comment]
For the googlers who might land here, this worked OK:
```python
import warnings
from fiona.errors import FionaDeprecationWarning
warnings.filterwarnings(
    action='ignore',
    category=FionaDeprecationWarning,
    module=r'geopandas\.io\.file'
)
```

**Comment by sgillies** [comment]
I think the situation here is different from the situation with deprecation warnings coming from the standard library and I'd like to keep the warnings visible to GeoPandas developers. I'm not yet aware of Fiona being so deep in anyone's stack that warnings can't be addressed. Will close if you don't mind.
