### ISSUE TITLE
Web source for proj.4 genparms is gone

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#730]
https://github.com/Toblerity/Fiona/blob/f2d4a6219eafc9e9bab3fd9c0fc466c4da2b2bd1/fiona/crs.py#L71 mentions http://trac.osgeo.org/proj/wiki/GenParms as source for a list of strings. That page is gone, I could not find a new location. https://proj4.org/usage/projections.html has some but just a sample.

Web Archive link: http://web.archive.org/web/20161211005523/http://trac.osgeo.org/proj/wiki/GenParms

I did not edit+PR  anything because I am not sure how the recent developments in proj might have affected these things, maybe this whole thing needs reworking soon anyways? :)

**Comment by sgillies** [comment]
I think the thing to do is remove link and, yes, begin to play down the old PROJ4 parameters. Fiona will switch over to WKT like Rasterio, soon, and eventually to WKT 2.

**Comment by sgillies** [comment]
This was resolved while making fiona.crs an extension module (pre-1.9.0).
