### ISSUE TITLE
GDAL version not being found when using GDAL_CONFIG=

### ISSUE THREAD

**Issue by BradCook** [Toblerity/Fiona#735]
Hi.

I am trying to get Fiona to install against a specific install of gdal, but it isn't picking up the correct gdal. I am following the instructions on the README and using the `GDAL_CONFIG=/path/to/config pip install fiona`, but that GDAL version is not being picked up. I've tried the building from source option but got the same result.

## Steps to reproduce the problem.

Here the setup (It assumes osgeo4mac tap has already been added):

```
$ brew install gdal osgeo-filegdb-api osgeo-gdal-filegdb

$ GDAL_CONFIG=/path/to/gdal-config pip install fiona

$ python
Python 3.6.6 (default, Dec  3 2018, 13:18:09)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>> fiona.supported_drivers
{'AeronavFAA': 'r', 'ARCGEN': 'r', 'BNA': 'raw', 'DXF': 'raw', 'CSV': 'raw', 'OpenFileGDB': 'r', 'ESRI Shapefile': 'raw', 'GeoJSON': 'rw', 'GPKG': 'rw', 'GML': 'raw', 'GPX': 'raw', 'GPSTrackMaker': 'raw', 'Idrisi': 'r', 'MapInfo File': 'raw', 'DGN': 'raw', 'S57': 'r', 'SEGY': 'r', 'SUA': 'r'}
```

When I install the GDAL python bindings though (through `pip install gdal`), it does find the gdal.

```
$ python
Python 3.6.6 (default, Dec  3 2018, 13:18:09)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import ogr
>>> for i in range(ogr.GetDriverCount()):
... 	print(ogr.GetDriver(i).GetDescription())
...
FileGDB
PCIDSK
netCDF
JP2OpenJPEG
JPEG2000
MBTiles
EEDA
ESRI Shapefile
MapInfo File
UK .NTF
OGR_SDTS
S57
DGN
OGR_VRT
REC
Memory
BNA
CSV
NAS
GML
GPX
LIBKML
KML
GeoJSON
GeoJSONSeq
ESRIJSON
TopoJSON
Interlis 1
Interlis 2
OGR_GMT
GPKG
SQLite
OGR_DODS
ODBC
WAsP
PGeo
MSSQLSpatial
PostgreSQL
OpenFileGDB
XPlane
DXF
CAD
Geoconcept
GeoRSS
GPSTrackMaker
VFK
PGDUMP
OSM
GPSBabel
SUA
OpenAir
OGR_PDS
WFS
WFS3
HTF
AeronavFAA
Geomedia
EDIGEO
GFT
SVG
CouchDB
Cloudant
Idrisi
ARCGEN
SEGUKOOA
SEGY
XLS
ODS
XLSX
ElasticSearch
Walk
Carto
AmigoCloud
SXF
Selafin
JML
PLSCENES
CSW
VDV
GMLAS
MVT
TIGER
AVCBin
AVCE00
NGW
HTTP
```

## Operating system

This is done on a Mac OS X 10.13.6 (High Sierra).

## Fiona and GDAL version and provenance

Fiona version is 1.8.4.
GDAL version I'm trying to install against is 2.4.0
GDAL version Fiona is installing against is 2.3.2.

GDAL 2.4.0 installed via Homebrew. GDAL 2.3.2 was also installed via Homebrew, but it has since been removed by `brew cleanup`. 

All python packages were installed in a python virtualenv

**Comment by sgillies** [comment]
@BradCook `GDAL_CONFIG=/path/to/gdal-config` was not meant literally, you must put the path to the actual GDAL 2.4.0 gdal-config program that you brew installed. That's probably /usr/local/bin/gdal-config.

**Comment by BradCook** [comment]
@sgillies I am aware of that, in the issue I just put down a indicative/dummy path because i couldn't remember the exact path when I wrote the issue. Although I should've put it in square brackets to make it clear that what I entered in was the actual path to gdal-config, not literally `/path/to/gdal-config`. 

I've updated the issue to show the path I actually did enter in, and that was found using
```
$ which gdal-config
/usr/local/bin/gdal-config. 
```

**Comment by sgillies** [comment]
Oh, are you interpreting the smaller number of drivers as the wrong GDAL being found by fiona's setup script? I can see how you could come to that conclusion. Fiona has historically not turned on many of OGR's possible format drivers because in 1.0, Fiona did not support multilayer formats. We're enabling formats as needed in https://github.com/Toblerity/Fiona/blob/master/fiona/drvsupport.py#L13.

Remember, too, that pip will use the platform wheels (.whl files) from https://pypi.org/project/Fiona/1.8.6/#files by default and that these .whl distributions contain their own copy of GDAL. To strictly use your own system GDAL, you must pass a `--no-binary fiona` option to pip: `GDAL_CONFIG=/usr/local/bin/gdal-config pip install --no-binary fiona fiona`.

**Comment by BradCook** [comment]
I was also seeing `fio --gdal-version` returning `2.3.2`, while `gdal-config --version` returning `2.4.0`, so that was an extra reason. But a pre-packaged GDAL in the whl makes sense, thought something like that might be the case.

`--no-binary` option did the trick though, cheers. Is that something that should be in the install instructions on the README? Perhaps others might want to use Fiona against a specific system GDAL, such as the one their QGIS (for example) is compiled against.
