### ISSUE TITLE
Fiona 1.8.5 supported_drivers Missing GeoJSONSeq, ESRIJSON, and TopoJSON

### ISSUE THREAD

**Issue by youngpm** [Toblerity/Fiona#736]
The fix for #720 and #721  ([this commit)](https://github.com/Toblerity/Fiona/commit/c66db9d5894f34d1b068bf14acf0136092f80b21) doesn't look like it made it into 1.8.5, but I see it in the release notes as added.  I pulled 1.8.5 down from PyPi and I see:
```
>>> import fiona
>>> fiona.drvsupport.supported_drivers
{'AeronavFAA': 'r', 'ARCGEN': 'r', 'BNA': 'raw', 'DXF': 'raw', 'CSV': 'raw', 'OpenFileGDB': 'r', 'ESRI Shapefile': 'raw', 'GeoJSON': 'rw', 'GPKG': 'rw', 'GML': 'raw', 'GPX': 'raw', 'GPSTrackMaker': 'raw', 'Idrisi': 'r', 'MapInfo File': 'raw', 'DGN': 'raw', 'S57': 'r', 'SEGY': 'r', 'SUA': 'r'}
```

It's in master but not the 1.8 maintenance branch, but I'm not positive which branch is used for wheel building.

I tried this on osx and linux so I'm guessing it's missing from all the wheels; not sure if that means other fixes didn't make it either!

## Expected behavior and actual behavior.

For example: I expected to read 10 features from a file and an exception occurred
on the 3rd.

## Steps to reproduce the problem.

For example: a script with required data.

## Operating system

For example: Mac OS X 10.12.3.

## Fiona and GDAL version and provenance

For example: the 1.7.10.post1 manylinux1 wheel installed from PyPI using pip version 9.0.1.

For example: GDAL 2.1.0 installed via Homebrew

**Comment by sgillies** [comment]
🤦‍♂️ 

1.8.6 coming up.

**Comment by youngpm** [comment]
🙇
