### ISSUE TITLE
GPKG writing slow when using write() loop

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#740]
## Expected behavior and actual behavior.

I am writing 300,000 features to a file. Depending on the driver, the performance of a write() loop is vastly different from a writerecords() call.

|                | ESRI Shapefile | GeoJSON | GeoPackage |
|----------------|----------------|---------|------------|
| write() loop   | 16             | 28      | **62**         | 
| writerecords() | 16             | 20      | 20         | 

I noticed this when writing onto a slow USB stick, so probably there is no buffering of the GeoPackage .write() calls. That totally makes sense but I had assumed Fiona did some magic buffering in the background. After all, the docs say in https://fiona.readthedocs.io/en/latest/manual.html#appending-data-to-existing-files:

> ### Buffering
> 
> Fiona’s output is buffered. The records passed to write() and writerecords() are flushed to disk when the collection is closed. You may also call flush() periodically to write the buffer contents to disk.

The GeoJSON result is also almost 50% slower with a loop than with writerecords(), as that is not as drastic as with GPKG I did not focus on it.

## Steps to reproduce the problem.

Write lots of features... :B
Sorry, no time for writing a shareble example right now.

```
for feature in features:
  output.write(feature)
```
vs
```
output.writerecords(features)
```

## Proposed fix

If the magick buffering is missing for GPKG (and others?), that should be fixed. If there is no way to do that, the docs should mention that in the note mentioned above.

## Operating system

Archlinux

## Fiona and GDAL version and provenance

Fiona from Pypi:
```
    $ pip freeze | grep Fiona
    Fiona==1.8.6
```

gdal from Archlinux repositories:
```
$ aurman -Qs gdal
community/gdal 2.3.2-11 [installed]
community/python-gdal 2.3.2-11 [installed]
community/python2-gdal 2.3.2-11 [installed]
```

**Comment by sgillies** [comment]
The reason why

```python
for feature in features:
  output.write(feature)
```

is slower than 

```python
output.writerecords(features)
```

Is that there is one geopackage transaction within each write call and only one per 20,000 features within each writerecords call.

I expect the following code to be just as slow as your first example, demonstrating that the transactions are the culprit.

```python
for feature in features:
  output.writerecords([feature])
```

Transactions in the GeoJSON are less costly because they do nothing in comparison to the geopackage transactions, but they do have a noticeable overhead.

**Comment by kannes** [comment]
That's what I assumed.

So the buffering mentioned in the docs is really just about file integrity? Buffering is the first thing I look for when writing something is slow that's why I assumed it to be relevant here.

**Comment by sgillies** [comment]
I mention buffering to warn users about the state of the output file in the (rare) case that they have opened it multiple times: writes from one collection object won't necessarily appear immediately in the file and be available from a second opened collection.
