### ISSUE TITLE
Support milliseconds for time / datetime types

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/Fiona#744]
Fiona is currently using `OGR_F_GetFieldAsDateTime` to get the values to construct date/time/datetime values:

https://github.com/Toblerity/Fiona/blob/be02274a53da81a68eb92d5c2a4d7a163ebb1e23/fiona/ogrext.pyx#L241-L243

By using `OGR_F_SetFieldDateTimeEx` (https://www.gdal.org/ogr__api_8h.html#a748995fa28574b25f6b723013a405a8f), it could support milliseconds (the only difference between both is that the `&ss` seconds is now a float instead of int.

Would this be a welcome change?

**Comment by sgillies** [comment]
Yes @jorisvandenbossche this would be very welcome.

**Comment by rbuffat** [comment]
Support for milliseconds is introduced with Fiona 1.8.14

**Comment by jorisvandenbossche** [comment]
This was implemented in #893, so I think this can be closed?
