### ISSUE TITLE
Thoughts about improving travis

### ISSUE THREAD

**Issue by rbuffat** [Toblerity/Fiona#747]
Fiona should work for a range of different gdal versions, which we want to ensure by testing fiona against them on CI such as travis and appveyor.  While on appveyor we can use prebuilt binaries of gdal, we compile gdal from source on travis. The reason for that is that the standard ubuntu repository, respectively PPA such as UbuntuGIS only contain specific versions of gdal, which we can not control. Compiling GDAL, again and again, is a waste of time and resources. Although the impact of this is mitigated by caching the compiled binaries. However, for certain scenarios, such as new branches, new PR or previously failed jobs, this is not possible.

A solution would be to create prebuilt binaries of gdal and related libraries, such as proj.4 on our own. The question is, what would be the best way to do it? I can think of a few alternatives, but I'm not knowledgable in any of them:
- Creating a specific PPA with packages prebuilt binaries for the travis image we currently use. I'm not sure if we can have multiple versions of the same package in the same PPA and install a specific version. Furthermore, for me at least, building packages for Launchpad does not look straight forward. It looks as @sebastic has some experience with debian packages, maybe he can provide some insights.  
- Building binaries with travis in a separate github project and deploy the gdal binaries as release artifacts. This would probably be kind of a misuse of releases.
- Instead of deploying to github deploying to S3.

**Comment by sebastic** [comment]
If you don't need packages for other architectures than amd64 (and i386), I would setup a custom package repository with reprepro for the various branches on GDAL you want to support, and add this repo to Travis.

If you need other architectures like arm*, Launchpad is a better option.

**Comment by rbuffat** [comment]
@sebastic Thanks! I will look into if I can manage to build something with reprepro, travis and github pages.
