### ISSUE TITLE
Is there a way to check for the existence of a shapefile in a ZipMemoryFile before trying to open the shapefile?

### ISSUE THREAD

**Issue by john-a-m** [Toblerity/Fiona#753]
Right now I'm doing something like this

    with ZipMemoryFile(download_zipfile(url)) as zip_file:
        for file_name in SHAPEFILES:
            try:
                zipped_file = zip_file.open(file_name)
            except fiona.errors.DriverError:
                print "File: {} was not found in ZIP file.".format(file_name)
                continue

however some part of fiona is still writing an error message out.

`ERROR 4: '/vsizip/vsimem/6260dee7-161c-4a34-82bb-e10cab1c06e5.zip/shape.shp' does not exist in the file system, and is not recognized as a supported dataset name.`

**Comment by sgillies** [comment]
@john-a-m no, not at the moment, though you can work around this with Python's zipfile module.

```python
>>> data = open('tests/data/coutwildrnp.zip', 'rb').read()
>>> zf = zipfile.ZipFile(io.BytesIO(data))
>>> zf.namelist()
['coutwildrnp.shp', 'coutwildrnp.shx', 'coutwildrnp.dbf', 'coutwildrnp.prj']
```

We should provide methods to list and access the multiple datasets that may be in a zip file in a future release, for sure. 

The error message is written by the GDAL library and you see it if there is no GDAL error handler configured. Running your code with a `with fiona.Env()` will set up the handlers.
