### ISSUE TITLE
please add Python-3.8 in AppVeyor

### ISSUE THREAD

**Issue by stonebig** [Toblerity/Fiona#763]
I fail to compile it myself

**Comment by stonebig** [comment]
targeting GDAL-3.0.0 along the way may be nice

**Comment by stonebig** [comment]
needed to get latest ipyleaflet working in Python-3.8

**Comment by rbuffat** [comment]
@stonebig Fiona currently does not (yet) support gdal 3.0, see https://github.com/Toblerity/Fiona/issues/745 

On travis / linux, fiona builds with Python 3.8.0b1+ with cython 0.29.10 (however, it fails to compile with version 0.28.3 specified in requirements-dev.txt). Regarding appveyor, I'm not sure if Python 3.8 is already available on Appveyor.

**Comment by stonebig** [comment]
ok, I workarounded the problem by downgrading from ipyleaflet-0.10.4 to ipyleaflet-0.10.2 that doesn't requires geopandas and so, fiona.
