### ISSUE TITLE
ImportError in Python 3.7.3 on Windows 10.

### ISSUE THREAD

**Issue by purpleskyfall** [Toblerity/Fiona#765]
## Expected behavior and actual behavior.

ImportError in Python 3.7.3 on Windows 10. 
## Steps to reproduce the problem.

I have installed `GDAL‑3.0.0‑cp37‑cp37m‑win_amd64.whl` and `Fiona‑1.8.6‑cp37‑cp37m‑win_amd64.whl` from <https://www.lfd.uci.edu/~gohlke/pythonlibs/>, Also, installed `GDAL-3.0.0.win-amd64-py3.7.msi`  and `gdal-300-1911-x64-core.msi`, then add the GDAL folder (`C:\Program Files\GDAL`, `C:\Program Files\GDAL\gdal-data`) into `PATH` environment variable.

But I still got the ImportError:

```
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\yingming.jiang\AppData\Local\Programs\Python\Python37\lib\site-packages\fiona\__init__.py", line 87, in <module>
    from fiona.collection import BytesCollection, Collection
  File "D:\Users\yingming.jiang\AppData\Local\Programs\Python\Python37\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: 找不到指定的模块。
```

## Operating system

Windows 10, 17763.437

## Fiona and GDAL version and provenance

`GDAL‑3.0.0‑cp37‑cp37m‑win_amd64.whl` and `Fiona‑1.8.6‑cp37‑cp37m‑win_amd64.whl` from <https://www.lfd.uci.edu/~gohlke/pythonlibs/>

**Comment by sgillies** [comment]
Fiona and GDAL 3 don't work together yet, it's a known problem. Thank you for the report. I added a note about the required GDAL versions in https://github.com/Toblerity/Fiona/commit/0fd1e297c85a0462b35ed8b44c578528d6741739.

**Comment by rbuffat** [comment]
@purpleskyfall Please understand that the files from https://www.lfd.uci.edu/~gohlke/pythonlibs/ are not supported here on this issue tracker. 

Nevertheless, I think the solution for your problem is that you didn't install GDAL wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal, as mentioned under https://www.lfd.uci.edu/~gohlke/pythonlibs/#fiona.
