### ISSUE TITLE
fiona.listlayers() does not accept Path objects

### ISSUE THREAD

**Issue by joehuanguf** [Toblerity/Fiona#768]
## Expected behavior and actual behavior.

I attempted to read the layers of a pathlib.Path object. However, it would not accept the object. I had to convert the object to a string. Since fiona.open() accepts Path objects, this seems inconsistent.

## Steps to reproduce the problem.

Pass a pathlib.Path object to fiona.listlayers()

## Operating system

For example: Mac OS X 10.12.3.

## Fiona and GDAL version and provenance

Fiona 1.8.6

**Comment by joehuanguf** [comment]
I'm willing to write a quick PR fixing this if people are interested.

**Comment by sgillies** [comment]
Totally interested @joehuanguf !

**Comment by joehuanguf** [comment]
> Totally interested @joehuanguf !

I created a PR here:  #769
