### ISSUE TITLE
Overwriting GeoJSON logs an ERROR but succeeds

### ISSUE THREAD

**Issue by kannes** [Toblerity/Fiona#771]
## Expected behavior and actual behavior.

Overwriting a GeoJSON file results in a `logging` error message about the file not existing.

## Steps to reproduce the problem.

Same example code as in https://github.com/Toblerity/Fiona/issues/438#issuecomment-343154689 but with logging enabled.

```
import logging

logging.basicConfig(
    level=logging.INFO,
)

import fiona
from fiona.crs import from_epsg
from shapely.geometry import Point, mapping

schema = {
    "geometry": "Point",
    "properties": {"id": "int"}
}

feature = {
    "geometry": mapping(Point(0,0)),
    "properties": {"id": "0"}
}

for i in range(2):
    with fiona.open("/tmp/test.geojson", "w", 
                    driver="GeoJSON",
                    schema=schema, 
                    crs=from_epsg(4326)) as sink:
        sink.write(feature)
        print(f"Write #{i+1} succeeded")
```

results in

```
Write #1 succeeded
ERROR:fiona._env:/tmp/test.geojson: No such file or directory
WARNING:fiona._env:driver GeoJSON does not support creation option ENCODING
Write #2 succeeded
```

The error message is false. The file exists after the first successful write. At least from my user perspective.

## Operating system

Archlinux

## Fiona and GDAL version and provenance

gdal 3.0.0-2 from Archlinux repositories.
Fiona 1.8.6 via pip.

**Comment by sgillies** [comment]
Thanks for the report, @kannes. When the `with` block ends, the file is definitely flushed to disk and will exist. I'll look into correcting the error message.
