### ISSUE TITLE
M Values in Shapefile aren't shown

### ISSUE THREAD

**Issue by alexmahrou** [Toblerity/Fiona#774]
## Expected behavior and actual behavior.

I have an M-Enabled Linestring Shapefile, and I've verified the x,y,m coordinates in a GIS. However upon bringing this into fiona and querying it, I only see the x,y. I plan to write this to postgis, but I'm concerned that the m values will not be preserved. Is there a way to ensure recognition of M values within fiona?

## Steps to reproduce the problem.

fiona.open(shp)
pprint.pprint(next(shp)['geometry']) yields only x and y.
![image](https://user-images.githubusercontent.com/10987392/61474643-4ca1fc80-a946-11e9-9ea2-a5591e8bd9d9.png)

## Operating system

Windows 10 conda virtual env.

## Fiona and GDAL version and provenance

gdal_version = 2.4.1
fiona = 1.8.6

**Comment by sgillies** [comment]
@alexmahrou Fiona 1.x doesn't support M geometry types. It's on the radar for 2.0. Meanwhile, I recommend shp2pgsql or some other classic tool.

**Comment by alexmahrou** [comment]
Thanks @sgillies  I appreciate your response! I'll give that a whirl for sure.
