### ISSUE TITLE
MapInfo geometry precision

### ISSUE THREAD

**Issue by adrianaksan** [Toblerity/Fiona#777]
Unable to write MapInfo->MapInfo file as Fiona truncates the precision of the geometry to 2 decimal places. 

Have tried Python 2.7.x with Fiona 1.8.6 and GDAL 2.1.3. Same issue for Python 3.7.4 with Fiona 1.8.6 and GDAL 2.4.1. 

If I write MapInfo-> GeoJson the geometry precision is retained.

Second and unrelated issue with copying the schema from MapInfo files where column type is "int", I'm having to modify the string to "int:-1" as otherwise I see a schema error:

SchemaError: IMapInfoFile::CreateField() called with unsupported field type 12. Note that Mapinfo files don't support list field types.

**Comment by snorfalorpagus** [comment]
@adrianaksan Could you provide a small code sample that demonstrates the problem(s)?

**Comment by adrianaksan** [comment]
#!python3
import fiona

#
def read_tab_files(file_path):

    """
    :param file_path: TAB file path
    :return: TAB files data as list of ordered dict
    """

    data = []
    with fiona.open(file_path) as data_source:
        meta = data_source.meta
        data.extend(data_source)
    #
    return data, meta


#
def write_layer_changes(layer_name, layer, metadata):

    # schema details
    driver = metadata["driver"]
    schema = metadata["schema"]

    # broken schema fix
    for each in schema["properties"]:
        if schema["properties"][each] == "int":
            schema["properties"][each] = "int:-1"

    # multi geometry issues in cable layer
    if layer_name == "new_cable":
        schema["geometry"] = ["LineString", "MultiLineString"]
        
    #
    output_layer_path = '{}.tab'.format(layer_name)

    # write to MapInfo # srs=srs
    with fiona.open(output_layer_path, 'w', driver="MapInfo File", schema=schema) as dst:

        for each_row in layer:
            dst.write(each_row)

if __name__ == "__main__":

    output, metadata = read_tab_files("cable.TAB")
    write_layer_changes("new_cable", output, metadata)

**Comment by adrianaksan** [comment]
> 
> 
> #!python3
> import fiona
> 
> def read_tab_files(file_path):
> 
> ```
> """
> :param file_path: TAB file path
> :return: TAB files data as list of ordered dict
> """
> 
> data = []
> with fiona.open(file_path) as data_source:
>     meta = data_source.meta
>     data.extend(data_source)
> #
> return data, meta
> ```
> 
> def write_layer_changes(layer_name, layer, metadata):
> 
> ```
> # schema details
> driver = metadata["driver"]
> schema = metadata["schema"]
> 
> # broken schema fix
> for each in schema["properties"]:
>     if schema["properties"][each] == "int":
>         schema["properties"][each] = "int:-1"
> 
> # multi geometry issues in cable layer
> if layer_name == "new_cable":
>     schema["geometry"] = ["LineString", "MultiLineString"]
>     
> #
> output_layer_path = '{}.tab'.format(layer_name)
> 
> # write to MapInfo # srs=srs
> with fiona.open(output_layer_path, 'w', driver="MapInfo File", schema=schema) as dst:
> 
>     for each_row in layer:
>         dst.write(each_row)
> ```
> 
> if **name** == "**main**":
> 
> ```
> output, metadata = read_tab_files("cable.TAB")
> write_layer_changes("new_cable", output, metadata)
> ```

**Comment by adrianaksan** [comment]
Oops accidentally closed. Code attached. Cheers.

**Comment by adrianaksan** [comment]
As you can see above, I'm having to patch up some problems with reading the MapInfo schema:

1. Mixed geometry is not being read correctly by Fiona's .meta function.
2. "int" data types are not being read correctly by Fiona's .meta function.

I'm not modifying the .tab file, simply reading the file and then writing the output. The layer is a mixed geometry type ["Linestring", "Multi-linestring"].

**Comment by adambasile** [comment]
I was experiencing this problem as well and what fixed it for me was specifying a crs with "crs=" in the call to fiona.open()

**Comment by adrianaksan** [comment]
Awesome @adambasile, thanks for that. Worked for me too. I guess I shouldn't be surprised that the argument must be a string.
