### ISSUE TITLE
fiona.collection logging behaviour

### ISSUE THREAD

**Issue by EvertEt** [Toblerity/Fiona#780]
## Expected behavior and actual behavior.

I would expect the following log to dissapear when setting the level to `WARNING` on `fiona.collection`.
`[/Users/evert/Documents/Sitemark/sitemark-processingslave/venv3.7/lib/python3.7/site-packages/fiona/collection.py ; 2019-08-05 18:24:49,476 ; DEBUG] Index: 0`

The first line has no impact whereas the second one actually hides the log message.
`logging.getLogger("fiona.collection").setLevel(logging.WARNING)`
`logging.getLogger("fiona").setLevel(logging.WARNING)`

I could not find the source of this debug log message in the source code.

## Steps to reproduce the problem.

Load a collection label file while applying the logging code above.

## Operating system

For example: Mac OS X 10.14.5.

## Fiona and GDAL version and provenance

GDAL==2.4.0, pip installed
fiona==1.8.6, pip installed

**Comment by sgillies** [comment]
That log message actually comes from the fiona.ogrext extension module: https://github.com/Toblerity/Fiona/blob/maint-1.8/fiona/ogrext.pyx#L1339. I'm not sure why the logger reports fiona.collection in your case. Setting the level for the entire fiona namespace is a good solution.
