### ISSUE TITLE
Can't be installed on Win10 with Python 3.7

### ISSUE THREAD

**Issue by mobigroup** [Toblerity/Fiona#783]
## Expected behavior and actual behavior.

Fiona installation via pip requires file python37.lib does not exist in Python 3.7 distributive and installation.

## Steps to reproduce the problem.

```
pip3.7 install fiona
...
    LINK : fatal error LNK1104: cannot open file 'python37.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1104
```

## Operating system

Windows 10

## Fiona and GDAL version and provenance

Python 3.7.0 and GDAL 2.4.1 and fiona 1.8.6 and previous versions too.

**Comment by sgillies** [comment]
We don't have any windows distributions on PyPI. Please see https://github.com/Toblerity/Fiona/blob/master/README.rst#windows for installation for Windows. The Anaconda Python distribution and conda-forge is another good solution.
