### ISSUE TITLE
Fiona seems to be broken 

### ISSUE THREAD

**Issue by Isaquedanielre** [Toblerity/Fiona#786]
hello, I'm trying to use fiona in miniconda and anaconda python last 3 days and all are getting the same error when running from a python script running by calling, the fiona seems not find the files. However the files are there and when I try open manually direct in python in the linux console it works.  

I try about files permissions and others modifications. Non of them work. 

I only can use normally my code in a old environment which the entire python is one version behind. 

The error 

Traceback (most recent call last):
  File "fiona/_shim.pyx", line 66, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 259, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: /home/CEOS/DATACENTER/GEOJSON_POLYGONS/polygon_23_0xdEBc673a65b1840deb772FDB836A4979eC51f972.shp : No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ConvertDappPolygons.py", line 185, in <module>
    convertDappPolygons()
  File "ConvertDappPolygons.py", line 176, in convertDappPolygons
    FunctionsPostgresqlControl.datapathandrowbypolygon(polygonStrSave)
  File "/home/CEOS/ceos_central/FunctionsPostgresqlControl.py", line 1200, in datapathandrowbypolygon
    SentinelPathRowList = FunctionsAuxiliary.SelectPathAndRowSentinel(polygonFileStr)
  File "/home/CEOS/ceos_central/FunctionsAuxiliary.py", line 1276, in SelectPathAndRowSentinel
    polygonFile = gpd.read_file(polygonFileStr, encoding="UTF-8")
  File "/opt/miniconda3/lib/python3.7/site-packages/geopandas/io/file.py", line 71, in read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/opt/miniconda3/lib/python3.7/site-packages/fiona/env.py", line 396, in wrapper
    return f(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/fiona/__init__.py", line 253, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/fiona/collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 467, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 73, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: /home/CEOS/DATACENTER/GEOJSON_POLYGONS/polygon_23_0xdEBc673a65b1840deb772FDB836A4979eC51f972.shp : No such file or directory

My environment: Miniconda3

# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
affine                    2.3.0                    pypi_0    pypi
anaconda-clean            1.1.0                    py37_1  
asn1crypto                0.24.0                   py37_0  
attrs                     19.1.0                     py_0    conda-forge
awscli                    1.16.237                 py37_0    conda-forge
beautifulsoup4            4.8.0                    py37_0  
blas                      1.0                         mkl  
boost-cpp                 1.67.0               h14c3975_4  
boto3                     1.9.199                    py_0  
botocore                  1.12.227                   py_0    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.14.12              h8948797_3  
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.12.3           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
click                     7.0                      pypi_0    pypi
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                    pypi_0    pypi
colorama                  0.3.9                    py37_0  
conda                     4.7.12                   py37_0    conda-forge
conda-package-handling    1.3.11                   py37_0  
cryptography              2.7              py37h1ba5d50_0  
curl                      7.65.3               hbc83047_0  
cycler                    0.10.0                   py37_0  
dbus                      1.13.6               h746ee38_0  
descartes                 1.1.0                      py_3  
docutils                  0.15.2                   py37_0  
expat                     2.2.6                he6710b0_0  
fiona                     1.8.3           py37heb36068_1000    conda-forge
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
freexl                    1.0.5                h14c3975_0  
future                    0.17.1                   pypi_0    pypi
gdal                      2.3.3            py37hbb2a789_0  
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.4.1                      py_0  
geos                      3.7.1                he6710b0_0  
giflib                    5.1.4                h14c3975_1  
glib                      2.56.2               hd408876_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.4               hb1b8bf9_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
intel-openmp              2019.4                      243  
jmespath                  0.9.4                      py_0  
jpeg                      9b                   h024ee3a_2  
json-c                    0.13.1               h1bed415_0  
kealib                    1.4.7                hd0c454d_6  
kiwisolver                1.1.0            py37he6710b0_0  
krb5                      1.16.1               h173b8e3_7  
libarchive                3.3.3                h5d8350f_5  
libboost                  1.67.0               h46d08c1_4  
libcurl                   7.65.3               h20c2e04_0  
libdap4                   3.19.1               h6ec2957_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   2.3.3                h2e7e64b_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15                 h63c8f33_5  
libkml                    1.3.0                h590aaf7_4  
libnetcdf                 4.6.1                h11d0813_2  
libpng                    1.6.37               hbc83047_0  
libpq                     11.2                 h20c2e04_0  
libspatialindex           1.9.0                he1b5a44_1    conda-forge
libspatialite             4.3.0a              hb08deb6_19  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
mapclassify               2.0.1                      py_0  
matplotlib                3.1.1            py37h5429711_0  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.14           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
munch                     2.3.2                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4           py37h7e9f1db_0  
numpy-base                1.16.4           py37hde5b4d6_0  
openjpeg                  2.3.0                h05c96fa_1  
openssl                   1.1.1c               h516909a_0    conda-forge
ordered-set               3.1.1                    pypi_0    pypi
pandas                    0.25.1           py37hb3f55d8_0    conda-forge
pcre                      8.43                 he6710b0_0  
pip                       19.2.2                   py37_0  
pixman                    0.38.0               h7b6447c_0  
poppler                   0.65.0               h581218d_1  
poppler-data              0.4.9                         0  
proj4                     5.2.0                he6710b0_1  
psycopg2                  2.7.6.1          py37h1ba5d50_0  
pyasn1                    0.4.6                      py_0  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pylatex                   1.3.0                    pypi_0    pypi
pymasker                  0.4.0                    pypi_0    pypi
pymodis                   2.0.9                    pypi_0    pypi
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.2                      py_0  
pyproj                    2.3.1                    pypi_0    pypi
pyqt                      5.9.2            py37h05f1152_2  
pysocks                   1.7.0                    py37_0  
pystretch                 0.2.1                    pypi_0    pypi
python                    3.7.4                h265db76_1  
python-dateutil           2.8.0                    py37_0  
python-libarchive-c       2.8                     py37_13  
pytz                      2019.2                     py_0  
pyyaml                    5.1.2            py37h7b6447c_0  
qt                        5.9.7                h5867ecd_1  
rasterio                  1.0.28                   pypi_0    pypi
rasterstats               0.13.1                   pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_0  
rsa                       3.4.2                      py_1    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0  
s3transfer                0.2.1                    py37_0  
scipy                     1.3.1            py37h7c811a0_0  
setuptools                41.0.1                   py37_0  
shapely                   1.6.4           py37h06cd6f9_1005    conda-forge
simplejson                3.16.0                   pypi_0    pypi
sip                       4.19.8           py37hf484d3e_0  
six                       1.12.0                   py37_0  
snuggs                    1.4.6                    pypi_0    pypi
soupsieve                 1.9.2                    py37_0  
sqlalchemy                1.3.8            py37h516909a_0    conda-forge
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tornado                   6.0.3            py37h7b6447c_0  
tqdm                      4.32.1                     py_0  
urllib3                   1.24.2                   py37_0  
wheel                     0.33.4                   py37_0  
xerces-c                  3.2.2                h780794e_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0

**Comment by ocefpaf** [comment]
Looks like this is a problem with your conda installation and not a problem with fiona. This may help: https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels

**Comment by sgillies** [comment]
@Isaquedanielre I'm sorry, but we don't use this issue tracker for debugging problems with anaconda installations. Users sometimes find that deleting their conda environments and creating new ones fixes problems.

**Comment by Isaquedanielre** [comment]
Well I try multiple installations (anaconda, miniconda, all packages from conda-forge, packages from pip and so on) and always the same problem.. Anyway. Thanks

**Comment by ocefpaf** [comment]
@Isaquedanielre conda-forge packages issues are welcomed and you can open them in https://github.com/conda-forge/fiona-feedstock/issues (however, my answer will be the same as above, you have a channel mix problem and the instructions in that documentation will help you fix it).

I'm pretty sure @sgillies will answer any issues regarding PyPI installation using `pip`, but you will have to provide him the proper information. This issue you only provided `conda` related stuff and has nothing to do with this issue tracker, as @sgillies stated above.
