### ISSUE TITLE
Release 1.8.8 gives `Symbol not found: sqlite3_column_table_name` for OS X 10.12

### ISSUE THREAD

**Issue by mmidzik** [Toblerity/Fiona#794]
I noticed today that installs of fiona/geopandas appear to be breaking on OS X 10.12, and believe the issue may be due to a recent release (1.8.8 from yesterday). The problem appears to be the same as this [2018 issue](https://github.com/Toblerity/Fiona/issues/588) (and corresponding [rasterio issue](https://github.com/mapbox/rasterio/issues/1360))

## Expected behavior and actual behavior.

Expected to be able to `pip install fiona` or `pip install geopandas` in a virtual environment on my mac. Instead I got a dlopen sqlite3 incompatibility when running `python -c "import fiona" `.

## Steps to reproduce the problem.

On Mac OS X 10.12.6:
sqlite3 version 3.16.0

```
virtualenv venv
venv/bin/activate
pip install fiona
python -c "import fiona"
...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/maya/libraries/test_fiona/lib/python2.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/maya/libraries/test_fiona/lib/python2.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/maya/libraries/test_fiona/lib/python2.7/site-packages/fiona/ogrext.so, 2): Symbol not found: _sqlite3_column_table_name
  Referenced from: /Users/maya/libraries/test_fiona/lib/python2.7/site-packages/fiona/.dylibs/libgdal.20.dylib
  Expected in: /usr/lib/libsqlite3.dylib
 in /Users/maya/libraries/test_fiona/lib/python2.7/site-packages/fiona/.dylibs/libgdal.20.dylib
```

I am able to fix the issue by pinning the fiona version to 1.8.0 (e.g. running `pip install fiona==1.8.0` instead)

In addition, I've confirmed that teammates with Mac OS X 10.13.2 (and sqlite3 --version 3.19.3) do not have the same issue with 1.8.8.

## Operating system

Mac OS X 10.12.3.
sqlite3 version 3.16.0

**Comment by sgillies** [comment]
@mmidzik sorry about this! Tests are passing with 10.13 and I didn't look in the wheel files until now, where I find that the 1.8.8 wheels do not include libsqlite3.dylib like 1.8.6 did. I'll sort this out and upload new wheels by the end of the week.

**Comment by mmidzik** [comment]
No problem at all. We've pinned all versions internally, and will unpin when the update is made. Thanks!

**Comment by sgillies** [comment]
@mmidzik I believe this should be fixed by the new wheels uploaded to PyPI. See #796.
