### ISSUE TITLE
Error when loading binary zipped shapefile [Fiona 1.8.6]

### ISSUE THREAD

**Issue by julianocruz** [Toblerity/Fiona#795]
Hi all, 

I'm trying to load a binary zipped shapefile from memory but I'm having the following error:
_fiona.errors.DriverError: '/vsizip//vsimem/afb41340075d4133a45c44bf0a6f9fa2.zip' not recognized as a supported file format._

I had a look on Fiona's documentation but I didn't find if there's a parameter that I should be using and I'm not.

**Code**
```
import json
import fiona
import geopandas
from google.cloud import storage

client = storage.Client()
bucket = client.get_bucket('bucket_name')
lss_blob = bucket.get_blob('wrs2_descending.zip').download_as_string() #zipped shapefile 

with fiona.BytesCollection(lss_blob) as f: #Error
    crs = f.crs
    lss_shp = geopandas.GeoDataFrame.from_features(f, crs=crs)
```

**Error when calling** _fiona.BytesCollection(lss_blob)_
> Traceback (most recent call last):
>   File "test_file.py", line 15, in <module>
>     with fiona.BytesCollection(landsat_scene_shp_blob) as f: #ERROR 4: `/vsizip//vsimem/b5833ccd78714c9e8c77468d3c7d2b0c.zip' not recognized as a supported file format.
>   File "C:\Anaconda3\lib\site-packages\fiona\collection.py", line 544, in __init__
>     encoding='utf-8', **kwds)
>   File "C:\Anaconda3\lib\site-packages\fiona\collection.py", line 159, in __init__
>     self.session.start(self, **kwargs)
>   File "fiona/ogrext.pyx", line 484, in fiona.ogrext.Session.start
>   File "fiona/_shim.pyx", line 80, in fiona._shim.gdal_open_vector
> fiona.errors.DriverError: '/vsizip//vsimem/afb41340075d4133a45c44bf0a6f9fa2.zip' not recognized as a supported file format.

**Comment by sgillies** [comment]
`BytesCollection` is being replaced by MemoryFile and ZipMemoryFile. See  https://fiona.readthedocs.io/en/latest/manual.html#memoryfile-and-zipmemoryfile.

That said, BytesCollection is still tested using a zipfile that contains 4 component files of a shapefile: https://github.com/Toblerity/Fiona/blob/master/tests/conftest.py#L89-L98. The shapefile is in the root of the zipfile. Can you check the layout of your zipfile? If you have some directories in there you will need to use ZipMemoryFile instead.

**Comment by julianocruz** [comment]
The folder:
![image](https://user-images.githubusercontent.com/1316674/65787206-c9afd600-e12e-11e9-8263-402916b6ef40.png)

With ZipMemoryFile it works! Thanks @sgillies
