### ISSUE TITLE
[discussion] optimizing `transform_geom` for repeated transformations

### ISSUE THREAD

**Issue by snowman2** [Toblerity/Fiona#799]
https://github.com/Toblerity/Fiona/blob/d6ec15f1c2e7a860bc57d35a51e36aeb48377a1a/fiona/_transform.pyx#L133

Currently, the transformer is recreated each time the geometry transform occurs. I am wondering if creating a `Transformer` class similar to the one in `pyproj` would make sense to prevent repeated re-creation of the transformer.

https://pyproj4.github.io/pyproj/stable/advanced_examples.html#repeated-transformations

Thoughts?

**Comment by sgillies** [comment]
@snowman2 maybe... is OCTNewCoordinateTransformation slow?

**Comment by snowman2** [comment]
Not that it is slow, but am wondering if GDAL 3 using PROJ 6 might impact performance. Not an issue with earlier versions of PROJ. Will have to time it on different versions and see if it matters.

**Comment by snowman2** [comment]
Actually, one thought I had was to allow users to pass in a list of geometries as well as a single geometry. This might make more sense. Thoughts?

**Comment by snowman2** [comment]
Okay, I modified the code to allow passing in a list of geometries and ran this test:

```python
from functools import partial

import geopandas
import fiona
from fiona.transform import transform_geom
from shapely.geometry import mapping

gdf = geopandas.read_file("zip://ne_110m_land.zip")

def base_transformer(geom, src_crs, dst_crs):
    return transform_geom(
            src_crs=src_crs,
            dst_crs=dst_crs,
            geom=geom,
            antimeridian_cutting=True,
    )

forward_transformer = partial(base_transformer, src_crs=gdf.crs, dst_crs="epsg:32628")

raw_geoms = gdf.geometry.apply(mapping)

def transform_geoms(raw_geoms):
    transform_geom(
        src_crs=gdf.crs,
        dst_crs="epsg:32628",
        geom=raw_geoms,
        antimeridian_cutting=True,
    )
```

Results:
![image](https://user-images.githubusercontent.com/8699967/66692010-15e73400-ec60-11e9-9b25-c336d95711d6.png)


Is this a change you would like to see?

**Comment by sgillies** [comment]
@snowman2 I think a function to transform a sequence of geometries would be great. Should it return an iterator?

**Comment by snowman2** [comment]
Sounds good. I have a potential implementation in #811.
