### ISSUE TITLE
fiona when to support GDAL 3.X ?

### ISSUE THREAD

**Issue by qq2898** [Toblerity/Fiona#803]
is there any schedule for fiono to support GDAL 3.X ?

**Comment by sgillies** [comment]
@qq2898 check out the email threads in https://fiona.groups.io/g/dev/topics for details. Fiona 2.0 will require GDAL 3. Fiona 1.9.0 will allow the use of GDAL 3 and announce deprecation of support for GDAL 2. We don't have a date for 1.9.0 yet.

**Comment by sgillies** [comment]
I found time at the end of this week to add GDAL 3 support in #804. A 1.8.9 release is scheduled for 2019-10-21 #805.
