### ISSUE TITLE
Bug when using filter + start:stop out of range with GPKG

### ISSUE THREAD

**Issue by culebron** [Toblerity/Fiona#813]
I wonder if this is solvable in Fiona, or it's a Geos bug. If so, sorry for inconvenience.

Here's a test:

1. make a geojson file in QGIS with 10 features
2. also save it as geopackage
3. make a filter that overlaps some or all of them
4. open those files in fiona: `jsn = fiona.open('features.geojson')`, `pkg = fiona.open('features.gpkg')`.
4. try a combination of filter+slice for both formats, e.g. `jsn.filter(2, 20, mask=mask_object)` . and iter them.

This prints records starting from the 3rd one. If `start` is out of range, it works correctly with GeoJSON, but not with GeoPackage.

Example files:

![Selection_070](https://user-images.githubusercontent.com/119675/67723251-07459e80-fa0e-11e9-86f4-347197b93b09.jpg)

Features GeoJSON:

	{
	"type": "FeatureCollection",
	"name": "features",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
	"features": [
	{ "type": "Feature", "properties": { "fid": 1 }, "geometry": { "type": "Point", "coordinates": [ 82.840822, 55.076574 ] } },
	{ "type": "Feature", "properties": { "fid": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.065732, 56.535160 ] } },
	{ "type": "Feature", "properties": { "fid": 3 }, "geometry": { "type": "Point", "coordinates": [ 86.066942, 55.319960 ] } },
	{ "type": "Feature", "properties": { "fid": 4 }, "geometry": { "type": "Point", "coordinates": [ 84.898864, 56.412274 ] } },
	{ "type": "Feature", "properties": { "fid": 5 }, "geometry": { "type": "Point", "coordinates": [ 83.656622, 53.397293 ] } },
	{ "type": "Feature", "properties": { "fid": 6 }, "geometry": { "type": "Point", "coordinates": [ 86.011319, 54.596072 ] } },
	{ "type": "Feature", "properties": { "fid": 7 }, "geometry": { "type": "Point", "coordinates": [ 86.956906, 53.771514 ] } },
	{ "type": "Feature", "properties": { "fid": 8 }, "geometry": { "type": "Point", "coordinates": [ 85.139896, 52.277353 ] } },
	{ "type": "Feature", "properties": { "fid": 9 }, "geometry": { "type": "Point", "coordinates": [ 91.499431, 53.738628 ] } }
	]
	}

Filter GeoJSON:

	{ "type": "FeatureCollection", "name": "filter",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
	"features": [
	{ "type": "Feature", "properties": { "fid": 1 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 81.264844, 55.256611 ], [ 85.102814, 56.967190 ], [ 88.097172, 53.524239 ], [ 83.628811, 52.683860 ], [ 81.264844, 55.256611 ] ] ] } } ] }

Code:

Opening and checking length:

	In [25]: json = fiona.open('/tmp/features.geojson')
	In [26]: gpkg = fiona.open('/tmp/features.gpkg')
	In [27]: len(json), len(gpkg)
	Out[27]: (9, 9)

reading filter geometry:

	In [28]: with fiona.open('/tmp/filter.geojson') as f3: flt = next(iter(f3))['geometry']

Checking all id's are read correctly for both files:

	In [31]: [r['id'] for r in json.filter(mask=flt)]
	Out[31]: ['0', '1', '2', '3', '4', '5', '6']
	In [32]: [r['id'] for r in gpkg.filter(mask=flt)]
	Out[32]: ['1', '2', '3', '4', '5', '6', '7']

Notice the id are off by 1, which seems ok.

Skipping 5 items (results are correct):

	In [38]: [r['id'] for r in json.filter(5, 30, mask=flt)]
	Out[38]: ['5', '6']
	In [37]: [r['id'] for r in gpkg.filter(5, 30, mask=flt)]
	Out[37]: ['6', '7']

Skipping 20 items: geojson driver skips all, but gpkg iterates over all of them like from the very beginning. The 2nd result is INCORRECT.

	In [35]: [r['id'] for r in json.filter(20, 30, mask=flt)]
	Out[35]: []
	In [36]: [r['id'] for r in gpkg.filter(20, 30, mask=flt)]
	Out[36]: ['1', '2', '3', '4', '5', '6', '7']

**Comment by sgillies** [comment]
@culebron very interesting. Which version of Fiona and GDAL? We're not testing the result of OGR_L_SetNextByIndex() here https://github.com/Toblerity/Fiona/blob/master/fiona/ogrext.pyx#L1309 and it looks like we need to start doing that.

**Comment by sgillies** [comment]
Resolved by #884.
