### ISSUE TITLE
Fiona in-memory shapefile not written (but works with geojson)

### ISSUE THREAD

**Issue by SergeBouchut** [Toblerity/Fiona#817]
## Expected behavior and actual behavior

I was expected to write in-memory shapefile using `ESRI Shapefile` driver and `MemoryFile` object : https://fiona.readthedocs.io/en/latest/fiona.html#fiona.io.MemoryFile

When I try to read written data, it returns empty buffer.

I followed the example used in unit test : https://github.com/Toblerity/Fiona/blob/master/tests/test_memoryfile.py#L36

Note that my code below works fine if: 
- I use another driver like `GeoJSON`,
- or I write to file system using `ESRI Shapefile` driver

This is why I think it could be a bug, sorry if it is not.

## Steps to reproduce the problem

```python
from fiona.crs import from_epsg
from fiona.io import MemoryFile

schema = {"properties": {"key": "str:254"}, "geometry": "LineString"}
feature = {
    "geometry": {
        "coordinates": [[2.239764, 48.83972], [2.240041, 48.839695]],
        "type": "LineString",
    },
    "id": "1",
    "properties": {"key": "val"},
    "type": "Feature",
}
with MemoryFile() as mf:
    with mf.open(crs=from_epsg(4326), driver="ESRI Shapefile", schema=schema) as f:
        f.write(feature)
    mf.seek(0)
    assert len(mf.read()) > 0
```

## Operating system

Debian GNU/Linux 10 (buster)

## Fiona and GDAL version and provenance

Python 3.7.4
Fiona-1.8.9.post2-cp37-cp37m-manylinux1_x86_64.whl installed from PyPI using pip 19.3
GDAL 2.4.0 installed via apt-get (libgdal-dev)

**Comment by sgillies** [comment]
Shapefiles are actually 3 or more files and MemoryFile's abstraction only handles single files at this time. ZipMemoryFile also does not yet support writing multiple files.

The workaround for now: switch to a single file format like GeoJSON or GPKG (writing is untested, but Fiona does testing reading from an in-memory geopackage).

**Comment by SergeBouchut** [comment]
Thank you @sgillies for your feedback.

Waiting for `ZipMemoryFile` to support writing multiple files, the better workaround I found is to write data on file system using temporary files, then to zip them and finally return the zip content before clean the files.
