### ISSUE TITLE
Write multiple layers to memory

### ISSUE THREAD

**Issue by aprilmay** [Toblerity/Fiona#830]
I need to create geopackages containing several layers, to be downloaded from a web server. Ideally in such a scenario, the data should be created in memory.

But Fiona has currently the following limitations:
- fiona.io.ZipMemoryFile supports multiple layers, but is for read only
- fiona.io.MemoryFile allows write, but switches to 'r' mode after writing the first layer.

So, my current implementation involves creating the file in the filesystem as a workaround, which is sub optimal.

Proposal: add a "mode" attribute in fiona.io.MemoryFile.open, which would be 'a' for this use case.

**Comment by sgillies** [comment]
Completed!
