### ISSUE TITLE
1.8.11 required gdal ~=3 or higher

### ISSUE THREAD

**Issue by samapriya** [Toblerity/Fiona#837]
Trying to install ```Fiona 1.8.11``` and seems it required ```gdal 3``` or higher. Can someone confirm this? the readme still says it handles upto GDAL 2.4

using python3.6.6, windows 10 using the recommended method from Readme

**Comment by rbuffat** [comment]
The Readme is outdated. Fiona 1.8.11 is compatible with gdal 1.11.x to 3.0.x.  Gdal >= 3.0.2 is supported since version 1.8.10.

I would recommend using a prebuilt version of Fiona, either from conda or https://www.lfd.uci.edu/~gohlke/pythonlibs/ (but do not mix the two sources).

**Comment by sgillies** [comment]
@samapriya the software works with GDAL 2 or 3, but packagers (Gohlke or conda-forge) might make it available only in combination with GDAL 3.

**Comment by samapriya** [comment]
Thank @sgillies and @rbuffat 
That is helpful to know. Would it be possible to update the ReadMe to suggest it does support everything from GDAL 2 to 3 for clarity? Appreciate the insight
