### ISSUE TITLE
Why does Fiona-1.8.11 need gdal-dev, when python3.7.x only need gdal

### ISSUE THREAD

**Issue by fenchu** [Toblerity/Fiona#838]
OS ubuntu 16.06LTS, python 3.8.0, Fiona-1.8.11
I've been using geopandas for a long time on python3.7.x, but when I tried to upgrade I had to install libgdal-dev to get it to work, but this drags in a massive load of other libraries aswell:
```
The following NEW packages will be installed:
  comerr-dev icu-devtools krb5-multidev libarmadillo6 libarpack2 libblas-common libblas3 libcurl4-gnutls-dev libdap-dev
  libdap17v5 libdapclient6v5 libdapserver7v5 libepsilon1 libfreexl1 libgdal-dev libgdal1i libgssrpc4 libhdf4-0-alt
  libhdf4-alt-dev libicu-dev libjasper-dev libkadm5clnt-mit9 libkadm5srv-mit9 libkdb5-8 libkmlbase1 libkmldom1
  libkmlengine1 liblapack3 libminizip1 libmysqlclient-dev libmysqlclient20 libnetcdf-dev libnetcdf11 libodbc1 libogdi3.2
  libopenjp2-7 libpq-dev libpq5 libspatialite-dev libspatialite7 libsuperlu4 liburiparser1 libwebp-dev libwebpdemux2
  libwebpmux3 libxerces-c-dev libxerces-c3.1 libxml2-dev odbcinst odbcinst1debian2 unixodbc unixodbc-dev uuid-dev
```
I upgraded my python3.7.5 pyenv and it only needs the gdal package.

**Comment by sgillies** [comment]
We don't have any binary wheels with compiled code on PyPI for Python 3.8, so you need the Python headers and such. We do have binary wheels for Python 3.7, so the dev packages aren't needed for that Python version.

**Comment by fenchu** [comment]
I really hope it will come :-), thanks
