### ISSUE TITLE
[Feature Request] Append mode for GeoPackage and GeoJSON

### ISSUE THREAD

**Issue by arredond** [Toblerity/Fiona#840]
Similar to #839 

Currently, Fiona allows read and write operations for both [GeoJSON](https://github.com/Toblerity/Fiona/blob/master/fiona/drvsupport.py#L52) and [GPKG](https://github.com/Toblerity/Fiona/blob/master/fiona/drvsupport.py#L60) (two of the most common spatial formats), but not appending to an existing file of these formats.

This seems to be supported by GDAL/OGR so it'd definitely be nice to have this in Fiona too.

I'd be happy to contribute with a PR if someone could point me to some guidelines for contributing!

## Appending with `ogr2ogr`

Sample data (`square.geojson`):

```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [ [0,0], [0,10], [10,10], [10,0], [0,0] ]
        ]
      }
    }
  ]
}
```

#### GeoJSON

Creating a copy, then appending to it
```bash
cp square.geojson square_double.geojson
ogr2ogr -f geojson -append -update square_double.geojson square.geojson
```

Checking contents:
```bash
fio info square.geojson | jq .counts # 1 feature
fio info square_double.geojson | jq .counts # 2 features
```

#### GeoPackage

Same procedure with GeoPackage. Converting original data:
```bash
ogr2ogr -f gpkg square.gpkg square.geojson
```

Creating a copy, then appending to it
```bash
cp square.gpkg square_double.gpkg
ogr2ogr -f gpkg -append -update square_double.gpkg square.gpkg
```

Checking contents:
```bash
fio info square.gpkg | jq .counts # 1 feature
fio info square_double.gpkg | jq .counts # 2 features
```

## Operating system

Mac OS Catalina 10.15.1

## Fiona and GDAL version and provenance

Fiona: 1.8.11 installed from PyPI using pip version 19.3.1.
GDAL: 2.4.2 installed via Homebrew

**Comment by snorfalorpagus** [comment]
Closed by #858
