### ISSUE TITLE
Cannot find proj.db

### ISSUE THREAD

**Issue by rbolgaryn** [Toblerity/Fiona#849]
Dear developers, 

I have a Miniconda installed on a new machine, where I added geopandas, shapely and therefore fiona was installed as a dependency.

fiona version is '1.8.11', pyproj version is '2.4.1'. I am running my code in Python console in PyCharm (using IPython).

When I import fiona, the following error message is displayed:

`import fiona`
`ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db`
`PROJ: proj_create_from_database: Cannot find proj.db` 

However, if I first import pyproj, and then import fiona, no error messages are displayed:

`import pyproj`
`import fiona`

In my opinion, 1) importing fiona without importing pyproj first should work 2) importing order should not matter.

It seems that fiona is not looking for the file proj.db at the correct location (in my case, Miniconda3\Library\share\proj\proj.db), but for some reason it does not matter if pyproj is imported first.

**Comment by sgillies** [comment]
@rbolgaryn the conda-forge fiona package (which you have to use, not the fiona package in the default channel) will require the conda-forge proj package. And that will set PROJ_LIB and make proj.db available when you activate your miniconda environment: https://github.com/conda-forge/proj.4-feedstock/blob/master/recipe/scripts/activate.sh#L14. Almost always, the message you've reported results from the environment not being activated. Can you check that for me?

**Comment by rbolgaryn** [comment]
Hi @sgillies, 

thank you for the reply, installing fiona from conda-forge has solved the issue.
According to the documentation of geopandas, in this case it is also recommended to install geopandas, shapely and dependencies from conda-forge.
