### ISSUE TITLE
Bad result after geoJSON export from geopandas GDF : Invalid field type <class 'cx_Oracle.LOB'>

### ISSUE THREAD

**Issue by tyomik-mnemonic** [Toblerity/Fiona#857]
I have a script, wich takes data from oracle, puts data to pandas.DataFrame -> geopandas df and export to geoJSON:

```
import cx_Oracle
import pandas as pd
import geopandas as gpd
from shapely.geometry import LineString
from shapely import wkb
from sqlalchemy import *

con = cx_Oracle.connect('argument/user@hoooooost/service_n')
#c = con.cursor()
forty_df = pd.read_sql('select * from schema.table where column = 40', con)
df = pd.DataFrame(forty_df)
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.LON, df.LAT))

gdf.to_file("geocoder/forty.geojson", driver='GeoJSON') #problem line
#print(gdf.T.dtypes)
```
When I tried run script, terminal throws: ```
File "
/home/user/raster_dir/x/lib/python3.7/site-packages/geopandas/geodataframe.py", line 515, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "/home/user/raster_dir/x/lib/python3.7/site-packages/geopandas/io/file.py", line 130, in to_file
    colxn.writerecords(df.iterfeatures())
  File "/home/user/raster_dir/x/lib/python3.7/site-packages/fiona/collection.py", line 342, in writerecords
    self.session.writerecs(records, self)
  File "fiona/ogrext.pyx", line 1195, in fiona.ogrext.WritingSession.writerecs
  File "fiona/ogrext.pyx", line 412, in fiona.ogrext.OGRFeatureBuilder.build
ValueError: Invalid field type <class 'cx_Oracle.LOB'>
```
I found that it dtype project, cause all my columns is object, not integer/string, etc.

What I have to do for fix it, and make export correclty
## Operating system

Arch (Manjaro)

## Fiona and GDAL version and provenance

Fiona is 1.8.13
GDAL is 3.0.1

**Comment by rbuffat** [comment]
`ValueError: Invalid field type <class 'cx_Oracle.LOB'>`

The problem here is that your database table contains columns with data types that are not compatible with the supported datatypes of Fiona: https://fiona.readthedocs.io/en/stable/manual.html#field-types (E.g. possible large binary data such as blobs). 

You could try to either only select columns with supported datatypes or trying to convert incompatible columns to compatible data types in the data frame.

**Comment by sgillies** [comment]
This problem will have to be solved in GeoPandas. If it will let you fill a data frame with instances of DB API specific classes, GeoPandas will need to solve the problem of mapping them to types that Fiona supports.

**Comment by sgillies** [comment]
Answer to the question (thanks @rbuffat!) has been added to https://github.com/Toblerity/Fiona/blob/master/FAQ.rst.

**Comment by jorisvandenbossche** [comment]
And a similar note is just being added to the geopandas docs as well: https://github.com/geopandas/geopandas/pull/1289
