### ISSUE TITLE
Error while Installing Geopandas 

### ISSUE THREAD

**Issue by chethan-bm** [Toblerity/Fiona#864]
getting an error while installing Geopandas with pip.

``Installing collected packages: fiona, geopandas
    Running setup.py install for fiona ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\admin\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-sggfl_ka\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\admin\appdata\local\programs\python\python38\Include\fiona'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-wm1plrzn\fiona\
    Complete output (54 lines):
    c:\users\admin\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'metadata_version'
      warnings.warn(msg)
    c:\users\admin\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'requires_python'
      warnings.warn(msg)
    c:\users\admin\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'requires_external'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\fiona
    copying .\fiona\collection.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\compat.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\crs.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\drvsupport.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\env.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\errors.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\inspector.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\io.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\logutils.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\path.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\rfc3339.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\session.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\transform.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\vfs.py -> build\lib.win-amd64-3.8\fiona
    copying .\fiona\__init__.py -> build\lib.win-amd64-3.8\fiona
    creating build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\bounds.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\calc.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\cat.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\collect.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\distrib.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\dump.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\env.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\filter.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\helpers.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\info.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\insp.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\load.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\ls.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\main.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\options.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\rm.py -> build\lib.win-amd64-3.8\fiona\fio
    copying .\fiona\fio\__init__.py -> build\lib.win-amd64-3.8\fiona\fio
    running build_ext
    building 'fiona.schema' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\fiona
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\admin\appdata\local\programs\python\python38\include -Ic:\users\admin\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcfiona/schema.c /Fobuild\temp.win-amd64-3.8\Release\fiona/schema.obj
    schema.c
    fiona/schema.c(620): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\admin\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-wm1plrzn\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\admin\AppData\Local\Temp\pip-record-sggfl_ka\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\admin\appdata\local\programs\python\python38\Include\fiona' Check the logs for full command output.``

**Comment by rbuffat** [comment]
As stated in https://github.com/Toblerity/Fiona#windows, as long as you don't have special requirements, it is advised to use binary packages, e.g. from conda or http://www.lfd.uci.edu/~gohlke/pythonlibs/#fiona

Fiona currently does not provide binary wheels for Windows. Thus, if you install fiona via pip, it is installed from source. In that case, you need a working environment: e.g. a working compiler, correctly setup gdal dependencies, etc. 

The relevant error message here is:
` fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory error: command`
This means, that the local gdal installation cannot be found. On Windows, it is necessary to specify the path to your gdal installation:
`python setup.py build_ext -IC:\\gdal\\include -lgdal_i -LC:\\gdal\\lib bdist_wheel --gdalversion %GDAL_VERSION%"`

Fiona's Readme provides more information in case you want to follow this route: https://github.com/Toblerity/Fiona#windows
