### ISSUE TITLE
fiona fails to pip install - where are the installation instructions? Jesus

### ISSUE THREAD

**Issue by devlocalca** [Toblerity/Fiona#865]
The very first thing I want to see in documentation is how to install.

I would think all I need to type is : `$pip install fiona`

When I do, I get this error message:
```
PS C:\Users\<user>pip install fiona
Collecting fiona
  Using cached https://files.pythonhosted.org/packages/6d/42/f4a7cac53b28fa70e9a93d0e89a24d33e14826dad6644b699362ad84dde0/Fiona-1.8.13.post1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\apps\python\3.8.0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\<user>\\AppData\\Local\\Temp\\pip-install-uzucy2j3\\fiona\\setup.py'"'"'; __file__='"'"'C:\\Users\\<user>\\AppData\\Local\\Temp\\pip-install-uzucy2j3\\fiona\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\<user>\AppData\Local\Temp\pip-install-uzucy2j3\fiona\pip-egg-info'
         cwd: C:\Users\<user>\AppData\Local\Temp\pip-install-uzucy2j3\fiona\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I don't know what the hell GDAL refers to.  I can search and find what I need to do, but why can't you please freaking provide an installation page that is reasonably easy to find somewhere like at the very top of all instructions.

This is where it typically goes.

---

Is this fact lost on the developers in this project?

Have you not ever tried to install something?

---

Have some common sense please, in every reference to `fiona` the installation instructions are well hidden, and apparently there is considerable pre-configuration to do here.

What's the deal here? If any developers here are involved with other projects, please go fix those as well.

Jesus

**Comment by rbuffat** [comment]
You nearly found the installation instructions:  https://github.com/Toblerity/Fiona 

Alternatively, you find them on the python package index (like all other Python libraries you can install with pip from the index): https://pypi.org/project/Fiona

Installation instructions are also included in Fiona's documentation: https://fiona.readthedocs.io/en/stable/README.html#installation

I assume you are new to Python. Especially on Windows, you can not expect that you can install a Python package just with pip install. This only works if either a binary package (=wheel) is available, or the library contains only Python code and has no external dependencies. Fiona currently does not provide binary packages for Windows, but there exist other sources for binary packages:  https://github.com/Toblerity/Fiona#windows

I perceive your bug report as confrontational. I would refrain from that in the future, especially if you expect help from somebody else.
