### ISSUE TITLE
DXF exporter writes layer tag in wrong subclass

### ISSUE THREAD

**Issue by mozman** [Toblerity/Fiona#869]
Your DXF exporter for LWPOLYLINE (and maybe other entities) writes the layer tag (group code 8) in front of the subclass marker `AcDbEntity`, according to the DXF reference this tag should be written after the the `AcDbEntity` marker:

![AcDbEntity](https://user-images.githubusercontent.com/4230966/77508283-a5794b80-6e6a-11ea-910a-44b48e46d8c6.png)

Excerpt from DXF file created by your package:

![image](https://user-images.githubusercontent.com/4230966/77508495-25071a80-6e6b-11ea-87b7-b29103433a79.png)

AutoCAD and BricsCAD do read this files, so it is not really a bug!

To the argument "don't assume tags in a particular order": This is true inside of a subclass but not overall subclasses, because with the introduction with DXF R13/14, the same group tag can occur in different subclasses with different meanings and a tag can also occur multiple times in the same subclass, example LWPOLYLINE vertex tag (10).

I am the author of [ezdxf](https://github.com/mozman/ezdxf) and got an [error message](https://groups.google.com/forum/#!topic/python-ezdxf/9kAOhxJfTK4) from one of your users:

> I have created a dxf by exporting a geopandas dataframe in python using fiona - a python wrapper for gdal/OGR. (Python version 3.7.4)

It would be nice if you could correct this issue in your package.

**Comment by rbuffat** [comment]
Fiona is a wrapper library for [GDAL](https://gdal.org/). GDAL is a library for input and output of geospatial data.  Some supported formats, e.g. DXF, deviate from the GDAL data model and thus have some limitations: https://gdal.org/drivers/vector/dxf.html

As the implementation of the DXF input/output is within GDAL, I would suggest creating your bug report on their issue tracker: https://github.com/OSGeo/gdal

**Comment by mozman** [comment]
Ok and thank  you for your response.
