### ISSUE TITLE
Opening Python 3.8 zipfile.Path() object with fiona raises AttributeError

### ISSUE THREAD

**Issue by zaneselvans** [Toblerity/Fiona#878]
##  Expected behavior and actual behavior.
I attempted to use `fiona.open()` to read a shapefile specified by a `zipfile.Path` object, which is a wrapper around the `pathlib.Path` [class introduced in Python 3.8](https://docs.python.org/3/library/zipfile.html#path-objects). It provides a path-like interface to directories and files contained within a zip archive.

I expected to get back a geometry as I would have if I'd been using a `pathlib.Path` object that wasn't pointing at a file inside of a zip archive.

Instead I got an `AttributeError: 'Path' object has no attribute 'startswith'`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-98-0a862a228c2d> in <module>
----> 1 fiona.open(hifld_epas_zippath)

~/miniconda3/envs/pudl-dev/lib/python3.8/site-packages/fiona/env.py in wrapper(*args, **kwargs)
    405             with Env.from_defaults(session=session):
    406                 log.debug("Credentialized: {!r}".format(getenv()))
--> 407                 return f(*args, **kwargs)
    408     return wrapper
    409 

~/miniconda3/envs/pudl-dev/lib/python3.8/site-packages/fiona/__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    248             path = ParsedPath(path, archive, scheme)
    249         else:
--> 250             path = parse_path(fp)
    251 
    252         if mode in ('a', 'r'):

~/miniconda3/envs/pudl-dev/lib/python3.8/site-packages/fiona/path.py in parse_path(path)
    130         return UnparsedPath(path)
    131 
--> 132     elif path.startswith('/vsi'):
    133         return UnparsedPath(path)
    134 

AttributeError: 'Path' object has no attribute 'startswith'
```
If the zip archive is unzipped, and I create a `pathlib.Path` object pointing to the same (unzipped) file, and attempt to open it with `fiona.open()` it opens up just fine.

## Steps to reproduce the problem.
```py
import pathlib
import zipfile
import fiona

# Works fine
string_path = "path/to/Electric_Planning_Areas.shp"
fiona_string = fiona.open(string_path) 

# Works fine
pathlib_path = pathlib.Path(string_path)
fiona_pathlib = fiona.open(pathlib_path)

# Raises AttributeError
zipfile_path = zipfile.Path(
    "path/to/electric_planning_areas.zip",
    "Electric_Planning_Areas.shp"
)
fiona_zipfile = fiona.open(zipfile_path)
```

## Operating system
Ubuntu Linux 19.10

## Fiona and GDAL version and provenance
fiona 1.8.13 & GDAL 3.0.4 installed via `miniconda3` under Python 3.8.2 from the `conda-forge` channel:
```
fiona                     1.8.13           py38h900e953_0    conda-forge
gdal                      3.0.4            py38h172510d_3    conda-forge
libgdal                   3.0.4                h94bbfbd_3    conda-forge
```

**Comment by sgillies** [comment]
We will consider this. Too many different input types (strings, file objects, pathlib.Path, zipfile.Path, etc) makes the implementation more complicated than I like. Meanwhile, the workaround is to make a valid fiona URI and pass that to fiona.open():

```
>>> zpth = zipfile.Path("tests/data/coutwildrnp.zip", "coutwildrnp.shp")
>>> zshpfile_uri = f"zip://{zpth.root.filename}!{zpth.name}"
```

Fiona will have to do the same thing because we use the OGR library to access zipped datasets and OGR can't use a Python zipfile.ZipFile.

**Comment by sgillies** [comment]
In the end, I think fiona will not accept zipfile.Path. The workaround in the previous comment will have to do.
