### ISSUE TITLE
Incorrect `crs` set on fiona.open()

### ISSUE THREAD

**Issue by koshy1123** [Toblerity/Fiona#879]
## Expected behavior and actual behavior.

I have a geodatabase I downloaded from this source (warning: fairly large attachment): https://pspsinfo.ss.pge.com/artifacts/wildfire-mitigation-data/Attachment-6-GIS-Files.zip

When I load one of the layers (`Transformer`) into QGIS, I see the CRS as `EPSG:4430` and looks right on the map: 
![image](https://user-images.githubusercontent.com/12819087/79241076-67e35f00-7e27-11ea-8c8c-d38b04c1a132.png)

When I used Fiona to load the layer, it is reading the crs as `EPSG:26910` (or in fiona land as `{'init': 'epsg:26910'}`)

Can I force Fiona to use another projected coordinate system while reading? Some kind of a set CRS method?

Can confirm that EPSG:26910 doesn't geo reference it correctly.

## Steps to reproduce the problem.

```
c = fiona.open('pge/pge/infrastructure/v1/pge_infrastructure/EDGIS_2-12/EDGIS2-12.gdb', layer='Transformer')
c.crs
> {'init': 'epsg:26910'}
```

## Operating system

On a debian-based docker container with python 3.7

## Fiona and GDAL version and provenance

`1.8.13` using PyPi and GDAL 3.0.4 and PROJ 6.3.1

**Comment by sgillies** [comment]
@koshy1123 this sounds related to https://github.com/OSGeo/PROJ/issues/2086 maybe?

There have been some unit and WKT issues in PROJ 6 recently. See also https://lists.osgeo.org/pipermail/gdal-dev/2020-January/051483.html and https://github.com/OSGeo/PROJ/pull/1863.

I'm not going to be able to download and inspect that zip file due to its size and the fact that I don't build the file gdb driver.

**Comment by koshy1123** [comment]
Thanks for the pointer @sgillies - in `fiona.open()`, is there a way to set the CRS directly now that I know what it is?

**Comment by rbuffat** [comment]
With Fiona installed with pip (arch linux) I get:

```
>>> c = fiona.open('EDGIS2-12.gdb', layer='Transformer')
>>> c.crs
{'init': 'epsg:4430'}
>>> fiona.__version__
'1.8.13.post1'
```

As far as I know fiona does not alter coordinates when reading. As long as you don't use the CRS in your processing pipeline you should be fine.

**Comment by koshy1123** [comment]
@rbuffat what PROJ version do you have? I, unfortunately, rely on an accurate CRS in my pipeline 😞

**Comment by brendan-ward** [comment]
I get the same results as @rbuffat for same version of Fiona on MacOS.

In case it helps, the underlying WKT from OGR is:

```
PROJCS["NAD83 / BLM 10N (ftUS)",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-123],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",1640416.67],PARAMETER["false_northing",0],UNIT["US survey foot",0.3048006096012192,AUTHORITY["EPSG","9003"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","4430"]]
```

(extracted by `OSRExportToWkt` in Cython)

I also get `EPSG:4430` via `OSRAutoIdentifyEPSG` in Cython with the same usage as `fiona`.

GDAL 2.4.3, Proj 6.2.1

**Comment by rbuffat** [comment]
I think the wheels use proj 4.9.3: https://github.com/sgillies/fiona-wheels/blob/master/env_vars.sh

I would guess that your version of QGIS is also using a proj version < 5, while Fiona on your system uses a recent version of proj. There are quite a few changes with newer versions of proj:  https://gdalbarn.com/

It might be possible to overwrite _crs and _crs_wkt with appropriate values. But it might be better to manually set a working crs when you use the data in the respective frameworks.

**Comment by rbuffat** [comment]
I just installed Fiona from source against proj 6.3.1. 
This results in: 
```
>>> import fiona
>>> c = fiona.open('EDGIS2-12.gdb', layer='Transformer')
>>> c.crs
{'init': 'epsg:26910'}
>>> fiona.__version__
'1.8.13.post1'
```

I'm not familiar with NAD83 projection. The difference between epsg 4430 and 26910 seems to be that 4430 units are in 'US survey foot' and 26910 is in meters. Also the false easting is different for both. Otherwise, they look identical.

https://epsg.io/26910
https://epsg.io/4430

The output of ogrinfo on my system is:
```
ogrinfo -so EDGIS2-12.gdb Transformer
INFO: Open of `EDGIS2-12.gdb'
      using driver `OpenFileGDB' successful.

Layer name: Transformer
Geometry: Point
Feature Count: 904968
Extent: (1249132.227783, 12538525.364014) - (2924078.282837, 15034743.860596)
Layer SRS WKT:
PROJCRS["NAD83 / UTM zone 10N",
    BASEGEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6269]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-123,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",1640416.66666667,
            LENGTHUNIT["US survey foot",0.304800609601219],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["US survey foot",0.304800609601219],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["US survey foot",0.304800609601219,
                ID["EPSG",9003]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["US survey foot",0.304800609601219,
                ID["EPSG",9003]]]]

```

**Comment by koshy1123** [comment]
😱 so it's fine in PROJ 6.2.1 but fails on PROJ 6.3.1?

For context, I was using `geopandas.read_file()` with the `bbox` param as a gdf in EPSG:4326 coordinates confident that geopandas will handle reprojecting the mask, but all I was getting was empty gdfs. 

My ugly workaround was to switch to using the `bbox` param as a tuple with bounds in EPSG:4430 and then setting the `gdf.crs` attribute to be `EPSG:4430` after the gdf was read in.

I'm closing this one out since this is a PROJ level issue. Thanks for the help, folks.
