### ISSUE TITLE
How can I install Fiona?

### ISSUE THREAD

**Issue by ibrahimLearning** [Toblerity/Fiona#900]
Environment:
windows 10 64 bit
Anaconda
python 3.6
GDAL 3.0.4

why pip install Fiona gives error?

**Comment by rbuffat** [comment]
@ibrahimLearning You can find install instruction in the project's documentation: https://github.com/Toblerity/Fiona/blob/master/README.rst#windows

If you use Anaconda you should be able to install Fiona using conda-forge: https://anaconda.org/conda-forge/fiona (this package is not maintained by this project)

**Comment by sgillies** [comment]
Yes, `conda install fiona` using the conda-forge channel is the way to install the package,
