### ISSUE TITLE
Feature request: Flatgeobuf read/write support

### ISSUE THREAD

**Issue by kylebarron** [Toblerity/Fiona#917]
## Expected behavior and actual behavior.

As of GDAL 3.1, there is read and write support for [Flatgeobuf](https://gdal.org/drivers/vector/flatgeobuf.html). It appears that there is no such support in Fiona.

Is adding a line to `drvsupport.py` all that would be needed, or would it be involved to add support here?

## Operating system

Ubuntu 18.04

## Fiona and GDAL version and provenance

`'1.8.13.post1'` from PyPI

GDAL 3.1.0 installed via Conda

**Comment by rbuffat** [comment]
It depends on the driver. Some drivers potentially work out of the box, but not all. 

You can use the following pattern to enable not supported drivers, given they are included in the gdal installation Fiona is built against:

https://github.com/Toblerity/Fiona/blob/maint-1.8/docs/manual.rst#77unsupported-drivers

**Comment by tomplex** [comment]
I was able to get reading to work fine just by following the instructions above:

```
import fiona
fiona.drvsupport.supported_drivers["FlatGeobuf"] = "rw"
src = fiona.open("file.fgb")
```

**Comment by kylebarron** [comment]
That's a good point! I didn't even think of trying to set that manually.

**Comment by sgillies** [comment]
I'm removing this from the 1.8.14 milestone since https://github.com/Toblerity/Fiona/pull/924 looks pretty complicated.

**Comment by sgillies** [comment]
Resolved.
