### ISSUE TITLE
Missing/skipped field

### ISSUE THREAD

**Issue by dingosaurus** [Toblerity/Fiona#920]
When I read geojson with fileds contains **list of string**, this field is missing in schema (and subsequently in geopandas dataframe).

```
geojson = '''
{
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "properties": {
            "id": "123",
            "type": "municipality",
            "email": ["xxx@xxx.cz"],
            "telephone": ["123 456 789"],
            "image": {
                "url": "https://www.xxx.eu/oYNMrvXeeo0wcymO.png",
                "size": 2387654,
                "mimetype": "image/png"
            }
        },
        "geometry": {
            "type": "Point",
            "coordinates": [
                14.0,
                50.0
            ]
        }
    }]
}
'''

import fiona
f = fiona.open(geojson)
f.schema
```
```
{'properties': OrderedDict([('id', 'str'), ('type', 'str'), ('image', 'str')]),
 'geometry': 'Point'}
```

- email is missing
- telephone is missing

## Operating system

Ubuntu 16.04, python 3.8

## Fiona and GDAL version and provenance

Fiona==1.8.13.post1

**Comment by rbuffat** [comment]
Currently, Fiona does not support lists. Supporting lists is tricky. E.g. there would be no guarantee that a Python list would only contain entries of the same datatype.

Maybe the GeoJSON driver open options FLATTEN_NESTED_ATTRIBUTES, respectively ARRAY_AS_STRING can help:
https://gdal.org/drivers/vector/geojson.html

**Comment by sgillies** [comment]
@rbuffat is right, those options are your best bet.
