### ISSUE TITLE
Not able to read track segments data from GPX files.

### ISSUE THREAD

**Issue by sackh** [Toblerity/Fiona#921]
example GPX file: https://github.com/Toblerity/Fiona/blob/master/tests/data/test_gpx.gpx

I am not able to read data with tags `<trkpt` from the above-mentioned example file.
OS: MAC OS X 10.14.6 
Fiona: 1.8.13.post1

My example code:
```python
from fiona import open
with open('test_gpx.gpx', driver='GPX') as fh:
   print(list(fh.values()))
```

### output
```
[]
```
### Expected output:
All the data with tags `<trkpt` should be returned.

Is this bug ? Please let me know if my understanding is correct?

**Comment by rbuffat** [comment]
For GPX, it is required to specify the correct layer:

```
import fiona
>>> fiona.listlayers('/tmp/test_gpx.gpx') 
['waypoints', 'routes', 'tracks', 'route_points', 'track_points']
```

```
with fiona.open("/tmp/test_gpx.gpx", driver='GPX', layer='track_points') as f:
    list(f)
```

**Comment by sackh** [comment]
Thanks for the quick reply. can we read all layers at once?

**Comment by rbuffat** [comment]
No, open can only access one layer at once.

**Comment by sackh** [comment]
Thank you, I am closing this as this not issue.
