### ISSUE TITLE
[Tests] Tests should not rely on write order

### ISSUE THREAD

**Issue by rbuffat** [Toblerity/Fiona#933]
Currently, some tests assume that the reading order of records is the same as they are written. This is not the case for all drivers.

See https://github.com/Toblerity/Fiona/pull/924

**Comment by sgillies** [comment]
@rbuffat historically, the tests were all based on shapefiles, which was at the time the most used and most tested driver. And we did assume preservation of order.

I would like us to be conservative about changing tests to be more specific to particular drivers. It's not Fiona's job, in my view, to find and document bugs and quirks in GDAL/OGR drivers. And let's be clear: many of the GDAL vector drivers are of historical interest at best and are fine to ignore. I'd like for us to focus on implementing properly our feature access API without thinking too much about individual GDAL drivers. Concretely, let's firm up the semantics for Fiona opening modes and make sure that they map to the set of OGR driver capabilities, but let's not write tests that are specific to a particular driver or add code to Fiona that works around limitations of drivers.

I'm sorry that this comment is a little vague and hand-waving.

**Comment by rbuffat** [comment]
@sgillies I was thinking about refactoring the test_equal method of the testdata_generator to work with a collection of records instead of individual records and only refactoring the tests using it. https://github.com/Toblerity/Fiona/blob/7559619bef3e2e3a2d712b674c3c7c358551ccae/tests/conftest.py#L398-L409

I see the benefit of testing all enabled drivers in having more confidence if a new driver is enabled. But I also see that the complexity of the tests increases. There needs to be a balance between benefits and complexity.
