### ISSUE TITLE
crs_wkt loaded incorrectly

### ISSUE THREAD

**Issue by daveisfera** [Toblerity/Fiona#959]
## Expected behavior and actual behavior.
expceted: Projection from `.prj` file is loaded correctly as `crs_wkt`

actual: Projection is changed resulting in incorrect projection of data

## Steps to reproduce the problem.

1. Download file from here: https://catalog.data.gov/dataset/tiger-line-shapefile-2017-nation-u-s-current-state-and-equivalent-national/resource/e4cd223d-7e9b-4dc8-8e92-7bba2d8d2821
2. Run the code below to output the loaded projection
3. Observe that it's been changed

Code to load projection:
```
#!/usr/bin/env python3

import sys
import traceback
import zipfile

import fiona


def _open_shapefile(filename):
    with zipfile.ZipFile(filename, 'r') as z:
        for file in z.namelist():
            if file.endswith('.shp'):
                return fiona.open('zip://' + filename + '!' + file)


def get_projection(filename):
    input_ = _open_shapefile(filename)
    print(input_.meta.get('crs_wkt'))


def main():
    if len(sys.argv) < 2:
        print('usage: {} <filename>')
        return 1

    try:
        get_projection(sys.argv[1])
        return 0
    except Exception as e:
        print('Error: {}'.format(e), file=sys.stderr)
        print(traceback.format_exc(), file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main())
```

From file: `GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]`

Output: `GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]]`

## Operating system

Debian Buster 10.5

## Fiona and GDAL version and provenance

From `pip list installed`:
```
Package                  Version
------------------------ -----------
attrs                    20.2.0
bcrypt                   3.2.0
boto                     2.49.0
cachetools               4.1.1
certifi                  2020.6.20
cffi                     1.14.3
chardet                  3.0.4
click                    7.1.2
click-plugins            1.1.1
cligj                    0.5.0
cryptography             3.1
cx-Oracle                7.2.3
dropbox                  9.3.0
et-xmlfile               1.0.1
Fiona                    1.8.17
GeoAlchemy2              0.6.3
geojson                  2.5.0
google-api-python-client 1.7.11
google-auth              1.21.2
google-auth-httplib2     0.0.4
httplib2                 0.18.1
idna                     2.8
jdcal                    1.3
munch                    2.5.0
oauth2client             4.1.3
oauthlib                 2.1.0
openpyxl                 2.4.8
paramiko                 2.7.2
pip                      20.2.3
psycopg2                 2.8.4
pyasn1                   0.3.2
pyasn1-modules           0.0.11
pycparser                2.20
pycryptodome             3.9.7
PyMySQL                  0.9.3
PyNaCl                   1.4.0
pyodbc                   4.0.27
pyproj                   2.6.1.post1
pyshp                    2.1.2
python-dateutil          2.7.3
pytz                     2018.5
redis                    3.4.1
requests                 2.22.0
requests-oauthlib        0.8.0
rethinkdb                2.3.0.post6
rsa                      3.4.2
setuptools               50.3.0
Shapely                  1.7.1
six                      1.11.0
SQLAlchemy               1.3.10
sshtunnel                0.1.5
uritemplate              3.0.0
urllib3                  1.25.3
wheel                    0.35.1
```

**Comment by rbuffat** [comment]
The output of `ogrinfo -wkt_format WKT1 -so tl_2017_us_state.shp tl_2017_us_state` is:

```
GEOGCS["NAD83",
    DATUM["North_American_Datum_1983",
        SPHEROID["GRS 1980",6378137,298.257222101,
            AUTHORITY["EPSG","7019"]],
        AUTHORITY["EPSG","6269"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AXIS["Latitude",NORTH],
    AXIS["Longitude",EAST],
    AUTHORITY["EPSG","4269"]]
```

which looks identical to what Fiona outputs:

`GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4269"]]`

https://spatialreference.org/ref/epsg/nad83/ suggests that the .prj file contains the ESRI WKT, while Fiona and GDAL report the OGC WKT.

**Comment by rbuffat** [comment]
@daveisfera  There is a significant difference in how [GDAL 2.x and GDAL 3.x](https://gdal.org/development/rfc/rfc73_proj6_wkt2_srsbarn.html) handle projections. Fiona's wheels currently include gdal 2.4.4. I'm not sure if you installed fiona as wheel or as a debian packaged. If on your system you have a GDAL 3.x installed, you can install Fiona with `pip install fiona --no-binary fiona`, which should use your systems GDAL installation. This requires cython to be installed.

**Comment by daveisfera** [comment]
This is happening in a docker container and we don't have `GDAL` installed. We are installing `fiona` using `pip` on Debian Buster, so I believe that it's using the wheel.

Here's the output from `fiona.show_versions()`:
```
Fiona version: 1.8.17
GDAL version: 2.4.4
PROJ version: Proj version not available

OS: Linux 4.19.76-linuxkit
Python: 3.8.6
Python executable: '/usr/local/bin/python'
```

**Comment by sgillies** [comment]
@daveisfera these are different representations of the same spatial reference system. WKT (version 1) is a loose standard and the GDAL/OGR community uses a different representation than Esri.

**Comment by daveisfera** [comment]
The problem is that it's causing the values to change axes. Here's a quick example that shows that:
```
from pyproj import Proj, Transformer

WGS84 = Proj("+init=EPSG:4326")

orig = 'GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]'
loaded = 'GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]]'


class ToWGS84:
    def __init__(self, *proj_args, **proj_kwargs):
        proj = Proj(*proj_args, **proj_kwargs)
        self._transformer = Transformer.from_proj(proj, WGS84)

    def transform(self, x, y):
        return self._transformer.transform(x, y)


proj_orig = ToWGS84(orig)
proj_loaded = ToWGS84(loaded)

print(proj_orig.transform(0.10, 0.01))
print(proj_loaded.transform(0.10, 0.01))

print(proj_orig.transform(0.01, 0.10))
print(proj_loaded.transform(0.01, 0.10))
```

**Comment by rbuffat** [comment]
@daveisfera 
Fiona returns it's coordinated in the traditional "GIS" order of x,y. Before proj6, this was the default case. With proj6 this has changed (see the link above) for some projections. I'm not sure if for NAD83, but definitely for EPSG:4326. I suspect the version of pyproj you are using is based on proj6.

You could try the `always_xy` parameter from [pyproj](https://pyproj4.github.io/pyproj/stable/api/transformer.html#pyproj.transformer.Transformer.from_proj).

> always_xy (bool, optional) – If true, the transform method will accept as input and return as output coordinates using the traditional GIS order, that is longitude, latitude for geographic CRS and easting, northing for most projected CRS. Default is false.

**Comment by daveisfera** [comment]
Thank! I'll give that a try
