### ISSUE TITLE
Migrate from travis-ci.org to .com

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#973]
The .org site will be read-only starting 2020-12-31.

First step: sign the Toblerity org up for the migration beta.

**Comment by sgillies** [comment]
@rbuffat any objections to me moving the project over tonight?

**Comment by rbuffat** [comment]
I wasn't even aware that there are any changes to travis org.

**Comment by sgillies** [comment]
I was also unaware. Then I saw this 2 days ago: https://mail.python.org/archives/list/distutils-sig@python.org/message/ZFNBTQGF5XELLMCRIF4CD7BJTKAJVHHP/.

**Comment by sgillies** [comment]
Done! https://travis-ci.com/github/Toblerity/Fiona
