### ISSUE TITLE
New travis pricing

### ISSUE THREAD

**Issue by rbuffat** [Toblerity/Fiona#975]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> You will not need to change your build definitions when you are pointed to the new plan
> When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

**Comment by rbuffat** [comment]
It should be fairly easy to port the travis tests to github CI. I could create a PR.

**Comment by sgillies** [comment]
Done!
