### ISSUE TITLE
convert to bounding box for object detection

### ISSUE THREAD

**Issue by thangldvn** [Toblerity/Fiona#976]
## Expected behavior and actual behavior.

I have 4 raster images and 1 shpfile contains polygons for these images and i want to convert shpfile to bounding box in object detection . Because the size of raster image is so big, i have to split into tiles. how can i get bounding box corresponding each tiles  by shpfile.

**Comment by rbuffat** [comment]
@ronaldocr9803 this issue tracker is to report bugs or other issues. There is a dedicated group for usage related questions: https://fiona.groups.io/g/main

> The primary forum for questions about installation and usage of Fiona is 
> https://fiona.groups.io/g/main. The authors and other users will answer 
> questions when they have expertise to share and time to explain. Please take the
> time to craft a clear question and be patient about responses. Please do not
> bring these questions to Fiona's issue tracker, which we want to reserve for
> bug reports and other actionable issues.
>
