### ISSUE TITLE
RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.

### ISSUE THREAD

**Issue by rbuffat** [Toblerity/Fiona#986]
The `RuntimeWarning` does not appear in 1.8.17. I think this is a regression introduced in 1.8.18. Related SO question: https://stackoverflow.com/q/64995369/9778755

_Originally posted by @StefanBrand in https://github.com/Toblerity/Fiona/issues/965#issuecomment-737073718_

**Comment by rbuffat** [comment]
@StefanBrand I believe this RuntimeWarning is not a regression. This behavior was introduced in https://github.com/Toblerity/Fiona/commit/e50b4ad8a31ecf65c56b95a9f05863c995039618 and the log message was later changed to a RuntimeWarning.

GDAL (the library Fiona uses to access the geodata) maintains a iterator over the features that are currently read. There a some operations that, for some drivers, can influence this iterator. Thus, after such operations we have to ensure that the iterator is set to the correct position that a continuous read of the data is ensured. Such operations include counting all features in a dataset, respectively calculating its extent.

There are different types of drivers in GDAL. Some drivers support random access, while some do not. For the drivers that do not support random access, the resetting of the iterator involves reading all features again up to the iterator position. As this is a possible costly operation, this RuntimeWarning is emitted, so that users are aware of this behavior.

It seems that this warning is not clear and we should probably improve the wording.

From https://stackoverflow.com/questions/64995369/geopandas-warning-on-read-file, the warning is shown when the bbox parameter is set in the read_file method of geopandas.

**Comment by StefanBrand** [comment]
I'm simply reading a small GPKG and creating a `list` from it:

```
    with fiona.open('sample.gpkg') as src:
        sample = list(src)  # issues a RuntimeWarning in fiona 1.8.18
```

**Comment by rbuffat** [comment]
So what's going on is that the list() method seems to call len() before it starts iterating over the Iterator. I assume this to create an efficient data structure for the list. Would be interesting to look at the implementation of list(). We probably should not emit a warning when the iterator was interrupted before an iteration has actually started. 

```
class Iterator:

    def __init__(self):
        print("__init__")
        self.counter = 0
        self.len = 5

    def __iter__(self):
        print("__iter__")
        return self

    def __next__(self):
        self.counter += 1
        if self.counter > self.len:
            raise StopIteration
        print("__next__", self.counter)
        return self.counter

    def __len__(self):
        print("__len__")
        return self.len

it = Iterator()
print(list(it))

```

Output:
```
__init__
__len__
__iter__
__len__
__next__ 1
__next__ 2
__next__ 3
__next__ 4
__next__ 5
```

**Comment by amercader** [comment]
If it helps, on 1.8.18 I'm also getting the same warning just by iterating over the records returned from a (very small) GML source:

```python
with fiona.open('mypolygon_px6.gml', 'r') as src:
     for record in src:
         print(record['type'])

# RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
```

**Comment by jamesmyatt** [comment]
I believe that there's something wrong here, because the warning occurs for the very first element:

```python
src = fiona.open("data.gpkg", "r")
it = iter(src)
x = next(it)
```

```raw
RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
```

This also doesn't call the __len__ method, as seen using the `Iterator` class from https://github.com/Toblerity/Fiona/issues/986#issuecomment-737367868

```python
src = Iterator()
it = iter(src)
x = next(it)
```

```raw
__init__
__iter__
__next__ 1
```

**Comment by jamesmyatt** [comment]
A separate issue is that the warning is not very useful, i.e. Is the performance actually being affected, or just maybe? What am I supposed to do about the warning? Is it an indication that it's actually switched to a less efficient but more robust method?

Also, if it's a driver that does support random access, then surely there's no problem, so there should be no warning.

**Comment by rbuffat** [comment]
@amercader @jamesmyatt I think in both cases the warning should not be emitted and can be currently (probabely until the next release of fiona) ignored in cases where there is no call to len() or bounds during an iteration, such as in the following examples:

```
src = fiona.open("data.gpkg", "r")
it = iter(src)
for _ in range(XX):
    x = next(it)
len(src)
for _ in range(XX):
    x = next(it)
```

or 

```
src = fiona.open("data.gpkg", "r")
it = iter(src)
for _ in range(XX):
    x = next(it)
src.bounds
for _ in range(XX):
    x = next(it)
``` 

The error message is currently only shown for drivers not supporting OLCFastSetNextByIndex.  How much of a performance impact a reset of the cursor position can have is difficult to estimate, as it can be dependent on the driver, the size of the data, or at what point an iteration is interrupted.

**Comment by rbuffat** [comment]
@Robinlovelace The original issue should be fixed with Fiona 1.8.19: https://github.com/Toblerity/Fiona/pull/987/files

**Comment by Robinlovelace** [comment]
Aha, great work on the fix and thank for the update. Just checked and it seems that we're running 1.8.18.

Reproducible example:

```
docker run -it geocompr/geocompr:geocompy /bin/bash
```

Do you know how to update to the latest version? I'm using conda to install fiona currently with this: https://github.com/geocompr/py/blob/main/environment.yml

I would expect it to update to the latest version automatically but am quite new to managing Python envionments (the joys!) so may have missed something... Also v. happy it seems to be fixed upstream and can be patient for that to filter down to other packages using `fiona` such as `geopandas`.

**Comment by rbuffat** [comment]
@Robinlovelace I'm sorry, I'm not really familiar with your setup. A guess would be to include a `Fiona>=1.8.18` in your environment.yml. 

But as long as you do not encounter any performance issues, you can safely ignore this warning. 

As a short summary of the background for this warning: Fiona uses GDAL to read data. GDAL supports various drivers for different formats. With some drivers, it is possible to read arbitrary features. But some drivers are only capable to start reading at the beginning of a file and then reading each feature sequentially (=sequential reading using an iterator).  Some operations, e.g. querying the number of features of a dataset may interrupt this sequential read. If now a driver does not support reading arbitrary features, the driver needs to read all already read features again to reach the same position in the file as before. This can be very slow.  But it might not need to be noticeable, e.g. if only a few additional features need to be read.

The warning is emitted to inform users that there is the potential for a performance issue that might not be easily detectable. But if there is no performance issue, the warning can be ignored.

**Comment by Robinlovelace** [comment]
Thanks for the explanation @rbuffat, sounds reasonable. Checking here it seems that there are indeed later versions available: https://anaconda.org/conda-forge/fiona 

I'm guess it may be because we pin the Python version as follows:

```
name: geocompy
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
```

Plan to set that as 

```
  - python>=3.9
```

Source: https://github.com/geocompr/py/blob/main/environment.yml
