### ISSUE TITLE
Failing to import fiona on Windows with python 3.6

### ISSUE THREAD

**Issue by cheginit** [Toblerity/Fiona#988]
## Expected behavior and actual behavior.

I added some new [tests](https://github.com/cheginit/pynhd/runs/1488289264?check_suite_focus=true) to my Python package's Actions workflow. The tests for Windows with Python 3.7 and 3.8 passed but 3.6 failed with the following error:
```bash
____________________ ERROR collecting tests/test_pynhd.py _____________________
tests\test_pynhd.py:7: in <module>
    import pynhd as nhd
pynhd\__init__.py:6: in <module>
    from .pynhd import NLDI, NHDPlusHR, WaterData, prepare_nhdplus, topoogical_sort, vector_accumulation
pynhd\pynhd.py:6: in <module>
    import geopandas as gpd
C:\Miniconda\envs\pynhd\lib\site-packages\geopandas\__init__.py:7: in <module>
    from geopandas.io.file import _read_file as read_file  # noqa
C:\Miniconda\envs\pynhd\lib\site-packages\geopandas\io\file.py:7: in <module>
    import fiona
C:\Miniconda\envs\pynhd\lib\site-packages\fiona\__init__.py:85: in <module>
    with fiona._loading.add_gdal_dll_directories():
E   AttributeError: module 'fiona' has no attribute '_loading'
```

## Steps to reproduce the problem.

You can check the full log [here](https://github.com/cheginit/pynhd/runs/1488289264?check_suite_focus=true)

## Operating system

Windows-latest on Github Actions

## Fiona and GDAL version and provenance

gdal-3.1.4
fiona-1.8.18

**Comment by rbuffat** [comment]
You are using a conda-forge package. Please consult the fiona-feedstock issue tracker. It looks as there is already an open bug report:  https://github.com/conda-forge/fiona-feedstock/issues/171


> Please note: Fiona contains extension modules and is thus susceptible to
> C library compatibility issues. If you are reporting an installation or module
> import issue, please note that this project only accepts reports about problems
> with packages downloaded from the Python Package Index. Conda users should take
> issues to one of the following trackers:
> 
> - https://github.com/ContinuumIO/anaconda-issues/issues
> - https://github.com/conda-forge/fiona-feedstock

**Comment by cheginit** [comment]
Yes, that's exactly the same problem. Thanks for the link, I will close this issue then and follow that one.
