### ISSUE TITLE
Problem in GeoJSON reader

### ISSUE THREAD

**Issue by bbuzz31** [Toblerity/Fiona#990]
There seems to be an issue in reading the large GeoJSON files in v1.8.17; works as expected in 1.8.13. Please see full details and steps for reproducing in the issue ticket I raised in geopandas: https://github.com/geopandas/geopandas/issues/1695.
Thanks and happy to help debug with further instructions.

**Comment by rbuffat** [comment]
I can't reproduce this on my system. 

```
>>> fiona.show_versions()
Fiona version: 1.8.18
GDAL version: 2.4.4
PROJ version: Proj version not available

OS: Linux 5.9.11-arch2-1
Python: 3.9.0
Python executable: '/usr/bin/python'
```

Could you add the following code and look if there is something suspicious in the log output?

```
import sys
import logging

logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
```

![Screenshot_20201205_220748](https://user-images.githubusercontent.com/259530/101265406-885d8200-3746-11eb-959f-c4d2ea681df3.png)

**Comment by bbuzz31** [comment]
Thanks for the logging tip.
Inserting `gdal.SetConfigOption('OGR_GEOJSON_MAX_OBJ_SIZE', '2000MB')` solves the issue.

The logger revealed:
`ERROR:fiona._env:GeoJSON object too complex, please see the OGR_GEOJSON_MAX_OBJ_SIZE environment option`

From gdal documentation (https://gdal.org/drivers/vector/geojson.html):
OGR_GEOJSON_MAX_OBJ_SIZE - (GDAL >= 3.0.2) size in MBytes of the maximum accepted single feature, default value is 200MB

And just to address your other question, the issue also happens using a local, unzipped file (as opposed to /vsicurl/vsizip).
Feel free to close; I'm leaving open currently in case you want to implement this workaround (or something better) into a later version of fiona.

**Comment by sgillies** [comment]
@rbuffat thank you! Ideally, OGR would set the error level for `ERROR:fiona._env:GeoJSON object too complex, please see the OGR_GEOJSON_MAX_OBJ_SIZE environment option` higher so that it would trigger an exception via fiona's error handler.

@bbuzz31 reminder that the fiona idiom for setting config options is

```
with fiona.Env(OGR_GEOJSON_MAX_OBJ_SIZE="2000MB"):
    with fiona.open("example.geojson") as collection:
        ...
```

You don't need to use gdal.py at all.
