### ISSUE TITLE
fiona `BytesCollection` errors on zipped GDB with "not recognized as a supported file format"

### ISSUE THREAD

**Issue by tjwebb** [Toblerity/Fiona#994]
## Expected behavior and actual behavior.
`BytesCollection` should recognize and open a zipped GDB file as it does with other formats, but it does not.

## Steps to reproduce the problem.

```python
with open(zipped_gdb_file, 'rb') as f:
    # behavior is the same with/without driver='OpenFileGDB'
    c = BytesCollection(f.read(), driver='OpenFileGDB')
```
results in:
```
fiona.errors.DriverError: '/vsizip//vsimem/7838b45f873541c39f148a40f9d019ad.zip' not recognized as a supported file format
```

This method works perfectly with zipped shapefiles, for example. whereas:

```python
    c = fiona.open(zipped_gdb_file)
```
works just fine.

The GDB is block data from the TIGER datasets.

## Operating system
Mac OS X 10.15

## Fiona and GDAL version and provenance
Fiona 1.8.18 installed from pip
GDAL 3.2.0 installed from kyngchaos installer

**Comment by tjwebb** [comment]
Tried this also with GDAL 3.2.1 from `apt-get`, and with different geodatabase files. Unable to get it to work with `ZipMemoryFile` either.

**Comment by rbuffat** [comment]
https://gdal.org/drivers/vector/openfilegdb.html mentions ```It can also read directly zipped .gdb directories (with .gdb.zip extension), provided they contain a .gdb directory at their first level.```. But I did not test this.

**Comment by tjwebb** [comment]
The two zips I have tried do contain a .gdb directory on the first level. I
suspect the issue is Fiona not correctly identifying the driver, but
bytecollection has no way to specify driver.

**Comment by jsadler2** [comment]
I've been trying to read a .gdb from S3 with geopandas and have gotten the same error. I've tried with the directory and the zipped directory.

**Comment by sgillies** [comment]
@jsadler2 @tjwebb can either of you provide a zipped GDB for me to debug with? We have tests covering the zipped shapefile case, but not GDB, and we're not testing many different zipfile layouts.

**Comment by tjwebb** [comment]
here's an example: https://hazards.fema.gov/nfhlv2/output/State/NFHL_51_20220414.zip

**Comment by sgillies** [comment]
If I make a change to allow the file extension to be specified, we can do this:

```
>>> with ZipMemoryFile(data, ext=".gdb.zip") as memfile:
...     with memfile.open(layer="surveyPoint") as collection:
...         collection.profile
... 
{'driver': 'OpenFileGDB', 'schema': {'properties': {'globalid': 'str', 'what_did_you_kill': 'str:1000', 'CreationDate': 'datetime', 'Creator': 'str:128', 'EditDate': 'datetime', 'Editor': 'str:128'}, 'geometry': 'Point'}, 'crs': CRS.from_epsg(4326), 'crs_wkt': 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]'}
```

The quirkiness of GDAL and OGR's format drivers is slowly but surely eroding my sanity :laughing:

**Comment by sgillies** [comment]
ZipMemoryFile will support zipped GDB in version 1.9.2. We won't do anything about BytesCollection.
