### ISSUE TITLE
collection created from ZipMemoryFile.open() not indexable

### ISSUE THREAD

**Issue by tjwebb** [Toblerity/Fiona#996]
## Expected behavior and actual behavior.

When collections are read from fiona.open, they are indexable e.g. `collection[i]`. Docs here: https://fiona.readthedocs.io/en/latest/manual.html#collection-indexing. Collections read from `ZipMemoryFile` return `None` at all indexes

## Steps to reproduce the problem.

```py
f = open('some_geodatabase.zip')
mem = ZipMemoryFile(f.read())
collection = mem.open()
```

`collection` is iterable and everything else appears as normal, but features are not accessible by indexing `[]`

## Operating system

OSX and Linux, GDAL 3.2.1, fiona 1.8.18

**Comment by tjwebb** [comment]
Interestingly, `len(collection)` returns the correct number of features.

**Comment by sgillies** [comment]
@tjwebb do you see the same issue with a zipped shapefile?

**Comment by tjwebb** [comment]
No, zipped shapefiles work just fine. I am only seeing this with gdb files.

**Comment by sgillies** [comment]
I'm feeling optimistic and will mark this as closed upstream in GDAL. We can reopen if that's not the case.

**Comment by tjwebb** [comment]
As of which GDAL version?
